import PluginManager from '@jbrowse/core/PluginManager'
import LinearGenomeViewPlugin from '@jbrowse/plugin-linear-genome-view'
import SequencePlugin from '@jbrowse/plugin-sequence'
import stateModelFactory from './model'

test('creation', () => {
  const pluginManager = new PluginManager([
    new LinearGenomeViewPlugin(),
    new SequencePlugin(),
  ])
    .createPluggableElements()
    .configure()
  const model = stateModelFactory(pluginManager)
  model.create({
    displayName: 'A vs B',
    // @ts-expect-error
    type: 'LinearSyntenyView',
    views: [
      {
        bpPerPx: 19914.295609223023,
        displayedRegions: [
          {
            assemblyName: 'peach',
            end: 47851208,
            refName: 'Pp01',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 30405870,
            refName: 'Pp02',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 27368013,
            refName: 'Pp03',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 25843236,
            refName: 'Pp04',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 18496696,
            refName: 'Pp05',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 30767194,
            refName: 'Pp06',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 22388614,
            refName: 'Pp07',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 22573980,
            refName: 'Pp08',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 167479,
            refName: 'scaffold_12',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 72028,
            refName: 'scaffold_15',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 69962,
            refName: 'scaffold_13',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 38727,
            refName: 'scaffold_16',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 32503,
            refName: 'scaffold_18',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 32043,
            refName: 'scaffold_19',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 30119,
            refName: 'scaffold_20',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 28663,
            refName: 'scaffold_21',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 27846,
            refName: 'scaffold_23',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 25707,
            refName: 'scaffold_24',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 23005,
            refName: 'scaffold_26',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 22324,
            refName: 'scaffold_32',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 21453,
            refName: 'scaffold_28',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 18616,
            refName: 'scaffold_40',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 18507,
            refName: 'scaffold_30',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 18477,
            refName: 'scaffold_38',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 18055,
            refName: 'scaffold_34',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 17159,
            refName: 'scaffold_33',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 16788,
            refName: 'scaffold_35',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 16633,
            refName: 'scaffold_37',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 15657,
            refName: 'scaffold_39',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 15118,
            refName: 'scaffold_101',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 14945,
            refName: 'scaffold_42',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 14802,
            refName: 'scaffold_58',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 13972,
            refName: 'scaffold_57',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 13173,
            refName: 'scaffold_199',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12576,
            refName: 'scaffold_51',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12535,
            refName: 'scaffold_295',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12322,
            refName: 'scaffold_69',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12283,
            refName: 'scaffold_53',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12175,
            refName: 'scaffold_54',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12137,
            refName: 'scaffold_62',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 12005,
            refName: 'scaffold_55',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 11986,
            refName: 'scaffold_61',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 11897,
            refName: 'scaffold_60',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 11828,
            refName: 'scaffold_67',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 11057,
            refName: 'scaffold_68',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 11032,
            refName: 'scaffold_73',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 11015,
            refName: 'scaffold_66',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10992,
            refName: 'scaffold_78',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10689,
            refName: 'scaffold_70',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10646,
            refName: 'scaffold_104',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10595,
            refName: 'scaffold_72',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10576,
            refName: 'scaffold_71',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10450,
            refName: 'scaffold_77',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 10371,
            refName: 'scaffold_196',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 9725,
            refName: 'scaffold_80',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 9539,
            refName: 'scaffold_84',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8994,
            refName: 'scaffold_297',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8951,
            refName: 'scaffold_92',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8670,
            refName: 'scaffold_90',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8639,
            refName: 'scaffold_135',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8426,
            refName: 'scaffold_129',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8362,
            refName: 'scaffold_121',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8262,
            refName: 'scaffold_97',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 8239,
            refName: 'scaffold_136',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7971,
            refName: 'scaffold_144',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7959,
            refName: 'scaffold_260',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7938,
            refName: 'scaffold_111',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7601,
            refName: 'scaffold_108',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7505,
            refName: 'scaffold_123',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7410,
            refName: 'scaffold_158',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7332,
            refName: 'scaffold_112',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7301,
            refName: 'scaffold_130',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7279,
            refName: 'scaffold_225',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7275,
            refName: 'scaffold_167',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7029,
            refName: 'scaffold_127',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7028,
            refName: 'scaffold_143',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 7027,
            refName: 'scaffold_116',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6961,
            refName: 'scaffold_125',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6946,
            refName: 'scaffold_242',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6895,
            refName: 'scaffold_157',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6780,
            refName: 'scaffold_149',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6743,
            refName: 'scaffold_155',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6571,
            refName: 'scaffold_353',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6550,
            refName: 'scaffold_137',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6504,
            refName: 'scaffold_328',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6486,
            refName: 'scaffold_200',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6400,
            refName: 'scaffold_134',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6379,
            refName: 'scaffold_194',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6282,
            refName: 'scaffold_302',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6232,
            refName: 'scaffold_138',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6198,
            refName: 'scaffold_232',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6164,
            refName: 'scaffold_139',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6143,
            refName: 'scaffold_146',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6128,
            refName: 'scaffold_140',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6087,
            refName: 'scaffold_141',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6011,
            refName: 'scaffold_166',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6007,
            refName: 'scaffold_335',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6001,
            refName: 'scaffold_147',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 6000,
            refName: 'scaffold_171',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5997,
            refName: 'scaffold_339',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5815,
            refName: 'scaffold_325',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5735,
            refName: 'scaffold_162',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5646,
            refName: 'scaffold_151',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5625,
            refName: 'scaffold_164',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5602,
            refName: 'scaffold_211',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5581,
            refName: 'scaffold_153',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5579,
            refName: 'scaffold_165',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5575,
            refName: 'scaffold_340',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5507,
            refName: 'scaffold_156',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5495,
            refName: 'scaffold_202',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5491,
            refName: 'scaffold_161',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5334,
            refName: 'scaffold_213',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5301,
            refName: 'scaffold_187',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5300,
            refName: 'scaffold_168',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5295,
            refName: 'scaffold_183',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5263,
            refName: 'scaffold_163',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5261,
            refName: 'scaffold_169',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5192,
            refName: 'scaffold_174',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5131,
            refName: 'scaffold_249',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5090,
            refName: 'scaffold_189',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5047,
            refName: 'scaffold_175',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5029,
            refName: 'scaffold_181',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 5022,
            refName: 'scaffold_326',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4999,
            refName: 'scaffold_256',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4969,
            refName: 'scaffold_332',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4914,
            refName: 'scaffold_234',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4850,
            refName: 'scaffold_319',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4837,
            refName: 'scaffold_272',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4817,
            refName: 'scaffold_208',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4817,
            refName: 'scaffold_182',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4624,
            refName: 'scaffold_219',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4608,
            refName: 'scaffold_188',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4575,
            refName: 'scaffold_191',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4533,
            refName: 'scaffold_192',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4525,
            refName: 'scaffold_247',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4499,
            refName: 'scaffold_221',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4478,
            refName: 'scaffold_220',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4446,
            refName: 'scaffold_258',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4391,
            refName: 'scaffold_231',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4346,
            refName: 'scaffold_203',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4257,
            refName: 'scaffold_236',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4251,
            refName: 'scaffold_288',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4247,
            refName: 'scaffold_237',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4116,
            refName: 'scaffold_228',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4100,
            refName: 'scaffold_215',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4092,
            refName: 'scaffold_281',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4017,
            refName: 'scaffold_244',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 4016,
            refName: 'scaffold_246',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3892,
            refName: 'scaffold_285',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3885,
            refName: 'scaffold_280',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3815,
            refName: 'scaffold_298',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3789,
            refName: 'scaffold_286',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3789,
            refName: 'scaffold_276',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3708,
            refName: 'scaffold_336',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3708,
            refName: 'scaffold_259',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3699,
            refName: 'scaffold_239',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3576,
            refName: 'scaffold_254',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3541,
            refName: 'scaffold_248',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3536,
            refName: 'scaffold_250',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3476,
            refName: 'scaffold_255',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3429,
            refName: 'scaffold_330',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3424,
            refName: 'scaffold_279',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3415,
            refName: 'scaffold_266',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3411,
            refName: 'scaffold_337',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3362,
            refName: 'scaffold_270',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3320,
            refName: 'scaffold_291',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3154,
            refName: 'scaffold_324',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3153,
            refName: 'scaffold_271',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 3020,
            refName: 'scaffold_296',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2997,
            refName: 'scaffold_307',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2995,
            refName: 'scaffold_346',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2957,
            refName: 'scaffold_306',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2907,
            refName: 'scaffold_284',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2890,
            refName: 'scaffold_311',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2805,
            refName: 'scaffold_347',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2536,
            refName: 'scaffold_321',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2380,
            refName: 'scaffold_308',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2374,
            refName: 'scaffold_313',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 2068,
            refName: 'scaffold_312',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1821,
            refName: 'scaffold_334',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1589,
            refName: 'scaffold_327',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1501,
            refName: 'scaffold_331',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1452,
            refName: 'scaffold_333',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1306,
            refName: 'scaffold_338',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1164,
            refName: 'scaffold_343',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1163,
            refName: 'scaffold_344',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1145,
            refName: 'scaffold_345',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1099,
            refName: 'scaffold_349',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1092,
            refName: 'scaffold_350',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1071,
            refName: 'scaffold_351',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'peach',
            end: 1061,
            refName: 'scaffold_352',
            reversed: false,
            start: 0,
          },
        ],
        offsetPx: 3973,
        tracks: [],
        type: 'LinearGenomeView',
      },
      {
        bpPerPx: 67300.98485738254,
        displayedRegions: [
          {
            assemblyName: 'grape',
            end: 23037639,
            refName: 'chr1',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 18140952,
            refName: 'chr10',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 789605,
            refName: 'chr10_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 19818926,
            refName: 'chr11',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 282498,
            refName: 'chr11_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 22702307,
            refName: 'chr12',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 1566225,
            refName: 'chr12_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 24396255,
            refName: 'chr13',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 3268264,
            refName: 'chr13_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 30274277,
            refName: 'chr14',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 20304914,
            refName: 'chr15',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 22053297,
            refName: 'chr16',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 740079,
            refName: 'chr16_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 17126926,
            refName: 'chr17',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 829735,
            refName: 'chr17_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 29360087,
            refName: 'chr18',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 5170003,
            refName: 'chr18_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 24021853,
            refName: 'chr19',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 568933,
            refName: 'chr1_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 18779844,
            refName: 'chr2',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 19341862,
            refName: 'chr3',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 1220746,
            refName: 'chr3_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 23867706,
            refName: 'chr4',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 76237,
            refName: 'chr4_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 25021643,
            refName: 'chr5',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 421237,
            refName: 'chr5_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 21508407,
            refName: 'chr6',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 21026613,
            refName: 'chr7',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 1447032,
            refName: 'chr7_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 22385789,
            refName: 'chr8',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 23006712,
            refName: 'chr9',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 487831,
            refName: 'chr9_random',
            reversed: false,
            start: 0,
          },
          {
            assemblyName: 'grape',
            end: 43154196,
            refName: 'chrUn',
            reversed: false,
            start: 0,
          },
        ],
        offsetPx: 5893,
        tracks: [],
        type: 'LinearGenomeView',
      },
    ],
  })
})
