/**
 * Used by plugin build systems to determine if a module is provided by JBrowse
 * globally and thus doesn't need to be bundled. A check in ./modules.tsx makes
 * sure this is in sync with the re-exported modules.
 *
 * Using this instead of just Object.keys(modules) allows this file to be
 * easily used by downstream tooling like simple esbuild scripts, rollup
 * configs, etc. without actually importing all the modules in modules.tsx,
 * which a Object.keys(modules) would do
 */

// Per-component MUI subpaths. The legacy `@material-ui/core/*` aliases resolve
// to the same MUI v5 modules, so they're derived from this one list rather than
// maintained as a parallel copy. Keep in sync with the keys of `Entries` in
// MuiReExports.ts (the modules.tsx check enforces this at load time).
const muiComponentSubpaths = [
  '@mui/material/Accordion',
  '@mui/material/AccordionActions',
  '@mui/material/AccordionDetails',
  '@mui/material/AccordionSummary',
  '@mui/material/Alert',
  '@mui/material/AlertTitle',
  '@mui/material/Autocomplete',
  '@mui/material/Avatar',
  '@mui/material/AvatarGroup',
  '@mui/material/Backdrop',
  '@mui/material/Badge',
  '@mui/material/Box',
  '@mui/material/Breadcrumbs',
  '@mui/material/Button',
  '@mui/material/ButtonGroup',
  '@mui/material/Card',
  '@mui/material/CardActions',
  '@mui/material/CardActionArea',
  '@mui/material/CardContent',
  '@mui/material/CardHeader',
  '@mui/material/CardMedia',
  '@mui/material/CircularProgress',
  '@mui/material/Collapse',
  '@mui/material/ClickAwayListener',
  '@mui/material/Chip',
  '@mui/material/Checkbox',
  '@mui/material/Container',
  '@mui/material/Dialog',
  '@mui/material/DialogActions',
  '@mui/material/DialogTitle',
  '@mui/material/DialogContent',
  '@mui/material/DialogContentText',
  '@mui/material/Divider',
  '@mui/material/Drawer',
  '@mui/material/Fab',
  '@mui/material/Fade',
  '@mui/material/FilledInput',
  '@mui/material/FormLabel',
  '@mui/material/FormControl',
  '@mui/material/FormControlLabel',
  '@mui/material/FormHelperText',
  '@mui/material/FormGroup',
  '@mui/material/Grid',
  '@mui/material/Grid2',
  '@mui/material/Grow',
  '@mui/material/Icon',
  '@mui/material/IconButton',
  '@mui/material/Input',
  '@mui/material/InputBase',
  '@mui/material/InputLabel',
  '@mui/material/InputAdornment',
  '@mui/material/Link',
  '@mui/material/LinearProgress',
  '@mui/material/List',
  '@mui/material/ListItem',
  '@mui/material/ListItemAvatar',
  '@mui/material/ListItemButton',
  '@mui/material/ListItemSecondaryAction',
  '@mui/material/ListItemIcon',
  '@mui/material/ListSubheader',
  '@mui/material/ListItemText',
  '@mui/material/Menu',
  '@mui/material/MenuItem',
  '@mui/material/MenuList',
  '@mui/material/Modal',
  '@mui/material/NativeSelect',
  '@mui/material/OutlinedInput',
  '@mui/material/Pagination',
  '@mui/material/PaginationItem',
  '@mui/material/Paper',
  '@mui/material/Popover',
  '@mui/material/Popper',
  '@mui/material/Portal',
  '@mui/material/Radio',
  '@mui/material/RadioGroup',
  '@mui/material/Rating',
  '@mui/material/ScopedCssBaseline',
  '@mui/material/Select',
  '@mui/material/Skeleton',
  '@mui/material/Slider',
  '@mui/material/Snackbar',
  '@mui/material/SnackbarContent',
  '@mui/material/SpeedDial',
  '@mui/material/SpeedDialAction',
  '@mui/material/SpeedDialIcon',
  '@mui/material/Stack',
  '@mui/material/Step',
  '@mui/material/StepButton',
  '@mui/material/StepConnector',
  '@mui/material/StepLabel',
  '@mui/material/StepIcon',
  '@mui/material/Stepper',
  '@mui/material/SvgIcon',
  '@mui/material/Switch',
  '@mui/material/Tab',
  '@mui/material/Table',
  '@mui/material/TableBody',
  '@mui/material/TableCell',
  '@mui/material/TableContainer',
  '@mui/material/TableFooter',
  '@mui/material/TableHead',
  '@mui/material/TablePagination',
  '@mui/material/TableRow',
  '@mui/material/TableSortLabel',
  '@mui/material/Tabs',
  '@mui/material/TextField',
  '@mui/material/TextareaAutosize',
  '@mui/material/ToggleButton',
  '@mui/material/ToggleButtonGroup',
  '@mui/material/Toolbar',
  '@mui/material/Tooltip',
  '@mui/material/Typography',
]

export default [
  'mobx',
  '@jbrowse/mobx-state-tree',
  'mobx-state-tree',
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  'mobx-react',
  '@mui/x-data-grid',
  '@mui/material/utils',
  '@material-ui/core/utils',
  'tss-react',
  'tss-react/mui',
  '@material-ui/core',
  '@mui/material',

  '@mui/material/styles',
  '@material-ui/core/styles',

  ...muiComponentSubpaths.map(p =>
    p.replace('@mui/material/', '@material-ui/core/'),
  ),
  ...muiComponentSubpaths,

  '@material-ui/lab/ToggleButton',
  '@material-ui/lab/ToggleButtonGroup',
  '@material-ui/lab/Autocomplete',
  '@material-ui/lab/Alert',
  '@material-ui/lab',

  '@jbrowse/core/Plugin',
  '@jbrowse/core/pluggableElementTypes',
  '@jbrowse/core/pluggableElementTypes/ViewType',
  '@jbrowse/core/pluggableElementTypes/AdapterType',
  '@jbrowse/core/pluggableElementTypes/DisplayType',
  '@jbrowse/core/pluggableElementTypes/TrackType',
  '@jbrowse/core/pluggableElementTypes/WidgetType',
  '@jbrowse/core/pluggableElementTypes/models',
  '@jbrowse/core/pluggableElementTypes/renderers/RendererType',
  '@jbrowse/core/configuration',
  '@jbrowse/core/util/types/mst',
  '@jbrowse/core/ui',
  '@jbrowse/core/ui/theme',
  '@jbrowse/core/util',
  '@jbrowse/core/util/color',
  '@jbrowse/core/util/layouts',
  '@jbrowse/core/util/tracks',
  '@jbrowse/core/util/Base1DViewModel',
  '@jbrowse/core/util/io',
  '@jbrowse/core/util/mst-reflection',
  '@jbrowse/core/util/rxjs',
  '@jbrowse/core/BaseFeatureWidget/BaseFeatureDetail',
  '@jbrowse/core/data_adapters/BaseAdapter',
]
