// Explicit re-export of @mui/material/styles as a plain object.
//
// The previous `import * as MUIStyles from '@mui/material/styles'` + spread
// forced webpack to build a "decoupled namespace object" for the module; under
// module concatenation its generated getters char-split each export name
// (`CssVarsProvider` -> `styles.C.s.s.V...`), so `styles.C` was undefined and
// every consumer of @mui/material/styles — including @mui/material's own
// ThemeProvider — crashed at render. Naming the bindings and collecting them in
// an object literal keeps them as direct references. `makeStyles` is omitted —
// the modules map overrides it with the legacy tss-react shim.
import {
  CssVarsProvider,
  Experimental_CssVarsProvider,
  StyledEngineProvider,
  THEME_ID,
  ThemeProvider,
  adaptV4Theme,
  alpha,
  createColorScheme,
  createStyles,
  createTheme,
  css,
  darken,
  decomposeColor,
  duration,
  easing,
  emphasize,
  enhanceHighContrast,
  experimental_sx,
  extendTheme,
  getContrastRatio,
  getInitColorSchemeScript,
  getLuminance,
  getOverlayAlpha,
  hexToRgb,
  hslToRgb,
  keyframes,
  private_createTypography,
  private_excludeVariablesFromRoot,
  recomposeColor,
  responsiveFontSizes,
  rgbToHex,
  shouldSkipGeneratingVar,
  styled,
  unstable_createBreakpoints,
  unstable_createMuiStrictModeTheme,
  unstable_getUnit,
  unstable_toUnitless,
  useColorScheme,
  useTheme,
  useThemeProps,
  withStyles,
  withTheme,
} from '@mui/material/styles'

export const MUIStyles = {
  CssVarsProvider,
  Experimental_CssVarsProvider,
  StyledEngineProvider,
  THEME_ID,
  ThemeProvider,
  adaptV4Theme,
  alpha,
  createColorScheme,
  createStyles,
  createTheme,
  css,
  darken,
  decomposeColor,
  duration,
  easing,
  emphasize,
  enhanceHighContrast,
  experimental_sx,
  extendTheme,
  getContrastRatio,
  getInitColorSchemeScript,
  getLuminance,
  getOverlayAlpha,
  hexToRgb,
  hslToRgb,
  keyframes,
  private_createTypography,
  private_excludeVariablesFromRoot,
  recomposeColor,
  responsiveFontSizes,
  rgbToHex,
  shouldSkipGeneratingVar,
  styled,
  unstable_createBreakpoints,
  unstable_createMuiStrictModeTheme,
  unstable_getUnit,
  unstable_toUnitless,
  useColorScheme,
  useTheme,
  useThemeProps,
  withStyles,
  withTheme,
}
