// The published `@jbrowse/core/util` module, listed by name.
//
// modules.ts used to serve `import * as coreUtil from '../util/index.ts'`, which
// made the external ABI a side effect of an internal barrel. The two want
// opposite things: in-tree code wants util/ reorganized freely, and a published
// plugin wants the names it linked against to still be there. Coupling them
// meant moving a file inside util/ silently edited the ABI, and nothing in the
// diff said so -- that is how `defaultCodonTable`, `iterMap`, `when` and the
// rest went, each one an `undefined` inside a bundle nobody was going to build
// again.
//
// Re-exporting by name from the barrel splits those jobs without freezing
// anything. Moving code between modules under util/ is still free, since only
// the barrel's own line changes. Taking a name *out* of the barrel stops
// compiling here, and the fix -- deleting the line below -- is an ABI removal
// that reads as one in review.
//
// So: adding a line is how a helper becomes public, and it is a decision rather
// than a side effect of where the code happens to live. This list is the ABI,
// which abiBaseline.json is deliberately not: that baseline fails on removals
// but not additions, so it sat 11 names behind what was actually being served
// by the time this was written. A list that has to be edited by hand cannot
// drift that way.
//
// The same split is worth making for '@jbrowse/core/ui' (115 pinned names) and
// '@jbrowse/core/util/tracks' (36), which have the same shape and the same
// history: BaseTooltip and getParentRenderProps each left this way.
//
// One name the served module has that this list does not: `renderToStaticMarkup`,
// added in modules.ts. It is the barrel's only reach into react-dom, and this
// file is what the RPC worker publishes, so serving it from here would put
// react-dom back on the worker's graph -- see documentOnlyNames.ts. Read this
// list as the ABI plus that one, which abiBaseline.json pins either way.
export {
  AuthNeededError,
  BEZIER_CONNECTOR_MAX_REACH_PX,
  ENCODED_PREFIX,
  IUPAC_MOTIF_REGEX,
  IntervalTree,
  JSON_PREFIX,
  MAX_ZOOM_RATE_PER_MS,
  SCROLL_ZOOM_FACTOR_DIVISOR,
  SHARE_PREFIX,
  SimpleFeature,
  UNKNOWN,
  UNSUPPORTED,
  UnknownRefNameError,
  ZOOM_ACTIVE_WINDOW_MS,
  accumulateScroll,
  adapterConfigFromSpec,
  addAdapterGuesser,
  addAddTrackComponent,
  addAndShowTrack,
  addOrReplaceView,
  addTrackFromWidget,
  addTrackTypeGuesser,
  aesDecrypt,
  aesEncrypt,
  animationAllowed,
  applyOrderWithin,
  applyZoomAccum,
  assembleLocString,
  assembleLocStringRaw,
  avg,
  b64PadSuffix,
  bezierConnectorPath,
  bpSpanPx,
  bpToPx,
  bytesForRegions,
  calculateRedispatchRange,
  canReplaceView,
  capitalizeFirst,
  checkStopToken,
  checkStopTokenThrottled,
  clamp,
  clearFileFromCache,
  cmpStr,
  coarseStripHTML,
  codonTable,
  compareLocStrings,
  compareLocs,
  complement,
  complementTable,
  createProgressReporter,
  createScrollLatch,
  createSharedSetup,
  createStatusChannel,
  createStatusFanOut,
  createStatusWindow,
  createStopToken,
  createStopTokenChecker,
  createStopTokenRotation,
  dedupe,
  defaultCodonTable,
  defaultStarts,
  diagonalizeRegions,
  diffTrackConfig,
  doesIntersect2,
  downloadStatus,
  drawImageOntoCanvasContext,
  encodeSessionParam,
  ensureFileHandleReady,
  expandLooseTrackConfig,
  featureSpanPx,
  fetchAndMaybeUnzip,
  fetchAndMaybeUnzipText,
  fetchJson,
  fileToLocation,
  findFileHandleIds,
  findParentThat,
  findParentThatIs,
  flattenTrackConfigDelta,
  formatRelativeTime,
  fromUrlSafeB64,
  gatherOverlaps,
  generateCodonTable,
  generateUnknownTrackConf,
  generateUnsupportedTrackConf,
  getAssemblyHost,
  getBlob,
  getBlobMap,
  getBpDisplayStr,
  getConfAssemblyNames,
  getContainingDisplay,
  getContainingTrack,
  getContainingView,
  getDialogHost,
  getEnv,
  launchOrReplaceView,
  getFileFromCache,
  getFileHandle,
  getFileName,
  getFillProps,
  getFrame,
  getNotificationSink,
  getNumberGrouping,
  getPaletteHost,
  getPluginUpdate,
  getRenderingServices,
  getRpcHost,
  getRpcSessionId,
  getSession,
  getSessionServices,
  getStr,
  getStrokeProps,
  getTickDisplayStr,
  getTrackAssemblyNames,
  getTrackName,
  getZoomNormalizer,
  groupBy,
  guessAdapter,
  guessTrackConf,
  guessTrackType,
  hasFileHandlesInCache,
  hasSharedArrayBuffer,
  hashCode,
  hideTrackGeneric,
  installedVersionFromUrl,
  intersection2,
  isAbortException,
  isAbstractMenuManager,
  isActivelyZooming,
  isAppRootModel,
  isAuthNeededException,
  isBlobLocation,
  isDataCurrent,
  isDisplayModel,
  isElectron,
  isFeature,
  isFileHandleLocation,
  isFileSystemAccessSupported,
  isGzip,
  isLocalPathLocation,
  isLooseTrackConfig,
  isNode,
  isObject,
  isPalindromic,
  isPluginInstalled,
  isRootModelWithInternetAccounts,
  isRpcResult,
  isSelectionContainer,
  isSessionModel,
  isSessionServices,
  isSessionModelWithConfigEditing,
  isSessionModelWithConnectionEditing,
  isSessionModelWithConnections,
  isSessionModelWithWidgets,
  isSessionWithAddAssembly,
  isSessionWithAddSessionTrack,
  isSessionWithAddTracks,
  isSessionWithPublishTrackConf,
  isSessionWithDeleteTrackConf,
  isSessionWithSessionPlugins,
  isSessionWithSessionTracks,
  isSessionWithShareURL,
  isSessionWithViewReplacement,
  isStopToken,
  isStopped,
  isSupportedIndexingAdapter,
  isTrackModel,
  isTrackViewModel,
  isUriLocation,
  isValidTag,
  isViewContainer,
  isViewModel,
  iupacToRegex,
  linkify,
  locStringsToRegions,
  localStorageGetBoolean,
  localStorageGetItem,
  localStorageGetJSON,
  localStorageGetNumber,
  localStorageRemoveItem,
  localStorageSetBoolean,
  localStorageSetItem,
  localStorageSetJSON,
  localStorageSetNumber,
  makeAbortError,
  makeIndex,
  makeIndexType,
  makeTrackId,
  markStopTokenStopped,
  matchTrackId,
  max,
  maxFinite,
  measureGridWidth,
  measureText,
  mergeIntervals,
  mergeTrackConfig,
  min,
  minmax,
  normalizeWheelDelta,
  notEmpty,
  objectHash,
  openFeatureWidget,
  openPromotableDisplays,
  parseLocString,
  parseLocStringOneBased,
  parseMotifList,
  pluralize,
  polarToCartesian,
  progressLabel,
  rIC,
  radToDeg,
  readSessionFromDynamo,
  reducePrecision,
  registerStopTokenBroadcaster,
  renameRegionIfNeeded,
  renameRegionsIfNeeded,
  reorder,
  reorderWithin,
  resolvePlugin,
  resolveSelectedIds,
  restoreFileHandles,
  restoreFileHandlesFromSnapshot,
  revcom,
  reverse,
  reverseComplementIupac,
  revlist,
  saveAs,
  saveSvgAsImage,
  selectNamedRegions,
  setBlobMap,
  setFileInCache,
  setNumberGrouping,
  sha256,
  sha256Base64,
  sha256Base64Url,
  shareEndpoint,
  shorten,
  shorten2,
  showTrackGeneric,
  springAnimate,
  statusFraction,
  statusMessageText,
  statusProgressLabel,
  statusReading,
  stitch,
  stopStopToken,
  stopTokenSignal,
  storeBlobLocation,
  storeFileHandle,
  storeFileHandleLocation,
  stringify,
  stripAlpha,
  stripFileExtension,
  stripTrackIds,
  sum,
  svgHtmlToPngBlob,
  tagRegex,
  testAdapter,
  toBase64,
  toBase64Url,
  toLocale,
  toUrlSafeB64,
  toggleTrackGeneric,
  truncateMiddle,
  updateStatus,
  useDebounce,
  useLocalStorage,
  useWidthSetter,
  verifyPermission,
  wheelFrameElapsedMs,
  wheelZoomAccum,
  withProgress,
  withStopTokenCheck,
  withStopTokenSignal,
} from '../util/index.ts'
