import { DATA_GRID_NAMES } from './MuiDataGridReExports.ts'
import { MUI_COMPONENT_NAMES } from './muiComponentNames.ts'

/**
 * Every real own-key name of a namespace-shaped module the RPC worker stubs
 * instead of importing (`workerModules.ts`), so the stub can carry the same
 * own properties as the module it stands in for rather than answering every
 * name through a proxy trap. `modules.ts` throws at load time if one of these
 * drifts from what it actually re-exports.
 *
 * `@mui/material`/`@material-ui/core`'s 112 component names live in
 * `MUI_COMPONENT_NAMES` already — that list is also type-checked against
 * `MuiReExports.ts`'s `Entries`, so only the handful of non-component exports
 * each adds are written out here.
 */

export const REACT_DOM_NAMES = [
  '__DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE',
  'createPortal',
  'default',
  'flushSync',
  'preconnect',
  'prefetchDNS',
  'preinit',
  'preinitModule',
  'preload',
  'preloadModule',
  'requestFormReset',
  'unstable_batchedUpdates',
  'useFormState',
  'useFormStatus',
  'version',
]

export const REACT_DOM_CLIENT_NAMES = [
  'createRoot',
  'default',
  'hydrateRoot',
  'version',
]

export const MOBX_REACT_NAMES = [
  'Observer',
  '_observerFinalizationRegistry',
  'clearTimers',
  'enableStaticRendering',
  'isUsingStaticRendering',
  'observer',
  'useLocalObservable',
]

export const MUI_UTILS_NAMES = [
  'capitalize',
  'createChainedFunction',
  'createSvgIcon',
  'debounce',
  'deprecatedPropType',
  'getActiveElement',
  'isMuiElement',
  'mergeSlotProps',
  'ownerDocument',
  'ownerWindow',
  'requirePropFactory',
  'setRef',
  'unstable_ClassNameGenerator',
  'unstable_memoTheme',
  'unstable_useEnhancedEffect',
  'unstable_useId',
  'unsupportedProp',
  'useControlled',
  'useEventCallback',
  'useForkRef',
]

export const MUI_STYLES_NAMES = [
  'CssVarsProvider',
  'Experimental_CssVarsProvider',
  'StyledEngineProvider',
  'THEME_ID',
  'ThemeProvider',
  'adaptV4Theme',
  'alpha',
  'createColorScheme',
  'createStyles',
  'createTheme',
  'css',
  'darken',
  'decomposeColor',
  'duration',
  'easing',
  'emphasize',
  'enhanceHighContrast',
  'experimental_sx',
  'extendTheme',
  'getContrastRatio',
  'getInitColorSchemeScript',
  'getLuminance',
  'getOverlayAlpha',
  'hexToRgb',
  'hslToRgb',
  'keyframes',
  'makeStyles',
  'private_createTypography',
  'private_excludeVariablesFromRoot',
  'recomposeColor',
  'responsiveFontSizes',
  'rgbToHex',
  'shouldSkipGeneratingVar',
  'styled',
  'unstable_createBreakpoints',
  'unstable_createMuiStrictModeTheme',
  'unstable_getUnit',
  'unstable_toUnitless',
  'useColorScheme',
  'useTheme',
  'useThemeProps',
  'withStyles',
  'withTheme',
]

export const TSS_REACT_NAMES = ['cx', 'keyframes', 'makeStyles']

export const MATERIAL_UI_LAB_NAMES = [
  'Alert',
  'Autocomplete',
  'ToggleButton',
  'ToggleButtonGroup',
]

export const MUI_MATERIAL_NAMES = [
  ...MUI_COMPONENT_NAMES,
  'alpha',
  'createTheme',
  'useTheme',
]

export const MATERIAL_UI_CORE_NAMES = [
  ...MUI_COMPONENT_NAMES,
  'alpha',
  'makeStyles',
  'useTheme',
]

export const CORE_UI_NAMES = [
  'ActionLink',
  'AssemblySelector',
  'BaseExportSvgDialog',
  'CONTEXT_MENU_Z_INDEX',
  'CascadingMenu',
  'CascadingMenuButton',
  'ConfirmDialog',
  'ContextMenu',
  'CopyToClipboardButton',
  'Crosshairs',
  'Dialog',
  'EditableTypography',
  'ErrorBanner',
  'ErrorBar',
  'ErrorMessage',
  'ErrorOverlay',
  'ExportSvgDialog',
  'ExternalLink',
  'FatalErrorDialog',
  'FileDropZone',
  'FileSelector',
  'GRADIENT_LEGEND_HEIGHT',
  'GRADIENT_LEGEND_SVG_AREA_WIDTH',
  'GRADIENT_LEGEND_WIDTH',
  'GpuFallbackButton',
  'INLINE_MENU_ROW_WIDTH',
  'InfoDialog',
  'JexlFilterDialog',
  'LAUNCH_LABEL',
  'LEGEND_ROW_HEIGHT',
  'LEGEND_SWATCH',
  'LabeledCheckbox',
  'LegendSwatchGlyph',
  'LoadingEllipses',
  'LoadingOverlay',
  'LoadingProgress',
  'LogoFull',
  'Logomark',
  'MAX_LEGEND_ITEMS',
  'Menu',
  'MonospaceTextField',
  'NumberTextField',
  'PinAdornment',
  'PluggableComponent',
  'PluggableComponents',
  'PluggableElements',
  'PrerenderedCanvas',
  'ProgressChip',
  'RefNameAutocomplete',
  'RefNameAutocompleteEndAdornment',
  'ReplaceCurrentViewButton',
  'ResetToDefaultButton',
  'ResizeHandle',
  'SanitizedHTML',
  'ScrollEdgeShadow',
  'SettingsChangesTable',
  'ShareLinkField',
  'SingleSlider',
  'SliderTooltip',
  'StatusProgressBar',
  'SubmitDialog',
  'SubmitForm',
  'SvgColorLegend',
  'SvgGradientLegend',
  'TOOLTIP_Z_INDEX',
  'TagTextField',
  'VIEW_HEADER_HEIGHT',
  'VerticalScrollbar',
  'ViewLoadingScreen',
  'addExtensionElement',
  'adornmentReservePx',
  'checkboxItem',
  'colorFwdStrand',
  'colorInterchrom',
  'colorLongInsert',
  'colorLongreadInv',
  'colorNeutralRead',
  'colorPairLL',
  'colorPairLR',
  'colorPairLRDark',
  'colorPairRL',
  'colorPairRR',
  'colorRevStrand',
  'colorShortInsert',
  'colorSplitReadInversion',
  'colorSupplementary',
  'colorUnmappedMate',
  'colorUnmappedMateDark',
  'createJBrowseBaseTheme',
  'createJBrowseTheme',
  'createJBrowseThemeFromArgs',
  'defaultThemes',
  'displayTypesWithPromotableSlots',
  'getInputWidth',
  'hoverBoxStyle',
  'launchTargetsMenuItem',
  'legendEntries',
  'legendIsReadable',
  'legendSwatches',
  'makePromotableSizeMenu',
  'makeSizeMenu',
  'makeSizeSubMenu',
  'matchesTrackSelector',
  'measureLegendText',
  'methylated5hmC',
  'methylated5mC',
  'nonEmptyLegendSections',
  'promotableRadioItem',
  'promotableRadioItems',
  'promotableSlotsWithoutPin',
  'promotableToggleItem',
  'pushIntoSubMenu',
  'pushLaunchViewMenuItem',
  'radioItems',
  'replaceViewAction',
  'resolveSubMenu',
  'sliderScale',
  'staysOpenOnClick',
  'tagColorPalette',
  'unmethylated5mC',
  'useAssemblySelection',
  'useCopyToClipboard',
  'useExportSvgPreference',
  'useMouseState',
  'useMouseTracking',
  'useRecentLocations',
  'wrapComponent',
]

/**
 * Module specifier -> its real own-key names, for every UI entry the worker
 * shapes as a namespace object rather than a bare stub. Anything in
 * `list.ts`'s `reExportsList` that is absent here is a single-value module
 * (one component per `@mui/material/Name` path, `@jbrowse/core/ui/BaseTooltip`)
 * and gets the bare stub, which is already callable/constructible/readable at
 * any depth.
 */
export const WORKER_NAMESPACE_NAMES: Record<string, readonly string[]> = {
  'react-dom': REACT_DOM_NAMES,
  'react-dom/client': REACT_DOM_CLIENT_NAMES,
  'mobx-react': MOBX_REACT_NAMES,
  '@mui/material/utils': MUI_UTILS_NAMES,
  '@material-ui/core/utils': MUI_UTILS_NAMES,
  'tss-react': TSS_REACT_NAMES,
  'tss-react/mui': TSS_REACT_NAMES,
  '@mui/material': MUI_MATERIAL_NAMES,
  '@material-ui/core': MATERIAL_UI_CORE_NAMES,
  '@mui/material/styles': MUI_STYLES_NAMES,
  '@material-ui/core/styles': MUI_STYLES_NAMES,
  '@material-ui/lab': MATERIAL_UI_LAB_NAMES,
  '@mui/x-data-grid': DATA_GRID_NAMES,
  '@jbrowse/core/ui': CORE_UI_NAMES,
}
