export default [
  'mobx',
  '@jbrowse/mobx-state-tree',
  'mobx-state-tree',
  'react',
  'react/jsx-runtime',
  'mobx-react',

  '@mui/material/styles',
  '@material-ui/core/styles',
  '@mui/material',
  '@material-ui/core',

  '@jbrowse/core/Plugin',
  '@jbrowse/core/pluggableElementTypes',
  '@jbrowse/core/pluggableElementTypes/ViewType',
  '@jbrowse/core/pluggableElementTypes/AdapterType',
  '@jbrowse/core/pluggableElementTypes/DisplayType',
  '@jbrowse/core/pluggableElementTypes/TrackType',
  '@jbrowse/core/pluggableElementTypes/WidgetType',
  '@jbrowse/core/pluggableElementTypes/models',
  '@jbrowse/core/pluggableElementTypes/renderers/ServerSideRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/CircularChordRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/BoxRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/FeatureRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/RendererType',
  '@jbrowse/core/configuration',
  '@jbrowse/core/util/types/mst',
  '@jbrowse/core/util',
  '@jbrowse/core/util/color',
  '@jbrowse/core/util/layouts',
  '@jbrowse/core/util/tracks',
  '@jbrowse/core/util/Base1DViewModel',
  '@jbrowse/core/util/io',
  '@jbrowse/core/util/mst-reflection',
  '@jbrowse/core/util/rxjs',
  '@jbrowse/core/data_adapters/BaseAdapter',
]
