// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from coverageBand.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

// Scalar twins of coverageBand.slang, transliterated from slangc's WGSL so
// the Canvas2D and SVG paths run the shader's own math. See adr-051.

function _clamp(x: number, lo: number, hi: number) {
  return _min(_max(x, lo), hi)
}

function _max(a: number, b: number) {
  return b > a || Number.isNaN(a) ? b : a
}

function _min(a: number, b: number) {
  return b < a || Number.isNaN(a) ? b : a
}

export function covEffectiveHeightPx(covHeight: number, covYOffset: number): number {
  return _max((covHeight - (2.0 * covYOffset)), 0.0)
}

export function covBottomOffsetPx(covHeight: number, covYOffset: number): number {
  return (covHeight - covYOffset)
}

function log1pf(x: number): number {
  let u = (1.0 + x)
  let _t0: number
  if ((u == 1.0)) {
    _t0 = x
  } else {
    _t0 = (Math.log(u) * (x / (u - 1.0)))
  }
  return _t0
}

function symlogTransform(x: number, c: number): number {
  return ((((Math.sign(x)) | 0)) * log1pf(Math.abs((x / c))))
}

function normalizeScore(score: number, domainMin: number, domainMax: number, scaleType: number, symlogConstant: number): number {
  let tMax: number
  let tMin: number
  let t: number
  if ((scaleType == 2)) {
    let _t0 = symlogTransform(score, symlogConstant)
    let _t1 = symlogTransform(domainMin, symlogConstant)
    tMax = symlogTransform(domainMax, symlogConstant)
    tMin = _t1
    t = _t0
  } else {
    if ((scaleType == 1)) {
      if ((domainMin > 0.0)) {
        tMax = domainMin
      } else {
        tMax = 1.0
      }
      let _t2 = Math.log2(_max(score, tMax))
      let _t3 = Math.log2(tMax)
      tMax = Math.log2(_max(domainMax, tMax))
      tMin = _t3
      t = _t2
    } else {
      tMax = domainMax
      tMin = domainMin
      t = score
    }
  }
  let tRange = (tMax - tMin)
  if ((tRange <= 0.0)) {
    if ((t > tMin)) {
      tMax = 1.0
    } else {
      tMax = 0.0
    }
    return tMax
  }
  return _clamp(((t - tMin) / tRange), 0.0, 1.0)
}

export function normalizeDepthScalar(rawDepth: number, domainMin: number, domainMax: number, scaleType: number, symlogConstant: number): number {
  return normalizeScore(rawDepth, domainMin, domainMax, scaleType, symlogConstant)
}

export function covBarHeightPx(depthFraction: number, effectiveHeightPx: number): number {
  return (depthFraction * effectiveHeightPx)
}

export function covSegBottomPx(baselinePx: number, yOffset: number, barHeightPx: number): number {
  return (baselinePx - (yOffset * barHeightPx))
}

export function covSegTopPx(baselinePx: number, yOffset: number, segHeight: number, barHeightPx: number): number {
  return (covSegBottomPx(baselinePx, yOffset, barHeightPx) - (segHeight * barHeightPx))
}
