// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from insertion.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

export const LONG_INSERTION_MIN_LENGTH = 10

export const LONG_INSERTION_TEXT_THRESHOLD_PX = 15

export const MIN_HEIGHT_FOR_TEXT = 5

export const INSERTION_SERIF_MIN_PX_PER_BP = 3
