import { settledAs } from '@jbrowse/browser-test-utils/reviewApp'

import { LIVE_WHICH } from './liveLinks.ts'

import type { SpecEntry } from '../review-payload.ts'
import type { LiveWhich } from './liveLinks.ts'

// The predicates the header, the badges and the card list all ask, in one place
// — the badge that counts what a toggle would show and the filter that applies
// it were two copies of some of these, and did disagree.

// Least to most processed: two columns, the same two stacked, then only what
// differs between them. `side` first because it is the one that shows each
// picture as itself, which is what most cards want. Each is [id, the label on
// the card's own segmented button, its tooltip, the label in the header select].
export const COMPARE_MODES = [
  ['side', '◫ side', 'The two images in two columns', 'Side by side'],
  [
    'onion',
    '◐ onion',
    'Stacked, with a slider that fades between them',
    'Onion fade',
  ],
  [
    'swipe',
    '⇔ swipe',
    'Stacked, with a divider you drag across the picture',
    'Swipe divider',
  ],
  [
    'diff',
    '◆ diff',
    'Pixel difference — black wherever the two agree',
    'Difference',
  ],
] as const

export const COMPARE_IDS = COMPARE_MODES.map(m => m[0])

export type CompareMode = (typeof COMPARE_MODES)[number][0]

export const STATUSES = ['needs', 'good', 'answered', 'bad', 'all'] as const
export const KINDS = ['all', 'manual', 'auto'] as const
export const KIND_LABELS = {
  all: 'All kinds',
  manual: 'Manual only',
  auto: 'Autogenerated only',
} as const

export const SORTS = ['default', 'recent'] as const
export const SORT_LABELS = {
  default: 'A–Z',
  recent: 'Recently reviewed',
} as const

export type Status = (typeof STATUSES)[number]
export type Kind = (typeof KINDS)[number]
export type Sort = (typeof SORTS)[number]

export interface Filters {
  q: string
  status: Status
  changedOnly: boolean
  runOnly: boolean
  sortBy: Sort
  group: string
  kind: Kind
  compare: CompareMode
  live: LiveWhich
}

// The one statement of what each control starts at. readUrl falls back to these
// and writeUrl omits them, so a changed default cannot leave a value that writes
// itself into the URL but never restores from it — which is what three separate
// copies of this list were one edit away from.
export const defaultFilters: Filters = {
  q: '',
  status: 'needs',
  changedOnly: false,
  runOnly: false,
  sortBy: 'default',
  group: '',
  kind: 'all',
  compare: 'side',
  live: 'hosted',
}

// Diff vs origin/main, the screenshots a branch review cares about:
// "new" = added on this branch (not named by figures.lock on main); "changed" =
// named there but the bytes on disk differ (an update). `changed` is computed
// server-side against the store hashes.
export const isNew = (s: { exists: boolean; mainUrl?: string }) =>
  s.exists && !s.mainUrl

// A compose figure counts as changed when a part it stacks changed, even if the
// stack itself wasn't recomposed — that gap is the bug the card warns about.
export const isChanged = (s: SpecEntry) =>
  s.changed || s.parts.some(p => p.changed || isNew(p))

// parts moved but the published stack didn't: the figure on the site is stale
export const partsAhead = (s: SpecEntry) =>
  !s.changed && !isNew(s) && isChanged(s)

// Needs review when unreviewed, when its verdict went stale because the
// reviewed image changed since, or when a denial has been answered and is
// waiting on your call. The third case is the one staleness cannot see: an
// answer that changed no pixels leaves the hash matching, so it is only
// 'answered' that puts it back in the queue.
export const needsReview = (s: SpecEntry) =>
  !s.verdict || s.stale || s.verdict.status === 'answered'

// A spec the last run could not render, rendered differently twice, or only
// kept because its own diffThreshold was raised. All three mean the image on
// the card is not simply "what the app produces now".
export const hasRunProblem = (s: SpecEntry) =>
  !!s.run &&
  (!!s.run.failed ||
    s.run.flaky !== undefined ||
    s.run.suppressed !== undefined)

// Most spec names are namespaced with '/' (gallery/x, multiway_synteny/x); only
// the hand-listed desktop-* names use a hyphen instead. Grouping only on '-'
// left ~85% of names in a singleton group of their own.
export const nameGroup = (name: string) =>
  name.includes('/')
    ? name.split('/')[0]!
    : name.includes('-')
      ? name.split('-')[0]!
      : name

// Trimmed, because no figure name contains a space: an unnoticed trailing one —
// pasted, or left behind by a keyboard that space-completes — otherwise selects
// nothing at all, and an empty list with no card on it reads as a finished queue
// rather than as a typo in the search box.
export const searchText = (f: Filters) => f.q.trim().toLowerCase()

// Everything except the status tab and the two toggles — the three controls
// whose own badges have to count what switching to them would show.
export function matchesScope(s: SpecEntry, f: Filters) {
  const q = searchText(f)
  return (
    (!q || s.name.toLowerCase().includes(q)) &&
    (!f.group || nameGroup(s.name) === f.group) &&
    (f.kind === 'all' ||
      (f.kind === 'manual' && !s.autogenerated) ||
      (f.kind === 'auto' && s.autogenerated))
  )
}

// 'all' and 'needs' are the two questions with their own shape; the other three
// tabs are all the same question about a different status word, and spelling
// each out separately is three chances for one of them to drift from the pill
// row that counts it.
export function hasStatus(s: SpecEntry, status: Status) {
  return status === 'all'
    ? true
    : status === 'needs'
      ? needsReview(s)
      : settledAs(s, status)
}

export const matchesChanged = (s: SpecEntry, f: Filters) =>
  !f.changedOnly || isNew(s) || isChanged(s)

export const matchesRun = (s: SpecEntry, f: Filters) =>
  !f.runOnly || hasRunProblem(s)

// The other half: the status tab and the two toggles, i.e. everything a badge
// might be asked to count what switching to it would show. Named separately
// because that is exactly how a badge asks — "the current filters, with my own
// term replaced" — so App can hand it one overridden copy rather than spelling
// the remaining terms out again per badge. It used to spell them out three
// times, and the copies disagreed: 'Changed vs main' read 40 over a needs-review
// queue that would show 3.
export const matchesBeyondScope = (s: SpecEntry, f: Filters) =>
  hasStatus(s, f.status) && matchesChanged(s, f) && matchesRun(s, f)

// The live query. What is ON SCREEN is a capture of this taken when the reviewer
// last asked for one (useStickyQueue), so a verdict recorded here never moves
// the card it was recorded on — see the hook for why that matters.
export const matchesFilters = (s: SpecEntry, f: Filters) =>
  matchesScope(s, f) && matchesBeyondScope(s, f)

// Which of a card's own properties the list is selected and ordered on: change
// one of these and the reviewer is asking a different question, so the queue is
// re-captured. `compare` and `live` are absent on purpose — they change how a
// card draws and where one of its links points, not which cards there are, and
// re-capturing on them threw away the batch a reviewer had settled every time
// they reached for a closer look.
export const queryKey = (f: Filters) =>
  [
    searchText(f),
    f.status,
    f.changedOnly,
    f.runOnly,
    f.sortBy,
    f.group,
    f.kind,
  ].join(' ')

// Which query parameter holds each filter. One table for both directions, so a
// renamed parameter cannot come back out of readUrl under a name writeUrl never
// wrote — the failure of which is a bookmark that silently drops one control.
// The names are shorter than the fields on purpose: they are what a reviewer
// pastes into chat.
const URL_PARAM: Record<keyof Filters, string> = {
  q: 'q',
  status: 'status',
  sortBy: 'sort',
  group: 'group',
  kind: 'kind',
  compare: 'compare',
  live: 'live',
  changedOnly: 'changed',
  runOnly: 'problems',
}

const FILTER_KEYS = Object.keys(URL_PARAM) as (keyof Filters)[]

// Persist the filter state in the URL query string so a review view can be
// reloaded, bookmarked, or shared. Only non-default values are written, to keep
// the URL clean; `1` for a toggle, which is what readUrl looks for.
export function writeUrl(f: Filters) {
  const params = new URLSearchParams()
  for (const key of FILTER_KEYS) {
    const value = f[key]
    if (value !== defaultFilters[key]) {
      params.set(URL_PARAM[key], value === true ? '1' : String(value))
    }
  }
  const qs = params.toString()
  history.replaceState(null, '', qs ? `?${qs}` : location.pathname)
}

// A value only restores if it still names something the UI can show. A typo or
// a stale bookmark otherwise leaves every card filtered out and no control
// looking active — a blank page that reads as "nothing to review".
function oneOf<T extends string>(
  allowed: readonly T[],
  raw: string | null,
  dflt: T,
): T {
  return allowed.find(a => a === raw) ?? dflt
}

export function readUrl(): Filters {
  const p = new URLSearchParams(location.search)
  const raw = (key: keyof Filters) => p.get(URL_PARAM[key])
  const d = defaultFilters
  return {
    q: raw('q') ?? d.q,
    status: oneOf(STATUSES, raw('status'), d.status),
    changedOnly: raw('changedOnly') === '1',
    runOnly: raw('runOnly') === '1',
    sortBy: oneOf(SORTS, raw('sortBy'), d.sortBy),
    // validated against the data once it arrives, since only that knows which
    // groups exist
    group: raw('group') ?? d.group,
    kind: oneOf(KINDS, raw('kind'), d.kind),
    compare: oneOf(COMPARE_IDS, raw('compare'), d.compare),
    live: oneOf(LIVE_WHICH, raw('live'), d.live),
  }
}
