// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from variant.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { VertexAttributeLayout, ShaderBinding, BlendState } from '@jbrowse/render-core/hal'

export const BINDINGS: readonly ShaderBinding[] = [
  { index: 1, kind: 'uniform', name: 'u' },
]

export const VERTS_PER_INSTANCE = 6

export const BLEND_STATE: BlendState = { srcFactor: 'one', dstFactor: 'one-minus-src-alpha' }

export const UNIFORMS_SIZE_BYTES = 48

// Word indices into a Float32Array view over the uniform buffer.
export const UNIFORM_OFFSET_F32 = {
  bpRangeX: 0,
  canvasHeight: 3,
  canvasWidth: 4,
  rowHeight: 5,
  scrollTop: 6,
  zero: 7,
  devicePixelRatio: 8,
} as const


export interface Uniforms {
  bpRangeX: [number, number, number]
  canvasHeight: number
  canvasWidth: number
  rowHeight: number
  scrollTop: number
  zero: number
  devicePixelRatio: number
}

export function writeUniforms(buf: ArrayBuffer, uniforms: Uniforms) {
  const f32 = new Float32Array(buf)
  f32[0] = uniforms.bpRangeX[0]
  f32[1] = uniforms.bpRangeX[1]
  f32[2] = uniforms.bpRangeX[2]
  f32[3] = uniforms.canvasHeight
  f32[4] = uniforms.canvasWidth
  f32[5] = uniforms.rowHeight
  f32[6] = uniforms.scrollTop
  f32[7] = uniforms.zero
  f32[8] = uniforms.devicePixelRatio
}

export const INSTANCE_STRIDE_BYTES = 20
export const INSTANCE_STRIDE_WORDS = 5

// Word indices into a Uint32Array view over the instance buffer.
export const INSTANCE_OFFSET_U32 = {
  startEnd: 0,
  rowIndex: 2,
  shapeType: 3,
  color: 4,
} as const

export const VERTEX_ATTRIBUTES: readonly VertexAttributeLayout[] = [
  { name: 'a_startEnd', components: 2, type: 'uint', offsetBytes: 0, integer: true },
  { name: 'a_rowIndex', components: 1, type: 'uint', offsetBytes: 8, integer: true },
  { name: 'a_shapeType', components: 1, type: 'uint', offsetBytes: 12, integer: true },
  { name: 'a_color', components: 1, type: 'uint', offsetBytes: 16, integer: true },
]

export interface InstanceArrays {
  startEnd: ArrayLike<number>
  rowIndex: ArrayLike<number>
  shapeType: ArrayLike<number>
  color: ArrayLike<number>
}

export function packInstances(
  arrays: InstanceArrays,
  numInstances: number,
  buf: ArrayBuffer = new ArrayBuffer(numInstances * INSTANCE_STRIDE_BYTES),
) {
  const u32 = new Uint32Array(buf)
  const { startEnd, rowIndex, shapeType, color } = arrays
  for (let i = 0; i < numInstances; i++) {
    const o = i * INSTANCE_STRIDE_WORDS
    u32[o + 0] = startEnd[i * 2 + 0]!
    u32[o + 1] = startEnd[i * 2 + 1]!
    u32[o + 2] = rowIndex[i]!
    u32[o + 3] = shapeType[i]!
    u32[o + 4] = color[i]!
  }
  return buf
}

// Component `c` of instance `i`'s `startEnd` (2 components).
export function getInstanceStartEnd(u32: Uint32Array, i: number, c: number) {
  return u32[i * INSTANCE_STRIDE_WORDS + c]!
}

export function setInstanceStartEnd(
  u32: Uint32Array,
  i: number,
  v0: number,
  v1: number,
) {
  const o = i * INSTANCE_STRIDE_WORDS
  u32[o] = v0
  u32[o + 1] = v1
}

// Instance `i`'s `rowIndex`.
export function getInstanceRowIndex(u32: Uint32Array, i: number) {
  return u32[i * INSTANCE_STRIDE_WORDS + 2]!
}

export function setInstanceRowIndex(u32: Uint32Array, i: number, v: number) {
  u32[i * INSTANCE_STRIDE_WORDS + 2] = v
}

// Instance `i`'s `shapeType`.
export function getInstanceShapeType(u32: Uint32Array, i: number) {
  return u32[i * INSTANCE_STRIDE_WORDS + 3]!
}

export function setInstanceShapeType(u32: Uint32Array, i: number, v: number) {
  u32[i * INSTANCE_STRIDE_WORDS + 3] = v
}

// Instance `i`'s `color`.
export function getInstanceColor(u32: Uint32Array, i: number) {
  return u32[i * INSTANCE_STRIDE_WORDS + 4]!
}

export function setInstanceColor(u32: Uint32Array, i: number, v: number) {
  u32[i * INSTANCE_STRIDE_WORDS + 4] = v
}
