// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from variant.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './variant.iface.generated.ts'
export * from './variant.consts.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./variant.wgsl.generated.ts'),
  glsl: () => import('./variant.glsl.generated.ts'),
}
