// Generated by scripts/generateMarkRules.ts from plugins/marks/src/LinearMarkDisplay/markProblems.ts: do not edit, `pnpm autogen` rewrites it.
import { AUTO_BIN } from './autoBin.ts'
import { colorProblems, isJexl, paintedScale } from './markRuleFacts.ts'
import {
  DEFAULT_AGGREGATE_OP,
  DEFAULT_BIN_AS,
  DEFAULT_COVERAGE_AS,
  DEFAULT_FORMULA_AS,
  DEFAULT_MARK_SHAPE,
  DEFAULT_PILEUP_AS,
  DEFAULT_PILEUP_FIELDS,
} from './markVocabulary.ts'
import { SHAPE_SPECS, rampResolvesPerRegion, readsValue } from './shapeSpecs.ts'

import type { ColorScaleName } from './markRuleFacts.ts'
import type {
  AggregateOpName,
  MarkShapeName,
  MarkSourceName,
} from './markVocabulary.ts'

/**
 * What a config file validator calls a problem. `error`: the mark draws
 * nothing, never draws, or a step cannot run. `warning`: a slot waits unread,
 * or the marks draw in an arrangement the author may not have meant. The
 * display shows both as notices, since a load refuses neither (ADR-133).
 */
export type MarkProblemLevel = 'error' | 'warning'

/**
 * The level of every rule of the list, by the stable id a report and a test
 * refer to it by. A single mark's combination that a JSON schema can state is
 * the mark schema's `requires` and is not restated here.
 */
export const MARK_RULES = {
  'unread-channel': 'warning',
  'span-density-source': 'warning',
  'threshold-cuts': 'warning',
  'threshold-range': 'warning',
  'ramp-domain': 'warning',
  'ramp-ends': 'warning',
  'unpinned-span-ramp': 'warning',
  'empty-zoom-range': 'error',
  'step-expression': 'error',
  'bin-width': 'error',
  'step-pair': 'warning',
  'op-field': 'error',
  'step-field-expression': 'error',
  'unwritten-y': 'error',
  'value-beside-rows': 'warning',
  'two-packings': 'warning',
  'second-density-mark': 'warning',
} as const satisfies Record<string, MarkProblemLevel>

export type MarkRuleId = keyof typeof MARK_RULES

/**
 * What a `marks` list says that the display cannot draw as written: the rule,
 * the mark, or none for the display's own `transform`, the slot to look at,
 * and why. A problem is a combination of slots,
 * which a load cannot refuse: the config editor writes one slot at a time, so
 * moving a bar to a span passes through a span that still names a `y`, and a
 * refusal there drops the track from the session it was saved in (ADR-133).
 * The display draws what it can and says the rest in its corner notice.
 */
export interface MarkProblem {
  rule: string
  level: MarkProblemLevel
  mark?: number
  slot: string
  message: string
}

type OwnProblem = Omit<MarkProblem, 'mark'>

interface OpSnapshot {
  op?: AggregateOpName
  field?: string
  as?: string
}

/** One `transform` step as a config snapshot holds it, defaults left off. */
export type StepSnapshot =
  | { type: 'filter'; expr?: string }
  | { type: 'formula'; expr?: string; as?: string }
  | { type: 'bin'; step?: number | string; field?: string; as?: string[] }
  | { type: 'aggregate'; groupby?: string[]; ops?: OpSnapshot[] }
  | { type: 'coverage'; as?: string }
  | { type: 'flatten'; field?: string; index?: string; keepEmpty?: boolean }
  | { type: 'pileup'; as?: string; fields?: string[]; padding?: number }

interface ColorSnapshot {
  field?: string
  scale?: ColorScaleName
  domain?: string[]
  domainMin?: number
  domainMax?: number
}

/**
 * The display's `facet` as a config snapshot holds it. A facet naming no field
 * groups nothing, the one thing the rule list reads of it, so a caller holding
 * a config object of its own passes that object.
 */
export interface FacetSnapshot {
  field?: unknown
}

/**
 * One entry of a `marks` list as a config snapshot holds it, defaults left
 * off. A type alias, which a `Record<string, unknown>` reader takes.
 */
export type MarkSnapshot = {
  shape?: MarkShapeName
  source?: MarkSourceName
  minBpPerPx?: number
  maxBpPerPx?: number
  encoding?: {
    x?: string
    x2?: string
    y?: string
    row?: string
    color?: ColorSnapshot
    glyph?: unknown
  }
  transform?: StepSnapshot[]
}

function found(rule: MarkRuleId, slot: string, message: string): OwnProblem {
  return { rule, level: MARK_RULES[rule], slot, message }
}

function shapeOf(mark: MarkSnapshot) {
  return mark.shape ?? DEFAULT_MARK_SHAPE
}

function stepsOf(mark: MarkSnapshot) {
  return mark.transform ?? []
}

function rampColor(mark: MarkSnapshot) {
  const color = mark.encoding?.color ?? {}
  const painted = paintedScale(
    { scale: color.scale, field: color.field ?? '' },
    'categorical',
  )
  return painted === 'linear' || painted === 'log' ? color : undefined
}

function drawTogether(a: MarkSnapshot, b: MarkSnapshot) {
  const upper = (m: MarkSnapshot) => m.maxBpPerPx || Infinity
  const lower = (m: MarkSnapshot) => m.minBpPerPx ?? 0
  return lower(a) < upper(b) && lower(b) < upper(a)
}

type BinSnapshot = Extract<StepSnapshot, { type: 'bin' }>

// The field names a step reads, by the slot each is written in.
function fieldRefs(step: StepSnapshot): [string, string | undefined][] {
  const list = (slot: string, refs: readonly string[] = []) =>
    refs.map((ref, k): [string, string] => [`${slot}.${k}`, ref])
  switch (step.type) {
    case 'bin':
    case 'flatten':
      return [['field', step.field]]
    case 'pileup':
      return list('fields', step.fields)
    case 'aggregate':
      return [
        ...list('groupby', step.groupby),
        ...(step.ops ?? []).map((o, k): [string, string | undefined] => [
          `ops.${k}.field`,
          o.field,
        ]),
      ]
    default:
      return []
  }
}

// A slot naming two fields, and the default it reads as when it names another
// number of them.
function pairSlot(step: StepSnapshot) {
  return step.type === 'bin'
    ? { slot: 'as', names: step.as, fallback: DEFAULT_BIN_AS }
    : step.type === 'pileup'
      ? { slot: 'fields', names: step.fields, fallback: DEFAULT_PILEUP_FIELDS }
      : undefined
}

function packs(mark: MarkSnapshot) {
  return stepsOf(mark).some(s => s.type === 'pileup')
}

function banded(mark: MarkSnapshot) {
  return packs(mark) || !!mark.encoding?.row
}

// The fields the last step that makes its features from nothing leaves behind,
// with what the steps after it add; undefined where no step does, and every
// field of the file is still there.
function madeFields(mark: MarkSnapshot) {
  const steps = stepsOf(mark)
  const made = steps.findLastIndex(
    s => s.type === 'aggregate' || s.type === 'coverage',
  )
  const last = steps[made]
  if (!last) {
    return undefined
  }
  const fields = new Set(['refName', 'start', 'end'])
  if (last.type === 'coverage') {
    fields.add(last.as ?? DEFAULT_COVERAGE_AS)
  } else if (last.type === 'aggregate') {
    const bin = steps
      .slice(0, made)
      .findLast((s): s is BinSnapshot => s.type === 'bin')
    const edges = bin?.as ?? DEFAULT_BIN_AS
    for (const field of last.groupby?.length
      ? last.groupby
      : edges.length === 2
        ? edges
        : []) {
      fields.add(field)
    }
    for (const { op = DEFAULT_AGGREGATE_OP, field, as } of last.ops ?? []) {
      fields.add(as || (op === 'count' || !field ? op : `${op}_${field}`))
    }
  }
  for (const step of steps.slice(made + 1)) {
    if (step.type === 'formula') {
      fields.add(step.as ?? DEFAULT_FORMULA_AS)
    } else if (step.type === 'pileup') {
      fields.add(step.as ?? DEFAULT_PILEUP_AS)
    } else if (step.type === 'flatten' && step.index) {
      fields.add(step.index)
    }
  }
  return fields
}

// What a list of steps cannot run as written, whether a mark's or the display's
function stepProblems(steps: readonly StepSnapshot[]) {
  const problems: OwnProblem[] = []
  for (const [i, step] of steps.entries()) {
    const { type } = step
    if ((type === 'filter' || type === 'formula') && !isJexl(step.expr ?? '')) {
      problems.push(
        found(
          'step-expression',
          `transform.${i}.expr`,
          `a ${type} reads a jexl: expression`,
        ),
      )
    }
    if (
      type === 'bin' &&
      step.step !== undefined &&
      step.step !== AUTO_BIN &&
      !(Number(step.step) > 0)
    ) {
      problems.push(
        found(
          'bin-width',
          `transform.${i}.step`,
          'a bin is a positive width in bp',
        ),
      )
    }
    const pair = pairSlot(step)
    if (pair?.names && pair.names.length !== 2) {
      problems.push(
        found(
          'step-pair',
          `transform.${i}.${pair.slot}`,
          `a ${type} reads two field names from ${pair.slot} and this names ${pair.names.length}, so it reads ${pair.fallback.join(' and ')}`,
        ),
      )
    }
    if (type === 'aggregate') {
      for (const [k, { op = DEFAULT_AGGREGATE_OP, field }] of (
        step.ops ?? []
      ).entries()) {
        if (op !== 'count' && !field) {
          problems.push(
            found(
              'op-field',
              `transform.${i}.ops.${k}.field`,
              `${op} reads a field and names none`,
            ),
          )
        }
      }
    }
    for (const [slot, ref] of fieldRefs(step)) {
      if (ref && isJexl(ref)) {
        problems.push(
          found(
            'step-field-expression',
            `transform.${i}.${slot}`,
            `the ${type} step reads a field name or a dotted path; a formula step in front computes one`,
          ),
        )
      }
    }
  }
  return problems
}

function ownProblems(mark: MarkSnapshot) {
  const shape = shapeOf(mark)
  const problems: OwnProblem[] = []
  const y = mark.encoding?.y
  const channels = new Set<string>(['x', 'x2', ...SHAPE_SPECS[shape].channels])
  for (const channel of Object.keys(mark.encoding ?? {})) {
    if (!channels.has(channel)) {
      problems.push(
        found(
          'unread-channel',
          `encoding.${channel}`,
          `a ${shape} does not read ${channel}`,
        ),
      )
    }
  }
  if (!readsValue(shape) && mark.source === 'density') {
    problems.push(
      found(
        'span-density-source',
        'source',
        `a ${shape} does not draw the density sidecar`,
      ),
    )
  }
  const color = mark.encoding?.color ?? {}
  for (const { rule, slot, message } of colorProblems(color, 'categorical')) {
    problems.push(found(rule, `encoding.color.${slot}`, message))
  }
  const ramp = rampColor(mark)
  if (ramp) {
    const { domainMin, domainMax } = ramp
    if (
      rampResolvesPerRegion(shape) &&
      (domainMin === undefined || domainMax === undefined)
    ) {
      problems.push(
        found(
          'unpinned-span-ramp',
          `encoding.color.${domainMin === undefined ? 'domainMin' : 'domainMax'}`,
          "a span's ramp resolves an open end against each region's own extremes, so its colours agree across regions only with domainMin and domainMax both pinned",
        ),
      )
    }
  }
  const { minBpPerPx = 0, maxBpPerPx = 0 } = mark
  if (minBpPerPx > 0 && maxBpPerPx > 0 && minBpPerPx >= maxBpPerPx) {
    problems.push(
      found(
        'empty-zoom-range',
        'minBpPerPx',
        `never draws: minBpPerPx ${minBpPerPx} is not below maxBpPerPx ${maxBpPerPx}`,
      ),
    )
  }
  problems.push(...stepProblems(stepsOf(mark)))
  const fields = madeFields(mark)
  if (fields && y && !isJexl(y) && !fields.has(y)) {
    problems.push(
      found(
        'unwritten-y',
        'encoding.y',
        `reads "${y}", which its steps do not write; they leave ${[...fields].join(', ')}`,
      ),
    )
  }
  return problems
}

/**
 * The problems of a `marks` list as a config snapshot holds it: shorthands
 * lifted, defaults left off. `facet` is the display's facet as written, naming
 * the field its sections stack by; under one, a rowless mark stands on each
 * section's first row by design. `transform` is the display's own steps,
 * checked as a mark's are and reported with no mark. A file's own spelling
 * goes through the schema's lift first, which `jbrowse validate` does from the
 * generated manifest.
 */
export function markProblems(
  marks: readonly MarkSnapshot[],
  facet?: FacetSnapshot,
  transform: readonly StepSnapshot[] = [],
): MarkProblem[] {
  const faceted = typeof facet?.field === 'string' && facet.field !== ''
  const problems: MarkProblem[] = [
    ...stepProblems(transform),
    ...marks.flatMap((mark, i) =>
      ownProblems(mark).map(p => ({ mark: i, ...p })),
    ),
  ]
  for (const [i, mark] of marks.entries()) {
    for (const [j, other] of marks.entries()) {
      if (i === j || !drawTogether(mark, other)) {
        continue
      }
      if (
        !faceted &&
        shapeOf(mark) !== 'span' &&
        !banded(mark) &&
        banded(other)
      ) {
        problems.push({
          mark: i,
          ...found(
            'value-beside-rows',
            'encoding.row',
            `stands in the first of the rows mark ${j} bands the plot into, its axis repeated per row`,
          ),
        })
      }
      if (i > j && packs(mark) && packs(other)) {
        problems.push({
          mark: i,
          ...found(
            'two-packings',
            'transform',
            `packs rows of its own, as mark ${j} does, and the two share row numbers; one pileup in the display's transform packs them together, with each mark's encoding.row naming the field the pileup writes`,
          ),
        })
      }
      if (i > j && mark.source === 'density' && other.source === 'density') {
        problems.push({
          mark: i,
          ...found(
            'second-density-mark',
            'source',
            `mark ${j} already stands in for the density sidecar here`,
          ),
        })
      }
    }
  }
  return problems
}

/**
 * A problem as one line of a notice: `mark 0 encoding.y: …`, or
 * `transform.0.step: …` for the display's own step.
 */
export function problemText({ mark, slot, message }: MarkProblem): string {
  return `${mark === undefined ? '' : `mark ${mark} `}${slot}: ${message}`
}
