// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from alignmentsUniforms.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

// Scalar twins of alignmentsUniforms.slang, transliterated from slangc's WGSL so
// the Canvas2D and SVG paths run the shader's own math. See adr-051.

export function frequencyAlpha(base: number, freq: number): number {
  return (base + (freq * (1.0 - base)))
}

export function frequencyFadeGate(base: number, freq: number, filterByFrequency: boolean): number {
  let _S1: boolean
  if (filterByFrequency) {
    _S1 = (base < 1.0)
  } else {
    _S1 = false
  }
  let _S2: number
  if (_S1) {
    _S2 = frequencyAlpha(base, freq)
  } else {
    _S2 = 1.0
  }
  return _S2
}

export function arcYFraction(yBp: number, arcsYDomainBp: number, useLog: boolean): number {
  if (useLog) {
    return (Math.log2(Math.max(1.0, (yBp))) / Math.log2(Math.max(2.0, arcsYDomainBp)))
  }
  let _S3: number
  if ((arcsYDomainBp > 0.0)) {
    _S3 = ((yBp) / arcsYDomainBp)
  } else {
    _S3 = 0.0
  }
  return _S3
}

export function arcYOffsetPx(yBp: number, arcsYDomainBp: number, useLog: boolean, availH: number): number {
  return Math.min(availH, (arcYFraction(yBp, arcsYDomainBp, useLog) * availH))
}
