// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from wiggle.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './wiggle.iface.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./wiggle.wgsl.generated.ts'),
  glsl: () => import('./wiggle.glsl.generated.ts'),
}
