packages:
  - 'packages/*'
  - 'products/*'
  - 'plugins/*'
  - 'tools/gfa-to-tabix'
  - 'tools/graph-truth-extractor'
  - 'tools/graph-server'
blockExoticSubdeps: true
allowBuilds:
  canvas: true
  electron: true
  electron-chromedriver: true
  esbuild: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAge: '1440'
minimumReleaseAgeExclude:
  - '@gmod/*'
  - 'g2p_mapper'
  - 'ixixx'
  - 'gff-nostream'
