packages:
  - 'packages/*'
  - 'products/*'
  - 'products/*/examples-site'
  - 'plugins/*'
  - 'website'
blockExoticSubdeps: true
allowBuilds:
  canvas: true
  core-js-pure: true
  electron: true
  electron-chromedriver: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
minimumReleaseAge: '1440'
minimumReleaseAgeExclude:
  - '@gmod/*'
  - 'g2p_mapper'
  - 'ixixx'
  - 'gff-nostream'
  - 'generic-filehandle2'
  - '@jbrowse/mobx-state-tree'
