import { type Loader, glob } from 'astro/loaders'
import { z } from 'astro/zod'
import { defineCollection } from 'astro:content'

const blogBase = new URL('../blog', import.meta.url).pathname
const docsBase = new URL('../docs', import.meta.url).pathname

const docsSchema = z.object({
  title: z.string(),
  description: z.string().optional(),
  sidebar_label: z.string().optional(),
  // Groups the page under a labeled section in both its guide's landing-page
  // index and the sidebar (see src/lib/guide-categories.ts). Only meaningful
  // for user_guides/config_guides/developer_guides pages.
  guide_category: z.string().optional(),
  // Buckets a tutorials/ page under a labeled section on the /docs/tutorials
  // landing page (src/pages/docs/tutorials/index.astro). Independent of
  // guide_category (which keeps every tutorial under the user guide's
  // "Tutorials" section). Pages without it fall into a trailing "More" bucket.
  tutorial_category: z.string().optional(),
  // introduction.md uses `slug: /` so the glob loader keys it at the docs root
  slug: z.string().optional(),
})

/**
 * Wrap the glob loader to remap the doc with `slug: /` frontmatter
 * (introduction.md) to id "index" so it serves as the docs root at /docs/.
 * The glob loader keys entries by filename, so the remap must look the entry
 * up by its parsed `slug`, not by a "/" store key.
 */
function jbrowseDocsLoader(): Loader {
  const inner = glob({
    base: docsBase,
    // `docs/img` and `docs/static` are symlinks into `static/`; skip both so
    // asset-adjacent READMEs (e.g. the R-export gallery index) aren't loaded as
    // doc pages.
    pattern: ['**/*.md', '!**/CLAUDE.md*', '!img/**', '!static/**'],
    // Autogenerated config/model docs are CamelCase files (BaseTrack.md) but
    // their cross-links — and hand-written links to them — use the lowercase
    // Docusaurus `id:` slug (../basetrack). Lowercase ids so routes match.
    generateId: ({ entry }) => entry.replace(/\.md$/, '').toLowerCase(),
  })
  return {
    name: 'jbrowse-docs-loader',
    async load(ctx) {
      await inner.load(ctx)
      const rootEntry = ctx.store.values().find(e => e.data.slug === '/')
      if (rootEntry) {
        ctx.store.delete(rootEntry.id)
        ctx.store.set({ ...rootEntry, id: 'index' })
      }
    },
  }
}

export const collections = {
  blog: defineCollection({
    loader: glob({
      base: blogBase,
      pattern: '*.md',
      generateId: ({ entry }) => entry.replace(/\.md$/, ''),
    }),
    schema: z.object({
      title: z.string(),
      date: z.coerce.date(),
      description: z.string().optional(),
      tags: z.array(z.string()).optional(),
      author: z.string().optional(),
      author_url: z.string().optional(),
    }),
  }),
  docs: defineCollection({
    loader: jbrowseDocsLoader(),
    schema: docsSchema,
  }),
}
