declare module '@gmod/jbrowse-core/util/offscreenCanvasPonyfill'
declare module '@gmod/jbrowse-core/util/range'
declare module '@gmod/jbrowse-core/configuration'
declare module '@gmod/jbrowse-core/pluggableElementTypes/renderers/BoxRendererType'
declare module '@gmod/jbrowse-core/util/range'
