import { HELPERS } from './rHelpers.generated.ts'
import { frameChain, packagesFor, renderPlot, rStr } from './rplot.ts'

import type { Plot, RFrame } from './rplot.ts'

export interface Region {
  refName: string
  start: number
  end: number
}

export interface Panel {
  variable: string
  plot: Plot
  /** Relative vertical share, carried from the display height. */
  heightWeight?: number
}

/** ggsave refuses a dimension over 50 inches, and a panel stack can ask for more. */
const MAX_INCHES = 50
const INCHES_PER_WEIGHT = 2
const WIDTH_INCHES = 10
const DPI = 150
/** The figure's width in device px, the zoom an `auto` bin follows. */
export const FIGURE_WIDTH_PX = WIDTH_INCHES * DPI

/**
 * The helpers a piece of R calls, and the helpers those call, so a script
 * carries what it reaches for and nothing else. Read off the code rather than
 * declared beside it: a declaration can miss an edge, and a missed edge is a
 * script calling a function it never defined.
 */
export function helpersIn(code: string) {
  const seen = new Set<string>()
  const scan = (text: string) => {
    for (const name of Object.keys(HELPERS)) {
      if (!seen.has(name) && new RegExp(`\\b${name}\\s*\\(`).test(text)) {
        seen.add(name)
        scan(HELPERS[name]!)
      }
    }
  }
  scan(code)
  return [...seen].sort()
}

function regionsFrame(regions: readonly Region[]) {
  const col = (f: (r: Region) => string | number) => regions.map(f).join(', ')
  return `regions <- region_layout(data.frame(
  chrom = c(${col(r => rStr(r.refName))}),
  start = c(${col(r => r.start)}),
  end = c(${col(r => r.end)})))`
}

function figureHeight(panels: readonly Panel[]) {
  const weight = panels.reduce((a, p) => a + (p.heightWeight ?? 1), 0)
  return Math.min(MAX_INCHES, Math.max(2, weight * INCHES_PER_WEIGHT))
}

function stacked(panels: readonly Panel[]) {
  if (panels.length === 1) {
    return panels[0]!.variable
  }
  const weights = panels.map(p => p.heightWeight ?? 1).join(', ')
  return `${panels.map(p => p.variable).join(' / ')} +
  patchwork::plot_layout(heights = c(${weights}))`
}

function rootOf(f: RFrame): RFrame {
  return f.parent ? rootOf(f.parent) : f
}

/**
 * Every frame the panels read, parents first, each once. A derived frame may
 * keep its base's name, since it is a further step over the same binding; two
 * unrelated frames may not, since every frame is built before any panel draws
 * and the second read would overwrite the first.
 */
function framesOf(panels: readonly Panel[]) {
  const frames = new Set<RFrame>()
  const rootByName = new Map<string, RFrame>()
  for (const p of panels) {
    for (const l of p.plot.layers) {
      for (const f of frameChain(l.frame)) {
        const root = rootOf(f)
        const other = rootByName.get(f.name)
        if (other && other !== root) {
          throw new Error(
            `two panels read unrelated frames both named ${f.name}: give each panel's frame a name of its own`,
          )
        }
        rootByName.set(f.name, root)
        frames.add(f)
      }
    }
  }
  return [...frames]
}

/**
 * A whole script: libraries, the helpers the panels reached for, the region
 * layout, each panel's frame and plot, and the save.
 *
 * `notes` lands in the header rather than nowhere — a figure that quietly
 * differs from the view it claims to redraw is the failure worth the lines.
 */
export function assembleRScript({
  regions,
  panels,
  notes = [],
  out = 'figure.png',
}: {
  regions: readonly Region[]
  panels: readonly Panel[]
  notes?: readonly string[]
  out?: string
}) {
  const packages = new Set(['ggplot2'])
  for (const p of panels) {
    for (const pkg of packagesFor(p.plot)) {
      packages.add(pkg)
    }
  }
  if (panels.length > 1) {
    packages.add('patchwork')
  }
  const frames = framesOf(panels).map(f => f.statements)
  const plots = panels.map(p => renderPlot(p.variable, p.plot))
  const layout = regionsFrame(regions)
  const helpers = helpersIn([layout, ...frames, ...plots].join('\n'))
  return [
    '# Generated by JBrowse 2 — this script redraws the view from its own data.',
    '# Edit it: it is plain rtracklayer and ggplot2, with no bespoke package.',
    ...(notes.length
      ? [
          '#',
          '# What this figure does not show:',
          ...notes.map(n => `#   - ${n}`),
        ]
      : []),
    '',
    `suppressPackageStartupMessages({
${[...packages]
  .sort()
  .map(p => `  library(${p})`)
  .join('\n')}
})`,
    '',
    helpers.map(h => HELPERS[h]).join('\n\n'),
    '',
    layout,
    '',
    frames.join('\n\n'),
    '',
    plots.join('\n\n'),
    '',
    `ggsave(${rStr(out)}, ${stacked(panels)},
  width = ${WIDTH_INCHES}, height = ${figureHeight(panels)}, dpi = ${DPI})`,
    '',
  ].join('\n')
}
