// Generated by scripts/generateReExports.ts — do not edit by hand.
// What jbrowse-react-circular-genome-view serves to a runtime plugin beyond @jbrowse/core: every subpath of every @jbrowse package it bundles.
// Regenerate with `pnpm autogen`.
import coreLibs from '@jbrowse/core/ReExports/modules'
import * as m0 from '@jbrowse/add-track-core'
import * as m1 from '@jbrowse/alignments-core'
import * as m2 from '@jbrowse/alignments-core/CoverageTooltipTables'
import * as m3 from '@jbrowse/cigar-utils'
import * as m4 from '@jbrowse/display-kit/BlockMsg'
import * as m5 from '@jbrowse/display-kit/BottomRightIndicators'
import * as m6 from '@jbrowse/display-kit/ChromeHighlight'
import * as m7 from '@jbrowse/display-kit/ChromeLegend'
import * as m8 from '@jbrowse/display-kit/coarseTier'
import * as m9 from '@jbrowse/display-kit/CoarseTierMixin'
import * as m10 from '@jbrowse/display-kit/coarseTierPhase'
import * as m11 from '@jbrowse/display-kit/configSchema'
import * as m12 from '@jbrowse/display-kit/const'
import * as m13 from '@jbrowse/display-kit/ContextMenuMixin'
import * as m14 from '@jbrowse/display-kit/densityTier'
import * as m15 from '@jbrowse/display-kit/densityTierConfigSchemaFields'
import * as m16 from '@jbrowse/display-kit/densityTierMenu'
import * as m17 from '@jbrowse/display-kit/DensityTierMixin'
import * as m18 from '@jbrowse/display-kit/displayAutoruns'
import * as m19 from '@jbrowse/display-kit/DisplayBackgroundProgress'
import * as m20 from '@jbrowse/display-kit/DisplayChrome'
import * as m21 from '@jbrowse/display-kit/DisplayChromeBase'
import * as m22 from '@jbrowse/display-kit/DisplayContextMenu'
import * as m23 from '@jbrowse/display-kit/DisplayErrorBar'
import * as m24 from '@jbrowse/display-kit/DisplayLoadingOverlay'
import * as m25 from '@jbrowse/display-kit/DisplayRenderErrorOverlay'
import * as m26 from '@jbrowse/display-kit/DisplayStatusChromeBase'
import * as m27 from '@jbrowse/display-kit/fetchEachRegion'
import * as m28 from '@jbrowse/display-kit/fetchInputs'
import * as m29 from '@jbrowse/display-kit/FetchMixin'
import * as m30 from '@jbrowse/display-kit/foundationDisplayPhase'
import * as m31 from '@jbrowse/display-kit/foundationPaintInert'
import * as m32 from '@jbrowse/display-kit/foundationSvgReady'
import * as m33 from '@jbrowse/display-kit/foundationView'
import * as m34 from '@jbrowse/display-kit/GlobalFetchMixin'
import * as m35 from '@jbrowse/display-kit/groupByMenu'
import * as m36 from '@jbrowse/display-kit/GroupLabelBox'
import * as m37 from '@jbrowse/display-kit/GroupLabelChips'
import * as m38 from '@jbrowse/display-kit/groupLabelChipStyles'
import * as m39 from '@jbrowse/display-kit/groupLabelStyle'
import * as m40 from '@jbrowse/display-kit/heightMode'
import * as m41 from '@jbrowse/display-kit/heightModeConfigSchemaFields'
import * as m42 from '@jbrowse/display-kit/heightModeMenu'
import * as m43 from '@jbrowse/display-kit/HeightModeMixin'
import * as m44 from '@jbrowse/display-kit/HiddenGroupsMixin'
import * as m45 from '@jbrowse/display-kit/highlightHost'
import * as m46 from '@jbrowse/display-kit/installClearHoverOnViewportChange'
import * as m47 from '@jbrowse/display-kit/installGlobalFetchAutorun'
import * as m48 from '@jbrowse/display-kit/installPerRegionFetchAutoruns'
import * as m49 from '@jbrowse/display-kit/KeyedFetchMixin'
import * as m50 from '@jbrowse/display-kit/legendHost'
import * as m51 from '@jbrowse/display-kit/LegendMixin'
import * as m52 from '@jbrowse/display-kit/MultiRegionDisplayMixin'
import * as m53 from '@jbrowse/display-kit/planRegionFetch'
import * as m54 from '@jbrowse/display-kit/regionCommit'
import * as m55 from '@jbrowse/display-kit/regionHost'
import * as m56 from '@jbrowse/display-kit/regionTooLargeConfigSchemaFields'
import * as m57 from '@jbrowse/display-kit/RegionTooLargeMixin'
import * as m58 from '@jbrowse/display-kit/regionTooLargeUtils'
import * as m59 from '@jbrowse/display-kit/renderDisplaySvg'
import * as m60 from '@jbrowse/display-kit/rpcArgs'
import * as m61 from '@jbrowse/display-kit/rpcPropsCacheKey'
import * as m62 from '@jbrowse/display-kit/SkippedFeaturesIndicator'
import * as m63 from '@jbrowse/display-kit/squashToHeightMenuItem'
import * as m64 from '@jbrowse/display-kit/stableIdentityComputed'
import * as m65 from '@jbrowse/display-kit/StoredHoverMixin'
import * as m66 from '@jbrowse/display-kit/subPixelBinBp'
import * as m67 from '@jbrowse/display-kit/TooLargeMessage'
import * as m68 from '@jbrowse/display-kit/TrackControl'
import * as m69 from '@jbrowse/display-kit/trackHeightConfigSchemaFields'
import * as m70 from '@jbrowse/display-kit/TrackHeightIndicator'
import * as m71 from '@jbrowse/display-kit/TrackHeightMixin'
import * as m72 from '@jbrowse/display-kit/triangleTransform'
import * as m73 from '@jbrowse/display-kit/triangleYScalar'
import * as m74 from '@jbrowse/display-kit/types'
import * as m75 from '@jbrowse/display-kit/viewportEmpty'
import * as m76 from '@jbrowse/display-ui'
import * as m77 from '@jbrowse/display-ui/embed'
import * as m78 from '@jbrowse/display-ui/yAxisConstants'
import * as m79 from '@jbrowse/ld-core'
import * as m80 from '@jbrowse/plugin-authentication'
import * as m81 from '@jbrowse/plugin-canvas'
import * as m82 from '@jbrowse/plugin-canvas/LinearBasicDisplay/baseStateModel'
import * as m83 from '@jbrowse/plugin-canvas/LinearBasicDisplay/stateModel'
import * as m84 from '@jbrowse/plugin-circular-view'
import * as m85 from '@jbrowse/plugin-config'
import * as m86 from '@jbrowse/plugin-data-management'
import * as m87 from '@jbrowse/plugin-linear-genome-view'
import * as m88 from '@jbrowse/plugin-sequence'
import * as m89 from '@jbrowse/plugin-variants'
import * as m90 from '@jbrowse/product-core'
import * as m91 from '@jbrowse/render-core/blockClipUtils'
import * as m92 from '@jbrowse/render-core/canvas2dUtils'
import * as m93 from '@jbrowse/render-core/canvasContext'
import * as m94 from '@jbrowse/render-core/colorRampLut'
import * as m95 from '@jbrowse/render-core/computePipeline'
import * as m96 from '@jbrowse/render-core/contractReports'
import * as m97 from '@jbrowse/render-core/coverageBand'
import * as m98 from '@jbrowse/render-core/coverageBandBuffers'
import * as m99 from '@jbrowse/render-core/createRenderingBackend'
import * as m100 from '@jbrowse/render-core/displayPhase'
import * as m101 from '@jbrowse/render-core/encodeMemo'
import * as m102 from '@jbrowse/render-core/gpuDevice'
import * as m103 from '@jbrowse/render-core/graphicsCapabilities'
import * as m104 from '@jbrowse/render-core/hal'
import * as m105 from '@jbrowse/render-core/installUpload'
import * as m106 from '@jbrowse/render-core/instanceCache'
import * as m107 from '@jbrowse/render-core/instancePass'
import * as m108 from '@jbrowse/render-core/marks'
import * as m109 from '@jbrowse/render-core/marks/backend'
import * as m110 from '@jbrowse/render-core/marks/colorFill'
import * as m111 from '@jbrowse/render-core/marks/drawAgainstHit'
import * as m112 from '@jbrowse/render-core/marks/glyphPaint'
import * as m113 from '@jbrowse/render-core/marks/hit'
import * as m114 from '@jbrowse/render-core/namedReactions'
import * as m115 from '@jbrowse/render-core/OverlayCanvas'
import * as m116 from '@jbrowse/render-core/perRegionRenderingBackend'
import * as m117 from '@jbrowse/render-core/regionDataMap'
import * as m118 from '@jbrowse/render-core/renderBlock'
import * as m119 from '@jbrowse/render-core/RenderCanvas'
import * as m120 from '@jbrowse/render-core/renderingBackendBase'
import * as m121 from '@jbrowse/render-core/RenderLifecycleMixin'
import * as m122 from '@jbrowse/render-core/scoreScale'
import * as m123 from '@jbrowse/render-core/ScrollLockedOverlay'
import * as m124 from '@jbrowse/render-core/shaders/antialias'
import * as m125 from '@jbrowse/render-core/shaders/barMarkIface'
import * as m126 from '@jbrowse/render-core/shaders/capsule'
import * as m127 from '@jbrowse/render-core/shaders/capsuleConsts'
import * as m128 from '@jbrowse/render-core/shaders/coverageBar'
import * as m129 from '@jbrowse/render-core/shaders/coverageIndicator'
import * as m130 from '@jbrowse/render-core/shaders/coverageInterbase'
import * as m131 from '@jbrowse/render-core/shaders/coverageMod'
import * as m132 from '@jbrowse/render-core/shaders/coverageSnp'
import * as m133 from '@jbrowse/render-core/shaders/hpmath'
import * as m134 from '@jbrowse/render-core/shaders/pointGlyph'
import * as m135 from '@jbrowse/render-core/shaders/pointGlyphConsts'
import * as m136 from '@jbrowse/render-core/shaders/pointMark'
import * as m137 from '@jbrowse/render-core/shaders/pointMarkConsts'
import * as m138 from '@jbrowse/render-core/shaders/pointMarkIface'
import * as m139 from '@jbrowse/render-core/shaders/rowRect'
import * as m140 from '@jbrowse/render-core/shaders/rowRectConsts'
import * as m141 from '@jbrowse/render-core/shaders/scoreScale'
import * as m142 from '@jbrowse/render-core/shaders/spanMarkIface'
import * as m143 from '@jbrowse/render-core/sharedBackendKey'
import * as m144 from '@jbrowse/render-core/slangPass'
import * as m145 from '@jbrowse/render-core/useGraphicsCapabilities'
import * as m146 from '@jbrowse/render-core/useRenderingBackend'
import * as m147 from '@jbrowse/render-core/useTabVisibilityRerender'
import * as m148 from '@jbrowse/sv-core'
import * as m149 from '@jbrowse/synteny-core'
import * as m150 from '@jbrowse/tree-sidebar'
import * as m151 from '@jbrowse/wiggle-core'
import * as m152 from '@jbrowse/wiggle-core/constants'
import * as m153 from '@jbrowse/wiggle-core/normalize'
import * as m154 from '@jbrowse/wiggle-core/renderingBackendTypes'
import * as m155 from '@jbrowse/wiggle-core/ScorePlotChrome'
import * as m156 from '@jbrowse/wiggle-core/ScorePlotSvgFrame'

const libs: Record<string, unknown> = {
  ...coreLibs,
  '@jbrowse/add-track-core': m0,
  '@jbrowse/alignments-core': m1,
  '@jbrowse/alignments-core/CoverageTooltipTables': m2,
  '@jbrowse/cigar-utils': m3,
  '@jbrowse/display-kit/BlockMsg': m4.default,
  '@jbrowse/display-kit/BottomRightIndicators': m5.default,
  '@jbrowse/display-kit/ChromeHighlight': m6.default,
  '@jbrowse/display-kit/ChromeLegend': m7.default,
  '@jbrowse/display-kit/coarseTier': m8,
  '@jbrowse/display-kit/CoarseTierMixin': m9.default,
  '@jbrowse/display-kit/coarseTierPhase': m10,
  '@jbrowse/display-kit/configSchema': m11.default,
  '@jbrowse/display-kit/const': m12,
  '@jbrowse/display-kit/ContextMenuMixin': m13,
  '@jbrowse/display-kit/densityTier': m14,
  '@jbrowse/display-kit/densityTierConfigSchemaFields': m15,
  '@jbrowse/display-kit/densityTierMenu': m16,
  '@jbrowse/display-kit/DensityTierMixin': m17.default,
  '@jbrowse/display-kit/displayAutoruns': m18,
  '@jbrowse/display-kit/DisplayBackgroundProgress': m19.default,
  '@jbrowse/display-kit/DisplayChrome': { ...m20, __esModule: true },
  '@jbrowse/display-kit/DisplayChromeBase': m21.default,
  '@jbrowse/display-kit/DisplayContextMenu': m22,
  '@jbrowse/display-kit/DisplayErrorBar': m23.default,
  '@jbrowse/display-kit/DisplayLoadingOverlay': m24.default,
  '@jbrowse/display-kit/DisplayRenderErrorOverlay': m25.default,
  '@jbrowse/display-kit/DisplayStatusChromeBase': m26.default,
  '@jbrowse/display-kit/fetchEachRegion': m27,
  '@jbrowse/display-kit/fetchInputs': m28,
  '@jbrowse/display-kit/FetchMixin': { ...m29, __esModule: true },
  '@jbrowse/display-kit/foundationDisplayPhase': m30,
  '@jbrowse/display-kit/foundationPaintInert': m31,
  '@jbrowse/display-kit/foundationSvgReady': m32,
  '@jbrowse/display-kit/foundationView': m33,
  '@jbrowse/display-kit/GlobalFetchMixin': { ...m34, __esModule: true },
  '@jbrowse/display-kit/groupByMenu': m35,
  '@jbrowse/display-kit/GroupLabelBox': { ...m36, __esModule: true },
  '@jbrowse/display-kit/GroupLabelChips': m37,
  '@jbrowse/display-kit/groupLabelChipStyles': m38,
  '@jbrowse/display-kit/groupLabelStyle': m39,
  '@jbrowse/display-kit/heightMode': m40,
  '@jbrowse/display-kit/heightModeConfigSchemaFields': m41,
  '@jbrowse/display-kit/heightModeMenu': m42,
  '@jbrowse/display-kit/HeightModeMixin': { ...m43, __esModule: true },
  '@jbrowse/display-kit/HiddenGroupsMixin': { ...m44, __esModule: true },
  '@jbrowse/display-kit/highlightHost': m45,
  '@jbrowse/display-kit/installClearHoverOnViewportChange': m46,
  '@jbrowse/display-kit/installGlobalFetchAutorun': m47,
  '@jbrowse/display-kit/installPerRegionFetchAutoruns': m48,
  '@jbrowse/display-kit/KeyedFetchMixin': m49.default,
  '@jbrowse/display-kit/legendHost': m50,
  '@jbrowse/display-kit/LegendMixin': { ...m51, __esModule: true },
  '@jbrowse/display-kit/MultiRegionDisplayMixin': { ...m52, __esModule: true },
  '@jbrowse/display-kit/planRegionFetch': m53,
  '@jbrowse/display-kit/regionCommit': m54,
  '@jbrowse/display-kit/regionHost': m55,
  '@jbrowse/display-kit/regionTooLargeConfigSchemaFields': m56,
  '@jbrowse/display-kit/RegionTooLargeMixin': m57.default,
  '@jbrowse/display-kit/regionTooLargeUtils': m58,
  '@jbrowse/display-kit/renderDisplaySvg': m59,
  '@jbrowse/display-kit/rpcArgs': m60,
  '@jbrowse/display-kit/rpcPropsCacheKey': m61,
  '@jbrowse/display-kit/SkippedFeaturesIndicator': { ...m62, __esModule: true },
  '@jbrowse/display-kit/squashToHeightMenuItem': m63,
  '@jbrowse/display-kit/stableIdentityComputed': m64,
  '@jbrowse/display-kit/StoredHoverMixin': m65.default,
  '@jbrowse/display-kit/subPixelBinBp': m66,
  '@jbrowse/display-kit/TooLargeMessage': m67.default,
  '@jbrowse/display-kit/TrackControl': m68.default,
  '@jbrowse/display-kit/trackHeightConfigSchemaFields': m69,
  '@jbrowse/display-kit/TrackHeightIndicator': m70.default,
  '@jbrowse/display-kit/TrackHeightMixin': m71.default,
  '@jbrowse/display-kit/triangleTransform': m72,
  '@jbrowse/display-kit/triangleYScalar': m73,
  '@jbrowse/display-kit/types': m74,
  '@jbrowse/display-kit/viewportEmpty': m75,
  '@jbrowse/display-ui': m76,
  '@jbrowse/display-ui/embed': m77,
  '@jbrowse/display-ui/yAxisConstants': m78,
  '@jbrowse/ld-core': m79,
  '@jbrowse/plugin-authentication': m80.default,
  '@jbrowse/plugin-canvas': { ...m81, __esModule: true },
  '@jbrowse/plugin-canvas/LinearBasicDisplay/baseStateModel': { ...m82, __esModule: true },
  '@jbrowse/plugin-canvas/LinearBasicDisplay/stateModel': m83.default,
  '@jbrowse/plugin-circular-view': { ...m84, __esModule: true },
  '@jbrowse/plugin-config': { ...m85, __esModule: true },
  '@jbrowse/plugin-data-management': { ...m86, __esModule: true },
  '@jbrowse/plugin-linear-genome-view': { ...m87, __esModule: true },
  '@jbrowse/plugin-sequence': m88.default,
  '@jbrowse/plugin-variants': { ...m89, __esModule: true },
  '@jbrowse/product-core': m90,
  '@jbrowse/render-core/blockClipUtils': m91,
  '@jbrowse/render-core/canvas2dUtils': m92,
  '@jbrowse/render-core/canvasContext': m93,
  '@jbrowse/render-core/colorRampLut': m94,
  '@jbrowse/render-core/computePipeline': m95,
  '@jbrowse/render-core/contractReports': m96,
  '@jbrowse/render-core/coverageBand': m97,
  '@jbrowse/render-core/coverageBandBuffers': m98,
  '@jbrowse/render-core/createRenderingBackend': m99,
  '@jbrowse/render-core/displayPhase': m100,
  '@jbrowse/render-core/encodeMemo': m101,
  '@jbrowse/render-core/gpuDevice': m102,
  '@jbrowse/render-core/graphicsCapabilities': m103,
  '@jbrowse/render-core/hal': m104,
  '@jbrowse/render-core/installUpload': m105,
  '@jbrowse/render-core/instanceCache': m106,
  '@jbrowse/render-core/instancePass': m107,
  '@jbrowse/render-core/marks': m108,
  '@jbrowse/render-core/marks/backend': m109,
  '@jbrowse/render-core/marks/colorFill': m110,
  '@jbrowse/render-core/marks/drawAgainstHit': m111,
  '@jbrowse/render-core/marks/glyphPaint': m112,
  '@jbrowse/render-core/marks/hit': m113,
  '@jbrowse/render-core/namedReactions': m114,
  '@jbrowse/render-core/OverlayCanvas': m115.default,
  '@jbrowse/render-core/perRegionRenderingBackend': m116,
  '@jbrowse/render-core/regionDataMap': m117,
  '@jbrowse/render-core/renderBlock': m118,
  '@jbrowse/render-core/RenderCanvas': m119.default,
  '@jbrowse/render-core/renderingBackendBase': m120,
  '@jbrowse/render-core/RenderLifecycleMixin': m121,
  '@jbrowse/render-core/scoreScale': m122,
  '@jbrowse/render-core/ScrollLockedOverlay': m123,
  '@jbrowse/render-core/shaders/antialias': m124,
  '@jbrowse/render-core/shaders/barMarkIface': m125,
  '@jbrowse/render-core/shaders/capsule': m126,
  '@jbrowse/render-core/shaders/capsuleConsts': m127,
  '@jbrowse/render-core/shaders/coverageBar': m128,
  '@jbrowse/render-core/shaders/coverageIndicator': m129,
  '@jbrowse/render-core/shaders/coverageInterbase': m130,
  '@jbrowse/render-core/shaders/coverageMod': m131,
  '@jbrowse/render-core/shaders/coverageSnp': m132,
  '@jbrowse/render-core/shaders/hpmath': m133,
  '@jbrowse/render-core/shaders/pointGlyph': m134,
  '@jbrowse/render-core/shaders/pointGlyphConsts': m135,
  '@jbrowse/render-core/shaders/pointMark': m136,
  '@jbrowse/render-core/shaders/pointMarkConsts': m137,
  '@jbrowse/render-core/shaders/pointMarkIface': m138,
  '@jbrowse/render-core/shaders/rowRect': m139,
  '@jbrowse/render-core/shaders/rowRectConsts': m140,
  '@jbrowse/render-core/shaders/scoreScale': m141,
  '@jbrowse/render-core/shaders/spanMarkIface': m142,
  '@jbrowse/render-core/sharedBackendKey': m143,
  '@jbrowse/render-core/slangPass': m144,
  '@jbrowse/render-core/useGraphicsCapabilities': m145,
  '@jbrowse/render-core/useRenderingBackend': m146,
  '@jbrowse/render-core/useTabVisibilityRerender': m147,
  '@jbrowse/sv-core': m148,
  '@jbrowse/synteny-core': m149,
  '@jbrowse/tree-sidebar': m150,
  '@jbrowse/wiggle-core': m151,
  '@jbrowse/wiggle-core/constants': m152,
  '@jbrowse/wiggle-core/normalize': m153,
  '@jbrowse/wiggle-core/renderingBackendTypes': m154,
  '@jbrowse/wiggle-core/ScorePlotChrome': m155,
  '@jbrowse/wiggle-core/ScorePlotSvgFrame': m156,
}

export default libs
