import React, { useState } from 'react'
import {
  ErrorMessage,
  FileSelector,
  Dialog,
  AssemblySelector,
} from '@jbrowse/core/ui'
import { getSession } from '@jbrowse/core/util'
import { openLocation } from '@jbrowse/core/util/io'
import { isSessionWithShareURL } from '@jbrowse/core/util/types'

// icons
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import ImportIcon from '@mui/icons-material/Publish'
import {
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Button,
  DialogContent,
  DialogActions,
  TextField,
  Typography,
} from '@mui/material'
import { observer } from 'mobx-react'
import { makeStyles } from 'tss-react/mui'

// locals
import { readSessionFromDynamo } from '../../sessionSharing'
import { fromUrlSafeB64 } from '../../utils'
import type { GridBookmarkModel } from '../../model'
import type { FileLocation } from '@jbrowse/core/util/types'

const useStyles = makeStyles()(theme => ({
  expandIcon: {
    color: theme.palette.tertiary.contrastText || '#fff',
  },
  minWidth: {
    minWidth: 500,
  },
}))

async function getBookmarksFromShareLink(shareLink: string, shareURL?: string) {
  const defaultURL = 'https://share.jbrowse.org/api/v1/'
  const urlParams = new URL(shareLink)
  const sessionQueryParam = urlParams.searchParams.get('bookmarks')
  const password = urlParams.searchParams.get('password')
  const decryptedSession = await readSessionFromDynamo(
    `${shareURL ?? defaultURL}load`,
    sessionQueryParam || '',
    password || '',
  )

  const sharedSession = JSON.parse(await fromUrlSafeB64(decryptedSession))
  return sharedSession.sharedBookmarks
}

function guessFileType(header: string) {
  return header.startsWith('chrom') && header.includes('assembly_name')
    ? 'TSV'
    : 'BED'
}

async function getBookmarksFromTSVFile(lines: string[]) {
  if (lines[0]!.startsWith('chrom')) {
    lines = lines.slice(1)
  }

  return lines
    .filter(f => !f.startsWith('#'))
    .map(line => {
      const [refName, start, end, label, assemblyName] = line.split('\t')
      return {
        assemblyName: assemblyName!,
        refName: refName!,
        start: +start!,
        end: +end!,
        label: label === '.' ? undefined : label,
      }
    })
}

async function getBookmarksFromBEDFile(lines: string[], selectedAsm: string) {
  return lines
    .filter(f => !f.startsWith('#'))
    .map(line => {
      const [refName, start, end, label] = line.split('\t')
      return {
        assemblyName: selectedAsm,
        refName: refName!,
        start: +start!,
        end: +end!,
        label: label === '.' ? undefined : label,
      }
    })
}

const ImportBookmarksDialog = observer(function ({
  onClose,
  model,
}: {
  onClose: () => void
  model: GridBookmarkModel
}) {
  const { classes } = useStyles()
  const [location, setLocation] = useState<FileLocation>()
  const [error, setError] = useState<unknown>()
  const [shareLink, setShareLink] = useState('')
  const session = getSession(model)
  const { assemblyNames } = session
  const [selectedAsm, setSelectedAsm] = useState(assemblyNames[0]!)
  const [expanded, setExpanded] = useState<
    'shareLinkAccordion' | 'fileAccordion'
  >('shareLinkAccordion')

  return (
    <Dialog open onClose={onClose} maxWidth="xl" title="Import bookmarks">
      <DialogContent className={classes.minWidth}>
        <Accordion
          expanded={expanded === 'shareLinkAccordion'}
          onChange={() => {
            setExpanded('shareLinkAccordion')
          }}
        >
          <AccordionSummary
            expandIcon={<ExpandMoreIcon className={classes.expandIcon} />}
          >
            <Typography
              style={{ display: 'flex', alignItems: 'center', gap: '5px' }}
            >
              Import from share link
            </Typography>
          </AccordionSummary>
          <AccordionDetails>
            <Typography>
              Paste a bookmark share link generated by the 'Share' button from
              the bookmarks widget
            </Typography>
            <TextField
              label="Enter Share URL"
              variant="outlined"
              fullWidth
              value={shareLink}
              onChange={e => {
                setShareLink(e.target.value)
              }}
            />
          </AccordionDetails>
        </Accordion>
        <Accordion
          expanded={expanded === 'fileAccordion'}
          onChange={() => {
            setExpanded('fileAccordion')
          }}
        >
          <AccordionSummary
            expandIcon={<ExpandMoreIcon className={classes.expandIcon} />}
          >
            <Typography>Import from file</Typography>
          </AccordionSummary>
          <AccordionDetails>
            <FileSelector
              location={location}
              setLocation={setLocation}
              name="File"
              description={`Choose a BED or TSV format file to import. Required TSV column headers are "chrom, start, end, label, assembly_name".`}
            />
            <AssemblySelector
              onChange={val => {
                setSelectedAsm(val)
              }}
              helperText={'Select the assembly for BED file.'}
              session={session}
              selected={selectedAsm}
            />
          </AccordionDetails>
        </Accordion>
        {error ? <ErrorMessage error={error} /> : null}
      </DialogContent>
      <DialogActions>
        <Button variant="contained" color="secondary" onClick={onClose}>
          Cancel
        </Button>
        <Button
          data-testid="dialogImport"
          variant="contained"
          color="primary"
          disabled={!location && !shareLink}
          startIcon={<ImportIcon />}
          onClick={async () => {
            try {
              if (expanded === 'fileAccordion' && location) {
                const data = await openLocation(location).readFile('utf8')
                const lines = data.split(/\n|\r\n|\r/).filter(f => !!f.trim())
                const fileType = guessFileType(lines[0]!)
                if (fileType === 'BED') {
                  model.importBookmarks(
                    await getBookmarksFromBEDFile(lines, selectedAsm),
                  )
                } else {
                  // TSV
                  model.importBookmarks(await getBookmarksFromTSVFile(lines))
                }
              } else if (
                expanded === 'shareLinkAccordion' &&
                shareLink &&
                isSessionWithShareURL(session)
              ) {
                model.importBookmarks(
                  await getBookmarksFromShareLink(shareLink, session.shareURL),
                )
              }
              onClose()
            } catch (e) {
              console.error(e)
              setError(e)
            }
          }}
        >
          Import
        </Button>
      </DialogActions>
    </Dialog>
  )
})
export default ImportBookmarksDialog
