#!/bin/bash
# Setup script for chr20_region GetSubgraph validation
# Generates tabix indices and runs validation tests

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GFA_FILE="$REPO_ROOT/test_data/chr20_region.gfa"
TABIX_TOOL="$REPO_ROOT/tools/gfa-to-tabix/target/release/gfa-to-tabix"

echo "=== CHR20 GetSubgraph Validation Setup ==="
echo ""

# Check if GFA file exists
if [ ! -f "$GFA_FILE" ]; then
  echo "❌ Error: chr20_region.gfa not found at $GFA_FILE"
  echo "   This file should be generated by graph-truth-extractor setup"
  exit 1
fi

echo "✓ Found GFA file: $GFA_FILE"

# Check if gfa-to-tabix is built
if [ ! -f "$TABIX_TOOL" ]; then
  echo "❌ Error: gfa-to-tabix not built at $TABIX_TOOL"
  echo "   Build it with: cd tools/gfa-to-tabix && cargo build --release"
  exit 1
fi

echo "✓ Found gfa-to-tabix tool: $TABIX_TOOL"
echo ""

# Check if indices already exist
INDICES_EXIST=true
for file in \
  "$REPO_ROOT/test_data/chr20_region.pos.bed.gz" \
  "$REPO_ROOT/test_data/chr20_region.synteny.bed.gz" \
  "$REPO_ROOT/test_data/chr20_region.edges.spatial.bed.gz" \
  "$REPO_ROOT/test_data/chr20_region.seglens.bin"; do
  if [ ! -f "$file" ]; then
    INDICES_EXIST=false
    break
  fi
done

if [ "$INDICES_EXIST" = true ]; then
  echo "✓ Tabix indices already exist"
else
  echo "⏳ Generating tabix indices from GFA..."
  echo ""

  cd "$REPO_ROOT"
  "$TABIX_TOOL" \
    "$GFA_FILE" \
    "$REPO_ROOT/test_data/chr20_region"

  echo ""
  echo "✓ Tabix indices generated successfully"
fi

echo ""
echo "=== Running GetSubgraph Validation Tests ==="
echo ""

cd "$REPO_ROOT"
npm test -- \
  plugins/comparative-adapters/src/GfaTabixAdapter/__tests__/getSubgraph-validation.test.ts \
  --verbose

echo ""
echo "=== Validation Complete ==="
echo ""
echo "✓ All GetSubgraph validation tests passed!"
echo ""
echo "Summary:"
echo "  - GFA file: $GFA_FILE"
echo "  - Tabix indices: test_data/chr20_region.*.bed.gz*"
echo "  - Test results: See above"
echo ""
