// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from barMark.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './barMark.iface.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./barMark.wgsl.generated.ts'),
  glsl: () => import('./barMark.glsl.generated.ts'),
}
