// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from lineStepMark.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './lineStepMark.iface.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./lineStepMark.wgsl.generated.ts'),
  glsl: () => import('./lineStepMark.glsl.generated.ts'),
}
