// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from lineCommon.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

// Scalar twins of lineCommon.slang, transliterated from slangc's WGSL so
// the Canvas2D and SVG paths run the shader's own math. See adr-051.

export function lineColorAlongY(rampMode: number, colorFromY: number, overridden: boolean): boolean {
  let _t0: boolean
  if ((rampMode == 3)) {
    _t0 = (colorFromY != 0)
  } else {
    _t0 = false
  }
  if (_t0) {
    _t0 = !overridden
  } else {
    _t0 = false
  }
  return _t0
}
