// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from markColor.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

export const RAMP_NONE = 0

export const RAMP_LINEAR = 1

export const RAMP_LOG = 2

export const RAMP_NO_VALUE_BITS = 2143289345

export const RAMP_NO_VALUE_COLOR = 4289703855

export const RAMP_NOT_A_NUMBER_COLOR = 4286611584
