import fs from 'fs'

import { buildConsensusTally, computeConsensus } from '@jbrowse/alignments-core'
import { firstValueFrom } from 'rxjs'
import { toArray } from 'rxjs/operators'

import BamAdapter from '../BamAdapter/BamAdapter.ts'
import configSchema from '../BamAdapter/configSchema.ts'

import type { ConsensusFeature } from '@jbrowse/alignments-core'

// Parity tests for our port of samtools' calculate_consensus_simple (see the
// attribution and license header on computeConsensus.ts). The windows below are
// the checked-in regression surface; they were chosen from a full-contig sweep
// against real samtools, done once by hand and recorded here so the result
// isn't lost:
//
//   samtools 1.23.1, all 50kb of volvox ctgA, callFract 0.75 / hetFract 0.5
//     ambiguity off vs `samtools consensus -a -m simple`
//        -> 0 differing positions out of 50000
//     ambiguity on vs the same plus `-A`
//        -> 1 differing position out of 50000, at ctgA:49680
//
// That single position is the intended uncapped divergence, not a bug. Its
// pileup is A=1, C=1, G=2: G wins at weight 16, het-fract needs 8, and A and C
// both sit at exactly 8. samtools folds in only the runner-up and emits 'R'
// (used score 24/32, exactly its 0.75 call-fract); folding in all three gives
// 'V'. It is a depth-4 column, so it is a thin example of the tetraploid/pooled
// case the uncapped fold exists for, but it is arithmetically the same case.
//
// Worth re-running after any change to the scoring or threshold arithmetic;
// three windows can't catch what a 50kb sweep can.

// Reference ctgA sequence, loaded once and sliced per region.
function loadCtgA() {
  const fa = fs.readFileSync(
    require.resolve('../../test_data/volvox.fa'),
    'utf8',
  )
  const lines = fa.split('\n')
  const seq: string[] = []
  let inCtgA = false
  for (const line of lines) {
    if (line.startsWith('>')) {
      inCtgA = line.slice(1).split(/\s/)[0] === 'ctgA'
    } else if (inCtgA) {
      seq.push(line.trim())
    }
  }
  return seq.join('')
}

function makeAdapter() {
  return new BamAdapter(
    configSchema.create({
      bamLocation: {
        localPath: require.resolve('../../test_data/volvox-sorted.bam'),
        locationType: 'LocalPathLocation',
      },
      index: {
        location: {
          localPath: require.resolve('../../test_data/volvox-sorted.bam.bai'),
          locationType: 'LocalPathLocation',
        },
      },
    }),
  )
}

// Golden strings generated by:
//   samtools consensus -a -m simple --show-ins no -r ctgA:S-E volvox-sorted.bam
// No `-A`, so these run with hetFract left undefined (ambiguity off), which is
// also computeConsensus's default. See GOLDEN_AMBIG below for the `-A` side.
const GOLDEN: Record<string, string> = {
  '0-200':
    'NNTTGTTGCGGAGTTGAACAACGGCATTAGGAACACTTCCGTCTCTCACTTTTATACGATTATGATTGGTTCTTTAGCCTTGGTTTAGATTGGTAGTAGTAGCGGCGCTAATGCTACCTGAATTGAGAACTCGAGCGGGGGCTAGGCAAATTCTGATTCAGCCTGACTTCTCTTGGAACCCTGCCCATAAATCAAAGGGT',
  '999-1200':
    'GCCGAGCGCAATAACCCCCGGAAAGCACTTGCTACTGGGAGGCGGGTTTATCCATCGGCAATAGGGGTTATCAGTACTACCAAGAAGATTGTGAAGATATTAACAGCATTGAAAAAAGTTCGGACTGGGCATGAAACGTGTGTCAGAGTTAGAGTCCTTGAGGGACTGAATGGGTTTGTCCCAGGCCCAAGCTTGAGGTGG',
  '4999-5200':
    'TTCTTCCCTGCATCTTCCGGATTCCTTCTTCTTGTCGGAGAATTCGCCGCTCGATCAAACTCATCATTGGTACTTATTGACCGTTTCATGCTATTACACCGGTACACTGATGATAACGCTGCGGTTTTATCCCCCCCAATACGCGCACACACGCTTCTTTCGGTGCGTCCTGTCGTACCCCTATTGCGCATCATGGCACTC',
  // The two positions that GOLDEN_AMBIG below calls lowercase 'cg': with
  // ambiguity off samtools gives up on them entirely and emits NN. Pinning the
  // same window in both modes is what proves the base/gap fold is doing the
  // work, rather than the window simply being unambiguous.
  '19800-20000':
    'TAACATATCTGCCACGTTGACAAGCCGCTATTATGAATTCAGGGTTGGATACTATTATGGCCCTTCACGGTCACTTGTAGGANNGCCCCAAACAGGATTAGTAAAGTCGGTGGTCTAAGTGTAAGCGATAGGCAAACTGCGGTTATTCGCGTAGACCGCTTGATGATGTAAAATAACAGTTTTCATGTCTTTGCAATTAC',
}

// ctgA:2601-2800 has a real 60/40-ish split (samtools' own scoring/het-fract
// arithmetic, not a 3+-allele case) that becomes a 'K' (G/T) under --ambig —
// generated with:
//   samtools consensus -a -m simple --show-ins no -A -r ctgA:2601-2800 volvox-sorted.bam
// Confirmed byte-identical between real samtools -A and computeConsensus at
// both their shared defaults (callFract 0.75, hetFract 0.5).
// ctgA:19801-20000 is the only place in ctgA where samtools -A emits a
// lowercase base, i.e. its base+gap convention (IUPAC has no base/gap code).
// Both positions are NN with ambiguity off, so this is the direct check that
// our gap-folding matches samtools rather than just our reading of it.
const GOLDEN_AMBIG: Record<string, string> = {
  '2600-2800':
    'GCCGATATTATAGGGGCAATAGGTCTCACCCACCACGGGTGTAKATTTAACGCCCTAAGTAGTTAACGGAGACTATTAAACAATTATGCACGTGAAAGATTAGGGTACTGCACACGTGTCACGTTGACGATGTAAACACCATAAAGGTTGTTCTGTGATGCGATGCCCATACCTGCGGTGCAACGTCCTAAACTTATGCG',
  '19800-20000':
    'TAACATATCTGCCACGTTGACAAGCCGCTATTATGAATTCAGGGTTGGATACTATTATGGCCCTTCACGGTCACTTGTAGGAcgGCCCCAAACAGGATTAGTAAAGTCGGTGGTCTAAGTGTAAGCGATAGGCAAACTGCGGTTATTCGCGTAGACCGCTTGATGATGTAAAATAACAGTTTTCATGTCTTTGCAATTAC',
}

// ctgA:15001-15200 contains a read-supported insertion that wins its column;
// generated with the same command minus `--show-ins no`. Exercises the real
// forEachMismatch inserted-base decoding end to end.
const GOLDEN_WITH_INSERTIONS = {
  '15000-15200':
    'CCACATTCAGCTCTCGGTAACATGGGAGGCTTGTGGTTGCACCGTAAAAGGGGGATAGCCCATCCATCCTGTAAACCAACAATCGCGCGTAGCTTAATACGCTCACATTAGACATTCGATCGAGAGACCTGGTTTCAAGAGCCTTCCCTTTTGCTTTAGTGGGCCCAAATCGCAACCCTGCTCCCCTCCCTTACGCCTTAT',
}

test.each(Object.keys(GOLDEN_WITH_INSERTIONS))(
  'consensus with insertions matches samtools for ctgA %s',
  async key => {
    const [start, end] = key.split('-').map(Number) as [number, number]
    const ctgA = loadCtgA()
    const adapter = makeAdapter()
    const region = { assemblyName: 'volvox', refName: 'ctgA', start, end }
    const features = (await firstValueFrom(
      adapter.getFeatures(region).pipe(toArray()),
    )) as unknown as ConsensusFeature[]

    const tally = buildConsensusTally(features, region)
    // Pins callFract to samtools' own default explicitly, independent of
    // computeConsensus's — this test validates the core scoring/arithmetic
    // against real samtools, not whatever the UI defaults happen to be.
    const consensus = computeConsensus(ctgA.slice(start, end), tally, {
      includeInsertions: true,
      callFract: 0.75,
    })

    expect(consensus).toBe(
      GOLDEN_WITH_INSERTIONS[key as keyof typeof GOLDEN_WITH_INSERTIONS],
    )
  },
)

test.each(Object.keys(GOLDEN))(
  'consensus matches samtools --mode simple for ctgA %s',
  async key => {
    const [start, end] = key.split('-').map(Number) as [number, number]
    const ctgA = loadCtgA()
    const adapter = makeAdapter()
    const region = { assemblyName: 'volvox', refName: 'ctgA', start, end }
    const features = (await firstValueFrom(
      adapter.getFeatures(region).pipe(toArray()),
    )) as unknown as ConsensusFeature[]

    const tally = buildConsensusTally(features, region)
    const consensus = computeConsensus(ctgA.slice(start, end), tally, {
      includeInsertions: false,
      callFract: 0.75,
    })

    expect(consensus).toBe(GOLDEN[key])
  },
)

test.each(Object.keys(GOLDEN_AMBIG))(
  'consensus matches samtools --ambig for ctgA %s',
  async key => {
    const [start, end] = key.split('-').map(Number) as [number, number]
    const ctgA = loadCtgA()
    const adapter = makeAdapter()
    const region = { assemblyName: 'volvox', refName: 'ctgA', start, end }
    const features = (await firstValueFrom(
      adapter.getFeatures(region).pipe(toArray()),
    )) as unknown as ConsensusFeature[]

    const tally = buildConsensusTally(features, region)
    const consensus = computeConsensus(ctgA.slice(start, end), tally, {
      includeInsertions: false,
      callFract: 0.75,
      hetFract: 0.5,
    })

    expect(consensus).toBe(GOLDEN_AMBIG[key])
  },
)
