import fs from 'fs'

import { buildConsensusTally, computeConsensus } from '@jbrowse/alignments-core'
import { firstValueFrom } from 'rxjs'
import { toArray } from 'rxjs/operators'

import BamAdapter from '../BamAdapter/BamAdapter.ts'
import configSchema from '../BamAdapter/configSchema.ts'

import type { ConsensusFeature } from '@jbrowse/alignments-core'

// Reference ctgA sequence, loaded once and sliced per region.
function loadCtgA() {
  const fa = fs.readFileSync(
    require.resolve('../../test_data/volvox.fa'),
    'utf8',
  )
  const lines = fa.split('\n')
  const seq: string[] = []
  let inCtgA = false
  for (const line of lines) {
    if (line.startsWith('>')) {
      inCtgA = line.slice(1).split(/\s/)[0] === 'ctgA'
    } else if (inCtgA) {
      seq.push(line.trim())
    }
  }
  return seq.join('')
}

function makeAdapter() {
  return new BamAdapter(
    configSchema.create({
      bamLocation: {
        localPath: require.resolve('../../test_data/volvox-sorted.bam'),
        locationType: 'LocalPathLocation',
      },
      index: {
        location: {
          localPath: require.resolve('../../test_data/volvox-sorted.bam.bai'),
          locationType: 'LocalPathLocation',
        },
      },
    }),
  )
}

// Golden strings generated by:
//   samtools consensus -a -m simple --show-ins no -r ctgA:S-E volvox-sorted.bam
// computeConsensus always attempts IUPAC ambiguity folding (there's no
// separate on/off flag), so this is really validating against `-A` — these
// three windows just happen to contain no position where a runner-up base
// clears het-fract, so samtools' plain and -A output coincide here. See
// GOLDEN_AMBIG below for a window that actually exercises an ambiguity code.
const GOLDEN: Record<string, string> = {
  '0-200':
    'NNTTGTTGCGGAGTTGAACAACGGCATTAGGAACACTTCCGTCTCTCACTTTTATACGATTATGATTGGTTCTTTAGCCTTGGTTTAGATTGGTAGTAGTAGCGGCGCTAATGCTACCTGAATTGAGAACTCGAGCGGGGGCTAGGCAAATTCTGATTCAGCCTGACTTCTCTTGGAACCCTGCCCATAAATCAAAGGGT',
  '999-1200':
    'GCCGAGCGCAATAACCCCCGGAAAGCACTTGCTACTGGGAGGCGGGTTTATCCATCGGCAATAGGGGTTATCAGTACTACCAAGAAGATTGTGAAGATATTAACAGCATTGAAAAAAGTTCGGACTGGGCATGAAACGTGTGTCAGAGTTAGAGTCCTTGAGGGACTGAATGGGTTTGTCCCAGGCCCAAGCTTGAGGTGG',
  '4999-5200':
    'TTCTTCCCTGCATCTTCCGGATTCCTTCTTCTTGTCGGAGAATTCGCCGCTCGATCAAACTCATCATTGGTACTTATTGACCGTTTCATGCTATTACACCGGTACACTGATGATAACGCTGCGGTTTTATCCCCCCCAATACGCGCACACACGCTTCTTTCGGTGCGTCCTGTCGTACCCCTATTGCGCATCATGGCACTC',
}

// ctgA:2601-2800 has a real 60/40-ish split (samtools' own scoring/het-fract
// arithmetic, not a 3+-allele case) that clears samtools' --ambig default and
// becomes a 'K' (G/T) — generated with:
//   samtools consensus -a -m simple --show-ins no -A -r ctgA:2601-2800 volvox-sorted.bam
// Confirmed byte-identical between real samtools -A and computeConsensus at
// both their shared defaults (callFract 0.75, hetFract 0.5).
const GOLDEN_AMBIG: Record<string, string> = {
  '2600-2800':
    'GCCGATATTATAGGGGCAATAGGTCTCACCCACCACGGGTGTAKATTTAACGCCCTAAGTAGTTAACGGAGACTATTAAACAATTATGCACGTGAAAGATTAGGGTACTGCACACGTGTCACGTTGACGATGTAAACACCATAAAGGTTGTTCTGTGATGCGATGCCCATACCTGCGGTGCAACGTCCTAAACTTATGCG',
}

// ctgA:15001-15200 contains a read-supported insertion that wins its column;
// generated with the same command minus `--show-ins no`. Exercises the real
// forEachMismatch inserted-base decoding end to end.
const GOLDEN_WITH_INSERTIONS = {
  '15000-15200':
    'CCACATTCAGCTCTCGGTAACATGGGAGGCTTGTGGTTGCACCGTAAAAGGGGGATAGCCCATCCATCCTGTAAACCAACAATCGCGCGTAGCTTAATACGCTCACATTAGACATTCGATCGAGAGACCTGGTTTCAAGAGCCTTCCCTTTTGCTTTAGTGGGCCCAAATCGCAACCCTGCTCCCCTCCCTTACGCCTTAT',
}

test.each(Object.keys(GOLDEN_WITH_INSERTIONS))(
  'consensus with insertions matches samtools for ctgA %s',
  async key => {
    const [start, end] = key.split('-').map(Number) as [number, number]
    const ctgA = loadCtgA()
    const adapter = makeAdapter()
    const region = { assemblyName: 'volvox', refName: 'ctgA', start, end }
    const features = (await firstValueFrom(
      adapter.getFeatures(region).pipe(toArray()),
    )) as unknown as ConsensusFeature[]

    const tally = buildConsensusTally(features, region)
    // Pins call/het-fract to samtools' own defaults explicitly, independent
    // of computeConsensus's own defaults — this test validates the core
    // scoring/arithmetic against real samtools, not whatever the UI defaults
    // happen to be.
    const consensus = computeConsensus(ctgA.slice(start, end), tally, {
      includeInsertions: true,
      callFract: 0.75,
      hetFract: 0.5,
    })

    expect(consensus).toBe(
      GOLDEN_WITH_INSERTIONS[key as keyof typeof GOLDEN_WITH_INSERTIONS],
    )
  },
)

test.each(Object.keys(GOLDEN))(
  'consensus matches samtools --mode simple for ctgA %s',
  async key => {
    const [start, end] = key.split('-').map(Number) as [number, number]
    const ctgA = loadCtgA()
    const adapter = makeAdapter()
    const region = { assemblyName: 'volvox', refName: 'ctgA', start, end }
    const features = (await firstValueFrom(
      adapter.getFeatures(region).pipe(toArray()),
    )) as unknown as ConsensusFeature[]

    const tally = buildConsensusTally(features, region)
    const consensus = computeConsensus(ctgA.slice(start, end), tally, {
      includeInsertions: false,
      callFract: 0.75,
      hetFract: 0.5,
    })

    expect(consensus).toBe(GOLDEN[key])
  },
)

test.each(Object.keys(GOLDEN_AMBIG))(
  'consensus matches samtools --ambig for ctgA %s',
  async key => {
    const [start, end] = key.split('-').map(Number) as [number, number]
    const ctgA = loadCtgA()
    const adapter = makeAdapter()
    const region = { assemblyName: 'volvox', refName: 'ctgA', start, end }
    const features = (await firstValueFrom(
      adapter.getFeatures(region).pipe(toArray()),
    )) as unknown as ConsensusFeature[]

    const tally = buildConsensusTally(features, region)
    const consensus = computeConsensus(ctgA.slice(start, end), tally, {
      includeInsertions: false,
      callFract: 0.75,
      hetFract: 0.5,
    })

    expect(consensus).toBe(GOLDEN_AMBIG[key])
  },
)
