// Scans docs/**/*.md(x) for <Figure src="/img/<name>.png" .../> usages and
// cross-references each against screenshotLiveUrls (built from
// screenshot-specs.ts) to classify every figure as autogenerated (tracked by
// a spec, so remark-figure.ts auto-adds a live link) or manual (a
// hand-curated screenshot/diagram with no spec — gets a live link only if the
// doc author added an explicit link= attribute). Writes figure-manifest.json
// so a reviewer can see at a glance which manual figures still have no way
// for a reader to reach a live, interactive view.
//
// Run with: node --experimental-strip-types scripts/audit-figures.ts
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

import { screenshotLiveUrls, screenshotSpecNames } from './screenshot-specs.ts'

const DOCS_DIR = join(import.meta.dirname, '..', 'docs')
const MANIFEST_PATH = join(import.meta.dirname, 'figure-manifest.json')

interface FigureEntry {
  name: string
  // autogenerated: produced by a screenshot-specs.ts spec (gets an auto live
  // link via remark-figure.ts). jbrowse-img: a static render produced by the
  // @jbrowse/img CLI (jb2export) and copied in by generate-img-doc.ts — also
  // autogenerated, but from the README pipeline, and has no interactive live
  // view to link to. manual: a hand-curated screenshot/diagram with neither.
  type: 'autogenerated' | 'jbrowse-img' | 'manual'
  liveUrl?: string
  docs: string[]
}

// Figures under /img/jbrowse-img/ are rendered by the @jbrowse/img CLI and
// copied into static/img/ by generate-img-doc.ts (driven by the example
// commands in products/jbrowse-img/README.md), so they are autogenerated even
// though no screenshot-specs.ts spec tracks them.
function isJbrowseImg(name: string) {
  return name.startsWith('jbrowse-img/')
}

function findDocFiles(dir: string): string[] {
  return readdirSync(dir).flatMap(entry => {
    const path = join(dir, entry)
    return statSync(path).isDirectory()
      ? findDocFiles(path)
      : /\.mdx?$/.test(entry)
        ? [path]
        : []
  })
}

const figureRe = /<Figure\s+([\s\S]*?)\s*\/>/g
const attrRe = /(\w+)=(?:"([^"]*)"|'([^']*)')/g

function parseAttrs(str: string): Record<string, string> {
  const attrs: Record<string, string> = {}
  attrRe.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = attrRe.exec(str)) !== null) {
    attrs[m[1]!] = m[2] ?? m[3] ?? ''
  }
  return attrs
}

const manifest: Record<string, FigureEntry> = {}

for (const docPath of findDocFiles(DOCS_DIR)) {
  const relPath = relative(join(import.meta.dirname, '..'), docPath)
  const text = readFileSync(docPath, 'utf8')
  figureRe.lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = figureRe.exec(text)) !== null) {
    const attrs = parseAttrs(match[1]!)
    const src = attrs.src ?? ''
    const name = src.replace(/^\/img\//, '').replace(/\.png$/, '')
    if (!name) {
      continue
    }
    const existing = manifest[name]
    if (existing) {
      existing.docs.push(relPath)
      continue
    }
    const trackedUrl = screenshotLiveUrls[name]
    // a combined figure links several specs via `links="Label=spec,..."`; treat
    // the first as its live URL so it isn't flagged as an unlinked manual figure
    const firstLinkSpec = (attrs.links ?? '')
      .split(',')[0]
      ?.split('=')[1]
      ?.trim()
    const liveUrl =
      attrs.link ??
      trackedUrl ??
      (firstLinkSpec ? screenshotLiveUrls[firstLinkSpec] : undefined)
    // A figure is autogenerated when a spec produces it — even an embedded or
    // localhost capture with no public live URL to link to. jbrowse-img specs
    // are also in `specs`, so test them first to keep their own bucket.
    const type = isJbrowseImg(name)
      ? 'jbrowse-img'
      : screenshotSpecNames.has(name)
        ? 'autogenerated'
        : 'manual'
    manifest[name] = {
      name,
      type,
      ...(liveUrl ? { liveUrl } : {}),
      docs: [relPath],
    }
  }
}

const sorted = Object.fromEntries(
  Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)),
)
writeFileSync(MANIFEST_PATH, `${JSON.stringify(sorted, null, 2)}\n`)

const entries = Object.values(sorted)
const autogenerated = entries.filter(f => f.type === 'autogenerated')
const jbrowseImg = entries.filter(f => f.type === 'jbrowse-img')
const manual = entries.filter(f => f.type === 'manual')
const untracked = manual.filter(f => !f.liveUrl)
console.log(
  `${entries.length} figures (${autogenerated.length} autogenerated, ${jbrowseImg.length} jbrowse-img, ${manual.length} manual)`,
)
if (untracked.length) {
  console.log(`\n${untracked.length} manual figures have no live link:`)
  for (const f of untracked) {
    console.log(`  ${f.name}  (${f.docs.join(', ')})`)
  }
}
