// Verifies every doc under website/docs/ is reachable from the sidebar
// (sidebars.json). Most guide directories (user_guides, config_guides,
// developer_guides, tutorials, config, models, api) are pulled in via
// `autogenerated` entries and can't drift, but the standalone pages (the
// quickstarts, the Embedding & scripting group, cli, faq) are hand-listed, so
// one could land on disk yet never appear in the sidebar nav. This check fails
// on exactly that: a doc no navigation path leads to.
//
// The sidebar-resolution logic here mirrors src/lib/docs-sidebar.ts
// (getAutoItems depth match + entrySlug). Run: `pnpm check-sidebar`.
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const docsDir = join(import.meta.dirname, '..', 'docs')
const sidebarPath = join(import.meta.dirname, '..', 'sidebars.json')

type SidebarItem =
  | string
  | { type: 'category'; label: string; items: SidebarItem[] }
  | { type: 'autogenerated'; dirName: string }
  | { type: 'link'; label: string; to: string }

// Slug for a doc file: path under docs/, lowercased, without .md. The content
// loader lowercases ids (CamelCase config docs route as lowercase), and
// introduction.md (`slug: /`) serves at the docs root, so its slug is "".
function slugOf(relPath: string, isRoot: boolean): string {
  return isRoot ? '' : relPath.replace(/\.md$/, '').toLowerCase()
}

function hasRootSlug(file: string): boolean {
  const text = readFileSync(file, 'utf8')
  const fm = /^---\n([\s\S]*?)\n---/.exec(text)
  return fm ? /^slug:\s*\/\s*$/m.test(fm[1]!) : false
}

function walk(dir: string, prefix = ''): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name
    if (entry.isDirectory()) {
      return walk(join(dir, entry.name), rel)
    }
    // CLAUDE.md is excluded from the docs collection (content.config.ts).
    return entry.name.endsWith('.md') && entry.name !== 'CLAUDE.md' ? [rel] : []
  })
}

const allSlugs = new Map(
  walk(docsDir).map(rel => [slugOf(rel, hasRootSlug(join(docsDir, rel))), rel]),
)

// Mirrors entrySlug(): strip a trailing /index, and treat "introduction" as the
// docs root (introduction.md is listed as "introduction" but serves at "").
function entrySlug(id: string): string {
  const s = id === 'introduction' ? '' : id
  return s.endsWith('/index') ? s.slice(0, -6) : s
}

// Mirrors getAutoItems(): every doc directly under dirName at the matching
// depth is pulled into the sidebar by an `autogenerated` entry.
function autoSlugs(dirName: string): string[] {
  const depth = dirName.split('/').length + 1
  return [...allSlugs.keys()].filter(
    slug => slug.startsWith(`${dirName}/`) && slug.split('/').length === depth,
  )
}

function collectCovered(items: SidebarItem[], covered: Set<string>): void {
  for (const item of items) {
    if (typeof item === 'string') {
      covered.add(entrySlug(item.toLowerCase()))
    } else if (item.type === 'link') {
      covered.add(entrySlug(item.to.toLowerCase()))
    } else if (item.type === 'autogenerated') {
      for (const slug of autoSlugs(item.dirName)) {
        covered.add(slug)
      }
    } else {
      collectCovered(item.items, covered)
    }
  }
}

// Reverse direction: a hand-listed string entry pointing at a doc that no
// longer exists (renamed/deleted) renders a dead 404 link in the nav with no
// build error. `link` entries can deliberately target non-doc pages (e.g. the
// /docs/tutorials/ index), so only string entries — which always name a
// docs-collection id — are validated here.
function collectListedDocSlugs(items: SidebarItem[], listed: Set<string>): void {
  for (const item of items) {
    if (typeof item === 'string') {
      listed.add(entrySlug(item.toLowerCase()))
    } else if (item.type === 'category') {
      collectListedDocSlugs(item.items, listed)
    }
  }
}

const sidebar = JSON.parse(readFileSync(sidebarPath, 'utf8'))
  .sidebar as SidebarItem[]
const covered = new Set<string>()
collectCovered(sidebar, covered)
const listed = new Set<string>()
collectListedDocSlugs(sidebar, listed)

const orphans = [...allSlugs.entries()].filter(([slug]) => !covered.has(slug))
const dangling = [...listed].filter(slug => !allSlugs.has(slug))

const problems: string[] = []
if (orphans.length > 0) {
  problems.push(
    `${orphans.length} doc(s) are not reachable from the sidebar (sidebars.json):`,
    ...orphans.map(([slug, rel]) => `  docs/${rel}  (slug: "${slug}")`),
    'Add each to website/sidebars.json (or an autogenerated dir it lives under).',
    '',
  )
}
if (dangling.length > 0) {
  problems.push(
    `${dangling.length} sidebar entr${dangling.length === 1 ? 'y' : 'ies'} point at a doc that does not exist:`,
    ...dangling.map(slug => `  "${slug}"`),
    'Remove or fix these entries in website/sidebars.json.',
    '',
  )
}

if (problems.length > 0) {
  console.error(problems.join('\n'))
  process.exit(1)
} else {
  console.log(
    `All ${allSlugs.size} docs are reachable; all sidebar entries resolve.`,
  )
}
