// Enforce how the hand-written docs present a JSON config block, the convention
// in website/docs/CLAUDE.md:
//
//   * a complete track config is tagged ```json addtrack, and a complete
//     assembly config ```json addassembly, so each renders the Config/CLI tab
//     pair (scripts/check-config-cli.ts then proves the derived command runs).
//     Only configs the CLI can actually express are flagged: the tag exists to
//     render that tab, so a config `deriveAddTrack`/`deriveAddAssembly` returns
//     null for (a synteny adapter's query/target slots, MultiWiggleAdapter
//     subadapters, any custom `displays`) has no tab to render and nothing to
//     fix. Flagging those would leave the author no remedy but an ALLOWED
//     entry, which records nothing a reader or a later change can use;
//   * no block presents a bare adapter or display object at the top level. Such
//     a blob reads as a track config — it even has a `type` — but pasting it
//     into `tracks` loads nothing. Nest it in the track/assembly it belongs to,
//     or, when the excerpt really is about the slot, prefix the parent key
//     (`"adapter": { ... }`), which this check accepts because the fence then
//     isn't standalone JSON.
//
// Autogenerated pages (config/, models/, api/) are skipped: their examples come
// from `#example` JSDoc in plugin source, so a violation there is fixed in the
// source, not here. ALLOWED lists the deliberate exceptions.
//
// Run: `pnpm check-config-blocks`
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import remarkGfm from 'remark-gfm'
import remarkParse from 'remark-parse'
import { unified } from 'unified'
import { visit } from 'unist-util-visit'

import { deriveAddAssembly } from '../src/lib/derive-add-assembly.ts'
import { deriveAddTrack } from '../src/lib/derive-add-track.ts'
import { isAddassembly, isAddtrack } from '../src/lib/remark-config-cli-tabs.ts'
import { reportProblems, walkFiles } from './check-utils.ts'

const docsDir = join(import.meta.dirname, '..', 'docs')

// blocks that stay untagged on purpose, keyed `<docs-relative path>#<trackId or
// assembly name>` so an exception survives the block moving down its page
const ALLOWED = new Map([
  [
    'tutorials/cli_desktop.md#sample',
    'shows what the CLI already wrote, not a track to add',
  ],
])

const parser = unified().use(remarkParse).use(remarkGfm)

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

// A parsed block is a complete track config when it carries the three things
// `tracks` entries always have; an assembly when it has a name plus a sequence
// (or the flattest `uri` shorthand for one).
function shape(obj: Record<string, unknown>) {
  const type = typeof obj.type === 'string' ? obj.type : ''
  return type.endsWith('Adapter')
    ? 'adapter'
    : type.endsWith('Display')
      ? 'display'
      : obj.trackId && obj.adapter && obj.type
        ? 'track'
        : obj.name && (obj.sequence ?? obj.uri)
          ? 'assembly'
          : 'other'
}

const problems: string[] = []
for (const file of walkFiles(docsDir, n => n.endsWith('.md'))) {
  const rel = file.slice(docsDir.length + 1)
  if (/^(config|models|api)\//.test(rel) || rel.endsWith('CLAUDE.md')) {
    continue
  }
  visit(parser.parse(readFileSync(file, 'utf8')), 'code', node => {
    if (node.lang !== 'json') {
      return
    }
    let parsed: unknown
    try {
      parsed = JSON.parse(node.value)
    } catch {
      // not standalone JSON: a key-prefixed excerpt (`"adapter": { ... }`),
      // which is unambiguous about where it goes
      return
    }
    if (!isRecord(parsed)) {
      return
    }
    const where = `${rel}:${node.position?.start.line ?? 0}`
    const id = parsed.trackId ?? parsed.name
    const kind = shape(parsed)
    const tagged = isAddtrack(node) || isAddassembly(node)
    if ((kind === 'adapter' || kind === 'display') && !tagged) {
      problems.push(
        `  ${where}`,
        `    → bare ${kind} object at the top level (type: ${String(parsed.type)}).`,
        `      Show the whole track/assembly it belongs to, or prefix the parent key.\n`,
      )
    } else if ((kind === 'track' || kind === 'assembly') && !tagged) {
      const derivable =
        kind === 'track'
          ? deriveAddTrack(parsed) !== null
          : deriveAddAssembly(parsed) !== null
      if (derivable && !ALLOWED.has(`${rel}#${String(id)}`)) {
        problems.push(
          `  ${where}`,
          `    → complete ${kind} config with no \`addtrack\`/\`addassembly\` tag,`,
          `      so it renders without its CLI tab. Tag the fence, or add it to`,
          `      ALLOWED in scripts/check-config-blocks.ts with the reason.\n`,
        )
      }
    }
  })
}

if (problems.length) {
  problems.unshift(
    `Found JSON config blocks that break the docs convention (see website/docs/CLAUDE.md):\n`,
  )
}
reportProblems(
  problems,
  'All hand-written JSON config blocks are whole configs, tagged for their CLI tab.',
)
