// Ratchets the number of over-length `<Figure caption="...">` strings in the
// hand-written docs.
//
// website/CLAUDE.md: "Captions name the tracks and the one visual takeaway. If a
// caption needs a paragraph of background, fix the figure." That rule had no
// enforcement, and captions are the one thing every new figure adds, so the long
// ones accumulated: a sweep found 37 past 400 characters, the two worst ~790,
// and what filled them was display legend (which hue means what, which stroke is
// a deletion) that the prose introducing the figure had usually already said.
//
// 400 is a proxy for a rule that is really about content, so this is a ratchet
// rather than a hard limit: the list below is the debt, and it may only shrink.
// A genuinely multi-panel figure naming each panel can be long and legitimately
// stays listed. What the ratchet stops is the quiet drift back.
//
// A tracked list, not a count, for the reason check-spec-recipes.ts spells out:
// a caption has a stable identity (its file plus its src), so the diff can name
// which figure regressed. A count would go green on a swap — trim one caption,
// bloat another — and would fire on whoever merged next rather than on whoever
// wrote the caption.
//
// Lengths are deliberately not stored: editing a listed caption from 455 to 460
// characters is not an event worth failing on, and storing lengths would churn
// the file on every prose tweak. The list changes only when a figure crosses the
// threshold, which is the event worth reviewing.
//
// Run `pnpm check-captions` to rewrite the list. CI runs `--check` through the
// root `pnpm check-docs`, alongside the other docs validators.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { check, checkOrWrite, docFiles } from './check-utils.ts'
import { docRelative, docsDir } from './paths.ts'

const listFile = join(import.meta.dirname, 'long-captions.txt')

// Generator output (generateConfigDocs et al.); its figures are not hand-written.
const GENERATED_PREFIXES = ['config/', 'models/', 'api/']

const MAX_CAPTION = 400

const HEADER = `# AUTO-GENERATED by scripts/check-captions.ts — do not edit by hand.
# Figures whose caption runs past ${MAX_CAPTION} characters, as "<doc> <src>".
# Regenerate with \`pnpm check-captions\`.
#
# Adding a line is a regression: keep the sentence naming the tracks and the one
# visual takeaway, and move the color/stroke/row glossary into the prose that
# introduces the figure. Removing one is the win. A multi-panel figure that has
# to name each panel is the legitimate reason to stay listed.
`

// Every <Figure> and <Video> in the corpus is a single-line self-closing tag
// with a double-quoted caption, so a line regex is enough and a JSX parser is
// not. A video's caption is under the same rule and the same ratchet: it sits in
// the same place on the page and does the same job, and a clip is if anything
// the more tempting thing to narrate at length.
const figureRe = /<(?:Figure|Video)\b[^>]*?caption="((?:[^"\\]|\\.)*)"[^>]*?>/g
const srcRe = /\bsrc="([^"]*)"/

const entries: string[] = []
for (const file of docFiles(docsDir)) {
  const rel = docRelative(file)
  if (GENERATED_PREFIXES.some(p => rel.startsWith(p))) {
    continue
  }
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    for (const match of line.matchAll(figureRe)) {
      if (match[1]!.length <= MAX_CAPTION) {
        continue
      }
      // The src is what makes the entry identifiable in a diff; a figure with
      // none is still worth listing, just by its doc alone.
      const src = srcRe.exec(match[0])?.[1] ?? '(no src)'
      entries.push(`${rel} ${src}`)
    }
  }
}
entries.sort()

const content = `${HEADER}${entries.join('\n')}\n`

// Name what moved rather than only that something did — the whole point of a
// tracked list over a count.
if (check) {
  const committed = new Set(
    readFileSync(listFile, 'utf8')
      .split('\n')
      .filter(l => l && !l.startsWith('#')),
  )
  const current = new Set(entries)
  const added = [...current].filter(e => !committed.has(e))
  const removed = [...committed].filter(e => !current.has(e))
  if (added.length > 0) {
    console.error(
      `${added.length} caption(s) newly past ${MAX_CAPTION} characters:\n${added
        .map(e => `  + ${e}`)
        .join(
          '\n',
        )}\n\nTrim to the tracks and the one visual takeaway, moving the legend ` +
        `into the prose that introduces the figure. If the figure is ` +
        `multi-panel and genuinely needs the length, run \`pnpm check-captions\` ` +
        `to record it.`,
    )
    process.exit(1)
  }
  if (removed.length > 0) {
    console.log(
      `${removed.length} caption(s) trimmed under ${MAX_CAPTION}:\n${removed
        .map(e => `  - ${e}`)
        .join('\n')}\n\nRun \`pnpm check-captions\` to hold the gain.`,
    )
    process.exit(1)
  }
}

checkOrWrite({
  path: listFile,
  content,
  label: `long-captions.txt (${entries.length} over ${MAX_CAPTION} chars)`,
  staleHint: 'run `pnpm check-captions`',
})
