// Validates the config slots a hand-written doc names against the schemas those
// slots actually come from.
//
// The gap this closes: NOTHING else catches a stale slot value. MST does not.
// Creating a JBrowse config with `displayDefaults: { showLabels: 'on' }` (a
// value retired when that slot became a five-way enum), or with a slot that no
// longer exists at all, throws nothing, warns nothing, and round-trips through
// `jbrowse add-track` clean — the object is stored verbatim and only quietly
// ignored once a display is instantiated in a browser. So `check-config-blocks`
// (shape) and `check-config-cli` (CLI round-trip) both pass on a config that
// cannot work, which is exactly how `showLabels: 'on'` sat in the cookbook.
//
// The oracle is `docs/config/*.md`. Those pages are regenerated by `pnpm
// autogen` from the `#slot` JSDoc at each definition site, so they cannot drift
// from the source: rename a slot, retire it, or add a value to its enum, and
// the table moves in the same commit. Parsing them needs no plugin imports,
// which matters because the website does not depend on `@jbrowse/core`.
//
// Deliberately conservative, so this can be a hard gate rather than a ratchet.
// Two rules, each of which can only fire on a definite error:
//
//   1. a literal value that NO declaration of that slot name could accept. A
//      slot name can be declared by many schemas and not always as the same
//      kind — `colorBy` is a stringEnum on SharedLDDisplay and a plain string
//      on the variant displays, `showLabels` is a five-way enum on the canvas
//      displays and a boolean on SharedLDDisplay. So the value is checked
//      against every declaration and only reported when all of them reject it:
//      "karyotype" survives via `colorBy`'s string declaration, while "on" is
//      rejected by the enums and cannot be a boolean either.
//   2. a key inside `displayDefaults` that no display schema anywhere defines.
//      Scoped to `displayDefaults` because that object is pure slot names;
//      elsewhere a JSON block mixes in shorthands (`uri`, `csi`) and adapter
//      payloads (`features`, `bigWigs`) that are not slots at all.
//
// What it does NOT check, on purpose: whether a valid slot belongs to the
// specific track type it was written under. Resolving track -> display types
// statically needs the registrations rather than the schema tables, and the
// false positives would outweigh the rarer error.
//
// Run: `pnpm check-doc-slots`.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { docFiles, reportProblems } from './check-utils.ts'
import { docRelative, docsDir } from './paths.ts'

// Slot rows come in two spellings, because only the kinds with a glossary entry
// are linked:
//   | <span id="slot-autoscale">**autoscale**</span><br>[`stringEnum`](...) (local, localsd) = <code>'local'</code> | ...
//   | <span id="slot-displaymode">**displayMode**</span><br>`maybeStringEnum` (normal, compact) = <code>'normal'</code> | ...
// Matching only the linked form silently drops every `maybeStringEnum` /
// `stringArray` slot, which then reads as "no schema defines this".
const SLOT_ROW =
  /id="slot-[a-z0-9.]+">\*\*([A-Za-z0-9.]+)\*\*<\/span><br>\[?`(\w+)`(?:\]\([^)]*\))?(?:\s*\(([^)]*)\))?/

// the `maybe` flavours are the promotable variants of the same kind
const ENUM_KINDS = new Set(['stringEnum', 'maybeStringEnum', 'enum'])

// Config vocabulary that is not a `#slot` row, so it never appears in the
// generated tables, but is routinely backticked in the same breath as a slot's
// values ("`showLabels` … goes in `displayDefaults`"). Without these the prose
// rule reads them as bad values.
const STRUCTURAL_KEYS = [
  'displayDefaults',
  'displays',
  'adapter',
  'uri',
  'type',
  'trackId',
  'displayId',
  'assemblyNames',
  'tracks',
  'assemblies',
  'sequence',
  'metadata',
  'category',
  'jexl',
  'configuration',
  'defaultSession',
  'plugins',
]
// kinds that cannot hold an arbitrary string, so a string literal against one of
// them is not an escape hatch for rule 1
const NON_STRING_KINDS = new Set([
  'number',
  'maybeNumber',
  'boolean',
  'maybeBoolean',
])

interface Decl {
  kind: string
  enumValues?: Set<string>
}

function buildInventory() {
  // slot name -> every declaration of it across all schemas
  const declsBySlot = new Map<string, Decl[]>()
  // slot names defined by at least one Display schema
  const displaySlots = new Set<string>()
  // "<page id>#<slot anchor>" -> that ONE schema's enum values. Prose links name
  // the exact type (`/docs/config/linearhicdisplay/#slot-colorscheme`), so a
  // value can be resolved against the schema the reader is being sent to rather
  // than against the union — which matters because a slot is not one type
  // everywhere: `displayMode` is (normal, compact, superCompact, collapsed) on
  // the canvas displays and (arcs, semicircles) on LinearArcDisplay.
  const enumByAnchor = new Map<string, Set<string>>()
  // every slot name and schema name, lowercased — a backticked token matching
  // one of these is prose naming a sibling setting, not a bad value
  const knownNames = new Set<string>(STRUCTURAL_KEYS.map(k => k.toLowerCase()))
  let schemaCount = 0

  for (const file of docFiles(join(docsDir, 'config'))) {
    const text = readFileSync(file, 'utf8')
    if (!/^title:\s*\S+/m.test(text)) {
      continue
    }
    schemaCount += 1
    const isDisplay = /^sidebar_label:\s*Display ->/m.test(text)
    const pageId = /^id:\s*(\S+)/m.exec(text)?.[1]
    const typeName = /^title:\s*(\S+)/m.exec(text)?.[1]
    if (typeName) {
      knownNames.add(typeName.toLowerCase())
    }
    for (const line of text.split('\n')) {
      const anchor = /id="(slot-[a-z0-9.]+)"/.exec(line)?.[1]
      const m = SLOT_ROW.exec(line)
      if (!m) {
        continue
      }
      const [, name, kind, values] = m
      const decl: Decl = { kind: kind! }
      if (ENUM_KINDS.has(kind!) && values) {
        decl.enumValues = new Set(values.split(',').map(v => v.trim()))
        if (pageId && anchor) {
          enumByAnchor.set(`${pageId}#${anchor}`, decl.enumValues)
        }
      }
      knownNames.add(name!.toLowerCase())
      const list = declsBySlot.get(name!) ?? []
      list.push(decl)
      declsBySlot.set(name!, list)
      if (isDisplay) {
        displaySlots.add(name!)
        // `labels.name` means a doc may legitimately write a `labels` object,
        // so the container counts as defined too
        if (name!.includes('.')) {
          displaySlots.add(name!.split('.')[0]!)
        }
      }
    }
  }
  assertInventoryParsed(declsBySlot, displaySlots)
  return { declsBySlot, displaySlots, enumByAnchor, knownNames, schemaCount }
}

// Rule 3, the prose one. Most of the risk lives here rather than in JSON blocks:
// a sweep counted 40 enum-slot mentions in prose against 30 inside fences, and
// two of the four stale values found by hand (the autoscale list, the
// `?renderer=` values) were prose.
//
// A doc that links a slot and then enumerates its values is the shape that goes
// stale. The link is what makes this checkable at all: it names the exact page,
// so the values resolve against that ONE schema instead of the union.
//
// Precision comes from only judging a paragraph that is clearly enumerating —
// it must already name at least two legal values — and from only flagging a
// backticked token that is not any known slot or schema name, so prose that
// mentions a sibling setting beside the values is left alone.
//
// It deliberately does not flag an INCOMPLETE list: abbreviating 14 rendering
// types down to the four worth naming is normal and correct, and there is no
// way to tell that from an omission.
function checkProse(
  text: string,
  inv: Inventory,
  report: (line: number, msg: string) => void,
) {
  const withoutFences = text.replaceAll(/```[\s\S]*?```/g, m =>
    m.replaceAll(/[^\n]/g, ' '),
  )
  for (const para of withoutFences.split(/\n\s*\n/)) {
    const link = /\/docs\/config\/([a-z0-9]+)\/?#(slot-[a-z0-9.]+)/.exec(para)
    if (!link) {
      continue
    }
    // both groups are required by the pattern, so a match has them
    const schema = link[1]!
    const anchor = link[2]!
    const legal = inv.enumByAnchor.get(`${schema}#${anchor}`)
    if (!legal) {
      continue
    }
    const ticked = [...para.matchAll(/`([A-Za-z][A-Za-z0-9_]*)`/g)].map(
      m => m[1]!,
    )
    if (ticked.filter(t => legal.has(t)).length < 2) {
      continue // not enumerating this slot's values
    }
    for (const token of new Set(ticked)) {
      if (legal.has(token) || inv.knownNames.has(token.toLowerCase())) {
        continue
      }
      report(
        text.slice(0, text.indexOf(para)).split('\n').length,
        `prose lists values for \`${anchor.replace('slot-', '')}\` but ` +
          `\`${token}\` is not one of them (${[...legal].sort().join(', ')})`,
      )
    }
  }
}

// Rule 4, over the generated pages themselves: a promotable row's prose promise
// ("…falling back to off") against the `promotedBase` printed in the same row.
//
// `products/jbrowse-web/src/tests/PromotedBaseDescriptions.test.ts` asks this of
// the runtime schema's `description`, and the two see different rows.
// `generateConfigDocs` renders the `#slot` JSDoc in PREFERENCE to `description`,
// so a slot carrying the sentence in only one of them is either checked there
// and unread by anyone, or read here and checked by nothing — and both exist:
// `SharedLDConfigSchema`'s `showLegend` puts it in the JSDoc with no
// `description`, `LinearMultiRowFeatureDisplay`'s `showLabels` the other way
// round. The page is the honest oracle, because it is the artifact the promise
// is actually made on, and it prints the base beside the prose.
const FALLBACK_PROMISE = /falling back to ([^;,.\s]+)/
const ROW_DEFAULT = /= <code>([^<]+)<\/code>/

// `on`/`off` for a boolean, a backticked member for an enum, a bare number —
// the three shapes the sentence takes. The page can run it straight into a
// trailing `<br>_advanced_`, so cut at the tag.
function promisedValue(text: string) {
  const word = text.split('<')[0]!
  if (word === 'on' || word === 'off') {
    return word === 'on'
  }
  if (/^`[^`]+`$/.test(word)) {
    return word.slice(1, -1)
  }
  const n = Number(word)
  return Number.isNaN(n) ? word : n
}

// the default column's own spelling: `false`, `2`, `'fixed'`
function declaredDefault(text: string) {
  if (text === 'true' || text === 'false') {
    return text === 'true'
  }
  if (/^'[^']*'$/.test(text)) {
    return text.slice(1, -1)
  }
  const n = Number(text)
  return Number.isNaN(n) ? text : n
}

function checkFallbackPromises(problems: Problem[]) {
  let rows = 0
  for (const file of docFiles(join(docsDir, 'config'))) {
    const rel = docRelative(file)
    const lines = readFileSync(file, 'utf8').split('\n')
    for (const [i, line] of lines.entries()) {
      const promise = FALLBACK_PROMISE.exec(line)
      const slot = SLOT_ROW.exec(line)
      if (!promise || !slot) {
        continue
      }
      rows += 1
      const shown = ROW_DEFAULT.exec(line)
      if (!shown) {
        problems.push({
          file: rel,
          line: i + 1,
          message:
            `\`${slot[1]}\` promises a fallback but its row prints no ` +
            `default, so a reader is told what it resolves to and never shown it`,
        })
        continue
      }
      const promised = promisedValue(promise[1]!)
      const base = declaredDefault(shown[1]!)
      if (promised !== base) {
        problems.push({
          file: rel,
          line: i + 1,
          message:
            `\`${slot[1]}\` says it falls back to ${JSON.stringify(promised)} ` +
            `but its promotedBase is ${JSON.stringify(base)}`,
        })
      }
    }
  }
  // Same canary reasoning as assertInventoryParsed: a sentence this stops
  // matching is a check that passes by reading nothing.
  if (rows < 40) {
    console.error(
      `check-doc-slots matched only ${rows} "falling back to" rows in ` +
        `docs/config/, expected 40+. FALLBACK_PROMISE or the generated ` +
        `description format probably changed.`,
    )
    process.exit(1)
  }
  return rows
}

// A regex over generated markdown degrades SILENTLY: if the table format shifts,
// fewer rows match, the inventory shrinks, and every doc passes because nothing
// is known to be checkable any more. That is not hypothetical — the first
// version of this file matched only the linked ``[`stringEnum`](…)`` spelling
// and so knew nothing about any `maybeStringEnum` / `stringArray` slot, which
// read as "no schema defines this" rather than as a parse failure.
//
// So pin a few canaries: slots whose kind is stable and which between them
// cover both row spellings and both enum flavours. If the generator's format
// moves, this fails loudly and names the parser as the thing to fix, rather than
// letting the gate go quiet.
function assertInventoryParsed(
  declsBySlot: Map<string, { kind: string; enumValues?: Set<string> }[]>,
  displaySlots: Set<string>,
) {
  const problems: string[] = []
  const canaries: [string, string][] = [
    ['autoscale', 'stringEnum'], // linked spelling
    ['displayMode', 'maybeStringEnum'], // bare spelling
    ['jexlFilters', 'stringArray'], // bare, non-enum
    ['height', 'number'], // linked, non-enum
    ['showSoftClipping', 'maybeBoolean'], // linked, promotable
  ]
  for (const [name, kind] of canaries) {
    if (!declsBySlot.get(name)?.some(d => d.kind === kind)) {
      problems.push(`  expected a \`${kind}\` declaration of \`${name}\``)
    }
  }
  // guards against a wholesale parse failure that still happens to catch the
  // canaries; the real numbers are ~300 slots over ~110 schemas
  if (declsBySlot.size < 200) {
    problems.push(`  only ${declsBySlot.size} slot names parsed, expected 200+`)
  }
  if (displaySlots.size < 50) {
    problems.push(
      `  only ${displaySlots.size} display slots parsed, expected 50+`,
    )
  }
  if (problems.length) {
    console.error(
      `check-doc-slots could not read docs/config/ properly, so it would ` +
        `have passed without checking anything:\n${problems.join(
          '\n',
        )}\n\nThe generated slot-table format probably changed. Fix SLOT_ROW in ` +
        `this file to match it again.`,
    )
    process.exit(1)
  }
}

// Could this declaration hold this literal string?
function accepts(decl: Decl, value: string) {
  if (decl.enumValues) {
    return decl.enumValues.has(value)
  }
  return !NON_STRING_KINDS.has(decl.kind)
}

interface Problem {
  file: string
  line: number
  message: string
}

type Inventory = ReturnType<typeof buildInventory>

function checkObject(
  obj: Record<string, unknown>,
  inv: Inventory,
  inDisplayDefaults: boolean,
  report: (msg: string) => void,
) {
  for (const [key, value] of Object.entries(obj)) {
    const decls = inv.declsBySlot.get(key)
    // a `jexl:` callback is a per-feature expression rather than one of the
    // enum's literals, so it is never a violation however the slot is typed
    if (
      decls &&
      typeof value === 'string' &&
      !value.startsWith('jexl:') &&
      !decls.some(d => accepts(d, value))
    ) {
      const legal = [
        ...new Set(decls.flatMap(d => [...(d.enumValues ?? [])])),
      ].sort()
      report(
        `\`${key}\`: "${value}" is not a legal value${
          legal.length ? ` (expected one of ${legal.join(', ')})` : ''
        }`,
      )
    }
    if (inDisplayDefaults && !inv.displaySlots.has(key)) {
      report(
        `\`${key}\` is inside displayDefaults but no display schema defines it, ` +
          `so JBrowse stores it and never applies it`,
      )
    }
    if (value && typeof value === 'object') {
      // displayDefaults' children are slot names; a nested object elsewhere
      // (adapter, a displays entry, index) carries slots of its own type
      const children = Array.isArray(value) ? value : [value]
      for (const child of children) {
        if (child && typeof child === 'object' && !Array.isArray(child)) {
          checkObject(
            child as Record<string, unknown>,
            inv,
            !Array.isArray(value) && key === 'displayDefaults',
            report,
          )
        }
      }
    }
  }
}

function main() {
  const inv = buildInventory()
  const problems: Problem[] = []
  const fallbackRows = checkFallbackPromises(problems)

  for (const file of docFiles(docsDir)) {
    const rel = docRelative(file)
    // config/, models/ and api/ are generated from source, so a violation there
    // is fixed at the definition site, not here
    if (/^(config|models|api)\//.test(rel)) {
      continue
    }
    const text = readFileSync(file, 'utf8')
    checkProse(text, inv, (line, message) => {
      problems.push({ file: rel, line, message })
    })
    const fence = /```json[^\n]*\n([\s\S]*?)```/g
    let m: RegExpExecArray | null
    while ((m = fence.exec(text))) {
      let parsed: unknown
      try {
        parsed = JSON.parse(m[1]!)
      } catch {
        continue // a fragment or an elided snippet, not standalone JSON
      }
      const line = text.slice(0, m.index).split('\n').length
      for (const root of Array.isArray(parsed) ? parsed : [parsed]) {
        if (root && typeof root === 'object') {
          checkObject(root as Record<string, unknown>, inv, false, message => {
            problems.push({ file: rel, line, message })
          })
        }
      }
    }
  }

  reportProblems(
    problems.length
      ? [
          'Found doc config values that no longer match their schema:',
          '',
          ...problems.map(p => `  ${p.file}:${p.line}\n    → ${p.message}`),
          '',
          'docs/config/ is generated from the schemas, so it is the authority:',
          'fix the doc, or if a slot really changed, run `pnpm autogen` first so',
          'the tables are current.',
        ]
      : [],
    `All config slots named in hand-written docs exist, and every value is legal (${inv.schemaCount} schemas, ${inv.declsBySlot.size} slot names); ${fallbackRows} promotable rows promise the promotedBase beside them.`,
  )
}

main()
