// Ratchets the tutorials that hand a reader a build script and never show a
// command out of it.
//
// `check-script-commands` runs the other way: it asserts that what a page DOES
// show still runs in the script it came from. Nothing asserted that a page
// shows anything at all, so the failure it cannot see is a tutorial whose every
// command sits inside `bash build_x.sh`. That is not hypothetical. `dtu`
// described satuRn across three paragraphs of prose and showed no R;
// `ld_mosquitoes` never named the `plink --r2` flags its whole page reads the
// output of, nor that plink2 has no `--r2` at all; `scrna_pseudobulk` showed
// only the route its script does not take.
//
// A page counts as showing its work when at least one fence carries a
// `<!-- from: -->` marker, which is the same fence check-script-commands then
// holds to the script. That is a coarser question than "which tools are
// unshown", and coarse on purpose. Deriving the tool list was tried twice and
// neither way is fit to gate on:
//
//   - Parsing the scripts. They embed python and awk heredocs, and the shell
//     parser reads their locals, their `case`/`esac` and their dict keys as
//     tools. Ninety false names buried the four real ones.
//   - Reading each script's `# Requires:` header. It is prose written for a
//     human, so it yields sentence words ("nothing output the ucsc") and loses
//     the tools that sit inside a parenthetical ("kent tools (bigWigInfo,
//     bigWigToBedGraph)" contributes neither binary).
//
// A checker nobody trusts gets switched off rather than fixed, so this asks the
// question it can answer exactly. Making `# Requires:` machine-readable would
// support the finer check; until then the finer question is a review question.
//
// Removing a line is the win, and the way to remove one is to put the command
// that produces the page's subject file in the prose, per
// `website/docs/tutorials/CLAUDE.md`. Some lines will not move, and the header
// of the generated file says which and why.
//
// Run `pnpm check-unshown-tools` to rewrite the list; CI runs `--check`.
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'

import { checkOrWrite } from './check-utils.ts'
import { repoRoot } from './paths.ts'

const tutorials = join(repoRoot, 'website/docs/tutorials')
const listFile = join(import.meta.dirname, 'unshown-tools.txt')

const rows: string[] = []

for (const name of readdirSync(tutorials).sort()) {
  if (!name.endsWith('.md') || name === 'CLAUDE.md') {
    continue
  }
  const src = readFileSync(join(tutorials, name), 'utf8')

  // The scripts the page points a reader at. A page with none is not making
  // this mistake: it has no build script to hide behind.
  const scripts = [
    ...new Set([...src.matchAll(/scripts\/[\w.-]+\.sh/g)].map(m => m[0])),
  ].filter(s => existsSync(join(repoRoot, s)))

  if (scripts.length > 0 && !/<!--\s*from: scripts\//.test(src)) {
    rows.push(`${name.replace(/\.md$/, '')}: ${scripts.sort().join(' ')}`)
  }
}

const HEADER = `# AUTO-GENERATED by scripts/check-unshown-tools.ts — do not edit by hand.
# Regenerate with \`pnpm check-unshown-tools\`; CI runs it with --check.
#
# Each line is a tutorial that points a reader at a build script and shows no
# command out of it, so the tool that produced the figure is only ever run as
# \`bash build_x.sh\`. Adding a line is a regression.
#
# Removing a line is the win. The way is to put the command that produces the
# page's subject file in the prose in the general form a reader would run on
# their own data, and mark that fence \`<!-- from: -->\` so check-script-commands
# holds it to the script. website/docs/tutorials/CLAUDE.md has the rules.
#
# The one line left is here because the check cannot tell it apart from a page
# that owes something, rather than because it owes anything: population_cnv
# fetches a published callset and converts it, and its script runs no analysis
# tool of its own. So a line appearing beside it is a page to fix, not a second
# exemption to write.
`

checkOrWrite({
  path: listFile,
  content: `${HEADER}${rows.join('\n')}\n`,
  label: 'tutorials that show a command from their build script',
  staleHint:
    'a tutorial now hands a reader a build script without showing a command ' +
    'out of it. Put the command that produces its subject file in the prose, ' +
    'or run `pnpm check-unshown-tools` to record the change deliberately.',
})
