// Regenerate src/lib/spec-recipe/hostedConfigs.generated.ts:
//
//   pnpm gen:hosted-configs
//
// A figure on a hosted config this repo holds no copy of names its tracks by
// id only, and the recipe beside it needs each one's name and file type. This
// fetches those configs and keeps only the tracks and assemblies some figure or
// video names, so the site build reads them without a network fetch.
// `check-spec-recipes` fails when a figure names a track this file never looked
// up.
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  figureLiveRefs,
  videoLiveRefs,
} from '../src/lib/liveLinks.generated.ts'
import { checkOrWrite } from './check-utils.ts'
import { hostedReferences } from './hosted-references.ts'

import type {
  RawAssembly,
  RawConfig,
  RawTrack,
} from '../src/lib/spec-recipe/configs.ts'

function trimTrack(track: RawTrack): RawTrack {
  return {
    trackId: track.trackId,
    ...(track.name ? { name: track.name } : {}),
    ...(track.type ? { type: track.type } : {}),
    ...(track.adapter?.type ? { adapter: { type: track.adapter.type } } : {}),
    ...(track.displays?.length
      ? { displays: track.displays.map(d => ({ type: d.type })) }
      : {}),
  }
}

function trimAssembly(assembly: RawAssembly): RawAssembly {
  const { trackId, adapter } = assembly.sequence ?? {}
  return {
    name: assembly.name,
    sequence: {
      ...(trackId ? { trackId } : {}),
      ...(adapter?.type ? { adapter: { type: adapter.type } } : {}),
    },
  }
}

const references = hostedReferences([
  ...Object.values(figureLiveRefs),
  ...Object.values(videoLiveRefs),
])

const snapshot: Record<string, RawConfig & { absent: string[] }> = {}
for (const [url, { trackIds, assemblyNames }] of [...references].sort(
  ([a], [b]) => a.localeCompare(b),
)) {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`${url}: HTTP ${response.status}`)
  }
  const config = (await response.json()) as RawConfig
  const assemblies = (config.assemblies ?? []).filter(
    a =>
      assemblyNames.has(a.name) ||
      trackIds.has(a.sequence?.trackId ?? `${a.name}-ReferenceSequenceTrack`),
  )
  const tracks = (config.tracks ?? []).filter(t => trackIds.has(t.trackId))
  const found = new Set([
    ...tracks.map(t => t.trackId),
    ...assemblies.map(
      a => a.sequence?.trackId ?? `${a.name}-ReferenceSequenceTrack`,
    ),
  ])
  snapshot[url] = {
    assemblies: assemblies.map(trimAssembly),
    tracks: tracks.map(trimTrack),
    absent: [...trackIds].filter(id => !found.has(id)).sort(),
  }
}

checkOrWrite({
  path: join(
    dirname(fileURLToPath(import.meta.url)),
    '../src/lib/spec-recipe/hostedConfigs.generated.ts',
  ),
  content: `// AUTO-GENERATED by scripts/gen-hosted-configs.ts — do not edit by hand.
// Regenerate with \`pnpm gen:hosted-configs\`, which fetches each config.
import type { RawConfig } from './configs.ts'

export const hostedConfigs: Record<string, RawConfig & { absent: string[] }> = ${JSON.stringify(snapshot, null, 2)}
`,
  label: 'src/lib/spec-recipe/hostedConfigs.generated.ts',
  staleHint: 'run `pnpm gen:hosted-configs`',
})
