import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { check, formatMarkdown } from './check-utils.ts'
import { docsDir, repoRoot } from './paths.ts'

// Mirrors products/jbrowse-capture/README.md into website/docs/jbrowse-capture.md,
// the same way generate-img-doc.ts handles jbrowse-img — the README is the
// source of truth. Edit it there, then run `pnpm autogen`. CI parity via
// `--check`.

const productDir = join(repoRoot, 'products', 'jbrowse-capture')
const readmePath = join(productDir, 'README.md')
const outPath = join(docsDir, 'jbrowse-capture.md')

const githubBase =
  'https://github.com/GMOD/jbrowse-components/blob/main/products/jbrowse-capture'

const title = 'Screenshot a live view (@jbrowse/capture)'
const description =
  'Drive a live JBrowse 2 instance with Puppeteer and screenshot it once it ' +
  'has actually finished rendering'

// Repo-relative links only resolve inside the repo, so point them at GitHub.
// Absolute (http), anchor (#), and root (/) links are left alone.
function rewriteRelativeLinks(md: string) {
  return md.replaceAll(/\]\(([^)]+)\)/g, (match, target: string) => {
    const isAbsolute = /^(https?:|mailto:|#|\/)/.test(target)
    return isAbsolute ? match : `](${githubBase}/${target})`
  })
}

function generate() {
  const readme = readFileSync(readmePath, 'utf8')
  // Drop the leading "# @jbrowse/capture" H1 — the frontmatter title supplies
  // the page heading. Keep everything after it.
  const body = readme.replace(/^# @jbrowse\/capture\n+/, '')
  const raw = [
    '---',
    `title: ${title}`,
    `description: ${description}`,
    '---',
    '',
    '<!-- DO NOT EDIT: autogenerated from products/jbrowse-capture/README.md by',
    'website/scripts/generate-capture-doc.ts — edit the README, then run',
    '`pnpm autogen` -->',
    '',
    rewriteRelativeLinks(body),
  ].join('\n')
  return formatMarkdown(raw, outPath)
}

const md = generate()

if (check) {
  const stale = readFileSync(outPath, 'utf8') !== md
  if (stale) {
    console.error(
      `${outPath} is out of date. Run \`pnpm autogen\` to regenerate.`,
    )
    process.exit(1)
  }
  console.log('jbrowse-capture.md is up to date')
} else {
  writeFileSync(outPath, md)
  console.log(`wrote ${outPath}`)
}
