import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { format, resolveConfig } from 'prettier'

// Mirrors products/jbrowse-cli/README.md into website/docs/cli.md. That README
// is itself generated from the CLI (products/jbrowse-cli/generate_readme.sh
// concatenates preamble.md with live `jbrowse <command> --help` output, run on
// the package's prepack), so it — not this doc — is the source of truth for
// command usage. To change the docs: edit the CLI command (or preamble.md),
// regenerate the README, then run `pnpm autogen`. CI parity via `--check`.

const repoRoot = join(import.meta.dirname, '..', '..')
const readmePath = join(repoRoot, 'products', 'jbrowse-cli', 'README.md')
const outPath = join(repoRoot, 'website', 'docs', 'cli.md')
const check = process.argv.includes('--check')

const title = 'Command line tools (JBrowse CLI)'

// The README is an npm package readme, so it points at @jbrowse/img on npm. On
// the docs site the sibling page is the better target. The lookbehind skips a
// URL already inside a markdown link target, so a bare URL is never
// double-wrapped.
function rewriteImgLink(md: string) {
  return md.replaceAll(
    /(?<!\]\()https:\/\/www\.npmjs\.com\/package\/@jbrowse\/img/g,
    '[@jbrowse/img](/docs/jbrowse-img)',
  )
}

// Drop the README's own frontmatter block; the website frontmatter supplies the
// page title (and the README's legacy Docusaurus id/toplevel fields aren't
// valid here).
function stripFrontmatter(md: string) {
  return md.replace(/^---\n[\s\S]*?\n---\n+/, '')
}

// Format through prettier with the repo config so the output matches what
// `pnpm format` (postautogen) produces — otherwise the committed file and the
// --check comparison would disagree on wrapping.
async function generate() {
  const body = rewriteImgLink(
    stripFrontmatter(readFileSync(readmePath, 'utf8')),
  )
  const raw = [
    '---',
    `title: ${title}`,
    '---',
    '',
    '<!-- DO NOT EDIT: autogenerated from products/jbrowse-cli/README.md by',
    'website/scripts/generate-cli-doc.ts — edit the CLI (or its preamble.md),',
    'regenerate the README, then run `pnpm autogen` -->',
    '',
    body,
  ].join('\n')
  const prettierConfig = await resolveConfig(outPath)
  return format(raw, { ...prettierConfig, filepath: outPath })
}

const md = await generate()

if (check) {
  if (readFileSync(outPath, 'utf8') !== md) {
    console.error(
      `${outPath} is out of date — run \`pnpm autogen\` to regenerate.`,
    )
    process.exit(1)
  }
  console.log('cli.md is up to date')
} else {
  writeFileSync(outPath, md)
  console.log(`wrote ${outPath}`)
}
