import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'

import { format, resolveConfig } from 'prettier'

import {
  syntenyTrackTypes,
  trackTypes,
} from '../../products/jbrowse-img/src/makeConfigs.ts'
import { buildFullHelp } from '../../products/jbrowse-img/src/options.ts'
import { check } from './check-utils.ts'

// Mirrors products/jbrowse-img/README.md into website/docs/jbrowse-img.md so the
// @jbrowse/img static-export docs live alongside the CLI docs (cli.md). The
// README is the source of truth — edit it there, then run `pnpm autogen` (or
// this script directly) to regenerate. CI parity via `--check`.

const repoRoot = join(import.meta.dirname, '..', '..')
const productDir = join(repoRoot, 'products', 'jbrowse-img')
const readmePath = join(productDir, 'README.md')
const outPath = join(repoRoot, 'website', 'docs', 'jbrowse-img.md')
const imgSrcDir = join(productDir, 'img')
const imgDestDir = join(repoRoot, 'website', 'static', 'img', 'jbrowse-img')

const githubBase =
  'https://github.com/GMOD/jbrowse-components/blob/main/products/jbrowse-img'

// The README points its example images at the in-repo copies via raw.github
// URLs (so they render on npm/GitHub). For the docs site we serve them from the
// website's own static dir instead, so the page is self-contained: versioned
// with the docs, rendering in offline/staging builds, with no raw.github
// runtime dependency. Astro's rehype-base-urls prefixes the `/img/...` path with
// the site base path, matching every other figure on the site.
const rawImgRe =
  /https:\/\/raw\.githubusercontent\.com\/GMOD\/jbrowse-components\/main\/products\/jbrowse-img\/img\/([\w.-]+)/g
const localImgUrl = '/img/jbrowse-img/'

const title = 'Static image export (@jbrowse/img)'

// Repo-relative links (data/*, scripts/*) only resolve inside the repo, so point
// them at GitHub. Absolute (http), anchor (#), and root (/) links
// are left alone. GitHub redirects /blob/ to /tree/ for directories.
function rewriteRelativeLinks(md: string) {
  return md.replaceAll(/\]\(([^)]+)\)/g, (match, target: string) => {
    const isAbsolute = /^(https?:|mailto:|#|\/)/.test(target)
    return isAbsolute ? match : `](${githubBase}/${target})`
  })
}

// Repoint raw.github image URLs at the local static dir; collect the referenced
// filenames so they can be copied/verified alongside the doc.
function rewriteImages(md: string) {
  const names = new Set<string>()
  const out = md.replaceAll(rawImgRe, (_match, name: string) => {
    names.add(name)
    return `${localImgUrl}${name}`
  })
  return { out, names }
}

// Fill the README's INJECT_HELP marker block with the live `jb2export --help`
// output (top-level + every subcommand), so the published help reference can't
// drift from the CLI. Mirrors the COLOR_TABLE marker pattern used in the guides.
const helpStartRe =
  /(<!-- INJECT_HELP START[^>]*-->)[\s\S]*?(<!-- INJECT_HELP END -->)/

function injectHelp(md: string) {
  if (!helpStartRe.test(md)) {
    throw new Error('README is missing the INJECT_HELP marker block')
  }
  const help = buildFullHelp('jb2export', trackTypes, syntenyTrackTypes)
  return md.replace(helpStartRe, `$1\n\n\`\`\`\n${help}\n\`\`\`\n\n$2`)
}

// The site renders captioned figures via the <Figure> component (handled by
// remark-figure), so convert the README's plain markdown images into <Figure>s
// — the image alt text becomes the figcaption.
function imagesToFigures(md: string) {
  return md.replaceAll(
    /!\[([^\]]*)\]\(([^)]+)\)/g,
    (_match, alt: string, src: string) =>
      `<Figure src="${src}" caption="${alt}" />`,
  )
}

// Format through prettier with the repo config so the output matches what
// `pnpm format` (postautogen) produces — otherwise the committed file and the
// --check comparison would disagree on line wrapping.
async function generate() {
  // The README is the source of truth, but its help block is auto-filled from
  // the CLI. Refresh it and run it through prettier so the injected README is
  // byte-identical to what `pnpm format` produces — then both the README and
  // the doc generated from it stay current and idempotent under --check.
  const readmeConfig = await resolveConfig(readmePath)
  const readme = await format(injectHelp(readFileSync(readmePath, 'utf8')), {
    ...readmeConfig,
    filepath: readmePath,
  })
  // Drop the leading "# @jbrowse/img" H1 — the frontmatter title supplies the
  // page heading. Keep everything after it.
  const body = readme.replace(/^# @jbrowse\/img\n+/, '')
  const { out, names } = rewriteImages(body)
  const withFigures = imagesToFigures(out)
  const raw = [
    '---',
    `title: ${title}`,
    '---',
    '',
    '<!-- DO NOT EDIT: autogenerated from products/jbrowse-img/README.md by',
    'website/scripts/generate-img-doc.ts — edit the README, then run',
    '`pnpm autogen` -->',
    '',
    rewriteRelativeLinks(withFigures),
  ].join('\n')
  const prettierConfig = await resolveConfig(outPath)
  const md = await format(raw, { ...prettierConfig, filepath: outPath })
  return { md, names, readme }
}

// Copy each referenced example image into the website's static dir (or, in check
// mode, list the ones that are missing/out of date so CI fails when a source
// image changed but wasn't re-synced).
function syncImages(names: Set<string>) {
  const stale: string[] = []
  for (const name of names) {
    const src = join(imgSrcDir, name)
    if (!existsSync(src)) {
      throw new Error(
        `README references ${localImgUrl}${name} but ${src} does not exist`,
      )
    }
    const dest = join(imgDestDir, name)
    const upToDate =
      existsSync(dest) && readFileSync(dest).equals(readFileSync(src))
    if (!upToDate) {
      stale.push(name)
      if (!check) {
        mkdirSync(imgDestDir, { recursive: true })
        copyFileSync(src, dest)
      }
    }
  }
  return stale
}

const { md, names, readme } = await generate()
const staleImages = syncImages(names)

if (check) {
  const docStale = readFileSync(outPath, 'utf8') !== md
  const readmeStale = readFileSync(readmePath, 'utf8') !== readme
  if (docStale || readmeStale || staleImages.length > 0) {
    if (readmeStale) {
      console.error(`${readmePath} help block is out of date.`)
    }
    if (docStale) {
      console.error(`${outPath} is out of date.`)
    }
    if (staleImages.length > 0) {
      console.error(
        `images out of date in ${imgDestDir}: ${staleImages.join(', ')}`,
      )
    }
    console.error('Run `pnpm autogen` to regenerate.')
    process.exit(1)
  }
  console.log('jbrowse-img.md is up to date')
} else {
  writeFileSync(readmePath, readme)
  writeFileSync(outPath, md)
  console.log(`wrote ${outPath}`)
  if (staleImages.length > 0) {
    console.log(
      `copied ${staleImages.length} image(s) to ${imgDestDir}: ${staleImages.join(', ')}`,
    )
  }
}
