import fs from 'node:fs'
import http from 'node:http'
import path from 'node:path'
import { parseArgs } from 'node:util'

import {
  createVerdictRoutes,
  isVerdictStale,
  reviewClientScript,
  sendJson,
} from '@jbrowse/browser-test-utils'

import { readManifest, unpublishedFigures } from './figure-paths.ts'
import { figureContentTypes, figureName, figurePath } from './figure-store.ts'
import {
  collectScreenshots,
  getBaselineState,
  getWorktreeState,
  imageHash,
  imgDir,
  loadReport,
  refreshWorkingTreeScans,
  reportPath,
  scannedImageHash,
  syncJbrowseImgMirror,
  websiteDir,
} from './screenshot-review-lib.ts'
// the record's shape and path only — NOT screenshot-report.ts, which reaches
// screenshot-options.ts and so parses this server's argv as if it were a
// generator run (see the header of screenshot-run-report.ts)
import { type RunReport, runReportPath } from './screenshot-run-report.ts'
import { screenshotLiveUrls, specs } from './screenshot-specs.ts'

const { values } = parseArgs({
  args: process.argv.slice(2),
  allowPositionals: false,
  options: {
    help: { type: 'boolean', short: 'h', default: false },
    port: { type: 'string' },
  },
})

if (values.help) {
  console.log(`Review website screenshots in a web UI.

Usage: pnpm review-screenshots-web [--port=3335]

Each figure is shown against the same figure on origin/main, with where the
docs use it, and approve/deny/note controls. Four ways to look at the pair,
per card or for every card from the Compare control:

  side    the two images in two columns
  onion   stacked, with a slider that fades between them (and a blink toggle)
  swipe   stacked, with a divider you drag across the picture
  diff    pixel difference — black wherever the two agree (with an amplifier)

Verdicts are written to ${path.relative(process.cwd(), reportPath)}.
`)
  process.exit(0)
}

const portVal = values.port ? Number(values.port) : Number.NaN
const port = Number.isFinite(portVal) ? portVal : 3335

// The image route is content-addressed: the URL carries `?v=<hash of the
// bytes>`, so a URL can only ever mean one picture and is safe to cache
// forever. Without this the reviewer's loop — regenerate, RELOAD, look again —
// re-downloaded every image (~70MB) on every single reload, because a bare 200
// with no validators is not cacheable at all. A missing hash means we cannot
// name the bytes, so don't store them.
//
// The baseline side needs nothing here: it is a store URL, already immutable and
// already served with a year of cache by CloudFront.
function cacheHeaders(hash: string | null) {
  return hash
    ? { 'Cache-Control': 'public, max-age=31536000, immutable' }
    : { 'Cache-Control': 'no-store' }
}

function buildSpecPayload() {
  // Every load is a fresh look at the working tree. A review session is
  // regenerate, reload, look again, so the store and doc-usage scans behind
  // `changed`/`mainUrl`/`usages` cannot be answered from what the tree looked
  // like when the server started. Everything below reads through that one scan.
  refreshWorkingTreeScans()
  const report = loadReport()
  // Figure bytes live in the S3 store, so what a reviewer sees here is the file
  // on THIS disk, which is not necessarily what anyone else or the published
  // site gets. An unpushed regen is invisible to git, so without this a verdict
  // could be recorded against pixels nobody else will ever see.
  //
  // Kept as paths, like the unpulled set: figureName conflates the 27 mirrored
  // jb2export figures, so a name-keyed set marks a card unpushed because the
  // OTHER file of that name is. They travel together today — the mirror is a
  // byte copy, so both sides go stale on the same jb2export — which is exactly
  // why a name-keyed version of this would read as correct indefinitely.
  const unpublished = new Set(unpublishedFigures(getWorktreeState()))
  const runStates = specRunStates(loadRunReport())
  // Which figures a sweep could have anything to say about. NOT `autogenerated`,
  // which is also true of the ten desktop figures — those come from a separate
  // Selenium generator (products/jbrowse-desktop/test/screenshots.ts) that
  // writes no run report here, so screenshot-run.json says nothing about them
  // either way and must not be read as saying they were skipped.
  const sweepable = new Set(specs.map(s => s.name))
  return collectScreenshots(specs).map(shot => {
    const verdict = report[shot.name]
    // the hash of the PNG as the reviewer is about to see it. It rides along so
    // the page can say which pixels a verdict was formed against — both to
    // cache-bust the <img> and as the precondition on the write. The stat-keyed
    // form, since this is the scan: the write path re-reads the bytes under the
    // report lock, which is where an unchanged mtime would actually matter.
    const currentHash = scannedImageHash(shot.name)
    // an approval/denial only resurfaces once the reviewed image changes
    const stale = isVerdictStale(verdict, currentHash)
    const liveUrl = screenshotLiveUrls[shot.name]
    // a compose figure has no session of its own; its parts carry the live
    // links, which is also what `<Figure links=...>` publishes for it
    return {
      ...shot,
      parts: shot.parts.map(part => ({
        ...part,
        liveUrl: screenshotLiveUrls[part.name],
      })),
      verdict,
      stale,
      unpublished: unpublished.has(figurePath(shot.name)),
      // undefined when the run had nothing to report about this spec — which,
      // now that the selection is seeded in, means it rendered fine and
      // unchanged rather than "we cannot say"
      run: runStates.get(shot.name),
      // The last run never reached this spec: narrowed past it by --filter,
      // --affected or --cover, or added since. Decided here rather than in the
      // page, because it needs the spec list and the run's own selection, and
      // the page has neither — it was inferring it from whether --filter had
      // been passed, which no --affected or --cover run ever sets.
      notCovered:
        runStates.size > 0 &&
        sweepable.has(shot.name) &&
        !runStates.has(shot.name),
      imageHash: currentHash ?? null,
      ...(liveUrl ? { liveUrl } : {}),
    }
  })
}

// The store state for the banner. Separate from /api/specs because the count
// includes figures no spec produces — a hand-made diagram dropped into
// static/img is exactly the kind that goes unpushed — and the banner should
// report the whole store, not the part that happens to have a spec.
//
// It reads the scan /api/specs just took rather than repeating it. Hashing the
// 62 MB of figures on disk is the most expensive thing either endpoint does, and
// doing it twice per page load bought nothing: the client fetches this straight
// after the spec list, off the same worktree.
function buildFigureStatePayload() {
  const state = getWorktreeState()
  const run = loadRunReport()
  // Deduplicated, because figureName is not injective: the 26 jb2export figures
  // exist as two files each (the render under products/jbrowse-img/img and the
  // website's byte copy of it), and they move together — so one regen produced
  // "2 figure(s) exist only on this machine" over the same name printed twice.
  // The cards next door stay keyed on the path for the same reason; here the
  // question is genuinely about the figure, so collapsing is the right answer.
  const names = (paths: string[]) => [...new Set(paths.map(figureName))].sort()
  return {
    unpublished: names(unpublishedFigures(state)),
    unpulled: names(state.missing),
    total: readManifest().size,
    // which origin/main the whole "new"/"changed" column is against. Reads off
    // the same memoized baseline /api/specs just used, so it costs a `git log -1`
    // and not a second parse of the manifest.
    baseline: getBaselineState(),
    run: run && {
      finishedAt: run.finishedAt,
      filter: run.filter,
      check: run.check,
      failed: run.failures.length,
      flaky: run.flaky.length,
      // How much of the corpus the run reached. `filter` cannot answer that:
      // --affected and --cover narrow just as hard and leave it empty, so a
      // 14-spec run said "a full sweep" and the 300 figures it never opened
      // read as verified by it. Zero for a report written before this was
      // recorded, which the banner reports as unknown rather than as a sweep.
      selected: run.selected.length,
      skipped: run.skipped.length,
      total: run.total,
    },
  }
}

// What the last sweep noticed, keyed by spec name. Re-read per request for the
// same reason the working-tree scans are: the loop is regenerate, reload, look
// again, and a report cached at server start describes the run before the one
// you just did.
//
// Absent is a real answer and is kept distinct from "fine". A spec the last run
// did not touch — because the run was narrowed past it, or predates the spec —
// has no verdict here, and the UI must not draw it as passing.
function loadRunReport(): RunReport | undefined {
  try {
    // A report on disk can predate any given field — `selected`/`total` were
    // added after reports were already being written — so the fields RunReport
    // declares are filled in here rather than guarded at every read.
    const parsed = JSON.parse(
      fs.readFileSync(runReportPath, 'utf8'),
    ) as Partial<RunReport>
    return {
      ...parsed,
      finishedAt: parsed.finishedAt ?? '',
      filter: parsed.filter ?? [],
      check: parsed.check ?? false,
      selected: parsed.selected ?? [],
      total: parsed.total ?? 0,
      skipped: parsed.skipped ?? [],
      failures: parsed.failures ?? [],
      flaky: parsed.flaky ?? [],
      updated: parsed.updated ?? [],
      suppressed: parsed.suppressed ?? [],
    }
  } catch {
    return undefined
  }
}

interface SpecRunState {
  failed?: string
  flaky?: number
  updated?: string
  suppressed?: number
  // selected and then deliberately not rendered, with why
  skipped?: string
}

function specRunStates(run: RunReport | undefined) {
  const byName = new Map<string, SpecRunState>()
  if (!run) {
    return byName
  }
  const touch = (name: string) => {
    let s = byName.get(name)
    if (!s) {
      s = {}
      byName.set(name, s)
    }
    return s
  }
  // Seed with the whole selection, so an entry means "this run reached it" and
  // the lists below only add what went wrong. A spec that rendered fine and
  // unchanged appears in none of them — most of a sweep does — so without this
  // pass "no entry" conflates "nothing to report" with "never opened".
  for (const name of run.selected) {
    touch(name)
  }
  for (const s of run.skipped) {
    touch(s.name).skipped = s.reason
  }
  for (const f of run.failures) {
    touch(f.name).failed = f.error
  }
  for (const f of run.flaky) {
    touch(f.name).flaky = f.frac
  }
  for (const u of run.updated) {
    touch(u.name).updated = u.detail
  }
  for (const s of run.suppressed) {
    touch(s.name).suppressed = s.frac
  }
  return byName
}

function sendNotFound(res: http.ServerResponse) {
  res.writeHead(404)
  res.end('not found')
}

// A hand-typed or truncated URL can carry a malformed escape, which throws.
// That is a request for a path that does not exist, not a server error.
function decodePath(s: string): string | undefined {
  try {
    return decodeURIComponent(s)
  } catch {
    return undefined
  }
}

// Serve /img/<name>.png, guarding against path traversal outside imgDir
function serveImage(
  res: http.ServerResponse,
  urlPath: string,
  v: string | null,
) {
  const rel = decodePath(urlPath.slice('/img/'.length))
  const full = rel === undefined ? undefined : path.resolve(imgDir, rel)
  if (full === undefined || !full.startsWith(imgDir + path.sep)) {
    sendNotFound(res)
    return
  }
  // a jb2export the reviewer produced a minute ago is only in
  // products/jbrowse-img/img until something copies it across
  syncJbrowseImgMirror(full.slice(imgDir.length + 1).replace(/\.png$/, ''))
  if (!fs.existsSync(full)) {
    sendNotFound(res)
    return
  }
  res.writeHead(200, {
    'Content-Type':
      figureContentTypes[path.extname(full).toLowerCase()] ??
      'application/octet-stream',
    ...cacheHeaders(v),
  })
  const stream = fs.createReadStream(full)
  // An unhandled stream 'error' is an uncaught exception that takes the whole
  // server down mid-review. The 200 is already out, so there is no status left
  // to send — drop the connection and let the <img> fail on its own.
  stream.on('error', () => {
    res.destroy()
  })
  stream.pipe(res)
}

const { handleVerdict, handleClearVerdict } = createVerdictRoutes({
  reportPath,
  hashOf: imageHash,
  // 'answered' has no button: flip-review.ts writes it, and the UI only posts
  // it back when a note is saved against an entry that is already in that
  // state. Rejecting it here would turn typing a note into a failed write.
  statuses: ['good', 'bad', 'answered'],
})

const server = http.createServer((req, res) => {
  const url = req.url ?? '/'
  const [rawPath, qs] = url.split('?')
  const pathname = rawPath!
  // the image routes are cacheable exactly when the URL names which bytes it
  // wants; `?v=` is that name
  const v = new URLSearchParams(qs ?? '').get('v') || null
  try {
    if (pathname === '/' || pathname === '/index.html') {
      res.writeHead(200, { 'Content-Type': 'text/html' })
      res.end(PAGE)
    } else if (pathname === '/api/specs') {
      sendJson(res, 200, buildSpecPayload())
    } else if (pathname === '/api/figure-state') {
      sendJson(res, 200, buildFigureStatePayload())
    } else if (pathname === '/api/verdict' && req.method === 'POST') {
      handleVerdict(req, res).catch((err: unknown) => {
        sendJson(res, 500, { error: `${err}` })
      })
    } else if (pathname === '/api/verdict/clear' && req.method === 'POST') {
      handleClearVerdict(req, res).catch((err: unknown) => {
        sendJson(res, 500, { error: `${err}` })
      })
    } else if (pathname.startsWith('/img/')) {
      serveImage(res, pathname, v)
    } else {
      sendNotFound(res)
    }
  } catch (err) {
    // an image route may already have committed its status line, and writing a
    // second one throws again — from a catch that has nowhere left to report
    if (res.headersSent) {
      res.destroy()
    } else {
      sendJson(res, 500, { error: `${err}` })
    }
  }
})

// Several agents share this worktree and the port is fixed, so "address in use"
// is a routine collision rather than a crash worth a stack trace.
server.on('error', (err: NodeJS.ErrnoException) => {
  if (err.code === 'EADDRINUSE') {
    console.error(
      `port ${port} is already in use — a review server is likely already ` +
        `running. Open it, or pass --port=<n> to start a second one.`,
    )
    process.exit(1)
  }
  throw err
})

server.listen(port, () => {
  console.log(`Screenshot review UI: http://localhost:${port}`)
  console.log(`Writing verdicts to: ${path.relative(websiteDir, reportPath)}`)
})

// The write protocol and the note-draft bookkeeping are shared with jbrowse-web's
// browser-test snapshot review; this page supplies the two halves that differ —
// what a card looks like and what the header counts.
const CLIENT = reviewClientScript({
  draftsKey: 'screenshot-review-drafts',
  imageMovedPhrase: 'this figure was regenerated',
})

const PAGE = /* html */ `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Screenshot review</title>
<!-- inline, both to stop the /favicon.ico 404 putting a red line in the console
     on every load and to tell this tab apart from the snapshot review UI, which
     the two tools are expected to be open beside -->
<link rel="icon" href='data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y=".9em" font-size="90">🖼️</text></svg>'>
<style>
  /* Surfaces/text/borders use CSS system colors so light and dark themes both
     work with no media query — the browser maps Canvas/Field/etc per scheme.
     Vivid accents (tab blue, pill pastels, card edges) stay fixed. */
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    font-family: system-ui, -apple-system, sans-serif;
    margin: 0;
    background: Canvas;
    color: CanvasText;
  }
  header {
    position: sticky; top: 0; z-index: 10;
    background: Canvas; border-bottom: 1px solid ButtonBorder;
    padding: 12px 20px; display: flex; gap: 16px; align-items: flex-end; flex-wrap: wrap;
  }
  header h1 { font-size: 16px; margin: 0; }
  header input[type=search] { padding: 6px 10px; width: 220px; border: 1px solid ButtonBorder; border-radius: 6px; background: Field; color: FieldText; }
  header select { padding: 6px 8px; border: 1px solid ButtonBorder; border-radius: 6px; font-size: 13px; background: Field; color: FieldText; cursor: pointer; }
  header select option { background: Field; color: FieldText; }
  header label { font-size: 13px; display: flex; gap: 5px; align-items: center; cursor: pointer; }
  .ctrl { flex-direction: column; align-items: flex-start; gap: 2px; }
  .ctrl > span { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; color: GrayText; }
  .tabs { display: flex; gap: 6px; }
  .tab {
    padding: 7px 14px; border: 1px solid ButtonBorder; border-radius: 6px; background: Canvas;
    cursor: pointer; font-size: 14px; font-weight: 500; color: CanvasText;
  }
  .tab.active { background: #2563eb; border-color: #2563eb; color: #fff; }
  .tab .tabcount { opacity: 0.7; margin-left: 5px; font-size: 12px; }
  .counts { font-size: 13px; color: GrayText; margin-left: auto; display: flex; gap: 14px; flex-wrap: wrap; }
  .pill { padding: 1px 8px; border-radius: 999px; font-size: 12px; font-weight: 500; }
  .pill.good { background: #d6f5dd; color: #14532d; }
  .pill.bad { background: #fbd9d9; color: #7f1d1d; }
  .pill.none { background: #eee; color: #666; }
  /* answered reads as "in flight", so blue rather than the red of an open
     denial or the green of an approval — it is neither yet. */
  .pill.answered { background: #dbeafe; color: #1e3a8a; }
  .pill.auto { background: #dbeafe; color: #1e40af; }
  .pill.manual { background: #f3e8ff; color: #6b21a8; }
  .pill.new { background: #cffafe; color: #155e63; }
  .pill.changed, .pill.stale { background: #fde68a; color: #854d0e; }
  .pill.unpublished { background: #ffe4d5; color: #7c2d12; }
  /* A spec that failed to render is the most consequential thing on a card —
     the image below it is whatever the last successful run left, which looks
     exactly like a current figure. Red, and louder than the verdict pills. */
  .pill.failed { background: #fbd9d9; color: #7f1d1d; font-weight: 700; }
  .pill.flaky { background: #ede9fe; color: #5b21b6; }
  .pill.notcovered { background: #f1f5f9; color: #64748b; }
  .runerr { margin: 6px 0 0; padding: 8px 10px; border-radius: 6px; background: #fbd9d9; color: #7f1d1d; font-size: 12px; white-space: pre-wrap; font-family: ui-monospace, monospace; max-height: 9em; overflow: auto; }
  /* Says the answer either way. A reviewer needs to know that what they are
     approving is what everyone else will get, and silence cannot say that. */
  #store { padding: 8px 14px; font-size: 13px; border-bottom: 1px solid ButtonBorder; }
  #store.ok { background: #d6f5dd; color: #14532d; }
  #store.pending { background: #ffe4d5; color: #7c2d12; }
  #store code { background: rgba(0,0,0,.08); padding: 1px 5px; border-radius: 4px; }
  /* one paragraph per thing the banner has to say (unpushed, unpulled, which
     baseline, which run), rather than an empty spacer div between them */
  #store .storeline + .storeline { margin-top: 6px; }
  #store .names { margin-top: 4px; font-size: 12px; opacity: .85; }
  main { padding: 20px; display: flex; flex-direction: column; gap: 18px; max-width: 1400px; margin: 0 auto; }
  .card {
    background: Canvas; border: 1px solid ButtonBorder; border-radius: 10px; overflow: hidden;
  }
  .card.good { border-left: 5px solid #22c55e; }
  .card.bad { border-left: 5px solid #ef4444; }
  .card.stale { border-left: 5px solid #f59e0b; }
  .card.answered { border-left: 5px solid #3b82f6; }
  .card-images {
    display: flex; gap: 0;
  }
  .imgcol { flex: 1; display: flex; flex-direction: column; }
  .imglabel {
    font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
    padding: 4px 10px; background: Canvas; border-bottom: 1px solid ButtonBorder; color: GrayText;
    display: flex; align-items: center; gap: 8px; justify-content: space-between;
  }
  .imgwrap { background: #222; display: flex; align-items: center; justify-content: center; min-height: 180px; flex: 1; }
  .imgwrap img { max-width: 100%; max-height: 400px; display: block; cursor: zoom-in; }
  .imgcol + .imgcol { border-left: 2px solid ButtonBorder; }
  /* Stacked comparison: the same two images one on top of the other, with a
     control that decides how much of each you see. Side by side answers "what
     changed" only for a change big enough to find twice; a figure whose row
     packing moved by a few pixels, or whose one bar recoloured, reads as
     identical in two columns 700px apart. Stacked, the eye is looking at one
     picture and the difference is the thing that moves.
     Three ways of doing that, sharing one stage: fade (onion), a draggable
     divider (swipe), and difference blending (diff). */
  .cmpbar {
    display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
    padding: 4px 10px; background: Canvas; border-bottom: 1px solid ButtonBorder;
    font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: GrayText;
  }
  .cmpbar input[type=range] { flex: 1; min-width: 140px; max-width: 420px; accent-color: #2563eb; cursor: ew-resize; }
  /* the readout does not reflow the bar as it is dragged */
  .cmppct { font-variant-numeric: tabular-nums; min-width: 3.2em; text-align: right; }
  /* A resize is the one change a pixel diff cannot see (pngDiffFraction returns
     null on a size mismatch), and it is also the one the overlay itself is
     worst at showing — everything below the change looks shifted. Say it. */
  .cmpnote { text-transform: none; letter-spacing: 0; font-weight: 500; color: #b45309; }
  .cmpnote:empty { display: none; }
  .cmphint, .cmplink { text-transform: none; letter-spacing: 0; font-weight: 500; }
  .cmplink { color: LinkText; }
  .cmpbtn {
    padding: 1px 9px; border-radius: 999px; border: 1px solid ButtonBorder;
    background: ButtonFace; color: ButtonText; cursor: pointer;
    font: inherit; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em;
  }
  .cmpbtn.on { background: #2563eb; border-color: #2563eb; color: #fff; }
  /* the four ways of looking are one segmented control, not four loose buttons:
     they are alternatives, and only one is ever on */
  .cmpmodes { display: flex; }
  .cmpmodes .cmpbtn { border-radius: 0; }
  .cmpmodes .cmpbtn + .cmpbtn { border-left: 0; }
  .cmpmodes .cmpbtn:first-child { border-radius: 999px 0 0 999px; padding-left: 11px; }
  .cmpmodes .cmpbtn:last-child { border-radius: 0 999px 999px 0; padding-right: 11px; }
  .cmpwrap { background: #222; display: flex; justify-content: center; min-height: 180px; }
  /* Both images at ONE scale and aligned at their top-left corner, sized by
     fitCompareStage off their natural dimensions — never each to its own
     max-width, which would rescale a resized figure into agreement and draw the
     one difference nothing else can see as no difference at all.
     \`isolation\` keeps difference blending inside the stage: without it the
     exposed strip beside a resized figure blends against the #222 wrap, which
     draws a grey band where the honest answer is "nothing here". */
  /* overflow, because between a repaint and the image's onload the stage
     carries its remembered box while the images are still at natural size —
     3000px of figure spilling across the page for one frame */
  .cmpstage { position: relative; isolation: isolate; user-select: none; overflow: hidden; }
  .cmpstage img { position: absolute; top: 0; left: 0; display: block; -webkit-user-drag: none; }
  /* so a pointerdown anywhere on the stage is a drag of the divider rather than
     the browser's own image drag, and \`e.target\` is always the stage */
  .cmpstage img, .cmpside, .cmphandle { pointer-events: none; }
  .cmpstage.onion .cmptop { opacity: var(--fade, 0.5); }
  /* clipped from the LEFT, so origin/main is what the left of the divider shows
     and the current branch the right — which is what the two corner labels say,
     and the only arrangement in which they stay true at every position */
  .cmpstage.swipe { cursor: ew-resize; touch-action: none; }
  .cmpstage.swipe .cmptop { clip-path: inset(0 0 0 var(--wipe, 50%)); }
  .cmphandle {
    position: absolute; top: 0; bottom: 0; left: var(--wipe, 50%);
    width: 2px; margin-left: -1px; background: #fff; box-shadow: 0 0 0 1px rgba(0,0,0,.55);
  }
  .cmphandle::after {
    content: '⇔'; position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);
    width: 26px; height: 26px; border-radius: 999px; background: #fff; color: #111;
    font-size: 13px; line-height: 26px; text-align: center; box-shadow: 0 0 0 1px rgba(0,0,0,.55);
  }
  /* Each label is capped at the width of the side it names, so a divider taken
     to an edge takes its label with it. Left at 6px, a label kept naming a
     region that was no longer on screen — "origin/main" over a stage showing
     nothing but the current branch, which is the one thing these labels exist
     to prevent getting backwards. */
  .cmpside { position: absolute; top: 6px; overflow: hidden; border-radius: 999px; }
  /* the pill's padding is on the inner span, so a label clipped to nothing is
     nothing — on the outer element, box-sizing floors the CONTENT box at 0 and
     leaves 14px of padded background as a lozenge stuck in the corner */
  .cmpside span {
    display: block; padding: 1px 7px; white-space: nowrap;
    background: rgba(0,0,0,.6); color: #fff;
    font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
  }
  .cmpside.left { left: 6px; max-width: calc(var(--wipe, 50%) - 6px); }
  .cmpside.right { right: 6px; max-width: calc(100% - var(--wipe, 50%) - 6px); }
  /* Difference: black wherever the two agree, so the only lit pixels are the
     change. It is the one mode that answers "did ANYTHING move" without the eye
     having to find it — and the one that needs amplifying, since a one-shade
     recolour differences to a value indistinguishable from black. */
  .cmpstage.diff { background: #000; }
  .cmpstage.diff .cmptop { mix-blend-mode: difference; }
  .cmpstage.diff.amp { filter: brightness(8); }
  /* Blink comparator: hard cuts, not a crossfade — a fade is a change
     everywhere, which is the one thing that hides a change somewhere. */
  .cmpstage.onion.blink .cmptop { animation: cmpblink 1.4s infinite; }
  @keyframes cmpblink { 0%, 49.9% { opacity: 1 } 50%, 100% { opacity: 0 } }
  .missing { color: #f88; padding: 30px; font-size: 14px; }
  .meta { padding: 14px 18px; display: flex; flex-direction: column; gap: 10px; border-top: 1px solid ButtonBorder; }
  .meta h2 { font-size: 14px; margin: 0; font-family: ui-monospace, monospace; word-break: break-all; display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
  .usages { font-size: 13px; display: flex; flex-direction: column; gap: 8px; }
  .usage { border-left: 3px solid ButtonBorder; padding-left: 10px; }
  .usage .loc { font-family: ui-monospace, monospace; font-size: 12px; color: LinkText; }
  .usage .caption { font-style: italic; margin-top: 2px; }
  .noref { font-size: 13px; color: #b45309; }
  .livelink { font-size: 13px; color: LinkText; align-self: flex-start; }
  .parts { font-size: 13px; display: flex; flex-direction: column; gap: 4px; }
  .parts > .partshead { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; color: GrayText; }
  .part { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
  .part .partname { font-family: ui-monospace, monospace; font-size: 12px; }
  .partstale { font-size: 13px; color: #b45309; }
  .actions { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
  button { padding: 7px 14px; border-radius: 6px; border: 1px solid ButtonBorder; background: ButtonFace; color: ButtonText; cursor: pointer; font-size: 14px; }
  button.approve { border-color: #22c55e; color: #16a34a; }
  button.approve.active { background: #22c55e; color: #fff; }
  button.deny { border-color: #ef4444; color: #dc2626; }
  button.deny.active { background: #ef4444; color: #fff; }
  button.clear { border-color: ButtonBorder; color: GrayText; }
  button.addnote { border-color: ButtonBorder; color: GrayText; }
  button:disabled { opacity: .45; cursor: not-allowed; border-color: ButtonBorder; color: GrayText; }
  /* height is set by the client's autosizeNote as you type; min-height keeps an
     empty box the two rows it was, and overflow-y lets it scroll once it hits
     the cap rather than clipping. No resize handle: autosize owns the height,
     so a dragged box snapped back on the next keystroke — a control that
     undoes itself is worse than no control. */
  .note { width: 100%; min-height: 3.6em; padding: 6px 9px; border: 1px solid ButtonBorder; border-radius: 6px; font-size: 13px; background: Field; color: FieldText; font-family: inherit; resize: none; overflow-y: auto; }
  .reviewedAt { font-size: 11px; color: GrayText; }
  /* a write that did not land, or one rejected because the entry moved. Empty
     for the overwhelmingly common case where it just worked. */
  .cardmsg { font-size: 13px; font-weight: 500; }
  .cardmsg:empty { display: none; }
  .cardmsg.error { color: #b91c1c; }
  .cardmsg.warn { color: #b45309; }
  /* whether what is in the note box has reached the report yet */
  .unsaved { font-size: 12px; font-weight: 500; color: #b45309; }
  .unsaved:empty { display: none; }
  .loaderror { color: #b91c1c; font-size: 14px; line-height: 1.5; white-space: pre-wrap; }
</style>
</head>
<body>
<header>
  <h1>Screenshot review</h1>
  <input id="search" type="search" placeholder="filter by name…" />
  <label class="ctrl"><span>Group</span>
    <select id="group" title="Filter by name group"><option value="">All groups</option></select>
  </label>
  <label class="ctrl"><span>Kind</span>
    <select id="kind" title="Filter by how the image is produced">
      <option value="all">All kinds</option>
      <option value="manual">Manual only</option>
      <option value="auto">Autogenerated only</option>
    </select>
  </label>
  <label class="ctrl"><span>Compare</span>
    <select id="compare" title="How each card shows the current image against origin/main">
      <option value="side">Side by side</option>
      <option value="onion">Onion fade</option>
      <option value="swipe">Swipe divider</option>
      <option value="diff">Difference</option>
    </select>
  </label>
  <label class="ctrl"><span>Sort</span>
    <select id="sortby" title="Sort order">
      <option value="default">A–Z</option>
      <option value="recent">Recently reviewed</option>
    </select>
  </label>
  <div class="tabs">
    <button class="tab" data-status="needs">Needs review<span class="tabcount" data-count="needs"></span></button>
    <button class="tab" data-status="good">Approved<span class="tabcount" data-count="good"></span></button>
    <button class="tab" data-status="answered">Answered<span class="tabcount" data-count="answered"></span></button>
    <button class="tab" data-status="bad">Denied<span class="tabcount" data-count="bad"></span></button>
    <button class="tab" data-status="all">All</button>
  </div>
  <button class="tab" data-toggle="changed" title="only screenshots new or changed vs origin/main">Changed vs main<span class="tabcount" data-count="changed"></span></button>
  <button class="tab" data-toggle="run" title="only specs the last run failed to render, rendered differently twice, or kept behind a raised diffThreshold">Render problems<span class="tabcount" data-count="run"></span></button>
  <div class="counts" id="counts"></div>
</header>
<div id="store"></div>
<main id="main"></main>
<script>
${CLIENT}

const filters = { status: 'needs', changedOnly: false, runOnly: false, sortBy: 'default', group: '', kind: 'all', compare: 'side' }

// How each card is showing its two pictures, and where its slider sits. Held
// out here rather than on \`data\` for the same reason note drafts are: a verdict
// click re-renders the card from \`data\`, and a comparison the reviewer has set
// up should survive that. Not persisted beyond the tab — the header's Compare
// control is the part worth restoring, and it rides in the URL with the rest of
// the view state.
//
// The header sets the default and a card's own control overrides it, so changing
// the default drops the overrides: otherwise switching everything to onion would
// silently leave behind whichever cards had been switched individually.
const compareOverrides = new Map()
const compareValues = new Map()
// The box fitCompareStage last worked out for a card, so a repaint of that card
// is born the right height instead of at nothing. See renderStage.
const compareSizes = new Map()
// Amplify (diff) and blink (onion) are momentary aids rather than ways of
// looking — you turn one on for the four seconds it takes to answer a question
// — so neither is a mode, and neither goes in the URL.
const amplified = new Set()
const blinking = new Set()
// half and half, the position at which both pictures are equally present and
// neither is the one being checked against the other
const COMPARE_DEFAULT = 50
const compareMode = name => compareOverrides.get(name) ?? filters.compare
const compareValue = name => compareValues.get(name) ?? COMPARE_DEFAULT

// Least to most processed: two columns, the same two stacked, then only what
// differs between them. \`side\` first because it is the one that shows each
// picture as itself, which is what most cards want.
const COMPARE_MODES = [
  ['side', '◫ side', 'The two images in two columns'],
  ['onion', '◐ onion', 'Stacked, with a slider that fades between them'],
  ['swipe', '⇔ swipe', 'Stacked, with a divider you drag across the picture'],
  ['diff', '◆ diff', 'Pixel difference — black wherever the two agree'],
]

// A spec the last run could not render, rendered differently twice, or only
// kept because its own diffThreshold was raised. All three mean the image on
// the card is not simply "what the app produces now".
const hasRunProblem = s =>
  !!s.run && (s.run.failed || s.run.flaky !== undefined || s.run.suppressed !== undefined)

// Most spec names are namespaced with '/' (gallery/x, multiway_synteny/x);
// only the hand-listed desktop-* names use a hyphen instead. Grouping only on
// '-' left ~85% of names in a singleton group of their own.
const nameGroup = name => name.includes('/') ? name.split('/')[0] : (name.includes('-') ? name.split('-')[0] : name)

// Persist the current filter state in the URL query string so a review view can
// be reloaded, bookmarked, or shared. Only non-default values are written to
// keep the URL clean.
function writeUrl() {
  const params = new URLSearchParams()
  const q = $('#search').value
  if (q) params.set('q', q)
  if (filters.status !== 'needs') params.set('status', filters.status)
  if (filters.changedOnly) params.set('changed', '1')
  if (filters.runOnly) params.set('problems', '1')
  if (filters.sortBy !== 'default') params.set('sort', filters.sortBy)
  if (filters.group) params.set('group', filters.group)
  if (filters.kind !== 'all') params.set('kind', filters.kind)
  if (filters.compare !== 'side') params.set('compare', filters.compare)
  const qs = params.toString()
  history.replaceState(null, '', qs ? '?' + qs : location.pathname)
}

// A value only restores if it still names something the UI can show. A typo or
// a stale bookmark otherwise leaves every card filtered out and no control
// looking active — a blank page that reads as "nothing to review".
const STATUSES = ['needs', 'good', 'answered', 'bad', 'all']
const KINDS = ['all', 'manual', 'auto']
const SORTS = ['default', 'recent']
const COMPARES = COMPARE_MODES.map(m => m[0])

function readUrl() {
  const params = new URLSearchParams(location.search)
  const status = params.get('status')
  if (STATUSES.includes(status)) filters.status = status
  filters.changedOnly = params.get('changed') === '1'
  filters.runOnly = params.get('problems') === '1'
  const sort = params.get('sort')
  if (SORTS.includes(sort)) filters.sortBy = sort
  const group = params.get('group')
  if (group) filters.group = group
  const kind = params.get('kind')
  if (KINDS.includes(kind)) filters.kind = kind
  const compare = params.get('compare')
  if (COMPARES.includes(compare)) filters.compare = compare
  const q = params.get('q')
  if (q) $('#search').value = q
}

// Diff vs origin/main, the screenshots a branch review cares about:
// "new" = added on this branch (not named by figures.lock on main); "changed" =
// named there but the bytes on disk differ (an update). \`s.changed\` is computed
// server-side against the store hashes. A compose figure counts as changed when
// a part it stacks changed, even if the stack itself wasn't recomposed — that
// gap is the bug the card warns about.
const isNew = s => s.exists && !s.mainUrl
const isChanged = s => s.changed || s.parts.some(p => p.changed || isNew(p))
// parts moved but the published stack didn't: the figure on the site is stale
const partsAhead = s => !s.changed && !isNew(s) && isChanged(s)
// needs review when unreviewed, when its verdict went stale because the
// reviewed image changed since (server-computed stale flag), or when a denial
// has been answered and is waiting on your call. The third case is the one
// staleness cannot see: an answer that changed no pixels leaves the hash
// matching, so it is only 'answered' that puts it back in the queue.
const needsReview = s => !s.verdict || s.stale || s.verdict.status === 'answered'

function changeFilter(key, value) {
  filters[key] = value
  clearJustActed()
  writeUrl()
  render()
}

function buildGroupOptions() {
  const sel = $('#group')
  const groups = [...new Set(data.map(s => nameGroup(s.name)))].sort()
  sel.innerHTML = '<option value="">All groups</option>' +
    groups.map(g => '<option value="' + esc(g) + '">' + esc(g) + '</option>').join('')
  // drop a restored group filter that no longer names an existing group
  if (!groups.includes(filters.group)) {
    filters.group = ''
  }
  sel.value = filters.group
}

async function load() {
  readUrl()
  const specs = fetch('/api/specs')
  // Started here and awaited below the cards' own data: the banner has to be in
  // the page BEFORE the first card is. It is four lines of prose above main and
  // it used to land ~120ms after the cards — a 217px shove of every card
  // downwards, a tenth of a second after they became clickable. A press that
  // straddles that has its button moved out from under the pointer and
  // dispatches no click, which is the reload-then-review half of "I have to
  // click Approve twice".
  //
  // Second in the pair, and that order is load-bearing: the server answers one
  // request at a time, and this one reads the working-tree scan /api/specs pays
  // for. Ahead of it, the 68 MB of figures gets hashed twice per load.
  const storeState = loadStoreState()
  try {
    const res = await specs
    const body = await res.json()
    if (!res.ok || !Array.isArray(body)) {
      throw new Error((body && body.error) || 'HTTP ' + res.status)
    }
    data = body
  } catch (err) {
    // Say why. The report being unparseable is a real case with real recovery
    // instructions in the message (loadReport writes them), and swallowing this
    // left an empty page that looked like a review with nothing left to do.
    $('#main').innerHTML =
      '<div class="loaderror">Could not load the screenshot list.\\n\\n' +
      esc(err.message) + '</div>'
    return
  }
  dropStaleDrafts()
  buildGroupOptions()
  // canonicalize: drops a shared-URL group that no longer names a real group
  writeUrl()
  await storeState
  render()
}

// Whether the figures on this disk are the figures everyone else gets.
//
// This says so in both directions on purpose. A reviewer approving a figure is
// approving pixels, and since figure bytes are gitignored there is otherwise
// nothing on screen distinguishing "published" from "only exists here" — the
// old world had \`git status\` for that. A silent banner would leave the good
// case indistinguishable from a banner that failed to render.
//
// Awaited before the first render rather than after it. It used to be fired and
// forgotten, because it was hashing 62 MB of its own and a review page should
// not wait on that — but it reads the scan /api/specs has already paid for, so
// what it actually costs now is one more round trip against a warm memo. Ahead
// of the cards that is a beat nobody notices; behind them it was four lines of
// banner appearing under a pointer already working through the queue.
//
// It still writes only #store: nothing a card shows depends on it, so it does
// not repaint main. It used to, because the run summary landing here was what
// the "not in the last run" pill was inferred from; that is decided server-side
// per card now, so the second full repaint (which harvested and re-applied every
// note field for nothing) went with it.
async function loadStoreState() {
  const el = $('#store')
  try {
    const res = await fetch('/api/figure-state')
    const s = await res.json()
    if (!res.ok) throw new Error(s && s.error || 'HTTP ' + res.status)
    const parts = []
    if (!s.unpublished.length) {
      parts.push('All ' + s.total + ' figures are published to the store — what you see here is what everyone gets.')
    } else {
      parts.push('<strong>' + s.unpublished.length + ' figure(s) exist only on this machine.</strong> ' +
        'Run <code>pnpm figures:push</code> and commit <code>figures.lock</code>, or they are silently dropped — ' +
        'a verdict recorded now is against pixels nobody else will see.' +
        '<div class="names">' + s.unpublished.map(esc).join(', ') + '</div>')
    }
    // The mirror image of that, and just as invisible to git: figures.lock names
    // a figure whose bytes were never fetched here. Those cards have no picture
    // at all, which reads as a broken figure rather than an unfinished pull.
    if (s.unpulled.length) {
      parts.push('<strong>' + s.unpulled.length + ' figure(s) in <code>figures.lock</code> are not on this disk.</strong> ' +
        'Run <code>pnpm figures:pull</code> — their cards are blank until you do.' +
        '<div class="names">' + s.unpulled.map(esc).join(', ') + '</div>')
    }
    parts.push(describeBaseline(s.baseline))
    parts.push(describeRun(s.run))
    el.className =
      s.unpublished.length || s.unpulled.length || !s.baseline.found || (s.run && s.run.failed) ? 'pending' : 'ok'
    el.innerHTML = parts.map(p => '<div class="storeline">' + p + '</div>').join('')
  } catch (err) {
    el.className = 'pending'
    el.textContent = 'Could not read the figure store state: ' + err.message
  }
}

function agoText(iso) {
  const hours = (Date.now() - new Date(iso).getTime()) / 3600000
  return hours < 1 ? 'less than an hour ago'
    : hours < 48 ? Math.round(hours) + 'h ago'
    : Math.round(hours / 24) + ' days ago'
}

// Which origin/main every "new" and "changed" pill on this page is against.
//
// Two things only git knows and the cards cannot show. First, whether there is
// a baseline at all: with no figures.lock at the ref, every figure reads "new"
// and "Changed vs main" selects all of them — which looks exactly like a branch
// that added everything, and was the shape of the bug this page had for months.
// Second, how old it is: a remote-tracking ref is only as fresh as the last
// fetch, so an unfetched checkout compares against a baseline that still calls
// itself main.
function describeBaseline(b) {
  if (!b.found) {
    return '<strong>No <code>figures.lock</code> at <code>' + esc(b.ref) + '</code>, so there is no baseline.</strong> ' +
      'Every figure below is drawn as new and <em>Changed vs main</em> selects all of them — that is this page ' +
      'having nothing to compare against, not a fact about your branch. <code>git fetch origin</code>.'
  }
  const at = b.commit
    ? ' at <code>' + esc(b.commit) + '</code>' + (b.date ? ', ' + agoText(b.date) : '')
    : ''
  return 'Compared against <code>' + esc(b.ref) + '</code>' + at + ' — ' + b.figures + ' figures. ' +
    'It is only as fresh as your last <code>git fetch</code>.'
}

// The last sweep, in one line. Says when, because a week-old run describes a
// week-old app; says what it covered, because a narrowed run is silent about
// everything else; and says whether flakiness was even tested for, since only
// --check can answer that and "0 flaky" from a normal run means "not measured".
//
// Scope is read off \`selected\`, the count of specs the run actually reached,
// and NOT off \`filter\`. --affected and --cover narrow just as hard as --filter
// while leaving \`filter\` empty, so the line called a 14-spec run "a full sweep"
// — and --affected is the workflow website/CLAUDE.md recommends for exactly the
// change most likely to move a figure.
function describeRun(r) {
  if (!r) {
    return 'No sweep has run on this machine, so no figure here carries a render verdict. ' +
      '<code>pnpm screenshots</code> writes one.'
  }
  const ago = agoText(r.finishedAt)
  const named = r.filter.length
    ? ', filtered to <code>' + r.filter.map(esc).join(',') + '</code>'
    : ''
  // Both counts are needed to call it a sweep. A report that recorded
  // selected but not total compares against 0 and reads as full, which is the
  // same wrong direction filter was standing in for. (No backticks in here:
  // this function lives inside the client template literal.)
  const scope = !r.selected || !r.total
    ? 'scope not recorded (it predates this page asking)'
    : r.selected >= r.total
      ? 'a full sweep' + named
      : r.selected + ' of ' + r.total + ' spec(s)' + named +
        ' — the rest carry no verdict from it'
  const bits = ['Last run ' + ago + ', ' + scope + '.']
  if (r.skipped) bits.push(r.skipped + ' selected spec(s) were skipped (curated / heavy remote data / needs a GPU).')
  if (r.failed) bits.push('<strong>' + r.failed + ' spec(s) failed to render</strong> — their cards show the last image that worked.')
  bits.push(r.check
    ? r.flaky + ' nondeterministic.'
    : 'Nondeterminism not measured (only <code>--check</code> tests for it).')
  return bits.join(' ')
}

function renderUsages(usages) {
  return usages.length
    ? '<div class="usages">' + usages.map(u =>
        '<div class="usage">' +
          '<div class="loc">' + esc(u.file) + ':' + u.line + '</div>' +
          (u.caption ? '<div class="caption">' + esc(u.caption) + '</div>' : '') +
        '</div>'
      ).join('') + '</div>'
    : '<div class="noref">⚠ not referenced in any doc / blog / gallery page</div>'
}

function kindPill(spec) {
  return spec.autogenerated
    ? pill('auto', 'autogenerated')
    : pill('manual', 'manual')
}

// What the last sweep had to say about this spec.
//
// The failure pill matters most: when a spec dies, the PNG on the card is
// whatever the last SUCCESSFUL run left behind, and nothing else on screen
// distinguishes that from a current figure. A reviewer could approve a figure
// the app stopped being able to produce.
//
// "not covered" is drawn rather than left blank, because blank reads as fine.
// It means the last run never reached this spec, so the card carries no
// evidence either way. Computed server-side (see notCovered) off the run's own
// recorded selection — it used to be guessed here from whether --filter had
// been passed, which no --affected or --cover run ever sets.
function runPills(spec) {
  const r = spec.run
  if (!r) {
    return spec.notCovered ? ' ' + pill('notcovered', 'not in the last run') : ''
  }
  let out = ''
  if (r.skipped) out += ' ' + pill('notcovered', 'skipped — ' + esc(r.skipped))
  if (r.failed) out += ' ' + pill('failed', '✗ failed to render')
  if (r.flaky !== undefined)
    out += ' ' + pill('flaky', 'nondeterministic — ' + (r.flaky * 100).toFixed(2) + '% between two renders')
  if (r.suppressed !== undefined)
    out += ' ' + pill('flaky', 'kept behind a raised diffThreshold (' + (r.suppressed * 100).toFixed(2) + '%)')
  return out
}

// A compose figure's parts are its ingredients, not figures of their own: the
// card above already shows the stack they add up to, so they render as a list of
// live links (what <Figure links=...> publishes) rather than separate cards.
function renderParts(spec) {
  return spec.parts.length
    ? '<div class="parts">' +
        '<div class="partshead">stacked from</div>' +
        spec.parts.map(p =>
          '<div class="part">' +
            '<span class="partname">' + esc(p.name) + '</span>' +
            (p.exists ? '' : ' ' + (p.unpulled
              ? pill('bad', 'not pulled')
              : pill('bad', 'image missing'))) +
            (isNew(p) ? ' ' + pill('new', 'new') : '') +
            (p.changed ? ' ' + pill('changed', 'changed') : '') +
            (p.liveUrl ? ' <a href="' + esc(p.liveUrl) + '" target="_blank" rel="noopener">open live ↗</a>' : '') +
          '</div>'
        ).join('') +
        (partsAhead(spec)
          ? '<div class="partstale">⚠ a part changed but the stacked image did not — ' +
            'rerun <code>generate-screenshots --filter ' + esc(spec.name) + '</code></div>'
          : '') +
      '</div>'
    : ''
}

function imgCol(label, inner) {
  return '<div class="imgcol">' +
    '<div class="imglabel"><span>' + label + '</span></div>' +
    '<div class="imgwrap">' + inner + '</div>' +
  '</div>'
}

// The hash rides in the URL so the browser refetches exactly when the pixels
// change and caches otherwise. Without it a regen leaves the reviewer looking
// at a cached image while judging the one now on disk.
const currentSrc = spec => '/img/' + esc(spec.name) + '.png?v=' + esc(spec.imageHash || '')

function currentImg(spec) {
  return spec.exists
    ? '<img src="' + currentSrc(spec) + '" onclick="window.open(this.src)" />'
    // Two different holes with two different fixes. figures.lock naming a figure
    // this checkout has not fetched is the ordinary one — the bytes are in the
    // store and a regen would be wasted work.
    : spec.unpulled
      ? '<div class="missing">⚠ not on this machine — <code>pnpm figures:pull</code></div>'
      : '<div class="missing">⚠ no image and nothing in the store — regenerate it</div>'
}

// Straight at the store. The URL is the baseline figure's content hash, so it
// is immutable, public and cached for a year by CloudFront — nothing for this
// server to proxy, and the link keeps resolving from any commit's manifest,
// which is what makes it worth pasting into an issue.
function mainImg(spec) {
  return spec.mainUrl
    ? '<img src="' + esc(spec.mainUrl) + '" loading="lazy" onclick="window.open(this.src)" ' +
      'onerror="this.replaceWith(Object.assign(document.createElement(\\'div\\'),' +
      '{className:\\'missing\\',textContent:\\'⚠ baseline bytes are not in the store\\'}))" />'
    : '<div class="missing" style="color:#aaa">not on origin/main</div>'
}

// The two pictures, however this card is set to show them.
//
// A stacked comparison is only offered where there are two pictures to stack: a
// figure added on this branch has no baseline, and one that is not on disk has
// nothing to draw. The side-by-side column already says which of those it is,
// so those cards get no bar and no choice.
function renderCompare(spec) {
  const canCompare = spec.exists && !!spec.mainUrl
  const mode = canCompare ? compareMode(spec.name) : 'side'
  return (canCompare ? compareBar(spec, mode) : '') +
    (mode === 'side'
      ? '<div class="card-images">' +
          imgCol('current branch', currentImg(spec)) +
          imgCol('origin/main', mainImg(spec)) +
        '</div>'
      : renderStage(spec, mode))
}

// One bar per card, in every mode, so the way you are looking at a pair is
// always switchable from the same place. It used to be a lone '⧉ onion' button
// tucked into the current-branch column header, which said nothing about there
// being anything else to switch to and nothing about what was on.
function compareBar(spec, mode) {
  return '<div class="cmpbar">' +
    '<span class="cmpmodes">' +
      COMPARE_MODES.map(m => cmpBtn(m[0] === mode, m[1], m[2], 'setCardMode(this,\\'' + m[0] + '\\')')).join('') +
    '</span>' +
    cmpControls(spec, mode) +
    '<span class="cmpnote"></span>' +
  '</div>'
}

const cmpBtn = (on, label, title, call) =>
  '<button class="cmpbtn' + (on ? ' on' : '') + '" title="' + esc(title) + '" ' +
    'onclick="' + call + '">' + label + '</button>'

// Whatever the mode being shown needs steering with, plus the way back to the
// full-size pictures — the stage modes lose the click-to-open each side-by-side
// column has, and full size is the fallback for an overlay that says "something
// moved here" without saying what.
function cmpControls(spec, mode) {
  if (mode === 'side') {
    return ''
  }
  const v = compareValue(spec.name)
  const slider = label =>
    '<input class="cmpslider" type="range" min="0" max="100" step="1" value="' + v + '" ' +
      'aria-label="' + esc(label) + '" oninput="setCompare(this)" />' +
    '<span class="cmppct">' + v + '%</span>'
  const body =
    mode === 'onion'
      // The ends are labelled with the two things being faded between rather
      // than with a number, because 0% and 100% do not say which picture is
      // which — and getting that backwards turns "the new one lost a track"
      // into "the new one gained a track".
      ? '<span>origin/main</span>' +
        slider('Fade between origin/main and the current branch') +
        '<span>current branch</span>' +
        cmpBtn(blinking.has(spec.name), '⚡ blink', 'Cut between the two twice a second — whatever moves is the change', 'toggleCmp(this,\\'blink\\')')
      : mode === 'swipe'
        // No end labels on this one: the divider answers which is which
        // spatially, the stage says so in its corners, and a second answer on
        // the slider would contradict them everywhere except the ends.
        ? '<span>divider</span>' +
          slider('Move the divider between origin/main and the current branch')
        : '<span class="cmphint">black = identical</span>' +
          cmpBtn(amplified.has(spec.name), '⊕ amplify', 'Multiply the difference 8× — a one-shade recolour is otherwise indistinguishable from black', 'toggleCmp(this,\\'amp\\')')
  return body +
    '<span class="cmplink">open ' +
      '<a href="' + currentSrc(spec) + '" target="_blank" rel="noopener">current ↗</a> · ' +
      '<a href="' + esc(spec.mainUrl) + '" target="_blank" rel="noopener">main ↗</a>' +
    '</span>'
}

// One stage for all three stacked modes. They differ only in what the CSS does
// with \`.cmptop\` — fade it, clip it, or blend it — so the markup, the sizing
// and the size-mismatch warning are written once.
function renderStage(spec, mode) {
  const v = compareValue(spec.name)
  const on = [
    mode,
    mode === 'diff' && amplified.has(spec.name) ? 'amp' : '',
    mode === 'onion' && blinking.has(spec.name) ? 'blink' : '',
  ].filter(Boolean).join(' ')
  // Born at the size it was last fitted to. The stage holds the box — the images
  // inside are absolutely positioned — and it is only sized from an image's
  // onload, so a repainted card was 180px of min-height until the bytes came
  // back from cache. Every Approve, Deny and mode switch dropped a 600px stage
  // to 180 and back, jerking the rest of the page 420px under a pointer that
  // was working through a queue. fitCompareStage still owns the real answer and
  // corrects this on arrival.
  const size = compareSizes.get(spec.name)
  return '<div class="cmpwrap">' +
    '<div class="cmpstage ' + on + '" style="--fade:' + v / 100 + ';--wipe:' + v + '%' +
      (size ? ';width:' + size.w + 'px;height:' + size.h + 'px' : '') + '">' +
      '<img class="cmpbase" src="' + esc(spec.mainUrl) + '" loading="lazy" draggable="false" ' +
        'onload="fitCompare(this)" onerror="baselineFailed(this)" />' +
      '<img class="cmptop" src="' + currentSrc(spec) + '" draggable="false" onload="fitCompare(this)" />' +
      (mode === 'swipe'
        ? '<div class="cmpside left"><span>origin/main</span></div>' +
          '<div class="cmpside right"><span>current branch</span></div>' +
          '<div class="cmphandle"></div>'
        : '') +
    '</div>' +
  '</div>'
}

function setCardMode(btn, mode) {
  const name = cardEl(btn).dataset.name
  compareOverrides.set(name, mode)
  updateCard(name)
}

function toggleCmp(btn, kind) {
  const name = cardEl(btn).dataset.name
  const set = kind === 'amp' ? amplified : blinking
  if (set.has(name)) {
    set.delete(name)
  } else {
    set.add(name)
  }
  updateCard(name)
}

// Moving the comparison moves two custom properties and nothing else.
// Deliberately no re-render: rebuilding the card mid-drag destroys the control
// the pointer is holding, and the drag ends there with the comparison stuck
// wherever it got to.
//
// Both \`--fade\` and \`--wipe\` are written every time, and each mode's CSS reads
// the one it cares about. The alternative — a mode-dependent write — leaves the
// other property behind at whatever it was when the mode last changed, which
// shows up the moment you switch modes mid-review.
function setCompareValue(name, raw) {
  const v = Math.max(0, Math.min(100, Math.round(raw)))
  compareValues.set(name, v)
  const card = cardOf(name)
  const stage = card && card.querySelector('.cmpstage')
  if (!stage) {
    return
  }
  stage.style.setProperty('--fade', v / 100)
  stage.style.setProperty('--wipe', v + '%')
  const pct = card.querySelector('.cmppct')
  if (pct) {
    pct.textContent = v + '%'
  }
  // the drag and the slider are two handles on one value, so each has to move
  // the other; guarded because setting .value mid-drag would fight the input
  const slider = card.querySelector('.cmpslider')
  if (slider && Number(slider.value) !== v) {
    slider.value = v
  }
}

const setCompare = input =>
  setCompareValue(cardEl(input).dataset.name, Number(input.value))

// Dragging on the picture itself is what a swipe comparison IS — the pointer
// lands on the thing being compared, so the divider goes where you are already
// looking rather than where a control 200px above it says. The slider in the
// bar is the keyboard-reachable half of the same value; both write through
// setCompareValue, so neither can leave the other behind.
$('#main').addEventListener('pointerdown', e => {
  const stage = e.target.closest('.cmpstage.swipe')
  if (!stage) {
    return
  }
  const name = stage.closest('.card').dataset.name
  const move = ev => {
    const box = stage.getBoundingClientRect()
    setCompareValue(name, ((ev.clientX - box.left) / box.width) * 100)
  }
  const stop = () => {
    stage.removeEventListener('pointermove', move)
    stage.removeEventListener('pointerup', stop)
    stage.removeEventListener('pointercancel', stop)
  }
  // Capture, because the useful end of a wipe is at the edges and most drags
  // leave the stage before they get there. Without it the divider stops dead
  // partway and the reviewer has to re-grab it.
  stage.setPointerCapture(e.pointerId)
  stage.addEventListener('pointermove', move)
  stage.addEventListener('pointerup', stop)
  stage.addEventListener('pointercancel', stop)
  move(e)
})

function cmpNote(stage, text) {
  const el = stage.closest('.card').querySelector('.cmpnote')
  if (el) {
    el.textContent = text
  }
}

const naturalDims = img => img.naturalWidth + '×' + img.naturalHeight

// Lay the stage out once bytes are here, since only they carry the natural
// sizes. Called from each image's own onload — including on a re-render, where
// both come from cache and load again — and again on resize.
//
// A cap on height, not on width, and never a scale above 1: the point is to put
// the two images in the same place at the same size, and an upscaled figure is
// two interpolations hiding the small differences the overlay exists to show.
const CMP_MAX_PX = 600

function fitCompareStage(stage) {
  if (!stage) {
    return
  }
  // Whatever has arrived, rather than waiting for both. The images are
  // absolutely positioned, so an unsized stage is a 0px-tall stage: waiting left
  // every card below the fold collapsed to its min-height, and the baseline half
  // is deliberately lazy — on a 184-card view that is 178 stages that only get a
  // height once you scroll to them, each shoving the page as it arrives. The
  // current image is local and eager, so it lands first and sizes the stage; the
  // baseline refits it on arrival, which moves nothing unless it is a different
  // size, and that case gets said out loud below.
  const imgs = [...stage.querySelectorAll('img')].filter(i => i.complete && i.naturalWidth)
  if (!imgs.length) {
    return
  }
  const w = Math.max(...imgs.map(i => i.naturalWidth))
  const h = Math.max(...imgs.map(i => i.naturalHeight))
  const scale = Math.min(1, (stage.parentElement.clientWidth || w) / w, CMP_MAX_PX / h)
  // the stage holds the box; the images are absolutely positioned inside it, so
  // it is the only thing giving the card its height
  const box = { w: Math.round(w * scale), h: Math.round(h * scale) }
  stage.style.width = box.w + 'px'
  stage.style.height = box.h + 'px'
  // so the next repaint of this card can start here rather than at nothing
  compareSizes.set(stage.closest('.card').dataset.name, box)
  for (const i of imgs) {
    i.style.width = Math.round(i.naturalWidth * scale) + 'px'
    i.style.height = Math.round(i.naturalHeight * scale) + 'px'
  }
  // A stage that lost its baseline is saying something this cannot improve on,
  // and the current image's own onload arrives after it whenever the bytes come
  // from cache rather than the network — which used to wipe the warning and
  // leave a single-image stage looking like an ordinary comparison.
  if (stage.dataset.noBaseline) {
    return
  }
  const [base, top] = imgs
  // only once both are here: one image is never a disagreement about size
  cmpNote(stage, imgs.length === 2 && naturalDims(base) !== naturalDims(top)
    ? 'resized ' + naturalDims(base) + ' → ' + naturalDims(top) +
      ' — drawn at one scale from the top-left, so the extra edge is the change in size'
    : '')
}

const fitCompare = img => fitCompareStage(img.closest('.cmpstage'))

// The store URL 404s (a baseline whose bytes were never pushed). Drop it and
// show the current image alone rather than fading to black, which reads as the
// figure having gone blank on this branch.
function baselineFailed(img) {
  const stage = img.closest('.cmpstage')
  img.remove()
  // before the fit, which reads it
  stage.dataset.noBaseline = '1'
  fitCompareStage(stage)
  cmpNote(stage, '⚠ baseline bytes are not in the store — only the current image is here')
}

// The stage is sized in px off natural dimensions, so a narrowed window leaves
// it overflowing the card until this re-runs. Layout only; nothing reloads.
let fitQueued = false
addEventListener('resize', () => {
  if (fitQueued) {
    return
  }
  fitQueued = true
  requestAnimationFrame(() => {
    fitQueued = false
    for (const stage of document.querySelectorAll('.cmpstage')) {
      fitCompareStage(stage)
    }
  })
})

const verdictBtn = (cls, label, want, status, spec) =>
  '<button class="' + cls + (status === want ? ' active' : '') + '"' +
    (spec.imageHash
      ? ' onclick="setVerdict(this,\\'' + want + '\\')"'
      : ' disabled title="no image on disk — nothing to record a verdict against"') +
  '>' + label + '</button>'

// the shared review client calls this to rebuild one card in place
function renderCard(spec) {
  const v = spec.verdict
  const status = v ? v.status : 'none'
  const cls = spec.stale ? 'stale' : status
  return '<div class="card ' + cls + '" data-name="' + esc(spec.name) + '" data-status="' + status + '">' +
    renderCompare(spec) +
    '<div class="meta">' +
      '<h2>' + esc(spec.name) + ' ' + kindPill(spec) +
        (status === 'answered' ? ' ' + pill('answered', 'answered — reply in the note') : '') +
        (spec.stale ? ' ' + pill('stale', 'image changed since ' + status) : '') +
        (isNew(spec) ? ' ' + pill('new', 'new') : '') +
        (isChanged(spec) ? ' ' + pill('changed', 'changed') : '') +
        (spec.unpublished ? ' ' + pill('unpublished', 'not pushed to the store') : '') +
        runPills(spec) + '</h2>' +
      (spec.run && spec.run.failed ? '<pre class="runerr">' + esc(spec.run.failed) + '</pre>' : '') +
      renderUsages(spec.usages) +
      renderParts(spec) +
      (spec.liveUrl ? '<a class="livelink" href="' + esc(spec.liveUrl) + '" target="_blank" rel="noopener">Open live in JBrowse ↗</a>' : '') +
      // the leading newline is eaten by the HTML parser, so a note that opens
      // with a blank line round-trips without it unless one is spent here
      '<textarea class="note" rows="2" placeholder="note (optional)" onchange="saveNote(this)">\\n' + esc(v ? v.note : '') + '</textarea>' +
      '<div class="actions">' +
        // A verdict is recorded against a hash of the image, so a card with no
        // image on disk has nothing to record one against and the server refuses
        // it — correctly, but only after the click, as an error message under a
        // button that looked live. There are two of these in a normal checkout
        // (figures.lock names them, figures:pull has not fetched them), and the
        // card already says which. Clear stays enabled: dropping an entry needs
        // no image. Same test as the server's, so the two cannot drift.
        verdictBtn('approve', '✓ Approve', 'good', status, spec) +
        verdictBtn('deny', '✗ Deny', 'bad', status, spec) +
        (v ? '<button class="clear" onclick="clearVerdict(this)">clear</button>' : '') +
        // Always rendered, including on an empty box where it only focuses the
        // field. The alternative (show it once there is text to preserve)
        // would have to appear and disappear as the note is typed, and the
        // note field deliberately does not re-render as you type, so it would
        // go stale immediately.
        '<button class="addnote" onclick="addNote(this)" title="Keep this note and start a new one above it">+ add note</button>' +
        (v ? '<span class="reviewedAt">' + new Date(v.reviewedAt).toLocaleString() + '</span>' : '') +
      '</div>' +
      // Below the buttons, not under the box it describes: this line appears
      // the moment you type and disappears the moment the note saves, and the
      // note saves on the blur that the Approve/Deny mousedown itself causes.
      // Above the buttons it moved them 27px out from under the pointer between
      // mousedown and mouseup, so no click was dispatched at all and the first
      // click after typing did nothing.
      '<div class="unsaved">' + esc(draftHint(spec)) + '</div>' +
      '<div class="' + msgClass(spec.name) + '">' + esc(messageText(spec.name)) + '</div>' +
    '</div>' +
  '</div>'
}

function syncControls() {
  for (const b of document.querySelectorAll('header [data-status]')) {
    b.classList.toggle('active', b.dataset.status === filters.status)
  }
  $('[data-toggle="changed"]').classList.toggle('active', filters.changedOnly)
  $('[data-toggle="run"]').classList.toggle('active', filters.runOnly)
  $('#sortby').value = filters.sortBy
  $('#kind').value = filters.kind
  $('#compare').value = filters.compare
  // group belongs here with the other two rather than only in
  // buildGroupOptions: it is the one control whose options are built from the
  // data, so it is the one most likely to be reset out from under the filters
  $('#group').value = filters.group
}

// no parameters: the shared review client calls this after every single-card
// repaint, so it has to be able to see the search box on its own
function renderCounts() {
  const q = $('#search').value.toLowerCase()
  // A badge answers "how many cards do I get if I click this", so it counts
  // within the group/kind/search scope and under every OTHER control's current
  // setting, replacing only its own predicate. A global 42 above a filtered
  // view showing 3 reads as a broken filter. The pill row below stays global:
  // that one is the progress reading for the whole sweep.
  const scoped = data.filter(s => matchesScope(s, q))
  for (const status of ['needs', 'good', 'bad', 'answered']) {
    $('[data-count="' + status + '"]').textContent =
      scoped.filter(s => hasStatus(s, status) && matchesChanged(s) && matchesRun(s)).length
  }
  // The two toggles count what turning them ON would leave, which means
  // honouring the status tab and each other. They used to honour neither, so
  // 'Changed vs main' read 40 over a needs-review queue that would show 3 —
  // exactly the broken-filter reading the tab badges above were written to fix.
  $('[data-count="changed"]').textContent =
    scoped.filter(s => hasStatus(s, filters.status) && matchesRun(s) && (isNew(s) || isChanged(s))).length
  $('[data-count="run"]').textContent =
    scoped.filter(s => hasStatus(s, filters.status) && matchesChanged(s) && hasRunProblem(s)).length

  const count = status => data.filter(s => settledAs(s, status)).length
  const answered = count('answered')
  const good = count('good')
  const bad = count('bad')
  const stale = data.filter(s => s.stale).length
  $('#counts').innerHTML =
    pill('good', good + ' approved') +
    pill('bad', bad + ' denied') +
    (answered ? pill('answered', answered + ' answered, awaiting you') : '') +
    (stale ? pill('stale', stale + ' changed since review') : '') +
    pill('none', data.filter(s => !s.verdict).length + ' unreviewed')
}

// everything except the status tab and the changed toggle — the two controls
// whose own badges have to count what switching to them would show
function matchesScope(s, q) {
  const matchesQuery = !q || s.name.toLowerCase().includes(q)
  const matchesGroup = !filters.group || nameGroup(s.name) === filters.group
  const matchesKind =
    filters.kind === 'all' ||
    (filters.kind === 'manual' && !s.autogenerated) ||
    (filters.kind === 'auto' && s.autogenerated)
  return matchesQuery && matchesGroup && matchesKind
}

// A verdict that still describes the image on the card. A stale one names a
// picture that has since been replaced, so it counts as neither approved nor
// denied — it is back in the queue.
const settledAs = (s, status) => s.verdict?.status === status && !s.stale

// 'all' and 'needs' are the two questions with their own shape; the other three
// tabs are all the same question about a different status word, and spelling
// each out separately is three chances for one of them to drift from the pill
// row that counts it.
function hasStatus(s, status) {
  return status === 'all'
    ? true
    : status === 'needs'
      ? needsReview(s)
      : settledAs(s, status)
}

// The two header toggles as predicates, so the badge that counts what a toggle
// would show and the filter that applies it cannot disagree — they were two
// copies of this, and did.
const matchesChanged = s => !filters.changedOnly || isNew(s) || isChanged(s)
const matchesRun = s => !filters.runOnly || hasRunProblem(s)

function matchesFilters(s, q) {
  return matchesScope(s, q) &&
    (justActed.has(s.name) ||
      (hasStatus(s, filters.status) && matchesChanged(s) && matchesRun(s)))
}

function render() {
  syncControls()
  renderCounts()
  const q = $('#search').value.toLowerCase()
  let visible = data.filter(s => matchesFilters(s, q))
  if (filters.sortBy === 'recent') {
    visible = [...visible].sort((a, b) => {
      const ta = a.verdict ? new Date(a.verdict.reviewedAt).getTime() : 0
      const tb = b.verdict ? new Date(b.verdict.reviewedAt).getTime() : 0
      return tb - ta
    })
  }
  harvestNotes()
  $('#main').innerHTML = visible.map(renderCard).join('')
  applyPendingNotes()
}

$('header').addEventListener('click', e => {
  const statusBtn = e.target.closest('[data-status]')
  const toggleBtn = e.target.closest('[data-toggle]')
  if (statusBtn) {
    changeFilter('status', statusBtn.dataset.status)
  } else if (toggleBtn) {
    const key = toggleBtn.dataset.toggle === 'run' ? 'runOnly' : 'changedOnly'
    changeFilter(key, !filters[key])
  }
})
$('#search').addEventListener('input', () => {
  writeUrl()
  render()
})
$('#sortby').addEventListener('change', () => changeFilter('sortBy', $('#sortby').value))
$('#group').addEventListener('change', () => changeFilter('group', $('#group').value))
$('#kind').addEventListener('change', () => changeFilter('kind', $('#kind').value))
$('#compare').addEventListener('change', () => {
  // the default this overrode has moved, so the overrides no longer mean what
  // the reviewer set them to
  compareOverrides.clear()
  changeFilter('compare', $('#compare').value)
})
load()
</script>
</body>
</html>`
