export type * from './screenshot-spec-types.ts'

import { CODE_BASE } from '../src/lib/code-base.ts'
// jbrowse-img CLI example figures (products/jbrowse-img/README.md)
import { jbrowseImgSpecs } from './screenshot-spec-helpers.ts'
import { alignmentsSpecs } from './specs/alignments.ts'
import { bigwigSpecs } from './specs/bigwig.ts'
import { conservationSpecs } from './specs/conservation.ts'
import { cookbookSpecs } from './specs/cookbook.ts'
import { embeddedSpecs } from './specs/embedded.ts'
import { featuresSpecs } from './specs/features.ts'
import { gallerySpecs } from './specs/gallery.ts'
import { gwasSpecs } from './specs/gwas.ts'
import { hprc2Specs } from './specs/hprc2.ts'
import { ldSpecs } from './specs/ld.ts'
import { mafSpecs } from './specs/maf.ts'
import { methylationSpecs } from './specs/methylation.ts'
import { pangenomeSpecs } from './specs/pangenome.ts'
import { pangenomeCactusSpecs } from './specs/pangenome_cactus.ts'
import { popgenSpecs } from './specs/popgen.ts'
import { qtlSpecs } from './specs/qtl.ts'
import { scatacSpecs } from './specs/scatac.ts'
import { svSpecs } from './specs/sv.ts'
import { syntenySpecs } from './specs/synteny.ts'
import { tcgaSpecs } from './specs/tcga.ts'
import { trioSpecs } from './specs/trio.ts'
import { uiSpecs } from './specs/ui.ts'
import { variantsSpecs } from './specs/variants.ts'

import type { ScreenshotSpec } from './screenshot-spec-types.ts'

export const specs: ScreenshotSpec[] = [
  ...syntenySpecs,
  ...alignmentsSpecs,
  ...variantsSpecs,
  ...bigwigSpecs,
  ...conservationSpecs,
  ...featuresSpecs,
  ...uiSpecs,
  ...methylationSpecs,
  ...ldSpecs,
  ...popgenSpecs,
  ...scatacSpecs,
  ...svSpecs,
  ...tcgaSpecs,
  ...gwasSpecs,
  ...qtlSpecs,
  ...trioSpecs,
  ...gallerySpecs,
  ...mafSpecs,
  ...pangenomeSpecs,
  ...pangenomeCactusSpecs,
  ...hprc2Specs,
  ...cookbookSpecs,
  ...embeddedSpecs,
  ...jbrowseImgSpecs,
]

// jbrowse.org hosts the same test_data/ configs (and the cgiab/hpylori demos)
// these specs load, so every spec's session can be opened as a live, clickable
// instance. The website Figure macro uses screenshotLiveUrls to link each
// screenshot to the running view that produced it. CODE_BASE is the hosted build
// they open in — see src/lib/code-base.ts for retargeting it.
export function specLiveUrl(spec: ScreenshotSpec): string | undefined {
  if (spec.mode === 'url') {
    if (spec.url.startsWith('http')) {
      // an absolute url is used verbatim — unless it's a localhost capture (a
      // local dev-plugin build, e.g. protein/connected), which has no public
      // equivalent and so can't become a reader-facing live link
      return /^https?:\/\/(localhost|127\.0\.0\.1)\b/.test(spec.url)
        ? undefined
        : spec.url
    } else {
      // a bare `?config=...` captured against the local build opens identically
      // on the public hosted instance
      return `${CODE_BASE}${spec.url}`
    }
  } else {
    return undefined
  }
}

// screenshot name -> live-instance URL (all current specs are url-mode)
export const screenshotLiveUrls: Record<string, string> = Object.fromEntries(
  specs.flatMap(spec => {
    const url = specLiveUrl(spec)
    return url ? [[spec.name, url] as const] : []
  }),
)

// Every figure produced by a spec, whether or not it has a public live URL.
// audit-figures uses this to classify a figure as autogenerated — an embedded
// or localhost-build capture is still autogenerated even though it has no
// interactive jbrowse.org link.
export const screenshotSpecNames = new Set(specs.map(spec => spec.name))

// Split a `--filter a,b,c` value into trimmed, non-empty tokens. Shared by the
// generate and review scripts so `--filter`/`--exact` mean the same thing in
// both.
export function parseFilterTokens(filter: string | undefined) {
  return filter
    ? filter
        .split(',')
        .map(t => t.trim())
        .filter(Boolean)
    : []
}

// True when `name` matches any filter token (exact name or substring). An empty
// token list matches everything, so an absent --filter selects all specs.
export function matchesFilterTokens(
  name: string,
  tokens: string[],
  exact: boolean,
) {
  return (
    tokens.length === 0 ||
    tokens.some(t => (exact ? name === t : name.includes(t)))
  )
}
