
import __ASTRO_IMAGE_IMPORT_4v0kV from "img/mm10_initial_load.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZmqDjy from "img/open_lgv_form.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_S8fck from "img/add_track_step_1.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2agjIp from "img/add_track_step_2.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z168rAO from "img/multi_sample_variant_display.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1TxKRW from "img/missense_variant_and_reads.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1R52qR from "img/reads_compact.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_I64G7 from "img/deletion.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1WM9v9 from "img/deletion_soft_clip_sort.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_21zPG7 from "img/insertion.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1MGPzH from "img/deletion_2.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1rQB9u from "img/deletion_2_zoom.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1TdJ3j from "img/deletion_2_zoom_soft_clipping.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_fP4pY from "img/read_arcs.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1laNNA from "img/linked_reads.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZlxHK7 from "img/rna_seq_gene.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2upHjz from "img/rna_seq_gene_soft_clipping.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md";
export default new Map([["img/mm10_initial_load.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_4v0kV], ["img/open_lgv_form.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_ZmqDjy], ["img/add_track_step_1.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_S8fck], ["img/add_track_step_2.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_2agjIp], ["img/multi_sample_variant_display.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_Z168rAO], ["img/missense_variant_and_reads.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_1TxKRW], ["img/reads_compact.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1R52qR], ["img/deletion.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_I64G7], ["img/deletion_soft_clip_sort.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_1WM9v9], ["img/insertion.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_21zPG7], ["img/deletion_2.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1MGPzH], ["img/deletion_2_zoom.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_1rQB9u], ["img/deletion_2_zoom_soft_clipping.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_1TdJ3j], ["img/read_arcs.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_fP4pY], ["img/linked_reads.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_1laNNA], ["img/rna_seq_gene.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_ZlxHK7], ["img/rna_seq_gene_soft_clipping.png?astroContentImageFlag=&importer=..%2Fwebsite%2Fdocs%2Farchive%2Fpag2026_setup_and_exploration%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2upHjz]]);
		