// Generates `${base}.generated.ts` from Slang's reflection JSON plus the
// compiled WGSL / GLSL outputs. The generated file is the single source of
// truth for:
//   - WGSL / GLSL shader strings
//   - Uniform std140 layout (field offsets, total size)
//   - Per-instance vertex buffer layout (field offsets, stride)
//   - GL_ATTRIBUTES descriptors (for PassDescriptor)
//   - TS interface types
//   - Typed writeInstance() + writeUniforms() packers
//
// The interleave-style fast-path packers in hand-written TS should import
// FIELD_OFFSET_F32 / FIELD_OFFSET_U32 (constant indices into Float32Array /
// Uint32Array) rather than hard-coding offsets. Renaming or reordering fields
// in the .slang source then either propagates cleanly (if fields are still
// named the same) or raises a tsc error.

import { readFileSync, writeFileSync } from 'node:fs'

interface ScalarType {
  kind: 'scalar'
  scalarType: 'float32' | 'uint32' | 'int32'
}
interface VectorType {
  kind: 'vector'
  elementCount: number
  elementType: ScalarType
}
type SlangType = ScalarType | VectorType

interface UniformBinding {
  kind: 'uniform'
  offset: number
  size: number
}
interface VaryingBinding {
  kind: 'varyingInput' | 'varyingOutput'
  index: number
}

interface Field {
  name: string
  type: SlangType
  binding?: UniformBinding | VaryingBinding
}

interface StructType {
  kind: 'struct'
  name: string
  fields: Field[]
}

interface ConstantBufferType {
  kind: 'constantBuffer'
  elementType: StructType
  elementVarLayout: { binding: UniformBinding }
}

interface Parameter {
  name: string
  binding: { kind: string; index: number; count?: number }
  type: ConstantBufferType | { kind: string }
}

interface EntryPoint {
  name: string
  stage: 'vertex' | 'fragment' | 'compute'
  parameters: {
    name: string
    type: SlangType | StructType
    semanticName?: string
  }[]
}

interface Reflection {
  parameters: Parameter[]
  entryPoints: EntryPoint[]
}

export interface CodegenTexture {
  name: string
  textureBinding: number
  samplerBinding: number
}

export interface CodegenInputs {
  baseName: string
  reflection: Reflection
  wgsl?: string
  glslVertex?: string
  glslFragment?: string
  textures?: CodegenTexture[]
}

function sizeOf(t: SlangType) {
  return t.kind === 'scalar' ? 4 : t.elementCount * 4
}

function tsFieldType(t: SlangType) {
  if (t.kind === 'scalar') {
    return 'number'
  }
  const ns = Array.from({ length: t.elementCount }, () => 'number').join(', ')
  return `[${ns}]`
}

function isUintField(t: SlangType) {
  if (t.kind === 'scalar') {
    return t.scalarType === 'uint32'
  }
  return t.elementType.scalarType === 'uint32'
}

function isIntField(t: SlangType) {
  if (t.kind === 'scalar') {
    return t.scalarType === 'int32'
  }
  return t.elementType.scalarType === 'int32'
}

function findVertexStruct(r: Reflection) {
  // Prefer an instance struct read from a StructuredBuffer at module scope —
  // that's the layout the TS side has to pack. Fall back to a vertex-input
  // struct (ATTR-semantic parameter) for shaders that use vertex attributes.
  for (const p of r.parameters) {
    const t = p.type as {
      kind?: string
      baseShape?: string
      resultType?: StructType
    }
    if (t.kind === 'resource' && t.baseShape === 'structuredBuffer' && t.resultType) {
      return t.resultType
    }
  }
  const vs = r.entryPoints.find(e => e.stage === 'vertex')
  if (!vs) {
    return undefined
  }
  for (const p of vs.parameters) {
    if (typeof p.type === 'object' && 'kind' in p.type && p.type.kind === 'struct') {
      return p.type
    }
  }
  return undefined
}

function findConstantBuffer(r: Reflection) {
  for (const p of r.parameters) {
    if ('kind' in p.type && p.type.kind === 'constantBuffer') {
      return p.type as ConstantBufferType
    }
  }
  return undefined
}

function toStringLiteral(s: string) {
  return JSON.stringify(s)
}

function componentType(t: SlangType): 'float' | 'uint' | 'int' {
  const s = t.kind === 'scalar' ? t.scalarType : t.elementType.scalarType
  if (s === 'uint32') {
    return 'uint'
  }
  if (s === 'int32') {
    return 'int'
  }
  return 'float'
}

export function emit(inputs: CodegenInputs) {
  const { baseName, reflection, wgsl, glslVertex, glslFragment, textures } = inputs
  const lines: string[] = [ `// AUTO-GENERATED by scripts/shader-codegen from ${baseName}.slang.`, '// Do not edit. Run `pnpm gen:shaders` to regenerate.', '']
  const halImports = ['GlAttributeLayout']
  if (textures && textures.length > 0) {
    halImports.push('TextureBinding')
  }
  lines.push(
    `import type { ${halImports.join(', ')} } from '@jbrowse/core/gpu/hal'`, ''
  )

  if (wgsl !== undefined) {
    lines.push(`export const WGSL_SOURCE = ${toStringLiteral(wgsl)}`, '')
  }
  if (glslVertex !== undefined) {
    lines.push(`export const GLSL_VERTEX = ${toStringLiteral(glslVertex)}`, '')
  }
  if (glslFragment !== undefined) {
    lines.push(`export const GLSL_FRAGMENT = ${toStringLiteral(glslFragment)}`, '')
  }

  const cb = findConstantBuffer(reflection)
  if (cb) {
    const u = cb.elementType
    const totalBytes = cb.elementVarLayout.binding.size
    lines.push(`export const UNIFORMS_SIZE_BYTES = ${totalBytes}`, `export const UNIFORMS_SIZE_F32 = ${totalBytes / 4}`, '', '// Byte offsets (into an ArrayBuffer / DataView).', 'export const UNIFORM_OFFSET_BYTES = {')
    for (const f of u.fields) {
      if (f.binding?.kind === 'uniform') {
        lines.push(`  ${f.name}: ${f.binding.offset},`)
      }
    }
    lines.push('} as const', '', '// Indices into a Float32Array / Uint32Array view.', 'export const UNIFORM_OFFSET_F32 = {')
    for (const f of u.fields) {
      if (f.binding?.kind === 'uniform') {
        lines.push(`  ${f.name}: ${f.binding.offset / 4},`)
      }
    }
    lines.push('} as const', '', 'export interface Uniforms {')
    for (const f of u.fields) {
      lines.push(`  ${f.name}: ${tsFieldType(f.type)}`)
    }
    lines.push('}', '')

    const uniformFields = u.fields.filter(f => f.binding?.kind === 'uniform')
    const hasUint = uniformFields.some(f => isUintField(f.type))
    const hasInt = uniformFields.some(f => isIntField(f.type))
    const hasFloat = uniformFields.some(
      f => !isUintField(f.type) && !isIntField(f.type),
    )
    lines.push('export function writeUniforms(buf: ArrayBuffer, uniforms: Uniforms) {')
    if (hasFloat) {
      lines.push('  const f32 = new Float32Array(buf)')
    }
    if (hasUint) {
      lines.push('  const u32 = new Uint32Array(buf)')
    }
    if (hasInt) {
      lines.push('  const i32 = new Int32Array(buf)')
    }
    for (const f of u.fields) {
      if (f.binding?.kind !== 'uniform') {
        continue
      }
      const off4 = f.binding.offset / 4
      let view: 'f32' | 'u32' | 'i32'
      if (isUintField(f.type)) {
        view = 'u32'
      } else if (isIntField(f.type)) {
        view = 'i32'
      } else {
        view = 'f32'
      }
      if (f.type.kind === 'scalar') {
        lines.push(`  ${view}[${off4}] = uniforms.${f.name}`)
      } else {
        for (let i = 0; i < f.type.elementCount; i++) {
          lines.push(`  ${view}[${off4 + i}] = uniforms.${f.name}[${i}]`)
        }
      }
    }
    lines.push('}', '')
  }

  const vs = findVertexStruct(reflection)
  if (vs) {
    let cursor = 0
    const attrs = vs.fields.map(f => {
      const entry = {
        name: f.name,
        offsetBytes: cursor,
        size: sizeOf(f.type),
        type: f.type,
      }
      cursor += sizeOf(f.type)
      return entry
    })
    const stride = cursor

    lines.push(`export const INSTANCE_STRIDE_BYTES = ${stride}`, `export const INSTANCE_STRIDE_F32 = ${stride / 4}`, '', 'export const FIELD_OFFSET_BYTES = {')
    for (const a of attrs) {
      lines.push(`  ${a.name}: ${a.offsetBytes},`)
    }
    lines.push('} as const', '', 'export const FIELD_OFFSET_F32 = {')
    for (const a of attrs) {
      lines.push(`  ${a.name}: ${a.offsetBytes / 4},`)
    }
    lines.push('} as const', '', `export const GL_ATTRIBUTES: readonly GlAttributeLayout[] = [`)
    for (const a of attrs) {
      const ct = componentType(a.type)
      const comps = a.type.kind === 'scalar' ? 1 : a.type.elementCount
      const integer = ct === 'uint' || ct === 'int'
      lines.push(
        `  { name: 'a_${a.name}', components: ${comps}, type: '${ct}', offsetBytes: ${a.offsetBytes}, integer: ${integer} },`,
      )
    }
    lines.push(']', '', `export interface ${vs.name} {`)
    for (const f of vs.fields) {
      lines.push(`  ${f.name}: ${tsFieldType(f.type)}`)
    }
    lines.push('}', '', 
      `export function write${vs.name}(buf: ArrayBuffer, instanceIndex: number, inst: ${vs.name}) {`, `  const base = instanceIndex * ${stride}`
    , `  const dv = new DataView(buf)`)
    for (const a of attrs) {
      const elemSize = a.type.kind === 'scalar' ? 4 : sizeOf(a.type.elementType)
      const uint = isUintField(a.type)
      const setter = uint ? 'setUint32' : 'setFloat32'
      if (a.type.kind === 'scalar') {
        lines.push(`  dv.${setter}(base + ${a.offsetBytes}, inst.${a.name}, true)`)
      } else {
        for (let i = 0; i < a.type.elementCount; i++) {
          lines.push(
            `  dv.${setter}(base + ${a.offsetBytes + i * elemSize}, inst.${a.name}[${i}], true)`,
          )
        }
      }
    }
    lines.push('}', '')
  }

  if (textures && textures.length > 0) {
    lines.push('// Combined `Sampler2D` bindings. Texture unit indices start at 0.', 'export const TEXTURES: readonly TextureBinding[] = [')
    for (let i = 0; i < textures.length; i++) {
      const t = textures[i]!
      lines.push(
        `  { textureBinding: ${t.textureBinding}, samplerBinding: ${t.samplerBinding}, glTextureUnit: ${i}, glUniformName: 'u_${t.name}', filter: 'linear' },`,
      )
    }
    lines.push(']', '')
  }

  return lines.join('\n')
}

function runCli() {
  const [, , reflectionPath, wgslPath, glslVertexPath, glslFragmentPath, outPath] = process.argv
  if (!reflectionPath || !outPath) {
    console.error(
      'usage: codegen.ts <reflection.json> [wgsl|-] [glslVertex|-] [glslFragment|-] <out.ts>',
    )
    process.exit(1)
  }
  const reflection = JSON.parse(readFileSync(reflectionPath, 'utf8')) as Reflection
  const wgsl =
    wgslPath && wgslPath !== '-' ? readFileSync(wgslPath, 'utf8') : undefined
  const glslVertex =
    glslVertexPath && glslVertexPath !== '-'
      ? readFileSync(glslVertexPath, 'utf8')
      : undefined
  const glslFragment =
    glslFragmentPath && glslFragmentPath !== '-'
      ? readFileSync(glslFragmentPath, 'utf8')
      : undefined

  const baseName = reflectionPath.replace(/\.reflection\.json$/, '').replace(/.*\//, '')
  const out = emit({ baseName, reflection, wgsl, glslVertex, glslFragment })
  writeFileSync(outPath, out)
  console.log(`wrote ${outPath}`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  runCli()
}
