import { getCollection } from 'astro:content'

import { entrySlug } from './docs-sidebar.ts'

// Build-time index of the autogenerated reference docs (config/models/api) and
// the hand-written guides that reference them. One source of truth drives both
// directions of cross-linking: guide→reference auto-links and reference→guide
// backlinks. Everything is derived from the docs content collection, so it
// stays correct as `pnpm gendocs` regenerates the reference pages.
//
// Guide→guide links are deliberately NOT here: every guide carries a curated
// "## See also", which reads better than anything derived from shared
// citations (see remark-related-guides.ts).

const autogenDirs = new Set(['config', 'models', 'api'])

// type name (e.g. "BamAdapter") -> reference page url. A name can be documented
// as both a config and a state model; the config page is the more useful target
// for a guide mention (and it already links onward to its model), so prefer it.
export const typeNameToUrl = new Map<string, string>()

interface GuideRef {
  title: string
  url: string
}

// reference page id -> guides that link to it (the backlink direction)
const backlinks = new Map<string, GuideRef[]>()

export interface DocListEntry {
  title: string
  description?: string
  url: string
  // Category prefix of a "<Category> -> <Name>" sidebar_label (config/models
  // pages), for the grouped index pages. Undefined for pages without one.
  category?: string
}
// top-level dir (e.g. "tutorials") -> its pages, for remark-doc-list. Lets an
// index page (introduction.md) render a directory's contents from frontmatter
// instead of hand-mirroring every title + description.
const docsByDir = new Map<string, DocListEntry[]>()

// page url ("/docs/user_guides/foo") -> its own frontmatter title, across
// every doc. Backs remark-wiki-title's empty-text `[](url)` links, so a
// cross-link's visible text can't drift from the title of the page it points
// to.
const titleByUrl = new Map<string, string>()

function topDir(id: string): string {
  return id.split('/')[0]!
}

function urlFor(id: string): string {
  return `/docs/${entrySlug(id)}`
}

// Every /docs/... reference a guide makes, normalized to a known page id.
function referencedIds(body: string, known: Set<string>): Set<string> {
  const ids = new Set<string>()
  const re =
    /\]\(\s*(?:\.\.\/)*\/?(?:docs\/)?((?:config|models|api)\/[a-z0-9-]+)/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(body)) !== null) {
    const id = m[1]!.toLowerCase()
    if (known.has(id)) {
      ids.add(id)
    }
  }
  return ids
}

let built: Promise<void> | undefined

// Populate the indexes once from the docs collection. Cached so repeated
// renderMarkdown calls share the work.
export function ensureAutogenIndex(): Promise<void> {
  built ??= (async () => {
    const docs = await getCollection('docs')
    const knownIds = new Set(docs.map(d => d.id))
    for (const d of docs) {
      titleByUrl.set(urlFor(d.id), d.data.title)
    }
    for (const d of docs) {
      const dir = topDir(d.id)
      // Only pages inside a subdirectory belong to that dir's doc-list; a
      // top-level page whose id equals the dir (e.g. the config.md index page,
      // id "config") is the index itself and must not list itself.
      if (d.id.includes('/')) {
        const categoryMatch = /^(.+?)\s*->\s*.+$/.exec(
          d.data.sidebar_label ?? '',
        )
        const entry = {
          title: d.data.title,
          description: d.data.description,
          url: urlFor(d.id),
          category: categoryMatch?.[1]!.trim(),
        }
        const list = docsByDir.get(dir)
        if (list) {
          list.push(entry)
        } else {
          docsByDir.set(dir, [entry])
        }
      }
    }

    // config wins over models for a shared type name (loop models first so a
    // later config entry overwrites it)
    for (const dir of ['models', 'config']) {
      for (const d of docs) {
        if (topDir(d.id) === dir) {
          typeNameToUrl.set(d.data.title, urlFor(d.id))
        }
      }
    }

    for (const d of docs) {
      if (!autogenDirs.has(topDir(d.id))) {
        for (const targetId of referencedIds(d.body ?? '', knownIds)) {
          const entry = { title: d.data.title, url: urlFor(d.id) }
          const list = backlinks.get(targetId)
          if (list) {
            list.push(entry)
          } else {
            backlinks.set(targetId, [entry])
          }
        }
      }
    }
  })()
  return built
}

// Pages directly under a top-level docs dir, sorted by title — the same order
// the /docs/tutorials/ landing page and the autogenerated sidebar use.
export function docsInDir(dir: string): DocListEntry[] {
  return [...(docsByDir.get(dir) ?? [])].sort((a, b) =>
    a.title.localeCompare(b.title),
  )
}

// Same pages as docsInDir, bucketed by their sidebar_label category. Categories
// and entries are both sorted alphabetically, matching the order the sidebar's
// prefixByCategory puts them in, so an index page and the sidebar stay
// consistent. Pages without a category fall into "General".
export function docsInDirGrouped(
  dir: string,
): { category: string; entries: DocListEntry[] }[] {
  const grouped = new Map<string, DocListEntry[]>()
  for (const entry of docsInDir(dir)) {
    const category = entry.category ?? 'General'
    const list = grouped.get(category)
    if (list) {
      list.push(entry)
    } else {
      grouped.set(category, [entry])
    }
  }
  return [...grouped.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([category, entries]) => ({ category, entries }))
}

export function backlinksFor(autogenId: string): GuideRef[] {
  return [...(backlinks.get(autogenId) ?? [])].sort((a, b) =>
    a.title.localeCompare(b.title),
  )
}

// Resolves a link href (as written in markdown source: a trailing slash and/or
// `#fragment` optional) to the title of the page it points to.
export function titleForUrl(url: string): string | undefined {
  return titleByUrl.get(url.replace(/#.*$/, '').replace(/\/$/, ''))
}
