// How a file under website/docs becomes a content-collection id, and how that
// id becomes the slug the page is served at. Two functions, one home: the pair
// had been rewritten from memory in src/content.config.ts, src/lib/docs-sidebar.ts,
// scripts/check-wiki-titles.ts and scripts/check-sidebar.ts, each of which
// carried a comment saying it "mirrors" one of the others — which is the shape
// drift takes, not a defense against it.

// The collection id for a docs file. Autogenerated config/model pages are
// CamelCase files (BaseTrack.md) whose cross-links use the lowercase Docusaurus
// `id:` slug (../basetrack), so ids lowercase; introduction.md carries
// `slug: /` and keys at the docs root instead.
// `frontmatterSlug` is `unknown` because the content loader hands it over
// untyped; the only value that means anything here is the literal "/".
export function docId(relPath: string, frontmatterSlug: unknown): string {
  return frontmatterSlug === '/'
    ? 'index'
    : relPath.replace(/\.md$/, '').toLowerCase()
}

// The URL slug for a collection id: the docs root is "", and a directory's
// index page is served at the directory itself.
export function entrySlug(id: string): string {
  if (id === 'index') {
    return ''
  }
  return id.endsWith('/index') ? id.slice(0, -6) : id
}
