// How a file under website/docs becomes a content-collection id, and how that
// id becomes the slug the page is served at. Two functions, one home: the pair
// had been rewritten from memory in src/content.config.ts, src/lib/docs-sidebar.ts,
// scripts/check-wiki-titles.ts and scripts/check-sidebar.ts, each of which
// carried a comment saying it "mirrors" one of the others — which is the shape
// drift takes, not a defense against it.

// The collection id for a docs file. Autogenerated config/model pages are
// CamelCase files (BaseTrack.md) whose cross-links use the lowercase Docusaurus
// `id:` slug (../basetrack), so ids lowercase; introduction.md carries
// `slug: /` and keys at the docs root instead.
// `frontmatterSlug` is `unknown` because the content loader hands it over
// untyped; the only value that means anything here is the literal "/".
export function docId(relPath: string, frontmatterSlug: unknown): string {
  return frontmatterSlug === '/'
    ? 'index'
    : relPath.replace(/\.md$/, '').toLowerCase()
}

// The URL slug for a collection id: the docs root is "", and a directory's
// index page is served at the directory itself.
export function entrySlug(id: string): string {
  if (id === 'index') {
    return ''
  }
  return id.endsWith('/index') ? id.slice(0, -6) : id
}

// The filename a page is emitted under by the raw-markdown build hook (and so
// the name /llms.txt links and check-llms.ts verifies): its slug, with the docs
// root — whose slug is the empty string — named `index`. Takes a collection id
// or an already-resolved slug; entrySlug is idempotent, so callers on either
// side of it agree without having to know which they hold.
export function slugFilename(idOrSlug: string): string {
  return entrySlug(idOrSlug) || 'index'
}

// A doc's own page URL, before the site base path is applied. Kept next to the
// derivation it is built from because the lookups keyed on it (the wiki-title
// index in autogen-links.ts, its validator in scripts/check-wiki-titles.ts) both
// have to spell it the same way as the pages do.
export function docUrl(id: string): string {
  return `/docs/${entrySlug(id)}`
}

// A link href as authored in markdown — trailing slash and `#fragment` both
// optional — reduced to the one spelling docUrl values are keyed under.
//
// The map side is normalized too, not just the lookup side. It wasn't: the docs
// root is `docUrl('index') === '/docs/'`, which no stripped lookup could ever
// produce, so introduction.md's title sat in the index under a key nothing could
// reach — `[](/docs/)` threw as unresolvable rather than resolving to
// "Introduction", and check-wiki-titles could not see a hand-written link that
// duplicated that title.
export function normalizeDocUrl(url: string): string {
  return url.replace(/#.*$/, '').replace(/\/+$/, '')
}
