import { entrySlug } from './doc-slug.ts'
import { GUIDE_CATEGORY_ORDER, guideRank } from './guide-categories.ts'
import sidebarsJson from '../../sidebars.json'

export { entrySlug }

export interface SidebarLink {
  type: 'link'
  label: string
  href: string
  slug: string
  // The section this page sits under, when its category renders as a heading
  // row rather than as a prefix on the label (see withHeadings). Carried
  // through to the link's `aria-label` and to the sidebar filter, so the
  // grouping the eye reads off the heading is still in the accessible name and
  // still matchable by typing — the two things the dropped prefix was doing.
  group?: string
}

// A section label inside a category: the "Adapter"/"Track types" that used to
// be prefixed onto every page under it. Not a disclosure — it hides nothing and
// there is nothing to click, so the sidebar stays one level of nesting deep.
export interface SidebarHeading {
  type: 'heading'
  label: string
}

export interface SidebarGroup {
  type: 'group'
  label: string
  items: SidebarEntry[]
  // A collapsible group whose summary is itself a link to that section's
  // overview page (`overview` in sidebars.json). `slug` marks it active/open
  // when the current page matches. A category with no landing page of its own
  // (Getting started, Showcase) omits both and is a pure toggle.
  href?: string
  slug?: string
}

export type SidebarEntry = SidebarLink | SidebarGroup | SidebarHeading

interface DocEntry {
  id: string
  data: { title: string; sidebar_label?: string; guide_category?: string }
}

type DocusaurusSidebarItem =
  | string
  | {
      type: 'category'
      label: string
      // The section's own landing page, promoted onto the category header so
      // the header is the link to it. Listing it as an ordinary item instead
      // gives seven sidebar rows all labeled "Overview", none of which matches
      // the h1 of the page it opens. A doc-relative slug, like `link`'s `to`,
      // and it need not be a docs-collection entry (Tutorials' index is an
      // .astro page).
      overview?: string
      items: DocusaurusSidebarItem[]
    }
  | { type: 'autogenerated'; dirName: string }
  // An explicit link to a page that isn't a docs-collection entry. `to` is a
  // doc-relative slug so the base URL is applied the same way as for doc links.
  | { type: 'link'; label: string; to: string }

export function containsSlug(entry: SidebarEntry, slug: string): boolean {
  switch (entry.type) {
    case 'heading':
      return false
    case 'link':
      return entry.slug === slug
    default:
      return (
        entry.slug === slug || entry.items.some(child => containsSlug(child, slug))
      )
  }
}

function docLabel(entry: DocEntry): string {
  return entry.data.sidebar_label ?? entry.data.title
}

function docHref(baseUrl: string, slug: string): string {
  return `${baseUrl}/docs/${slug}${slug ? '/' : ''}`
}

// The sidebar is deliberately at most one level deep: a top-level category,
// then pages. Subcategories used to be nested collapsible groups, which hid
// most of the docs behind a closed heading — a reader scrolls past a section
// they don't want far more reliably than they open one they can't see.
//
// A subcategory is therefore a heading ROW, and the pages under it stay in the
// same flat list at the same indent. It was a "<Subcategory>: " prefix on every
// label before this, which kept the grouping visible but said it once per page:
// 58 rows opening "Adapter: " on the config reference, "Adapter: BamAdapter"
// saying the word twice, and 30% of all the label text in the sidebar spent on
// repeating the heading. A heading row says it once and costs no nesting,
// because it is a label rather than a disclosure — nothing is behind it. The
// landing pages (guide indexes, /docs/config, /docs/models) render the same
// sections as `###` headings, from the same category names.
function withHeadings(
  sections: { category: string; links: SidebarLink[] }[],
): SidebarEntry[] {
  return sections.flatMap(({ category, links }) => [
    { type: 'heading' as const, label: category },
    ...links.map(link => ({ ...link, group: category })),
  ])
}

// Sections the config and state-model reference dirs, whose generated
// sidebar_label is "<Category> -> <Name>"; the label keeps only the name.
// Categories and their pages are both alphabetical, matching the order
// docsInDirGrouped puts the same pages in on the index page. A page whose label
// carries no category leads the list rather than vanishing (none do today).
function sectionByCategory(links: SidebarLink[]): SidebarEntry[] {
  const byCategory = new Map<string, SidebarLink[]>()
  const uncategorized: SidebarLink[] = []
  for (const link of links) {
    const match = /^(.+?)\s*->\s*(.+)$/.exec(link.label)
    if (match) {
      const category = match[1]!.trim()
      const inCategory = byCategory.get(category) ?? []
      inCategory.push({ ...link, label: match[2]!.trim() })
      byCategory.set(category, inCategory)
    } else {
      uncategorized.push(link)
    }
  }
  for (const inCategory of byCategory.values()) {
    inCategory.sort((a, b) => a.label.localeCompare(b.label))
  }
  return [
    ...uncategorized,
    ...withHeadings(
      [...byCategory.entries()]
        .sort((a, b) => a[0].localeCompare(b[0]))
        .map(([category, inCategory]) => ({
          category,
          links: inCategory,
        })),
    ),
  ]
}

// Sections a guide directory by its pages' `guide_category` frontmatter, in the
// same buckets and the same order the guide's landing page uses (see
// src/lib/guide-categories.ts). `docs` and `links` are aligned by position.
// Categories not in `categoryOrder` (a stray value) fall to the end
// alphabetically rather than vanishing.
function sectionByGuideCategory(
  dirName: string,
  docs: DocEntry[],
  links: SidebarLink[],
  categoryOrder: string[],
): SidebarEntry[] {
  const byCategory = new Map<string, SidebarLink[]>()
  for (let i = 0; i < docs.length; i++) {
    const category = docs[i]!.data.guide_category ?? 'Other'
    if (!byCategory.has(category)) {
      byCategory.set(category, [])
    }
    byCategory.get(category)!.push(links[i]!)
  }

  // `links` arrives alphabetical by label, so a stable sort on the curated rank
  // alone lifts the lead pages and leaves everything else as it was.
  for (const inCategory of byCategory.values()) {
    inCategory.sort(
      (a, b) => guideRank(dirName, a.slug) - guideRank(dirName, b.slug),
    )
  }

  const ordered = categoryOrder.filter(c => byCategory.has(c))
  const extra = [...byCategory.keys()]
    .filter(c => !categoryOrder.includes(c))
    .sort()
  return withHeadings(
    [...ordered, ...extra].map(category => ({
      category,
      links: byCategory.get(category)!,
    })),
  )
}

function getAutoItems(
  dirName: string,
  allDocs: DocEntry[],
  baseUrl: string,
): SidebarEntry[] {
  const dirDepth = dirName.split('/').length + 1
  const docs = allDocs
    .filter(d => {
      const slug = entrySlug(d.id)
      return (
        slug.startsWith(`${dirName}/`) && slug.split('/').length === dirDepth
      )
    })
    .sort((a, b) => docLabel(a).localeCompare(docLabel(b)))

  const links: SidebarLink[] = docs.map(d => {
    const slug = entrySlug(d.id)
    return {
      type: 'link',
      label: docLabel(d),
      href: docHref(baseUrl, slug),
      slug,
    }
  })

  const categoryOrder = GUIDE_CATEGORY_ORDER[dirName]
  return dirName === 'config' || dirName === 'models'
    ? sectionByCategory(links)
    : categoryOrder
      ? sectionByGuideCategory(dirName, docs, links, categoryOrder)
      : links
}

function convertItems(
  items: DocusaurusSidebarItem[],
  allDocs: DocEntry[],
  baseUrl: string,
  docsBySlug: Map<string, DocEntry>,
): SidebarEntry[] {
  const result: SidebarEntry[] = []

  for (const item of items) {
    if (typeof item === 'string') {
      const slug = entrySlug(item)
      const resolvedSlug = slug === 'introduction' ? '' : slug
      const entry = docsBySlug.get(resolvedSlug)
      const label = entry ? docLabel(entry) : slug
      result.push({
        type: 'link',
        label,
        href: docHref(baseUrl, resolvedSlug),
        slug: resolvedSlug,
      })
    } else if (item.type === 'autogenerated') {
      result.push(...getAutoItems(item.dirName, allDocs, baseUrl))
    } else if (item.type === 'link') {
      const slug = entrySlug(item.to)
      result.push({
        type: 'link',
        label: item.label,
        href: docHref(baseUrl, slug),
        slug,
      })
    } else {
      const overview =
        item.overview === undefined ? undefined : entrySlug(item.overview)
      result.push({
        type: 'group',
        label: item.label,
        href: overview === undefined ? undefined : docHref(baseUrl, overview),
        slug: overview,
        items: convertItems(item.items, allDocs, baseUrl, docsBySlug),
      })
    }
  }

  return result
}

export function buildSidebar(
  allDocs: DocEntry[],
  baseUrl: string,
): SidebarEntry[] {
  const docsBySlug = new Map(allDocs.map(d => [entrySlug(d.id), d]))
  return convertItems(
    sidebarsJson.sidebar as DocusaurusSidebarItem[],
    allDocs,
    baseUrl,
    docsBySlug,
  )
}

// Ancestor group labels of a page, outermost first ("User guide"), for the
// breadcrumb above its h1. With the sidebar flattened to one level this is
// normally a single label, but it stays a walk so a future nested group is
// handled. Derived from the resolved sidebar for the same reason
// buildSearchCategoryMap is: which group holds a page is only known after
// buildSidebar expands the autogenerated directories, so a second walk of the
// raw sidebars.json could not see it, and any hand-listed copy would drift when
// a page moves. The current page itself is not included
// (the h1 right below already names it), and a top-level page like FAQ has no
// ancestors and so gets an empty trail.
export function breadcrumbTrail(
  sidebar: SidebarEntry[],
  slug: string,
): string[] {
  for (const entry of sidebar) {
    // `entry.items.some` rather than `containsSlug(entry, …)` so a group that
    // *is* the page (a showcase group with its own href) isn't its own ancestor
    if (
      entry.type === 'group' &&
      entry.items.some(c => containsSlug(c, slug))
    ) {
      return [entry.label, ...breadcrumbTrail(entry.items, slug)]
    }
  }
  return []
}

// A group's own overview page counts as one of its links, and leads them — for
// /llms.txt it is the section's introduction, and for the search-category map it
// has to land in its own bucket like every other page under the heading.
function flattenLinks(entry: SidebarEntry): SidebarLink[] {
  switch (entry.type) {
    case 'heading':
      return []
    case 'link':
      return [entry]
    default:
      return [
        ...(entry.href !== undefined && entry.slug !== undefined
          ? [
              {
                type: 'link' as const,
                label: entry.label,
                href: entry.href,
                slug: entry.slug,
              },
            ]
          : []),
        ...entry.items.flatMap(flattenLinks),
      ]
  }
}

// Flattens the sidebar into ordered `## <section>` buckets for /llms.txt. Each
// top-level group is a section; standalone top-level links (Introduction,
// Cookbook, CLI, FAQ) merge into one "General" section (else each emits a
// duplicate "## General"). `has` filters to slugs with an emitted page; a slug
// appears in its first section only.
//
// Labels here keep the "<Section>: " prefix the sidebar dropped. Nothing is
// redundant about it in a flat text index: one `## Reference: Config schema`
// heading covers 116 bullets with no heading rows between them, so a bullet
// reading "BamAdapter" rather than "Adapter: BamAdapter" is the reader's only
// loss, with nothing gained — the argument against the prefix was always about
// repeating it down a rendered column.
export function sidebarSections(
  sidebar: SidebarEntry[],
  has: (slug: string) => boolean,
): { label: string; links: SidebarLink[] }[] {
  const seen = new Set<string>()
  const fresh = (links: SidebarLink[]) =>
    links
      .filter(link => {
        const ok = has(link.slug) && !seen.has(link.slug)
        if (ok) {
          seen.add(link.slug)
        }
        return ok
      })
      .map(link =>
        link.group ? { ...link, label: `${link.group}: ${link.label}` } : link,
      )

  const sections: { label: string; links: SidebarLink[] }[] = []
  const general: SidebarLink[] = []
  let generalIdx = -1
  for (const entry of sidebar) {
    if (entry.type === 'group') {
      const links = fresh(flattenLinks(entry))
      if (links.length) {
        sections.push({ label: entry.label, links })
      }
    } else if (entry.type === 'link') {
      if (generalIdx === -1) {
        generalIdx = sections.length
        sections.push({ label: 'General', links: [] })
      }
      general.push(entry)
    }
  }
  if (generalIdx !== -1) {
    sections[generalIdx]!.links = fresh(general)
    if (!sections[generalIdx]!.links.length) {
      sections.splice(generalIdx, 1)
    }
  }
  return sections
}

// The "showcase" pages (Features / Plugins / Gallery) hang off the same sidebar
// as the docs, so navigation is identical everywhere on the site. They're
// grouped under one "Showcase" category rather than sitting as three top-level
// links. No `overview`: there is no page that introduces the three, and the
// category is a pure toggle for that reason.
export function buildShowcaseGroups(baseUrl: string): SidebarEntry[] {
  const pageUrl = (path: string) => `${baseUrl}/${path}/`
  return [
    {
      type: 'group',
      label: 'Showcase',
      items: [
        {
          type: 'link',
          label: 'Features',
          href: pageUrl('features'),
          slug: 'features',
        },
        {
          type: 'link',
          label: 'Plugins',
          href: pageUrl('plugin_store'),
          slug: 'plugin_store',
        },
        {
          type: 'link',
          label: 'Gallery',
          href: pageUrl('gallery'),
          slug: 'gallery',
        },
      ],
    },
  ]
}

// Showcase is spliced in after the last collapsible category rather than
// appended, so the nav renders as one unbroken run of categories: a link with
// no disclosure arrow sitting between two categories reads as a rendering bug,
// and interleaving the two shapes makes neither run scannable. sidebars.json
// keeps its own standalone entries (the embedding pages, the CLI tools, FAQ)
// after every category for the same reason — a category added at the end of the
// file lands in the middle of that run and quietly breaks this, which is what
// happened to AI agents.
//
// The two links that lead the whole nav (Introduction, Cookbook) are the
// deliberate exception: both are pages a reader is sent to by name, and burying
// either under a category is what putting them here undoes.
export function buildSiteSidebar(
  allDocs: DocEntry[],
  baseUrl: string,
): SidebarEntry[] {
  const docs = buildSidebar(allDocs, baseUrl)
  const lastGroup = docs.findLastIndex(entry => entry.type === 'group')
  return [
    ...docs.slice(0, lastGroup + 1),
    ...buildShowcaseGroups(baseUrl),
    ...docs.slice(lastGroup + 1),
  ]
}

// The /search page groups results into a handful of broad audience filters.
// Rather than hand-list which slugs belong to which filter (a second copy of
// the categorization in sidebars.json that silently drifts whenever a page
// moves — see e.g. the 2026-07 sidebar reorg), derive it from the same
// top-level sidebar categories every doc is already placed in.
export type SearchCategory =
  'user' | 'config' | 'developer' | 'autogen' | 'other'

const TOP_LEVEL_CATEGORY_BUCKETS: Record<string, SearchCategory> = {
  'User guide': 'user',
  Tutorials: 'user',
  Configuration: 'config',
  Development: 'developer',
  'Reference: Config schema': 'autogen',
  'Reference: State models': 'autogen',
  'Reference: Exported functions': 'autogen',
}
// "Embedding", "Command line tools" and the loose introduction/faq links are
// intentionally unmapped: they fall through to the always-shown 'other' bucket
// so no search filter can hide them.

// Pages whose search-filter bucket is deliberately not their sidebar category.
// The cookbook is a top-level sidebar link (it is the page people arrive
// looking for, not a chapter of the config guide) but its content is config, so
// the "Config guides" filter should still return it; quickstart_adminserver is
// not in the sidebar at all (check-sidebar.ts lists it as intentionally
// unlisted, reached from user_guides/basic_usage.md) and reads as an ops topic.
// Keep this list short — most classification should come from
// TOP_LEVEL_CATEGORY_BUCKETS.
const SEARCH_CATEGORY_OVERRIDES: Record<string, SearchCategory> = {
  cookbook: 'config',
  quickstart_adminserver: 'developer',
}

function entrySlugsOf(entry: SidebarEntry): string[] {
  return flattenLinks(entry).map(link => link.slug)
}

export function buildSearchCategoryMap(
  allDocs: DocEntry[],
): Record<string, SearchCategory> {
  // Walk the same resolved sidebar the pages render from: each top-level
  // category becomes a group with that category's label, and every slug beneath
  // it inherits the group's bucket. Deriving from buildSidebar (rather than a
  // second walk of the raw sidebars.json) keeps a page's search bucket in sync
  // with its actual sidebar placement.
  const map: Record<string, SearchCategory> = {}
  for (const entry of buildSidebar(allDocs, '')) {
    const bucket =
      entry.type === 'group'
        ? TOP_LEVEL_CATEGORY_BUCKETS[entry.label]
        : undefined
    if (bucket) {
      for (const slug of entrySlugsOf(entry)) {
        map[slug] = bucket
      }
    }
  }
  Object.assign(map, SEARCH_CATEGORY_OVERRIDES)
  return map
}
