// Ordered `guide_category` values for each hand-written guide directory. A page
// declares one of these in its frontmatter; that value sections it on the
// landing-page index (scripts/generate-guide-indexes.ts) and prefixes its
// sidebar label (docs-sidebar.ts), in the order listed here. Keeping the orders
// in one place stops the two groupings from drifting — a page's sidebar
// neighbors and its overview-page section are guaranteed to match.
//
// Keep these names SHORT. Since the sidebar flattened they are prefixed onto
// every page label, so "<Category>: <Title>" has to fit ~40 characters or the
// entry wraps to two lines. "Callbacks and customization" wrapped every page
// under it, which is why it is now just "Callbacks".

export const USER_CATEGORIES = [
  'General usage',
  'Track types',
  'Views',
  'Other features',
  'Tutorials',
]

export const CONFIG_CATEGORIES = [
  'Getting started',
  'Core configuration',
  'Track types',
  'Callbacks',
  'Other features',
]

export const DEVELOPER_CATEGORIES = [
  'Getting started',
  'Core concepts',
  'Pluggable elements',
  'Advanced topics',
]

// Ordered `tutorial_category` values, shared by the tutorials landing page
// (pages/docs/tutorials/index.astro) and the user guide index, so the two
// groupings of the same pages can't drift. A tutorial with no category, or one
// not listed here, falls into TUTORIAL_FALLBACK rather than vanishing.
export const TUTORIAL_CATEGORIES = [
  'Getting started',
  'Synteny & comparative genomics',
  'Structural variation',
  'Population genomics',
  'Epigenomics & single cell',
  'Transcriptomics & proteins',
  'Configuration & embedding',
]

export const TUTORIAL_FALLBACK = 'More tutorials'

// Curated order within each tutorial category, by page slug. Sorting
// alphabetically floated niche pages to the top (the CLI config walkthrough
// once led Getting started); instead each section leads with its most
// representative page. Anything unlisted falls after, alphabetically. Includes
// a few slugs that only the landing page shows (the quickstarts, the cookbook,
// the external examples card); they are inert for the user guide index.
export const TUTORIAL_ORDER = [
  'quickstart_web',
  'quickstart_desktop',
  'synteny_visualization',
  'multiway_synteny',
  'allvsall_synteny',
  'pangenome_ecoli',
  'pangenome_cactus',
  'pangenome_hprc',
  'sv_visualization_cgiab',
  'sv_multisamples',
  'population_genomics',
  'analyze_trio',
  'linkage_disequilibrium',
  'bxd_qtl',
  'methylation',
  'bisulfite',
  'chromhmm',
  'scatac_pseudobulk',
  'rnaseq',
  'protein_structure',
  'cookbook',
  'display_settings',
  'embed_linear_genome_view',
  'embedding_examples',
  'cli_desktop',
]

// Maps an autogenerated sidebar `dirName` to its category order. Only the
// hand-written guide dirs order by frontmatter `guide_category`; `config` and
// `models` order by the category in their generated `sidebar_label`, and `api`
// not at all. `tutorials` is deliberately absent: its sidebar list stays flat
// and alphabetical, with no prefix — the landing page sections the same pages,
// which is enough categorization.
export const GUIDE_CATEGORY_ORDER: Record<string, string[]> = {
  user_guides: USER_CATEGORIES,
  config_guides: CONFIG_CATEGORIES,
  developer_guides: DEVELOPER_CATEGORIES,
}
