import fs from 'fs'

import { buildEnumConstantIndex } from './enumConstants.ts'
import { formatWithOxfmt } from './format.ts'
import {
  accumulateApi,
  writeApiDocs,
  writeApiReadmes,
} from './generateApiDocs.ts'
import { writeColorDocs } from './generateColorDocs.ts'
import {
  accumulateConfig,
  writeConfigDocs,
  writePromotableSlotDocs,
} from './generateConfigDocs.ts'
import { writeDisplayFoundationDocs } from './generateDisplayFoundationDocs.ts'
import { writeExtensionPointDocs } from './generateExtensionPointDocs.ts'
import {
  writeDisplayTypeDocs,
  writeFileTypeDocs,
  writeGotchaDocs,
} from './generateFileTypeDocs.ts'
import { writeJexlDocs } from './generateJexlDocs.ts'
import { accumulateModel, writeModelDocs } from './generateStateModelDocs.ts'
import { createDocProgram, extractWithComment, getAllFiles } from './util.ts'

import type { ApiGroup } from './generateApiDocs.ts'
import type { Config } from './generateConfigDocs.ts'
import type { StateModel } from './generateStateModelDocs.ts'
import type { DisplayTrackLink } from './util.ts'

// Build the TypeScript program over the whole repo ONCE and route each tagged
// node into the config, state-model, and API accumulators. Previously the
// generators ran as separate processes, each paying that whole-repo program load
// (the dominant cost); doing it once amortizes it across all of them.
// The pages that document a type but never show one being used. Committed as a
// list rather than left to the `console.warn` the generators already emit: that
// warning fails nothing and scrolls past in a CI log, which is how 40 config
// pages and 90 model pages came to be bare. As a tracked file it lands in the
// PR diff, so adding a bare type is a reviewable `+` line attributable to the
// change that caused it, and filling one in is a `-` line. The existing
// "config/model/api docs are up to date" step gates it — `pnpm gendocs`
// rewrites this file and CI fails on any diff (see push.yml).
//
// Same mechanism, and same reasoning, as scripts/spec-recipe-unmapped.txt.
function writeExampleGaps(configs: string[], models: string[]) {
  const file = `${import.meta.dirname}/example-gaps.txt`
  const body = (kind: string, names: string[]) =>
    `# ${kind} (${names.length})\n${[...names].sort().join('\n')}\n`
  fs.writeFileSync(
    file,
    `# AUTO-GENERATED by website/scripts/api-docs/generate.ts — do not edit by hand.
# Documented types with no #example, so their page shows a slot table and never
# a config a reader can paste. Regenerate with \`pnpm autogen\`.
#
# Adding a name here is a coverage regression; removing one is the win. Tag an
# #example on the type's #config/#stateModel JSDoc to clear it. Base/shared
# schemas are absent by design — they are never named in a config, so they route
# to their concrete types via "Extended by" instead of carrying an example.
${body('configs', configs)}${body('models', models)}`,
  )
  console.log(`wrote ${file}`)
}

async function main() {
  const configs: Record<string, Config> = {}
  const models: Record<string, StateModel> = {}
  const api: Record<string, ApiGroup> = {}
  const displayLinks: DisplayTrackLink[] = []
  const files = await getAllFiles()
  const docProgram = createDocProgram(files)
  // enum tables first: the config generator resolves `[...NAME]` spreads in
  // stringEnum models against this while rendering slots
  buildEnumConstantIndex(docProgram.sources)
  extractWithComment(
    docProgram,
    obj => {
      accumulateConfig(configs, obj)
      accumulateModel(models, obj)
      accumulateApi(api, obj)
    },
    link => displayLinks.push(link),
  )

  // Reverse index: a Track config's "Display types" section looks up displays
  // by the track's own name, the only end of this link a Track's source code
  // doesn't itself carry. displayToTrackType is the forward direction, so a
  // display page can find the adapters that feed its track type.
  const displayTypesByTrack = new Map<string, string[]>()
  const displayToTrackType = new Map<string, string>()
  for (const { displayName, trackType } of displayLinks) {
    const displayNames = displayTypesByTrack.get(trackType)
    if (displayNames) {
      // extractWithComment can emit the same link twice (the VariableStatement
      // and its inner declaration), so guard against a duplicate display bullet
      if (!displayNames.includes(displayName)) {
        displayNames.push(displayName)
      }
    } else {
      displayTypesByTrack.set(trackType, [displayName])
    }
    displayToTrackType.set(displayName, trackType)
  }
  const modelNames = new Set(
    Object.values(models)
      .map(m => m.header?.name)
      .filter((name): name is string => Boolean(name)),
  )
  const configNames = new Set(
    Object.values(configs)
      .map(c => c.header?.name)
      .filter((name): name is string => Boolean(name)),
  )

  const configsWithNoExample = writeConfigDocs(
    configs,
    displayTypesByTrack,
    displayToTrackType,
    modelNames,
  )
  writePromotableSlotDocs(configs, displayToTrackType)
  const modelsWithNoExample = writeModelDocs(models, configNames)
  writeExampleGaps(configsWithNoExample, modelsWithNoExample)
  writeApiDocs(api)
  const readmes = writeApiReadmes(api)
  writeColorDocs()
  writeJexlDocs()
  writeExtensionPointDocs()
  writeDisplayFoundationDocs()
  writeFileTypeDocs(files)
  writeDisplayTypeDocs(displayTypesByTrack, configNames)
  writeGotchaDocs(
    new Map(
      Object.values(configs)
        .filter(c => c.header?.gotchas.length)
        .map(c => [c.header!.name, c.header!.gotchas]),
    ),
  )

  await formatWithOxfmt([...FORMAT_DIRS, ...readmes])
}

// Directories this script is responsible for leaving format-clean: the
// generated pages, plus the hand-written guides whose marker blocks were
// rewritten above (FILE_TYPES, DISPLAY_TYPES, GOTCHA, COLOR_TABLE,
// EXTENSION_POINTS_INDEX, DISPLAY_FOUNDATIONS, PROMOTABLE_SLOTS). The tables
// carry `prettier-ignore` and are left compact, but the gotcha callouts are
// prose and must be rewrapped or every regen would fight `pnpm format`.
const FORMAT_DIRS = [
  'website/docs/config',
  'website/docs/models',
  'website/docs/api',
  'website/docs/config_guides',
  'website/docs/developer_guides',
  'website/docs/user_guides',
]

// eslint-disable-next-line @typescript-eslint/no-floating-promises
main()
