import fs from 'fs'

import { buildEnumConstantIndex } from './enumConstants.ts'
import { formatWithOxfmt, writtenDocs } from './format.ts'
import {
  accumulateApi,
  writeApiDocs,
  writeApiReadmes,
} from './generateApiDocs.ts'
import {
  accumulateConfig,
  writeConfigDocs,
  writePromotableSlotDocs,
} from './generateConfigDocs.ts'
import {
  assertEveryDisplayDeclaresAViewType,
  writeDisplayTypeDocs,
  writeDisplayViewTypeDocs,
  writeGotchaDocs,
} from './generateFileTypeDocs.ts'
import { writeSpecKeyDocs } from './generateSpecKeyDocs.ts'
import { accumulateModel, writeModelDocs } from './generateStateModelDocs.ts'
import { MARKER_GENERATORS } from './markerGenerators.ts'
import {
  assertEveryDisplayTypeIsDocumented,
  assertMarkersAndDocsAgree,
  createDocProgram,
  extractWithComment,
  getAllFiles,
  sourceCorpus,
} from './util.ts'

import type { ApiGroup } from './generateApiDocs.ts'
import type { Config } from './generateConfigDocs.ts'
import type { StateModel } from './generateStateModelDocs.ts'
import type { DisplayTrackLink } from './util.ts'

// Build the TypeScript program over the whole repo ONCE and route each tagged
// node into the config, state-model, and API accumulators. Previously the
// generators ran as separate processes, each paying that whole-repo program load
// (the dominant cost); doing it once amortizes it across all of them.

// Everywhere a generated page is thinner than it should be because the source
// doesn't say enough. Committed as a list rather than left to a `console.warn`:
// that warning fails nothing and scrolls past in a CI log, which is how 40
// config pages and 90 model pages came to be bare, and how 101 slots came to
// render a name and a type over an empty Description cell. As a tracked file
// each gap lands in the PR diff, so adding one is a reviewable `+` line
// attributable to the change that caused it, and filling one in is a `-` line.
// The existing "config/model/api docs are up to date" step gates it — `pnpm
// gendocs` rewrites this file and CI fails on any diff (see push.yml).
//
// Same mechanism, and same reasoning, as scripts/spec-recipe-unmapped.txt.
//
// Sections stay in the file at zero rather than disappearing: an empty section
// says the check ran and found nothing, so a regression is a `+` line under a
// heading that was already there rather than a new heading nobody notices.
interface GapSection {
  title: string
  // what to tag to clear an entry, shown above the names
  fix: string
  names: string[]
}

function writeCoverageGaps(sections: GapSection[]) {
  const file = `${import.meta.dirname}/coverage-gaps.txt`
  fs.writeFileSync(
    file,
    `# AUTO-GENERATED by website/scripts/api-docs/generate.ts — do not edit by hand.
# Documented surface the generators render incompletely because the source
# doesn't carry the text. Regenerate with \`pnpm autogen\`.
#
# Adding a name here is a coverage regression; removing one is the win. Each
# section names the tag that clears it.
${sections
  .map(
    ({ title, fix, names }) =>
      `\n# ${title} (${names.length})\n# fix: ${fix}\n${[...names].sort().join('\n')}${names.length ? '\n' : ''}`,
  )
  .join('')}`,
  )
  console.log(`wrote ${file}`)
}

async function main() {
  const configs: Record<string, Config> = {}
  const models: Record<string, StateModel> = {}
  const api: Record<string, ApiGroup> = {}
  const displayLinks: DisplayTrackLink[] = []
  const files = await getAllFiles()
  const docProgram = createDocProgram(files)
  // enum tables first: the config generator resolves `[...NAME]` spreads in
  // stringEnum models against this while rendering slots
  buildEnumConstantIndex(docProgram.sources)
  const { blindSpots, orphanMembers } = extractWithComment(
    docProgram,
    obj => {
      accumulateConfig(configs, obj)
      accumulateModel(models, obj)
      accumulateApi(api, obj)
    },
    link => displayLinks.push(link),
  )

  // Reverse index: a Track config's "Display types" section looks up displays
  // by the track's own name, the only end of this link a Track's source code
  // doesn't itself carry. displayToTrackType is the forward direction, so a
  // display page can find the adapters that feed its track type.
  const displayTypesByTrack = new Map<string, string[]>()
  const displayToTrackType = new Map<string, string>()
  for (const { displayName, trackType } of displayLinks) {
    const displayNames = displayTypesByTrack.get(trackType)
    if (displayNames) {
      // extractWithComment can emit the same link twice (the VariableStatement
      // and its inner declaration), so guard against a duplicate display bullet
      if (!displayNames.includes(displayName)) {
        displayNames.push(displayName)
      }
    } else {
      displayTypesByTrack.set(trackType, [displayName])
    }
    displayToTrackType.set(displayName, trackType)
  }
  // Push order is extractor traversal order, which moves with the composition
  // of the TS program — and `getAllFiles` includes untracked files, so one
  // scratch `.ts` reorders these bullets across 19 pages. Sort, so the artifact
  // is a function of the sources.
  for (const displayNames of displayTypesByTrack.values()) {
    displayNames.sort()
  }
  const modelNames = new Set(
    Object.values(models)
      .map(m => m.header?.name)
      .filter((name): name is string => Boolean(name)),
  )
  const configNames = new Set(
    Object.values(configs)
      .map(c => c.header?.name)
      .filter((name): name is string => Boolean(name)),
  )

  // Before any page is written, so a run that would silently drop a display
  // from every table fails without having rewritten the pages first — same
  // placement, and same argument, as `assertNoBlankSlotDescriptions`.
  assertEveryDisplayTypeIsDocumented(displayToTrackType, configNames)
  assertEveryDisplayDeclaresAViewType(displayLinks)

  const configGaps = writeConfigDocs(
    configs,
    displayTypesByTrack,
    displayToTrackType,
    modelNames,
  )
  writePromotableSlotDocs(configs, displayToTrackType)
  const modelGaps = writeModelDocs(models, configNames)
  // Not in MARKER_GENERATORS: this one needs `models` off the program, since
  // half of what a spec can set on a view is the model's composed-in
  // properties. After writeModelDocs, so the pages its rows link into exist by
  // the time anything checks them.
  writeSpecKeyDocs(models, sourceCorpus(files))
  writeCoverageGaps([
    {
      title: 'configs with no #example',
      // Base/shared schemas are absent by design — they are never named in a
      // config, so they route to their concrete types via "Extended by" instead
      // of carrying an example of their own.
      fix: 'add an #example to the type’s #config JSDoc',
      names: configGaps.noExample,
    },
    {
      title: 'display/view models with no #example',
      // Only displays and views: a model page's example is a config/session
      // snapshot, and no snapshot names a mixin, session, root or widget. See
      // wantsExample in generateStateModelDocs.
      fix: 'add an #example to the type’s #stateModel JSDoc',
      names: modelGaps.noExample,
    },
    {
      title: 'configs that fell back to the General category',
      fix: 'add #category to the #config JSDoc',
      names: configGaps.general,
    },
    {
      title: 'models that fell back to the General category',
      fix: 'add #category to the #stateModel JSDoc',
      names: modelGaps.general,
    },
    {
      title: 'members the structural pass cannot see',
      fix: 'add #getter/#method/#action to the local declaration the shorthand returns',
      names: blindSpots,
    },
    {
      title: 'member tags in a file that documents no #stateModel',
      // The counterpart of the delegated-block follow: a member tag is only
      // rendered by the page its file's #stateModel header owns, so a tagged
      // member in a file with no header renders nowhere and says nothing. A
      // block a model reaches through `.views(sharedViews)` is claimed by that
      // model and does not appear here.
      fix: 'give the file a #stateModel, reach the block from one via .views(name), or drop the tags',
      names: orphanMembers,
    },
    {
      title:
        'baseConfiguration references that resolved to no documented #config',
      fix: 'document the base with #config, or accept that the page shows raw code',
      names: configGaps.unresolvedBase,
    },
    {
      title: 'adapters whose #example defaulted to FeatureTrack',
      fix: 'add #trackType to the adapter’s #config JSDoc',
      names: configGaps.adapterNoTrackType,
    },
    {
      title: '#stateModel tags attached to a declaration that builds no model',
      fix: 'move the #stateModel JSDoc back onto its factory — a declaration in between takes the tag, and every inherited member row silently disappears',
      names: modelGaps.misattached,
    },
  ])
  writeApiDocs(api)
  writeApiReadmes(api)
  // The program-independent marker tables, from the one list markers.ts also
  // runs — so the set can't drift between a full run and the `--check` gate.
  const corpus = sourceCorpus(files)
  for (const { write } of MARKER_GENERATORS) {
    write(corpus, { check: false })
  }
  writeDisplayTypeDocs(displayTypesByTrack, configNames)
  writeDisplayViewTypeDocs(displayLinks, configNames)
  writeGotchaDocs(
    new Map(
      Object.values(configs)
        .filter(c => c.header?.gotchas.length)
        .map(c => [c.header!.name, c.header!.gotchas]),
    ),
  )
  pruneUnwritten()

  // Exactly the files written above, not a list of directories to keep in sync
  // with them: the generated pages, the package READMEs, and whichever
  // hand-written guides a marker block landed in (FILE_TYPES, DISPLAY_TYPES,
  // GOTCHA, COLOR_TABLE, EXTENSION_POINTS_INDEX, DISPLAY_FOUNDATIONS,
  // PROMOTABLE_SLOTS). The tables carry `prettier-ignore` and stay compact, but
  // the gotcha callouts are prose and must be rewrapped or every regen would
  // fight `pnpm format` — which is what a guide outside the old six directories
  // would silently have done.
  await formatWithOxfmt(writtenDocs())

  // After the formatter, not before it: this fails on marker bookkeeping rather
  // than on a page's content, and everything above it is already written. A
  // throw in between leaves those writes on disk unformatted, and the next run
  // does not repair them — it regenerates the same bytes, sees the file already
  // holds them, and so never writes (and never formats) it again.
  assertMarkersAndDocsAgree()
}

// The three directories this script owns outright — every `.md` in them is
// written by a run, so anything left over documents a type that no longer
// exists.
const GENERATED_DIRS = [
  'website/docs/config',
  'website/docs/models',
  'website/docs/api',
]

// Delete pages this run didn't write. `pnpm gendocs` used to `rm -rf` these
// directories before generating, which left them missing for the whole ~15s a
// run takes — long enough for a dev server or a second agent in the same
// worktree to read a half-built tree, and long enough to lose all three if the
// run then threw. Pruning after the write is the same guarantee with no window:
// a page only disappears once the set that replaces it is already on disk.
function pruneUnwritten() {
  const written = new Set(writtenDocs())
  for (const dir of GENERATED_DIRS) {
    for (const name of fs.readdirSync(dir)) {
      const file = `${dir}/${name}`
      if (name.endsWith('.md') && !written.has(file)) {
        fs.rmSync(file)
        console.log(`pruned ${file}`)
      }
    }
  }
}

// eslint-disable-next-line @typescript-eslint/no-floating-promises
main()
