export const fillColor = {
  color_fwd_strand_not_proper: '#ECC8C8',
  color_rev_strand_not_proper: '#BEBED8',
  color_fwd_strand: '#EC8B8B',
  color_rev_strand: '#8F8FD8',
  color_fwd_missing_mate: '#D11919',
  color_rev_missing_mate: '#1919D1',
  color_fwd_diff_chr: '#000',
  color_rev_diff_chr: '#969696',
  color_pair_lr: 'lightgrey',
  color_pair_rr: '#3a3a9d',
  color_pair_rl: 'teal',
  color_pair_ll: 'green',
  color_nostrand: '#c8c8c8',
  color_interchrom: 'purple',
  color_longinsert: 'red',
  color_shortinsert: 'pink',
  color_unmapped_mate: '#8B4513',
  color_unknown: 'grey',
  // Long-read split alignment orientation colors
  color_longread_rev_fwd: 'navy',
  color_longread_fwd_rev: 'green',
  color_longread_same: 'grey',
  // Supplementary/split alignment color (light orange)
  color_supplementary: '#f0b878',
}
