// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from ldUniforms.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

// Scalar twins of ldUniforms.slang, transliterated from slangc's WGSL so
// the Canvas2D and SVG paths run the shader's own math. See adr-051.

function _clamp(x: number, lo: number, hi: number) {
  return Math.min(Math.max(x, lo), hi)
}

export function dprimeFinalize(D: number, pA: number, pB: number, signedLD: boolean): number {
  let qA = (1.0 - pA)
  let qB = (1.0 - pB)
  if ((D > 0.0)) {
    let _t0 = Math.min((pA * qB), (qA * pB))
    if ((_t0 > 0.0)) {
      return Math.min(1.0, (D / _t0))
    }
  } else {
    if ((D < 0.0)) {
      let _t1 = Math.min((pA * pB), (qA * qB))
      if ((_t1 > 0.0)) {
        let _t2: number
        if (signedLD) {
          _t2 = Math.max(-1.0, (D / _t1))
        } else {
          _t2 = Math.min(1.0, (Math.abs(D) / _t1))
        }
        return _t2
      }
    }
  }
  return 0.0
}

export function ldRSquared(r: number): number {
  return _clamp((r * r), 0.0, 1.0)
}

function ldGenotypeCovariance(s1: number, s2: number, sprod: number, count: number): number {
  return ((sprod / count) - ((s1 / count) * (s2 / count)))
}

export function ldGenotypeD(s1: number, s2: number, sprod: number, count: number): number {
  return (ldGenotypeCovariance(s1, s2, sprod, count) * 0.5)
}

export function ldGenotypeCorrelation(s1: number, s2: number, s1sq: number, s2sq: number, sprod: number, count: number): number {
  let mean1 = (s1 / count)
  let mean2 = (s2 / count)
  let var1 = ((s1sq / count) - (mean1 * mean1))
  let var2 = ((s2sq / count) - (mean2 * mean2))
  let _t0: boolean
  if ((var1 > 0.0)) {
    _t0 = (var2 > 0.0)
  } else {
    _t0 = false
  }
  if (_t0) {
    return (ldGenotypeCovariance(s1, s2, sprod, count) / Math.sqrt((var1 * var2)))
  }
  return 0.0
}

export function ldHaplotypeCorrelation(D: number, pA: number, pB: number): number {
  let denom = (((pA * (1.0 - pA)) * pB) * (1.0 - pB))
  let _t0: number
  if ((denom > 0.0)) {
    _t0 = (D / Math.sqrt(denom))
  } else {
    _t0 = 0.0
  }
  return _t0
}
