// AUTO-GENERATED by scripts/shader-codegen from manhattan.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { GlAttributeLayout } from '@jbrowse/render-core/hal'

export const VERTS_PER_INSTANCE = 6

export const UNIFORMS_SIZE_BYTES = 48

// Indices into a Float32Array / Uint32Array view over the uniform buffer.
export const UNIFORM_OFFSET_F32 = {
  bpRangeX: 0,
  canvasHeight: 3,
  domainYMin: 4,
  domainYMax: 5,
  zero: 6,
  viewportWidth: 7,
  pointRadius: 8,
} as const


export interface Uniforms {
  bpRangeX: [number, number, number]
  canvasHeight: number
  domainYMin: number
  domainYMax: number
  zero: number
  viewportWidth: number
  pointRadius: number
}

export function writeUniforms(buf: ArrayBuffer, uniforms: Uniforms) {
  const f32 = new Float32Array(buf)
  f32[0] = uniforms.bpRangeX[0]
  f32[1] = uniforms.bpRangeX[1]
  f32[2] = uniforms.bpRangeX[2]
  f32[3] = uniforms.canvasHeight
  f32[4] = uniforms.domainYMin
  f32[5] = uniforms.domainYMax
  f32[6] = uniforms.zero
  f32[7] = uniforms.viewportWidth
  f32[8] = uniforms.pointRadius
}

export const INSTANCE_STRIDE_BYTES = 20
export const INSTANCE_STRIDE_F32 = 5

export const FIELD_OFFSET_F32 = {
  absPosition: 0,
  absEnd: 1,
  score: 2,
  color: 3,
  glyph: 4,
} as const

export const GL_ATTRIBUTES: readonly GlAttributeLayout[] = [
  { name: 'a_absPosition', components: 1, type: 'uint', offsetBytes: 0, integer: true },
  { name: 'a_absEnd', components: 1, type: 'uint', offsetBytes: 4, integer: true },
  { name: 'a_score', components: 1, type: 'float', offsetBytes: 8, integer: false },
  { name: 'a_color', components: 1, type: 'uint', offsetBytes: 12, integer: true },
  { name: 'a_glyph', components: 1, type: 'uint', offsetBytes: 16, integer: true },
]

export interface InstanceArrays {
  absPosition: ArrayLike<number>
  absEnd: ArrayLike<number>
  score: ArrayLike<number>
  color: ArrayLike<number>
  glyph: ArrayLike<number>
}

export function packInstances(
  arrays: InstanceArrays,
  numInstances: number,
  buf: ArrayBuffer = new ArrayBuffer(numInstances * INSTANCE_STRIDE_BYTES),
) {
  const f32 = new Float32Array(buf)
  const u32 = new Uint32Array(buf)
  const { absPosition, absEnd, score, color, glyph } = arrays
  for (let i = 0; i < numInstances; i++) {
    const o = i * INSTANCE_STRIDE_F32
    u32[o + 0] = absPosition[i]!
    u32[o + 1] = absEnd[i]!
    f32[o + 2] = score[i]!
    u32[o + 3] = color[i]!
    u32[o + 4] = glyph[i]!
  }
  return buf
}
