// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from arc.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

// Scalar twins of arc.slang, transliterated from slangc's WGSL so
// the Canvas2D and SVG paths run the shader's own math. See adr-051.

function arcIsFar(halfWidthPx: number, viewWidthPx: number): boolean {
  return ((2.0 * halfWidthPx) > (3.0 * viewWidthPx))
}

export function arcRadiiPx(halfWidthPx: number, destYPx: number, viewWidthPx: number): [number, number] {
  if (arcIsFar(halfWidthPx, viewWidthPx)) {
    return [halfWidthPx, halfWidthPx]
  }
  return [halfWidthPx, (0.75 * destYPx)]
}
