// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from arcFlat.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

// Scalar twins of arcFlat.slang, transliterated from slangc's WGSL so
// the Canvas2D and SVG paths run the shader's own math. See adr-051.

function _mix(a: number, b: number, t: number) {
  return a * (1 - t) + b * t
}

export function arcDashCoordPx(localX: number, halfLenPx: number, reversed: number): number {
  return (halfLenPx + _mix(localX, -localX, reversed))
}
