// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from arcMarker.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { VertexAttributeLayout, ShaderBinding } from '@jbrowse/render-core/hal'

export const BINDINGS: readonly ShaderBinding[] = [
  { index: 1, kind: 'uniform', name: 'u' },
]

export const VERTS_PER_INSTANCE = 6

export const UNIFORMS_SIZE_BYTES = 800

// Word indices into a Float32Array view over the uniform buffer.
export const UNIFORM_OFFSET_F32 = {
  bpHi: 0,
  bpLo: 1,
  bpLen: 2,
  hpZero: 3,
  canvasW: 4,
  canvasH: 5,
  rangeY0: 6,
  covOffset: 7,
  featHeight: 8,
  featSpacing: 9,
  blockStartPx: 10,
  blockWidth: 11,
  lineWidthPx: 12,
  pairedArcsDown: 13,
  arcsYDomainBp: 14,
  arcsYLog: 15,
  reversed: 21,
  pxPerBp: 196,
  arcBandH: 197,
  dpr: 198,
} as const

// Word indices into a Uint32Array view over the uniform buffer.
export const UNIFORM_OFFSET_U32 = {
  colorBaseA: 22,
  colorBaseC: 23,
  colorBaseG: 24,
  colorBaseT: 25,
  colorBaseN: 26,
  colorInsertion: 27,
  colorDeletion: 28,
  colorSkip: 29,
  colorSoftclip: 30,
  colorHardclip: 31,
  colorFlatConnector: 32,
  colorConnectingLine: 33,
  colorOverlapTint: 34,
  colorOverlap: 35,
} as const

// Word indices into a Int32Array view over the uniform buffer.
export const UNIFORM_OFFSET_I32 = {
  colorScheme: 16,
  chainMode: 17,
  showStroke: 18,
  filterMismatchesByFrequency: 19,
  mismatchAlpha: 20,
} as const


// Word indices of each array field’s elements, into a 4-byte-word
// view over the uniform buffer (Uint32Array or Float32Array — the
// field’s scalar type picks, same as UNIFORM_OFFSET_*). NOT
// consecutive: std140 pads every array element to 16 bytes.
export const UNIFORM_SLOT_ARRAYS = {
  arcColor: [36, 40, 44, 48, 52, 56, 60, 64, 68] as const,
  linkedReadColor: [72, 76, 80, 84, 88, 92, 96, 100] as const,
  readCategoryColor: [104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192] as const,
} as const

// Element `i` of the `arcColor` uniform array (4 components).
export function setUniformArcColor(
  f32: Float32Array,
  i: number,
  v0: number,
  v1: number,
  v2: number,
  v3: number,
) {
  const o = UNIFORM_SLOT_ARRAYS.arcColor[i]!
  f32[o] = v0
  f32[o + 1] = v1
  f32[o + 2] = v2
  f32[o + 3] = v3
}

// Element `i` of the `linkedReadColor` uniform array (4 components).
export function setUniformLinkedReadColor(
  f32: Float32Array,
  i: number,
  v0: number,
  v1: number,
  v2: number,
  v3: number,
) {
  const o = UNIFORM_SLOT_ARRAYS.linkedReadColor[i]!
  f32[o] = v0
  f32[o + 1] = v1
  f32[o + 2] = v2
  f32[o + 3] = v3
}

// Element `i` of the `readCategoryColor` uniform array (4 components).
export function setUniformReadCategoryColor(
  f32: Float32Array,
  i: number,
  v0: number,
  v1: number,
  v2: number,
  v3: number,
) {
  const o = UNIFORM_SLOT_ARRAYS.readCategoryColor[i]!
  f32[o] = v0
  f32[o + 1] = v1
  f32[o + 2] = v2
  f32[o + 3] = v3
}


export interface Uniforms {
  bpHi: number
  bpLo: number
  bpLen: number
  hpZero: number
  canvasW: number
  canvasH: number
  rangeY0: number
  covOffset: number
  featHeight: number
  featSpacing: number
  blockStartPx: number
  blockWidth: number
  lineWidthPx: number
  pairedArcsDown: number
  arcsYDomainBp: number
  arcsYLog: number
  colorScheme: number
  chainMode: number
  showStroke: number
  filterMismatchesByFrequency: number
  mismatchAlpha: number
  reversed: number
  colorBaseA: number
  colorBaseC: number
  colorBaseG: number
  colorBaseT: number
  colorBaseN: number
  colorInsertion: number
  colorDeletion: number
  colorSkip: number
  colorSoftclip: number
  colorHardclip: number
  colorFlatConnector: number
  colorConnectingLine: number
  colorOverlapTint: number
  colorOverlap: number
  arcColor: [[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]]
  linkedReadColor: [[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]]
  readCategoryColor: [[number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number], [number, number, number, number]]
  pxPerBp: number
  arcBandH: number
  dpr: number
}

export function writeUniforms(buf: ArrayBuffer, uniforms: Uniforms) {
  const f32 = new Float32Array(buf)
  const u32 = new Uint32Array(buf)
  const i32 = new Int32Array(buf)
  f32[0] = uniforms.bpHi
  f32[1] = uniforms.bpLo
  f32[2] = uniforms.bpLen
  f32[3] = uniforms.hpZero
  f32[4] = uniforms.canvasW
  f32[5] = uniforms.canvasH
  f32[6] = uniforms.rangeY0
  f32[7] = uniforms.covOffset
  f32[8] = uniforms.featHeight
  f32[9] = uniforms.featSpacing
  f32[10] = uniforms.blockStartPx
  f32[11] = uniforms.blockWidth
  f32[12] = uniforms.lineWidthPx
  f32[13] = uniforms.pairedArcsDown
  f32[14] = uniforms.arcsYDomainBp
  f32[15] = uniforms.arcsYLog
  i32[16] = uniforms.colorScheme
  i32[17] = uniforms.chainMode
  i32[18] = uniforms.showStroke
  i32[19] = uniforms.filterMismatchesByFrequency
  i32[20] = uniforms.mismatchAlpha
  f32[21] = uniforms.reversed
  u32[22] = uniforms.colorBaseA
  u32[23] = uniforms.colorBaseC
  u32[24] = uniforms.colorBaseG
  u32[25] = uniforms.colorBaseT
  u32[26] = uniforms.colorBaseN
  u32[27] = uniforms.colorInsertion
  u32[28] = uniforms.colorDeletion
  u32[29] = uniforms.colorSkip
  u32[30] = uniforms.colorSoftclip
  u32[31] = uniforms.colorHardclip
  u32[32] = uniforms.colorFlatConnector
  u32[33] = uniforms.colorConnectingLine
  u32[34] = uniforms.colorOverlapTint
  u32[35] = uniforms.colorOverlap
  f32[36] = uniforms.arcColor[0][0]
  f32[37] = uniforms.arcColor[0][1]
  f32[38] = uniforms.arcColor[0][2]
  f32[39] = uniforms.arcColor[0][3]
  f32[40] = uniforms.arcColor[1][0]
  f32[41] = uniforms.arcColor[1][1]
  f32[42] = uniforms.arcColor[1][2]
  f32[43] = uniforms.arcColor[1][3]
  f32[44] = uniforms.arcColor[2][0]
  f32[45] = uniforms.arcColor[2][1]
  f32[46] = uniforms.arcColor[2][2]
  f32[47] = uniforms.arcColor[2][3]
  f32[48] = uniforms.arcColor[3][0]
  f32[49] = uniforms.arcColor[3][1]
  f32[50] = uniforms.arcColor[3][2]
  f32[51] = uniforms.arcColor[3][3]
  f32[52] = uniforms.arcColor[4][0]
  f32[53] = uniforms.arcColor[4][1]
  f32[54] = uniforms.arcColor[4][2]
  f32[55] = uniforms.arcColor[4][3]
  f32[56] = uniforms.arcColor[5][0]
  f32[57] = uniforms.arcColor[5][1]
  f32[58] = uniforms.arcColor[5][2]
  f32[59] = uniforms.arcColor[5][3]
  f32[60] = uniforms.arcColor[6][0]
  f32[61] = uniforms.arcColor[6][1]
  f32[62] = uniforms.arcColor[6][2]
  f32[63] = uniforms.arcColor[6][3]
  f32[64] = uniforms.arcColor[7][0]
  f32[65] = uniforms.arcColor[7][1]
  f32[66] = uniforms.arcColor[7][2]
  f32[67] = uniforms.arcColor[7][3]
  f32[68] = uniforms.arcColor[8][0]
  f32[69] = uniforms.arcColor[8][1]
  f32[70] = uniforms.arcColor[8][2]
  f32[71] = uniforms.arcColor[8][3]
  f32[72] = uniforms.linkedReadColor[0][0]
  f32[73] = uniforms.linkedReadColor[0][1]
  f32[74] = uniforms.linkedReadColor[0][2]
  f32[75] = uniforms.linkedReadColor[0][3]
  f32[76] = uniforms.linkedReadColor[1][0]
  f32[77] = uniforms.linkedReadColor[1][1]
  f32[78] = uniforms.linkedReadColor[1][2]
  f32[79] = uniforms.linkedReadColor[1][3]
  f32[80] = uniforms.linkedReadColor[2][0]
  f32[81] = uniforms.linkedReadColor[2][1]
  f32[82] = uniforms.linkedReadColor[2][2]
  f32[83] = uniforms.linkedReadColor[2][3]
  f32[84] = uniforms.linkedReadColor[3][0]
  f32[85] = uniforms.linkedReadColor[3][1]
  f32[86] = uniforms.linkedReadColor[3][2]
  f32[87] = uniforms.linkedReadColor[3][3]
  f32[88] = uniforms.linkedReadColor[4][0]
  f32[89] = uniforms.linkedReadColor[4][1]
  f32[90] = uniforms.linkedReadColor[4][2]
  f32[91] = uniforms.linkedReadColor[4][3]
  f32[92] = uniforms.linkedReadColor[5][0]
  f32[93] = uniforms.linkedReadColor[5][1]
  f32[94] = uniforms.linkedReadColor[5][2]
  f32[95] = uniforms.linkedReadColor[5][3]
  f32[96] = uniforms.linkedReadColor[6][0]
  f32[97] = uniforms.linkedReadColor[6][1]
  f32[98] = uniforms.linkedReadColor[6][2]
  f32[99] = uniforms.linkedReadColor[6][3]
  f32[100] = uniforms.linkedReadColor[7][0]
  f32[101] = uniforms.linkedReadColor[7][1]
  f32[102] = uniforms.linkedReadColor[7][2]
  f32[103] = uniforms.linkedReadColor[7][3]
  f32[104] = uniforms.readCategoryColor[0][0]
  f32[105] = uniforms.readCategoryColor[0][1]
  f32[106] = uniforms.readCategoryColor[0][2]
  f32[107] = uniforms.readCategoryColor[0][3]
  f32[108] = uniforms.readCategoryColor[1][0]
  f32[109] = uniforms.readCategoryColor[1][1]
  f32[110] = uniforms.readCategoryColor[1][2]
  f32[111] = uniforms.readCategoryColor[1][3]
  f32[112] = uniforms.readCategoryColor[2][0]
  f32[113] = uniforms.readCategoryColor[2][1]
  f32[114] = uniforms.readCategoryColor[2][2]
  f32[115] = uniforms.readCategoryColor[2][3]
  f32[116] = uniforms.readCategoryColor[3][0]
  f32[117] = uniforms.readCategoryColor[3][1]
  f32[118] = uniforms.readCategoryColor[3][2]
  f32[119] = uniforms.readCategoryColor[3][3]
  f32[120] = uniforms.readCategoryColor[4][0]
  f32[121] = uniforms.readCategoryColor[4][1]
  f32[122] = uniforms.readCategoryColor[4][2]
  f32[123] = uniforms.readCategoryColor[4][3]
  f32[124] = uniforms.readCategoryColor[5][0]
  f32[125] = uniforms.readCategoryColor[5][1]
  f32[126] = uniforms.readCategoryColor[5][2]
  f32[127] = uniforms.readCategoryColor[5][3]
  f32[128] = uniforms.readCategoryColor[6][0]
  f32[129] = uniforms.readCategoryColor[6][1]
  f32[130] = uniforms.readCategoryColor[6][2]
  f32[131] = uniforms.readCategoryColor[6][3]
  f32[132] = uniforms.readCategoryColor[7][0]
  f32[133] = uniforms.readCategoryColor[7][1]
  f32[134] = uniforms.readCategoryColor[7][2]
  f32[135] = uniforms.readCategoryColor[7][3]
  f32[136] = uniforms.readCategoryColor[8][0]
  f32[137] = uniforms.readCategoryColor[8][1]
  f32[138] = uniforms.readCategoryColor[8][2]
  f32[139] = uniforms.readCategoryColor[8][3]
  f32[140] = uniforms.readCategoryColor[9][0]
  f32[141] = uniforms.readCategoryColor[9][1]
  f32[142] = uniforms.readCategoryColor[9][2]
  f32[143] = uniforms.readCategoryColor[9][3]
  f32[144] = uniforms.readCategoryColor[10][0]
  f32[145] = uniforms.readCategoryColor[10][1]
  f32[146] = uniforms.readCategoryColor[10][2]
  f32[147] = uniforms.readCategoryColor[10][3]
  f32[148] = uniforms.readCategoryColor[11][0]
  f32[149] = uniforms.readCategoryColor[11][1]
  f32[150] = uniforms.readCategoryColor[11][2]
  f32[151] = uniforms.readCategoryColor[11][3]
  f32[152] = uniforms.readCategoryColor[12][0]
  f32[153] = uniforms.readCategoryColor[12][1]
  f32[154] = uniforms.readCategoryColor[12][2]
  f32[155] = uniforms.readCategoryColor[12][3]
  f32[156] = uniforms.readCategoryColor[13][0]
  f32[157] = uniforms.readCategoryColor[13][1]
  f32[158] = uniforms.readCategoryColor[13][2]
  f32[159] = uniforms.readCategoryColor[13][3]
  f32[160] = uniforms.readCategoryColor[14][0]
  f32[161] = uniforms.readCategoryColor[14][1]
  f32[162] = uniforms.readCategoryColor[14][2]
  f32[163] = uniforms.readCategoryColor[14][3]
  f32[164] = uniforms.readCategoryColor[15][0]
  f32[165] = uniforms.readCategoryColor[15][1]
  f32[166] = uniforms.readCategoryColor[15][2]
  f32[167] = uniforms.readCategoryColor[15][3]
  f32[168] = uniforms.readCategoryColor[16][0]
  f32[169] = uniforms.readCategoryColor[16][1]
  f32[170] = uniforms.readCategoryColor[16][2]
  f32[171] = uniforms.readCategoryColor[16][3]
  f32[172] = uniforms.readCategoryColor[17][0]
  f32[173] = uniforms.readCategoryColor[17][1]
  f32[174] = uniforms.readCategoryColor[17][2]
  f32[175] = uniforms.readCategoryColor[17][3]
  f32[176] = uniforms.readCategoryColor[18][0]
  f32[177] = uniforms.readCategoryColor[18][1]
  f32[178] = uniforms.readCategoryColor[18][2]
  f32[179] = uniforms.readCategoryColor[18][3]
  f32[180] = uniforms.readCategoryColor[19][0]
  f32[181] = uniforms.readCategoryColor[19][1]
  f32[182] = uniforms.readCategoryColor[19][2]
  f32[183] = uniforms.readCategoryColor[19][3]
  f32[184] = uniforms.readCategoryColor[20][0]
  f32[185] = uniforms.readCategoryColor[20][1]
  f32[186] = uniforms.readCategoryColor[20][2]
  f32[187] = uniforms.readCategoryColor[20][3]
  f32[188] = uniforms.readCategoryColor[21][0]
  f32[189] = uniforms.readCategoryColor[21][1]
  f32[190] = uniforms.readCategoryColor[21][2]
  f32[191] = uniforms.readCategoryColor[21][3]
  f32[192] = uniforms.readCategoryColor[22][0]
  f32[193] = uniforms.readCategoryColor[22][1]
  f32[194] = uniforms.readCategoryColor[22][2]
  f32[195] = uniforms.readCategoryColor[22][3]
  f32[196] = uniforms.pxPerBp
  f32[197] = uniforms.arcBandH
  f32[198] = uniforms.dpr
}

export const INSTANCE_STRIDE_BYTES = 12
export const INSTANCE_STRIDE_WORDS = 3

// Word indices into a Float32Array view over the instance buffer.
export const INSTANCE_OFFSET_F32 = {
  colorType: 1,
} as const

// Word indices into a Uint32Array view over the instance buffer.
export const INSTANCE_OFFSET_U32 = {
  position: 0,
  yBp: 2,
} as const

export const VERTEX_ATTRIBUTES: readonly VertexAttributeLayout[] = [
  { name: 'a_position', components: 1, type: 'uint', offsetBytes: 0, integer: true },
  { name: 'a_colorType', components: 1, type: 'float', offsetBytes: 4, integer: false },
  { name: 'a_yBp', components: 1, type: 'uint', offsetBytes: 8, integer: true },
]

export interface InstanceArrays {
  position: ArrayLike<number>
  colorType: ArrayLike<number>
  yBp: ArrayLike<number>
}

export function packInstances(
  arrays: InstanceArrays,
  numInstances: number,
  buf: ArrayBuffer = new ArrayBuffer(numInstances * INSTANCE_STRIDE_BYTES),
) {
  const f32 = new Float32Array(buf)
  const u32 = new Uint32Array(buf)
  const { position, colorType, yBp } = arrays
  for (let i = 0; i < numInstances; i++) {
    const o = i * INSTANCE_STRIDE_WORDS
    u32[o + 0] = position[i]!
    f32[o + 1] = colorType[i]!
    u32[o + 2] = yBp[i]!
  }
  return buf
}

// Instance `i`'s `position`.
export function getInstancePosition(u32: Uint32Array, i: number) {
  return u32[i * INSTANCE_STRIDE_WORDS]!
}

export function setInstancePosition(u32: Uint32Array, i: number, v: number) {
  u32[i * INSTANCE_STRIDE_WORDS] = v
}

// Instance `i`'s `colorType`.
export function getInstanceColorType(f32: Float32Array, i: number) {
  return f32[i * INSTANCE_STRIDE_WORDS + 1]!
}

export function setInstanceColorType(f32: Float32Array, i: number, v: number) {
  f32[i * INSTANCE_STRIDE_WORDS + 1] = v
}

// Instance `i`'s `yBp`.
export function getInstanceYBp(u32: Uint32Array, i: number) {
  return u32[i * INSTANCE_STRIDE_WORDS + 2]!
}

export function setInstanceYBp(u32: Uint32Array, i: number, v: number) {
  u32[i * INSTANCE_STRIDE_WORDS + 2] = v
}
