// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from connectingLine.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './connectingLine.iface.generated.ts'
export * from './connectingLine.consts.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./connectingLine.wgsl.generated.ts'),
  glsl: () => import('./connectingLine.glsl.generated.ts'),
}
