// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from packedColorQuad.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './packedColorQuad.iface.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./packedColorQuad.wgsl.generated.ts'),
  glsl: () => import('./packedColorQuad.glsl.generated.ts'),
}
