// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from read.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

export const READ_CATEGORY_SLOTS = 21

export const RC_SPLIT_INVERSION = 1

export const RC_SPLIT_DELETION = 2

export const RC_UNMAPPED_MATE = 3

export const RC_INTERCHROM = 4

export const RC_FWD_STRAND = 5

export const RC_REV_STRAND = 6

export const RC_NON_SPLIT = 7

export const RC_PAIR_LR = 8

export const RC_PAIR_RL = 9

export const RC_PAIR_RR = 10

export const RC_PAIR_LL = 11

export const RC_LONG_INSERT = 12

export const RC_SHORT_INSERT = 13

export const RC_NORMAL_INSERT = 14

export const RC_PLAIN = 0

export const RC_MAPQ = 15

export const RC_TAG = 16

export const RC_NO_TAG_VALUE = 17

export const RC_MOD_FWD = 18

export const RC_MOD_REV = 19

export const RC_MAPQ_UNAVAILABLE = 20

export const CHEVRON_DIRLESS_MIN_WIDTH_PX = 30

export const PAIR_MIN_SPAN_PX = 10

export const READ_OUTLINE_PX = 1

export const READ_OUTLINE_SHADE = 0.85

export const READ_OUTLINE_MIN_WIDTH_PX = 2

export const READ_OUTLINE_MIN_HEIGHT_PX = 4
