export { default as AboutDialog } from './AboutDialog.tsx'
export { default as DrawerWidget } from './DrawerWidget.tsx'
export { default as ModalWidget } from './ModalWidget.tsx'
export { default as PreferencesDialog } from './PreferencesDialog.tsx'
export * from './PreferencesDialog.tsx'
export { removeAttr } from './util.ts'
