/* eslint-disable no-console */
// Generates `${base}.generated.ts` from Slang's reflection JSON plus the
// compiled WGSL / GLSL outputs. The generated file is the single source of
// truth for:
//   - WGSL / GLSL shader strings
//   - Uniform std140 layout (field offsets, total size)
//   - Per-instance vertex buffer layout (field offsets, stride)
//   - GL_ATTRIBUTES descriptors (for PassDescriptor)
//   - Uniforms TS interface + writeUniforms() packer
//   - InstanceArrays TS interface + packInstances() struct-of-arrays packer
//
// `packInstances` takes one input array per instance field (vecN fields read N
// consecutive values per instance) and interleaves them into the vertex
// buffer. Crucially, the destination view (u32 / i32 / f32) for each field is
// derived from the shader struct, so a field-type change in .slang updates the
// packing automatically. The FIELD_OFFSET_F32 constants remain exported for
// callers that pack multiple sources into one buffer (wiggle, synteny) and so
// can't use the single-array-per-field shape.

import { readFileSync, writeFileSync } from 'node:fs'

interface ScalarType {
  kind: 'scalar'
  scalarType: 'float32' | 'uint32' | 'int32'
}
interface VectorType {
  kind: 'vector'
  elementCount: number
  elementType: ScalarType
}
type SlangType = ScalarType | VectorType

interface UniformBinding {
  kind: 'uniform'
  offset: number
  size: number
}
interface VaryingBinding {
  kind: 'varyingInput' | 'varyingOutput'
  index: number
}

interface Field {
  name: string
  type: SlangType
  binding?: UniformBinding | VaryingBinding
}

interface StructType {
  kind: 'struct'
  name: string
  fields: Field[]
}

interface ConstantBufferType {
  kind: 'constantBuffer'
  elementType: StructType
  elementVarLayout: { binding: UniformBinding }
}

interface Parameter {
  name: string
  binding: { kind: string; index: number; count?: number }
  type: ConstantBufferType | { kind: string }
}

interface EntryPoint {
  name: string
  stage: 'vertex' | 'fragment' | 'compute'
  parameters: {
    name: string
    type: SlangType | StructType
    semanticName?: string
  }[]
}

interface Reflection {
  parameters: Parameter[]
  entryPoints: EntryPoint[]
}

export interface CodegenTexture {
  name: string
  textureBinding: number
  samplerBinding: number
}

export interface CodegenInputs {
  baseName: string
  reflection: Reflection
  wgsl?: string
  glslVertex?: string
  glslFragment?: string
  textures?: CodegenTexture[]
  vertsPerInstance?: number
  exportedConsts?: Record<string, number>
}

function sizeOf(t: SlangType) {
  return t.kind === 'scalar' ? 4 : t.elementCount * 4
}

function tsFieldType(t: SlangType) {
  if (t.kind === 'scalar') {
    return 'number'
  }
  const ns = Array.from({ length: t.elementCount }, () => 'number').join(', ')
  return `[${ns}]`
}

function isUintField(t: SlangType) {
  if (t.kind === 'scalar') {
    return t.scalarType === 'uint32'
  }
  return t.elementType.scalarType === 'uint32'
}

function isIntField(t: SlangType) {
  if (t.kind === 'scalar') {
    return t.scalarType === 'int32'
  }
  return t.elementType.scalarType === 'int32'
}

function findVertexStruct(r: Reflection) {
  // Prefer an instance struct read from a StructuredBuffer at module scope —
  // that's the layout the TS side has to pack. Fall back to a vertex-input
  // struct (ATTR-semantic parameter) for shaders that use vertex attributes.
  for (const p of r.parameters) {
    const t = p.type as {
      kind?: string
      baseShape?: string
      resultType?: StructType
    }
    if (
      t.kind === 'resource' &&
      t.baseShape === 'structuredBuffer' &&
      t.resultType
    ) {
      return t.resultType
    }
  }
  const vs = r.entryPoints.find(e => e.stage === 'vertex')
  if (!vs) {
    return undefined
  }
  for (const p of vs.parameters) {
    if (
      typeof p.type === 'object' &&
      'kind' in p.type &&
      p.type.kind === 'struct'
    ) {
      return p.type
    }
  }
  return undefined
}

function findConstantBuffer(r: Reflection) {
  for (const p of r.parameters) {
    if ('kind' in p.type && p.type.kind === 'constantBuffer') {
      return p.type as ConstantBufferType
    }
  }
  return undefined
}

function toStringLiteral(s: string) {
  return JSON.stringify(s)
}

function componentType(t: SlangType): 'float' | 'uint' | 'int' {
  const s = t.kind === 'scalar' ? t.scalarType : t.elementType.scalarType
  if (s === 'uint32') {
    return 'uint'
  }
  if (s === 'int32') {
    return 'int'
  }
  return 'float'
}

const header = (baseName: string) => [
  `// AUTO-GENERATED by scripts/shader-codegen from ${baseName}.slang.`,
  '// Do not edit. Run `pnpm gen:shaders` to regenerate.',
  '',
]

// The heavy WGSL / GLSL shader strings, kept in their own module. Eager
// model-side code only ever needs the layout constants / packers from the
// interface module, so isolating the strings here lets the bundler keep them
// out of the always-loaded plugin chunk and in the lazy render path. The
// strings module re-exports the interface so existing `import * as xShader`
// render-path imports get the full ShaderModule surface unchanged.
export function emitShaderStrings(inputs: CodegenInputs) {
  const { baseName, wgsl, glslVertex, glslFragment } = inputs
  const lines = header(baseName)
  if (wgsl !== undefined) {
    lines.push(`export const WGSL_SOURCE = ${toStringLiteral(wgsl)}`, '')
  }
  if (glslVertex !== undefined) {
    lines.push(`export const GLSL_VERTEX = ${toStringLiteral(glslVertex)}`, '')
  }
  if (glslFragment !== undefined) {
    lines.push(
      `export const GLSL_FRAGMENT = ${toStringLiteral(glslFragment)}`,
      '',
    )
  }
  lines.push(`export * from './${baseName}.iface.generated.ts'`, '')
  return lines.join('\n')
}

// Everything except the shader strings: exported consts, uniform/instance
// layout, typed packers, GL_ATTRIBUTES, textures. This is the module eager
// code imports (it never pulls in WGSL_SOURCE/GLSL_*).
export function emitInterface(inputs: CodegenInputs) {
  const { baseName, reflection, textures, vertsPerInstance, exportedConsts } =
    inputs
  const lines = header(baseName)
  const halImports = ['GlAttributeLayout']
  if (textures && textures.length > 0) {
    halImports.push('TextureBinding')
  }
  lines.push(
    `import type { ${halImports.join(', ')} } from '@jbrowse/render-core/hal'`,
    '',
  )

  if (vertsPerInstance !== undefined) {
    lines.push(`export const VERTS_PER_INSTANCE = ${vertsPerInstance}`, '')
  }

  if (exportedConsts) {
    for (const [name, value] of Object.entries(exportedConsts)) {
      lines.push(`export const ${name} = ${value}`, '')
    }
  }

  const cb = findConstantBuffer(reflection)
  if (cb) {
    const u = cb.elementType
    const totalBytes = cb.elementVarLayout.binding.size
    lines.push(
      `export const UNIFORMS_SIZE_BYTES = ${totalBytes}`,
      '',
      '// Indices into a Float32Array / Uint32Array view over the uniform buffer.',
      'export const UNIFORM_OFFSET_F32 = {',
    )
    for (const f of u.fields) {
      if (f.binding?.kind === 'uniform') {
        lines.push(`  ${f.name}: ${f.binding.offset / 4},`)
      }
    }
    lines.push('} as const', '')

    // Auto-detect palette groups: fields with a shared prefix and consecutive
    // integer suffixes starting at 0 (e.g. arcColor0..7, arcLineColor0..1).
    // Emits `UNIFORM_SLOT_ARRAYS_F32.<prefix>` so TS callers iterate without
    // maintaining parallel hand-rolled slot arrays.
    const groups = new Map<string, Map<number, number>>()
    for (const f of u.fields) {
      if (f.binding?.kind !== 'uniform') {
        continue
      }
      const m = /^(.+?)(\d+)$/.exec(f.name)
      if (!m) {
        continue
      }
      const prefix = m[1]!
      const n = Number(m[2]!)
      if (!groups.has(prefix)) {
        groups.set(prefix, new Map())
      }
      groups.get(prefix)!.set(n, f.binding.offset / 4)
    }
    const emittedGroups: { prefix: string; offsets: number[] }[] = []
    for (const [prefix, idxMap] of groups) {
      if (idxMap.size < 2 || !idxMap.has(0)) {
        continue
      }
      const offsets: number[] = []
      for (let i = 0; idxMap.has(i); i++) {
        offsets.push(idxMap.get(i)!)
      }
      if (offsets.length === idxMap.size) {
        emittedGroups.push({ prefix, offsets })
      }
    }
    if (emittedGroups.length > 0) {
      lines.push(
        '',
        '// Palette-group slot arrays: offsets of consecutive <prefix>0..N',
        '// fields, indexed into the 4-byte-word uniform buffer (works with',
        '// either Uint32Array or Float32Array views — the field kind picks).',
        'export const UNIFORM_SLOT_ARRAYS = {',
      )
      for (const g of emittedGroups) {
        lines.push(`  ${g.prefix}: [${g.offsets.join(', ')}] as const,`)
      }
      lines.push('} as const')
    }

    lines.push('', 'export interface Uniforms {')
    for (const f of u.fields) {
      lines.push(`  ${f.name}: ${tsFieldType(f.type)}`)
    }
    lines.push('}', '')

    const uniformFields = u.fields.filter(f => f.binding?.kind === 'uniform')
    const hasUint = uniformFields.some(f => isUintField(f.type))
    const hasInt = uniformFields.some(f => isIntField(f.type))
    const hasFloat = uniformFields.some(
      f => !isUintField(f.type) && !isIntField(f.type),
    )
    lines.push(
      'export function writeUniforms(buf: ArrayBuffer, uniforms: Uniforms) {',
    )
    if (hasFloat) {
      lines.push('  const f32 = new Float32Array(buf)')
    }
    if (hasUint) {
      lines.push('  const u32 = new Uint32Array(buf)')
    }
    if (hasInt) {
      lines.push('  const i32 = new Int32Array(buf)')
    }
    for (const f of u.fields) {
      if (f.binding?.kind !== 'uniform') {
        continue
      }
      const off4 = f.binding.offset / 4
      let view: 'f32' | 'u32' | 'i32'
      if (isUintField(f.type)) {
        view = 'u32'
      } else if (isIntField(f.type)) {
        view = 'i32'
      } else {
        view = 'f32'
      }
      if (f.type.kind === 'scalar') {
        lines.push(`  ${view}[${off4}] = uniforms.${f.name}`)
      } else {
        for (let i = 0; i < f.type.elementCount; i++) {
          lines.push(`  ${view}[${off4 + i}] = uniforms.${f.name}[${i}]`)
        }
      }
    }
    lines.push('}', '')
  }

  const vs = findVertexStruct(reflection)
  if (vs) {
    let cursor = 0
    const attrs = vs.fields.map(f => {
      const entry = {
        name: f.name,
        offsetBytes: cursor,
        size: sizeOf(f.type),
        type: f.type,
      }
      cursor += sizeOf(f.type)
      return entry
    })
    const stride = cursor

    lines.push(
      `export const INSTANCE_STRIDE_BYTES = ${stride}`,
      `export const INSTANCE_STRIDE_F32 = ${stride / 4}`,
      '',
      'export const FIELD_OFFSET_F32 = {',
    )
    for (const a of attrs) {
      lines.push(`  ${a.name}: ${a.offsetBytes / 4},`)
    }
    lines.push(
      '} as const',
      '',
      `export const GL_ATTRIBUTES: readonly GlAttributeLayout[] = [`,
    )
    for (const a of attrs) {
      const ct = componentType(a.type)
      const comps = a.type.kind === 'scalar' ? 1 : a.type.elementCount
      const integer = ct === 'uint' || ct === 'int'
      lines.push(
        `  { name: 'a_${a.name}', components: ${comps}, type: '${ct}', offsetBytes: ${a.offsetBytes}, integer: ${integer} },`,
      )
    }
    lines.push(']', '')

    // Struct-of-arrays instance packer. Takes one input array per field (vecN
    // fields read N consecutive values per instance) and interleaves them into
    // the vertex buffer. The destination view (u32 / i32 / f32) for each field
    // is derived from the shader struct here, so changing a field's type in
    // the .slang source updates the packing automatically — the hand-written
    // interleave functions this replaces chose the view by hand and could
    // silently drift from the shader.
    lines.push('export interface InstanceArrays {')
    for (const a of attrs) {
      lines.push(`  ${a.name}: ArrayLike<number>`)
    }
    lines.push('}', '')

    const hasF32 = attrs.some(a => componentType(a.type) === 'float')
    const hasU32 = attrs.some(a => componentType(a.type) === 'uint')
    const hasI32 = attrs.some(a => componentType(a.type) === 'int')
    // `numInstances` (not `count`) avoids colliding with an instance field
    // literally named `count` — the destructure below binds field names as
    // locals, so the loop bound must not share a name with any field.
    lines.push(
      'export function packInstances(',
      '  arrays: InstanceArrays,',
      '  numInstances: number,',
      '  buf: ArrayBuffer = new ArrayBuffer(numInstances * INSTANCE_STRIDE_BYTES),',
      ') {',
    )
    if (hasF32) {
      lines.push('  const f32 = new Float32Array(buf)')
    }
    if (hasU32) {
      lines.push('  const u32 = new Uint32Array(buf)')
    }
    if (hasI32) {
      lines.push('  const i32 = new Int32Array(buf)')
    }
    lines.push(`  const { ${attrs.map(a => a.name).join(', ')} } = arrays`)
    lines.push('  for (let i = 0; i < numInstances; i++) {')
    lines.push('    const o = i * INSTANCE_STRIDE_F32')
    for (const a of attrs) {
      const ct = componentType(a.type)
      const view = ct === 'uint' ? 'u32' : ct === 'int' ? 'i32' : 'f32'
      const word = a.offsetBytes / 4
      const comps = a.type.kind === 'scalar' ? 1 : a.type.elementCount
      if (comps === 1) {
        lines.push(`    ${view}[o + ${word}] = ${a.name}[i]!`)
      } else {
        for (let c = 0; c < comps; c++) {
          lines.push(
            `    ${view}[o + ${word + c}] = ${a.name}[i * ${comps} + ${c}]!`,
          )
        }
      }
    }
    lines.push('  }', '  return buf', '}', '')
  }

  if (textures && textures.length > 0) {
    lines.push(
      '// Combined `Sampler2D` bindings. Texture unit indices start at 0.',
      // Emitted as a non-empty tuple type so it matches ShaderModule.TEXTURES
      // (which slangPass.ts requires to be `readonly [TextureBinding, ...TextureBinding[]]`).
      // Codegen only enters this branch when textures.length > 0.
      'export const TEXTURES: readonly [TextureBinding, ...TextureBinding[]] = [',
    )
    for (let i = 0; i < textures.length; i++) {
      const t = textures[i]!
      lines.push(
        `  { textureBinding: ${t.textureBinding}, samplerBinding: ${t.samplerBinding}, glTextureUnit: ${i}, glUniformName: 'u_${t.name}', filter: 'linear' },`,
      )
    }
    lines.push(']', '')
  }

  return lines.join('\n')
}

// Emits only the instance buffer layout constants (stride + field offsets) with
// no shader source strings, GL attributes, or typed packers. Used to write a
// layout-only file into a package that can't import from the plugin that owns
// the full generated file (e.g. packages/alignments-core importing snpCoverage
// layout without being able to import from plugins/alignments).
export function emitLayoutOnly(
  inputs: Pick<CodegenInputs, 'baseName' | 'reflection'>,
) {
  const { baseName, reflection } = inputs
  const lines: string[] = [
    `// AUTO-GENERATED by scripts/shader-codegen from ${baseName}.slang.`,
    '// Do not edit. Run `pnpm gen:shaders` to regenerate.',
    '',
  ]

  const vs = findVertexStruct(reflection)
  if (vs) {
    let cursor = 0
    const attrs = vs.fields.map(f => {
      const entry = { name: f.name, offsetBytes: cursor, size: sizeOf(f.type) }
      cursor += sizeOf(f.type)
      return entry
    })
    const stride = cursor

    lines.push(
      `export const INSTANCE_STRIDE_BYTES = ${stride}`,
      `export const INSTANCE_STRIDE_F32 = ${stride / 4}`,
      '',
      'export const FIELD_OFFSET_F32 = {',
    )
    for (const a of attrs) {
      lines.push(`  ${a.name}: ${a.offsetBytes / 4},`)
    }
    lines.push('} as const', '')
  }

  return lines.join('\n')
}

function runCli() {
  const [
    ,
    ,
    reflectionPath,
    wgslPath,
    glslVertexPath,
    glslFragmentPath,
    outPath,
  ] = process.argv
  if (!reflectionPath || !outPath) {
    console.error(
      'usage: codegen.ts <reflection.json> [wgsl|-] [glslVertex|-] [glslFragment|-] <out.ts>',
    )
    process.exit(1)
  }
  const reflection = JSON.parse(
    readFileSync(reflectionPath, 'utf8'),
  ) as Reflection
  const wgsl =
    wgslPath && wgslPath !== '-' ? readFileSync(wgslPath, 'utf8') : undefined
  const glslVertex =
    glslVertexPath && glslVertexPath !== '-'
      ? readFileSync(glslVertexPath, 'utf8')
      : undefined
  const glslFragment =
    glslFragmentPath && glslFragmentPath !== '-'
      ? readFileSync(glslFragmentPath, 'utf8')
      : undefined

  const baseName = reflectionPath
    .replace(/\.reflection\.json$/, '')
    .replace(/.*\//, '')
  const codegenInputs = { baseName, reflection, wgsl, glslVertex, glslFragment }
  writeFileSync(outPath, emitShaderStrings(codegenInputs))
  const ifacePath = outPath.replace(/\.generated\.ts$/, '.iface.generated.ts')
  writeFileSync(ifacePath, emitInterface(codegenInputs))
  console.log(`wrote ${outPath} + ${ifacePath}`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  runCli()
}
