export default [
  'mobx',
  'mobx-state-tree',
  'react',
  'react-dom',
  'mobx-react',
  'prop-types',

  '@material-ui/core',
  '@material-ui/core/SvgIcon',
  '@material-ui/core/utils',
  '@material-ui/lab',
  '@material-ui/data-grid',

  '@jbrowse/core/Plugin',
  '@jbrowse/core/pluggableElementTypes/ViewType',
  '@jbrowse/core/pluggableElementTypes/AdapterType',
  '@jbrowse/core/pluggableElementTypes/DisplayType',
  '@jbrowse/core/pluggableElementTypes/TrackType',
  '@jbrowse/core/pluggableElementTypes/WidgetType',

  '@jbrowse/core/pluggableElementTypes/models',
  '@jbrowse/core/pluggableElementTypes/renderers/ServerSideRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/CircularChordRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/BoxRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/FeatureRendererType',
  '@jbrowse/core/pluggableElementTypes/renderers/RendererType',
  '@jbrowse/core/configuration',
  '@jbrowse/core/util/types/mst',
  '@jbrowse/core/ui',
  '@jbrowse/core/util',
  '@jbrowse/core/util/color',
  '@jbrowse/core/util/tracks',
  '@jbrowse/core/util/Base1DViewModel',
  '@jbrowse/core/util/io',
  '@jbrowse/core/util/mst-reflection',
  '@jbrowse/core/util/rxjs',
  '@jbrowse/core/BaseFeatureWidget/BaseFeatureDetail',

  '@jbrowse/core/data_adapters/BaseAdapter',
]
