import { makeStyles } from '../util/tss-react/index.ts'
import ErrorActions from './ErrorActions.tsx'
import RedErrorMessageBox from './RedErrorMessageBox.tsx'
import { parseError } from './parseError.ts'

import type { ReactNode } from 'react'

const useStyles = makeStyles()(theme => ({
  bg: {
    background: theme.palette.divider,
    border: '1px solid black',
    margin: 20,
  },
  message: {
    background: theme.palette.action.hover,
    border: `1px solid ${theme.palette.divider}`,
    padding: '12px 16px',
    margin: '16px 20px',
    fontFamily: 'monospace',
    fontSize: '0.9rem',
  },
  iconFloat: {
    float: 'right',
    marginLeft: 100,
  },
}))

function ErrorBanner({
  error,
  onReset,
  extraAction,
}: {
  error: unknown
  onReset?: () => void
  extraAction?: ReactNode
}) {
  const { classes } = useStyles()
  const errorText = `${error}`
  // trim "expected an instance of ..." tail — still generated by MST for
  // individual field errors but is noise after the type mismatch is stated
  const instanceIdx = errorText.indexOf('expected an instance of')
  const displayText =
    instanceIdx === -1 ? errorText : errorText.slice(0, instanceIdx)
  const { snapshotValue, message } = parseError(errorText)
  return (
    <RedErrorMessageBox>
      {displayText.slice(0, 10000)}
      <div className={classes.iconFloat}>
        <ErrorActions
          error={error}
          onRetry={onReset}
          extraAction={extraAction}
          color="primary"
        />
      </div>
      {snapshotValue !== undefined ? (
        <>
          <div className={classes.message}>{message}</div>
          <pre className={classes.bg}>
            {JSON.stringify(snapshotValue, null, 2)}
          </pre>
        </>
      ) : null}
    </RedErrorMessageBox>
  )
}

export default ErrorBanner
