#!/usr/bin/env node
// Announce a release to Bluesky, Mastodon, and the email newsletter.
//
// Run manually AFTER the GitHub release is published (parallel to how
// `pnpm releasenotes` is copied into the release body). In CI this is the
// `announce` workflow_dispatch; locally it's `pnpm announce`.
//
//   pnpm announce -- --dry-run            # preview everything, send nothing
//   pnpm announce -- --tag v4.3.1         # override auto-detected tag
//
// Each channel is attempted only when its credentials are present in the env,
// so partial configuration is fine:
//   BLUESKY_IDENTIFIER, BLUESKY_APP_PASSWORD      -> Bluesky
//   MASTODON_ACCESS_TOKEN (+ MASTODON_INSTANCE)   -> Mastodon
//   NEWSLETTER_LAMBDA (+ AWS creds in env)        -> email newsletter

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import {
  BLOG_DIR,
  REPO,
  findLatestReleasePost,
  parseReleaseFilename,
  parseReleasePost,
  splitReleaseBody,
} from './releaseBlog.mjs'

const MASTODON_INSTANCE =
  process.env.MASTODON_INSTANCE ?? 'https://genomic.social'

const args = process.argv.slice(2)
const dryRun = args.includes('--dry-run')
const tagIdx = args.indexOf('--tag')
const tagArg = tagIdx === -1 ? undefined : args[tagIdx + 1]

// ---------------------------------------------------------------------------
// Read the newest release blog post (same source as `pnpm releasenotes`).
// ---------------------------------------------------------------------------
const newest = findLatestReleasePost()
const { body, title } = parseReleasePost(
  readFileSync(path.join(BLOG_DIR, newest), 'utf8'),
  newest,
)
const { y, m, d, slug, tag: fileTag } = parseReleaseFilename(newest)
const tag = tagArg ?? fileTag

// Human-written notes only — the part before the "## Downloads" block, so the
// email carries the summary rather than the full autogenerated changelog.
const { notes } = splitReleaseBody(body)

const releaseUrl = `https://github.com/${REPO}/releases/tag/${tag}`
const blogUrl = `https://jbrowse.org/jb2/blog/${y}/${m}/${d}/${slug}/`

// ---------------------------------------------------------------------------
// Minimal markdown -> HTML for the notes subset (paragraphs, bullet lists,
// links, bold, inline code, subheadings). Input is our own release notes, and
// every send is previewable via --dry-run.
// ---------------------------------------------------------------------------
function escapeHtml(s) {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

function inline(s) {
  // One pass handles [text](url) and bare URLs via alternation: a markdown
  // link is consumed whole before its inner URL can match as a bare URL, so
  // no placeholder tokens are needed.
  return s
    .replaceAll(
      /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)|(https?:\/\/[^\s<]+)/g,
      (_, text, url, bare) =>
        bare ? `<a href="${bare}">${bare}</a>` : `<a href="${url}">${text}</a>`,
    )
    .replaceAll(/`([^`]+)`/g, '<code>$1</code>')
    .replaceAll(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
}

function mdToHtml(md) {
  const lines = escapeHtml(md).split('\n')
  const html = []
  let para = []
  let list = []
  const flushPara = () => {
    if (para.length) {
      html.push(`<p>${inline(para.join(' '))}</p>`)
      para = []
    }
  }
  const flushList = () => {
    if (list.length) {
      html.push(`<ul>${list.map(li => `<li>${inline(li)}</li>`).join('')}</ul>`)
      list = []
    }
  }
  // The notes are prettier prose-wrapped, so a bullet or paragraph spans
  // several physical lines. A non-blank line that isn't itself a bullet or
  // heading is a lazy continuation of whichever block is currently open.
  for (const line of lines) {
    const bullet = /^\s*[-*]\s+(.*)$/.exec(line)
    const heading = /^(#{2,4})\s+(.*)$/.exec(line)
    if (bullet) {
      flushPara()
      list.push(bullet[1])
    } else if (heading) {
      flushPara()
      flushList()
      const level = heading[1].length
      html.push(`<h${level}>${inline(heading[2])}</h${level}>`)
    } else if (line.trim() === '') {
      flushPara()
      flushList()
    } else if (list.length) {
      list[list.length - 1] += ` ${line.trim()}`
    } else {
      para.push(line.trim())
    }
  }
  flushPara()
  flushList()
  return html.join('\n')
}

// ---------------------------------------------------------------------------
// Compose the messages.
// ---------------------------------------------------------------------------
const socialText = `JBrowse ${tag} is out! Release notes and downloads: ${releaseUrl}`
const subject = `JBrowse ${tag} released`
const htmlBody = `<h1>JBrowse ${tag}</h1>
${mdToHtml(notes)}
<p><a href="${releaseUrl}">Full release notes and downloads →</a></p>`
const textBody = `${notes}\n\nFull release notes and downloads: ${releaseUrl}`

console.log(`Announcing ${tag}${dryRun ? ' (DRY RUN — nothing sent)' : ''}`)
console.log(`  title:   ${title}`)
console.log(`  release: ${releaseUrl}`)
console.log(`  blog:    ${blogUrl}`)

// ---------------------------------------------------------------------------
// Bluesky (AT Protocol) — with a link facet so the URL is clickable.
// ---------------------------------------------------------------------------
async function postBluesky() {
  const identifier = process.env.BLUESKY_IDENTIFIER
  const password = process.env.BLUESKY_APP_PASSWORD
  const call = async (method, payload, jwt) => {
    const res = await fetch(`https://bsky.social/xrpc/${method}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(jwt ? { Authorization: `Bearer ${jwt}` } : {}),
      },
      body: JSON.stringify(payload),
    })
    if (!res.ok) {
      throw new Error(`bluesky ${method}: ${res.status} ${await res.text()}`)
    }
    return res.json()
  }
  const enc = new TextEncoder()
  const byteStart = enc.encode(
    socialText.slice(0, socialText.indexOf(releaseUrl)),
  ).length
  const facets = [
    {
      index: {
        byteStart,
        byteEnd: byteStart + enc.encode(releaseUrl).length,
      },
      features: [{ $type: 'app.bsky.richtext.facet#link', uri: releaseUrl }],
    },
  ]
  const { accessJwt, did } = await call('com.atproto.server.createSession', {
    identifier,
    password,
  })
  const res = await call(
    'com.atproto.repo.createRecord',
    {
      repo: did,
      collection: 'app.bsky.feed.post',
      record: {
        $type: 'app.bsky.feed.post',
        text: socialText,
        facets,
        createdAt: new Date().toISOString(),
      },
    },
    accessJwt,
  )
  console.log(`  ✓ Bluesky: ${res.uri}`)
}

// ---------------------------------------------------------------------------
// Mastodon (REST) — POST a status.
// ---------------------------------------------------------------------------
async function postMastodon() {
  const token = process.env.MASTODON_ACCESS_TOKEN
  const res = await fetch(`${MASTODON_INSTANCE}/api/v1/statuses`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ status: socialText }),
  })
  if (!res.ok) {
    throw new Error(`mastodon: ${res.status} ${await res.text()}`)
  }
  const json = await res.json()
  console.log(`  ✓ Mastodon: ${json.url}`)
}

// ---------------------------------------------------------------------------
// Newsletter — invoke the send Lambda via the AWS CLI (matches the README).
// Only called for a real send; --dry-run short-circuits before we reach the
// network, same as the Bluesky/Mastodon paths below.
// ---------------------------------------------------------------------------
function sendNewsletter() {
  const fn = process.env.NEWSLETTER_LAMBDA
  // The newsletter stack is deployed in us-east-1; pin it so a local run whose
  // default region differs still finds the function.
  const region = process.env.AWS_REGION ?? 'us-east-1'
  const payload = { subject, htmlBody, textBody }
  const payloadFile = path.join(tmpdir(), `announce-payload-${tag}.json`)
  const outFile = path.join(tmpdir(), `announce-response-${tag}.json`)
  writeFileSync(payloadFile, JSON.stringify(payload))
  execFileSync(
    'aws',
    [
      'lambda',
      'invoke',
      '--function-name',
      fn,
      '--region',
      region,
      '--payload',
      `fileb://${payloadFile}`,
      outFile,
    ],
    { stdio: 'inherit' },
  )
  console.log(`  ✓ Newsletter: ${readFileSync(outFile, 'utf8')}`)
}

// ---------------------------------------------------------------------------
// Fan out to whatever is configured.
// ---------------------------------------------------------------------------
if (dryRun) {
  console.log(`\n--- social post ---\n${socialText}`)
  console.log(`\n--- email subject ---\n${subject}`)
  console.log(`\n--- email html ---\n${htmlBody}`)
}

if (process.env.BLUESKY_APP_PASSWORD) {
  if (dryRun) {
    console.log('\n[dry-run] would post to Bluesky')
  } else {
    await postBluesky()
  }
} else {
  console.log('  – Bluesky skipped (no BLUESKY_APP_PASSWORD)')
}

if (process.env.MASTODON_ACCESS_TOKEN) {
  if (dryRun) {
    console.log('[dry-run] would post to Mastodon')
  } else {
    await postMastodon()
  }
} else {
  console.log('  – Mastodon skipped (no MASTODON_ACCESS_TOKEN)')
}

if (process.env.NEWSLETTER_LAMBDA) {
  if (dryRun) {
    console.log('[dry-run] would invoke newsletter Lambda')
  } else {
    sendNewsletter()
  }
} else {
  console.log('  – Newsletter skipped (no NEWSLETTER_LAMBDA)')
}
