#!/usr/bin/env -S node --experimental-strip-types

// Compiles the R helper library used by "Export R script" into its TS artifact:
//
//   plugins/linear-genome-view/src/LinearGenomeView/rhelpers/*.R
//     -> plugins/linear-genome-view/src/LinearGenomeView/rHelpers.generated.ts
//
// Each `.R` file is one inline helper the exporter can emit into a generated
// script (see exportR.ts). They live as real R files so they can be read,
// linted and run by R tooling directly — and so their source needs no
// TS-template-literal escaping (`"\\.cram$"` here is what R sees, rather than
// the `"\\\\.cram$"` an embedded template literal would need).
//
// The helper's name is its filename; the emission order in a generated script is
// this file's sort order (alphabetical), and the R body is emitted verbatim.
// `--check` verifies the artifact is current without writing (used by CI).

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

// This file lives at scripts/build-r-helpers.ts, so the repo root is one level up.
const REPO_ROOT = path.resolve(
  path.dirname(import.meta.url.replace('file://', '')),
  '..',
)
const DIR = path.join(
  REPO_ROOT,
  'plugins/linear-genome-view/src/LinearGenomeView',
)
const SRC = path.join(DIR, 'rhelpers')
const OUT = path.join(DIR, 'rHelpers.generated.ts')

const names = readdirSync(SRC)
  .filter(f => f.endsWith('.R'))
  .map(f => path.basename(f, '.R'))
  .sort()

// An R helper must define the identifier it is named for — the exporter emits a
// helper only when a fragment asks for it by name, so a mismatch means a script
// that references a function it never defined.
for (const name of names) {
  const body = readFileSync(path.join(SRC, `${name}.R`), 'utf8')
  if (!new RegExp(`^${name} <- `, 'm').test(body)) {
    throw new Error(
      `${name}.R does not define \`${name}\` at top level: a helper's file name is the name fragments request it by`,
    )
  }
}

const entries = names
  .map(name => {
    const body = readFileSync(path.join(SRC, `${name}.R`), 'utf8').trimEnd()
    return `  ${/^[a-z_][a-z_0-9]*$/i.test(name) ? name : JSON.stringify(name)}: ${JSON.stringify(body)},`
  })
  .join('\n')

const generated = `// AUTO-GENERATED by scripts/build-r-helpers.ts from rhelpers/*.R.
// Do not edit. Edit the .R sources and run \`pnpm gen:rhelpers\` to regenerate.

/**
 * The inline R helper definitions "Export R script" can emit — one entry per
 * \`rhelpers/*.R\` file, keyed by the name a fragment requests it by. Only the
 * helpers a script actually references are emitted into it (see exportR.ts).
 * They are plain rtracklayer/ggplot2 so a user (or an assistant) can read and
 * edit them in the emitted script without learning a bespoke package.
 */
export const HELPERS: Record<string, string> = {
${entries}
}
`

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8')
  if (current !== generated) {
    console.error(
      `Error: ${path.relative(REPO_ROOT, OUT)} is out of date.\nRun 'pnpm gen:rhelpers' and commit the changes.`,
    )
    process.exit(1)
  }
  console.log(`${names.length} R helpers up to date`)
} else {
  writeFileSync(OUT, generated)
  console.log(
    `wrote ${path.relative(REPO_ROOT, OUT)} (${names.length} helpers)`,
  )
}
