// Computes the `@jbrowse/*` pin lists the component-test apps install from.
//
// Only `component_tests/*/packed/` is uploaded to the component-test job, which
// runs off a fresh checkout — so the *committed* manifests are what yarn/pnpm
// actually read, and any rewrite `pack.ts` does on the runner is discarded.
// That means a new cross-package dependency edge silently falls through to the
// npm registry (for an unpublished version) until a component test fails, which
// is how `@jbrowse/alignments-core` and then `@jbrowse/cigar-utils` broke
// cgv-vite. `gen-component-test-pins.ts --check` runs this in lint to catch the
// drift at its source.
//
// pack.ts packs every workspace package, so a pin list computed from the
// workspace listing alone matches one computed from a full pack — which is what
// lets the check run without the tarballs on disk.
import fs from 'node:fs'
import path from 'node:path'

export const subDirs = [
  'cgv-vite',
  'lgv-vite',
  'app-vite',
  'plugin-vite',
  'cli-node18',
  'jbrowse-img',
]

const workspaceDirs = ['packages', 'products', 'plugins', 'example-plugins']

export interface WorkspaceIndex {
  /** package name -> the tarball name `pnpm pack` produces, minus the version */
  tarballs: Record<string, string>
  /** package name -> its `dependencies` map */
  dependencies: Record<string, Record<string, string>>
}

/** `@jbrowse/core` -> `jbrowse-core.tgz` */
export function tarballName(pkgName: string) {
  return `${pkgName.replace('@', '').replace('/', '-')}.tgz`
}

export function readWorkspace(root: string): WorkspaceIndex {
  const tarballs: Record<string, string> = {}
  const dependencies: Record<string, Record<string, string>> = {}
  for (const dir of workspaceDirs) {
    const fullDir = path.join(root, dir)
    if (fs.existsSync(fullDir)) {
      for (const subdir of fs.readdirSync(fullDir)) {
        const pkgJsonPath = path.join(fullDir, subdir, 'package.json')
        if (fs.existsSync(pkgJsonPath)) {
          const pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'))
          tarballs[pkgJson.name] = tarballName(pkgJson.name)
          dependencies[pkgJson.name] = pkgJson.dependencies ?? {}
        }
      }
    }
  }
  return { tarballs, dependencies }
}

// Walk an app's @jbrowse/* dependency closure and pin exactly that set, rather
// than hand-maintaining the list. Pinning every packed package unconditionally
// was tried and rejected: yarn still resolves the full dependency tree of every
// entry even if nothing depends on it, so an unrelated package's transitive
// dependency with a stricter `engines.node` (e.g. puppeteer, pulled in only by
// @jbrowse/browser-test-utils) can fail an install on an older Node.
function closureOf(startDeps: Record<string, string>, index: WorkspaceIndex) {
  const closure = new Set<string>()
  const queue = Object.keys(startDeps).filter(name => name in index.tarballs)
  while (queue.length > 0) {
    const name = queue.pop()!
    if (!closure.has(name)) {
      closure.add(name)
      queue.push(
        ...Object.keys(index.dependencies[name] ?? {}).filter(
          depName => depName in index.tarballs,
        ),
      )
    }
  }
  return closure
}

function pinnedClosure(
  existing: Record<string, string>,
  deps: Record<string, string>,
  index: WorkspaceIndex,
) {
  const preserved = Object.fromEntries(
    Object.entries(existing).filter(([name]) => !(name in index.tarballs)),
  )
  return {
    ...preserved,
    ...Object.fromEntries(
      [...closureOf(deps, index)]
        .sort()
        .map(name => [name, `file:./packed/${index.tarballs[name]}`]),
    ),
  }
}

const BEGIN = '# BEGIN packed-overrides'
const END = '# END packed-overrides'

// The yarn apps spell the pins as `resolutions` in package.json; the pnpm apps
// spell them as `overrides` in pnpm-workspace.yaml (pnpm 11 dropped the `pnpm`
// field from package.json, and an overrides map left there is ignored
// *silently* — the install just falls through to the registry). The computed
// value is identical either way.
//
// The yaml block is rewritten by hand rather than with a serializer: every key
// and value is a plain quoted string, and the surrounding file (comments,
// allowBuilds) has to survive verbatim.
function yamlWithOverrides(yml: string, pins: Record<string, string>) {
  const start = yml.indexOf(BEGIN)
  const end = yml.indexOf(END)
  if (start === -1 || end === -1) {
    throw new Error(
      `pnpm-workspace.yaml is missing the ${BEGIN}/${END} markers`,
    )
  }
  const entries = Object.entries(pins)
  const body =
    entries.length > 0
      ? `overrides:\n${entries.map(([k, v]) => `  '${k}': '${v}'`).join('\n')}\n`
      : 'overrides: {}\n'
  return `${yml.slice(0, start)}${BEGIN} (generated by scripts/gen-component-test-pins.ts, do not edit by hand)\n${body}${yml.slice(end)}`
}

/**
 * The content each pinned file in `component_tests/` should have. Writing and
 * checking both go through this, so `--check` can never disagree with a write.
 */
export function pinnedFiles(root: string, index: WorkspaceIndex) {
  const files: { path: string; content: string }[] = []
  for (const dir of subDirs) {
    const appDir = path.join(root, 'component_tests', dir)
    const pkgJsonPath = path.join(appDir, 'package.json')
    const pkgJson = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'))
    const deps = pkgJson.dependencies ?? {}

    // Yarn classic's `resolutions` only steers a TRANSITIVE dependency to the
    // packed tarball — a name this app depends on directly still resolves the
    // range in `dependencies` itself, straight from the registry. So a
    // directly-depended-on entry point (lgv-vite on
    // @jbrowse/react-linear-genome-view2, cgv-vite on
    // @jbrowse/react-circular-genome-view2, app-vite on @jbrowse/react-app2)
    // needs its own `dependencies` entry pinned, the same as `resolutions`.
    let dependenciesChanged = false
    for (const name of Object.keys(deps)) {
      if (name in index.tarballs) {
        const pinned = `file:./packed/${index.tarballs[name]}`
        if (deps[name] !== pinned) {
          deps[name] = pinned
          dependenciesChanged = true
        }
      }
    }
    if (dependenciesChanged) {
      pkgJson.dependencies = deps
    }

    if (pkgJson.resolutions) {
      pkgJson.resolutions = pinnedClosure(pkgJson.resolutions, deps, index)
      files.push({
        path: pkgJsonPath,
        content: `${JSON.stringify(pkgJson, null, 2)}\n`,
      })
    } else if (dependenciesChanged) {
      files.push({
        path: pkgJsonPath,
        content: `${JSON.stringify(pkgJson, null, 2)}\n`,
      })
    }

    const ymlPath = path.join(appDir, 'pnpm-workspace.yaml')
    if (fs.existsSync(ymlPath)) {
      files.push({
        path: ymlPath,
        content: yamlWithOverrides(
          fs.readFileSync(ymlPath, 'utf8'),
          pinnedClosure({}, deps, index),
        ),
      })
    }
  }
  return files
}
