// Copies the mark display's rule list into `jbrowse validate`, so the validator
// reports what the display's corner notice reports, from one source. @jbrowse/cli
// depends on neither @jbrowse/core nor a plugin, so it carries the rule list the
// way it carries the config manifest: as committed output `pnpm autogen --check`
// compares. Run directly after editing the rule list:
//
//   node --experimental-strip-types scripts/generateMarkRules.ts
//
// Every file is copied whole and unedited under a one-line header, which is
// what keeps a copy from meaning something its source does not. That works
// because the rule list's import closure is files beside it, imported by
// relative path and so resolving the same way in the copy, plus one seam,
// markRuleFacts.ts, whose only content is re-exports of what the rules read
// from another package. Each module the seam names imports nothing, is copied
// whole like the rest, and the seam's counterpart is written here over the
// copies. An import that breaks either rule fails this run.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import path from 'node:path'

import ts from 'typescript'

import { check } from '../website/scripts/check-utils.ts'
import { closure, edgesOf, resolve } from './moduleClosure.ts'

const REPO_ROOT = path.resolve(import.meta.dirname, '..')
const RULES_DIR = path.join(REPO_ROOT, 'plugins/marks/src/LinearMarkDisplay')
const ENTRY = path.join(RULES_DIR, 'markProblems.ts')
const SEAM = path.join(RULES_DIR, 'markRuleFacts.ts')
const OUT_DIR = path.join(
  REPO_ROOT,
  'products/jbrowse-cli/src/commands/validate/markRules',
)

const relative = (file: string) => path.relative(REPO_ROOT, file)

function header(source: string) {
  return `// Generated by scripts/generateMarkRules.ts from ${relative(source)}: do not edit, \`pnpm autogen\` rewrites it.\n`
}

// The docs generator reads every source under products/, so a copy carrying a
// `#api` or `#slot` tag would document its symbol a second time.
function refuseDocTags(file: string, text: string) {
  if (/^\s*\*\s*#[a-zA-Z]/m.test(text)) {
    throw new Error(
      `${relative(file)} carries an api-docs tag, and its copy in the CLI would be documented a second time`,
    )
  }
}

const files = [...closure(ENTRY, true).files]
const local = files.filter(f => path.dirname(f) === RULES_DIR && f !== SEAM)
const foreign = files.filter(f => path.dirname(f) !== RULES_DIR)

for (const file of local) {
  for (const { specifier } of edgesOf(file)) {
    if (!/^\.\/[\w.-]+\.ts$/.test(specifier)) {
      throw new Error(
        `${relative(file)} imports "${specifier}". The rule list stands on modules beside it, imported as "./name.ts", and reads another package through ${relative(SEAM)}`,
      )
    }
  }
}

const seamSource = ts.createSourceFile(
  SEAM,
  readFileSync(SEAM, 'utf8'),
  ts.ScriptTarget.ESNext,
  true,
)
const seamLines = seamSource.statements.map(statement => {
  if (
    !ts.isExportDeclaration(statement) ||
    !statement.exportClause ||
    !statement.moduleSpecifier ||
    !ts.isStringLiteral(statement.moduleSpecifier)
  ) {
    throw new Error(
      `${relative(SEAM)} holds only \`export { … } from '…'\` lines, and "${statement.getText(seamSource)}" is not one`,
    )
  }
  const specifier = statement.moduleSpecifier.text
  const target = resolve(specifier, SEAM)
  if (!target || !foreign.includes(target)) {
    throw new Error(
      `${relative(SEAM)} names "${specifier}", which resolves to no source outside the plugin`,
    )
  }
  if (edgesOf(target).length > 0) {
    throw new Error(
      `${relative(target)} imports other modules, and the CLI carries a copy of it alone: state what ${relative(SEAM)} reads in a module that imports nothing`,
    )
  }
  return {
    target,
    line: `export ${statement.isTypeOnly ? 'type ' : ''}${statement.exportClause.getText(seamSource)} from './${path.basename(target)}'`,
  }
})

const unnamed = foreign.filter(f => !seamLines.some(s => s.target === f))
if (unnamed.length > 0) {
  throw new Error(
    `the rule list reaches ${unnamed.map(relative).join(', ')}, which ${relative(SEAM)} does not name`,
  )
}

const copied = [...local, ...new Set(seamLines.map(s => s.target))]
const names = copied.map(f => path.basename(f))
const clash = names.find(
  (n, i) => names.indexOf(n) !== i || n === path.basename(SEAM),
)
if (clash) {
  throw new Error(`two modules the CLI would carry are both named ${clash}`)
}

const outputs = new Map<string, string>([
  ...copied.map((file): [string, string] => {
    const text = readFileSync(file, 'utf8')
    refuseDocTags(file, text)
    return [path.basename(file), header(file) + text]
  }),
  [
    path.basename(SEAM),
    `${header(SEAM)}${seamLines.map(s => s.line).join('\n')}\n`,
  ],
])

const onDisk = existsSync(OUT_DIR) ? readdirSync(OUT_DIR) : []
const orphans = onDisk.filter(name => !outputs.has(name))
const stale = [...outputs].filter(([name, content]) => {
  const file = path.join(OUT_DIR, name)
  return !existsSync(file) || readFileSync(file, 'utf8') !== content
})

if (check) {
  if (stale.length > 0 || orphans.length > 0) {
    console.error(
      `${relative(OUT_DIR)} is out of date — run \`pnpm autogen\`:\n${[
        ...stale.map(([name]) => `  ${name} differs from its source`),
        ...orphans.map(name => `  ${name} is no longer part of the rule list`),
      ].join('\n')}`,
    )
    process.exit(1)
  }
  console.log(`${relative(OUT_DIR)} is up to date (${outputs.size} files)`)
} else {
  mkdirSync(OUT_DIR, { recursive: true })
  for (const name of orphans) {
    rmSync(path.join(OUT_DIR, name))
    console.log(`removed ${relative(path.join(OUT_DIR, name))}`)
  }
  for (const [name, content] of outputs) {
    writeFileSync(path.join(OUT_DIR, name), content)
    console.log(`wrote ${relative(path.join(OUT_DIR, name))}`)
  }
}
