// Emits the `SyntenyFeatureLanes` interface — the regular lanes of the synteny
// RPC payload — from the lane table in
// packages/synteny-core/src/syntenyLaneSchema.ts, so the interface, the packers
// and the renamers cannot drift apart lane by lane. Rides `pnpm autogen`; run
// directly after editing the table:
//
//   node --experimental-strip-types scripts/generateSyntenyLanes.ts
import path from 'node:path'

import { SYNTENY_LANES } from '../packages/synteny-core/src/syntenyLaneSchema.ts'
import { checkOrWrite } from '../website/scripts/check-utils.ts'

const REPO_ROOT = path.resolve(import.meta.dirname, '..')
const OUT = path.join(
  REPO_ROOT,
  'packages/synteny-core/src/syntenyFeatureLanes.generated.ts',
)

function docBlock(doc: string, indent: string) {
  const words = doc.split(/\s+/)
  const width = 80 - indent.length - 3
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    if (line && line.length + 1 + word.length > width) {
      lines.push(line)
      line = word
    } else {
      line = line ? `${line} ${word}` : word
    }
  }
  lines.push(line)
  return [
    `${indent}/**`,
    ...lines.map(l => `${indent} * ${l}`),
    `${indent} */`,
  ].join('\n')
}

const fields = SYNTENY_LANES.flatMap(lane => {
  switch (lane.kind) {
    case 'i8':
      return [`${docBlock(lane.doc, '  ')}\n  ${lane.name}: Int8Array`]
    case 'u32':
      return [`${docBlock(lane.doc, '  ')}\n  ${lane.name}: Uint32Array`]
    case 'string[]':
      return [`${docBlock(lane.doc, '  ')}\n  ${lane.name}: string[]`]
    case 'string-dict':
      return [
        `${docBlock(lane.doc, '  ')}\n  ${lane.name}Dict: string[]\n  ${lane.name}Ids: Uint32Array`,
      ]
    case 'opaque':
      return []
  }
})

checkOrWrite({
  path: OUT,
  label: `${path.relative(REPO_ROOT, OUT)} (${fields.length} lanes)`,
  staleHint: 'run `pnpm autogen`',
  content: `// Generated by scripts/generateSyntenyLanes.ts from syntenyLaneSchema.ts — do
// not edit by hand. Regenerate with \`pnpm autogen\` after editing the table.

/**
 * The regular lanes of the synteny RPC payload: parallel typed arrays plus
 * dictionary-encoded string lanes (a \`<name>Dict\`/\`<name>Ids\` pair each — see
 * \`StringDict\` for why per-feature strings ship this way). Emitted from
 * \`SYNTENY_LANES\`; the irregular payload fields stay on the hand-written
 * \`SyntenyFeatureData\`, which extends this.
 */
export interface SyntenyFeatureLanes {
${fields.join('\n')}
}
`,
})
