// Shared helpers for locating and parsing the newest release blog post.
// Used by both announce.mjs (social/newsletter) and releasenotes.mjs (GitHub
// release body) so they can never disagree on which post is "the release".

import { readdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
)
export const REPO = 'GMOD/jbrowse-components'
export const BLOG_DIR = path.join(ROOT, 'website', 'blog')

// Release posts are named YYYY-MM-DD-vX.Y.Z-release.md. Requiring the version
// in the slug means a non-release post (office hours, etc.) can never be picked
// as "the newest release".
const RELEASE_FILE = /^(\d{4})-(\d{2})-(\d{2})-(v\d+\.\d+\.\d+.*)\.md$/

// Newest release post by filename. The date prefix makes lexical order match
// chronological order, so this is stable regardless of file mtimes.
export function findLatestReleasePost(blogDir = BLOG_DIR) {
  const newest = readdirSync(blogDir)
    .filter(f => RELEASE_FILE.test(f))
    .sort()
    .at(-1)
  if (!newest) {
    throw new Error(`no release blog posts found in ${blogDir}`)
  }
  return newest
}

export function parseReleaseFilename(filename) {
  const m = RELEASE_FILE.exec(filename)
  if (!m) {
    throw new Error(`unexpected release blog filename: ${filename}`)
  }
  const [, y, mo, d, slug] = m
  return { y, m: mo, d, slug, tag: /v\d+\.\d+\.\d+/.exec(slug)[0] }
}

export function parseReleasePost(raw, filename) {
  const fm = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(raw)
  if (!fm) {
    throw new Error(`no frontmatter in ${filename}`)
  }
  const [, frontmatter, body] = fm
  const title = /^title:\s*(.+)$/m.exec(frontmatter)?.[1].trim() ?? filename
  return { frontmatter, body, title }
}

// The human-written summary is everything before the "## Downloads" block; the
// autogenerated changelog is the "## Changes since ..." section after it.
export function splitReleaseBody(body) {
  const notes = body.split(/\n#+\s+Downloads/)[0].trim()
  const changelog = /\n#+\s+Changes since[\s\S]*$/.exec(body)?.[0].trim() ?? ''
  return { notes, changelog }
}
