// Mirror `.claude/skills/` into the standalone distribution repo
// (github.com/cmdcolin/jbrowse-skills), so an agent working outside this
// monorepo can install them without cloning it.
//
//   node --experimental-strip-types scripts/sync-skills-repo.ts <checkout>
//   node --experimental-strip-types scripts/sync-skills-repo.ts <checkout> --check
//
// THIS REPO IS THE SOURCE OF TRUTH, and it has to be: the authoring skill's
// `references/config-types.md` is generated by `pnpm autogen` from the live
// ConfigurationSchema objects (scripts/generateConfigManifest.ts writes it), and
// the whole point of generating it is that it cannot drift from the schemas. A
// skill edited in the mirror is an edit that the next autogen silently reverts,
// so the mirror carries a do-not-edit header and this script is the only way
// content reaches it.
//
// `--check` exits non-zero on drift, for the mirror's own CI to run against a
// checkout of this repo.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'

// An allowlist, not "whatever is in .claude/skills". That directory is also
// where a contributor's own tooling lives (react-doctor is a general React
// skill, nothing to do with JBrowse), and publishing is outward-facing enough
// that adding a local skill should not silently push it to a public repo.
const PUBLISHED = [
  'jbrowse-authoring',
  'jbrowse-hosted-data',
  'jbrowse-capture',
]

const root = join(import.meta.dirname, '..')
const source = join(root, '.claude', 'skills')
const [target, ...flags] = process.argv.slice(2)
const check = flags.includes('--check')

if (!target) {
  console.error(
    'usage: sync-skills-repo.ts <path-to-jbrowse-skills-checkout> [--check]',
  )
  process.exit(1)
}
if (!existsSync(target)) {
  console.error(`no such directory: ${target}`)
  process.exit(1)
}

const HEADER = `<!-- Synced from GMOD/jbrowse-components .claude/skills/ by
scripts/sync-skills-repo.ts. Edit it there: this copy is overwritten, and the
authoring skill's references/config-types.md is generated from the live config
schemas by \`pnpm autogen\`. -->
`

const README = `# JBrowse 2 agent skills

Skills for working with [JBrowse 2](https://jbrowse.org/jb2/) from an AI coding
agent: authoring a config, using the hosted genomes, and screenshotting the
result.

## Install

They are plain Markdown files, so "installing" them is copying a directory into
\`.claude/skills/\`. Any of these does that.

**curl + tar**, no Node, nothing left behind:

\`\`\`bash
mkdir -p .claude/skills
curl -sL https://github.com/cmdcolin/jbrowse-skills/archive/refs/heads/main.tar.gz |
  tar -xz --strip-components=2 -C .claude/skills jbrowse-skills-main/skills
\`\`\`

**git**, if you want to pull updates later:

\`\`\`bash
git clone --depth 1 https://github.com/cmdcolin/jbrowse-skills /tmp/jbrowse-skills
cp -r /tmp/jbrowse-skills/skills/. .claude/skills/
\`\`\`

**degit**, the shortest if you have Node:

\`\`\`bash
npx --yes degit cmdcolin/jbrowse-skills/skills .claude/skills
\`\`\`

Any of them takes a single skill instead of all three — append its directory
name to the source path (\`.../skills/jbrowse-capture\`) and to the destination.

To pull updates, re-run the same command: the files are generated, so there is
nothing local to merge.

## What is here

| Skill | Use it when |
| --- | --- |
| \`jbrowse-authoring\` | writing a \`config.json\`, session or track from scratch, including preparing the data files |
| \`jbrowse-hosted-data\` | the genome is one of the tens of thousands already published at [genomes.jbrowse.org](https://genomes.jbrowse.org) |
| \`jbrowse-capture\` | you need to see a view rather than just build one |

Each is a directory with a \`SKILL.md\` and, where it needs one, a
\`references/\` folder. The format is
[Claude Code's](https://docs.claude.com/en/docs/claude-code/skills), but nothing
in the content is Claude-specific — the files are plain Markdown and work as
context for any assistant.

## Source

**Generated. Do not edit here.** These are mirrored from
[GMOD/jbrowse-components](https://github.com/GMOD/jbrowse-components) under
\`.claude/skills/\`, by \`scripts/sync-skills-repo.ts\` in that repo. Edits made
here are overwritten on the next sync, and the authoring skill's
\`references/config-types.md\` is generated from the live config schemas, so it
would be reverted even sooner.

Open issues and pull requests against jbrowse-components.

## See also

- [Using JBrowse with AI agents](https://jbrowse.org/jb2/docs/agents/)
- [\`@jbrowse/capture\`](https://www.npmjs.com/package/@jbrowse/capture) — the
  Puppeteer helper the capture skill drives
- [\`@jbrowse/img\`](https://www.npmjs.com/package/@jbrowse/img) — static export
  with no browser
`

// A markdown file gets the do-not-edit header, except SKILL.md, whose YAML
// frontmatter must be the first bytes in the file or the skill fails to load.
function withHeader(path: string, body: string) {
  return path.endsWith('SKILL.md') ? body : `${HEADER}\n${body}`
}

interface Entry {
  path: string
  body: string
}

function collect(dir: string, prefix: string): Entry[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap(item => {
    const abs = join(dir, item.name)
    const rel = prefix ? `${prefix}/${item.name}` : item.name
    if (item.isDirectory()) {
      return collect(abs, rel)
    }
    const raw = readFileSync(abs, 'utf8')
    return [{ path: rel, body: withHeader(rel, raw) }]
  })
}

const missing = PUBLISHED.filter(name => !existsSync(join(source, name)))
if (missing.length) {
  console.error(`no such skill in .claude/skills: ${missing.join(', ')}`)
  process.exit(1)
}

const entries = [
  ...PUBLISHED.flatMap(name =>
    collect(join(source, name), name).map(e => ({
      ...e,
      path: `skills/${e.path}`,
    })),
  ),
  { path: 'README.md', body: README },
]

const drift = entries.filter(entry => {
  const dest = join(target, entry.path)
  return !existsSync(dest) || readFileSync(dest, 'utf8') !== entry.body
})

// A skill deleted here has to disappear there too, or the mirror keeps offering
// something this repo no longer stands behind.
const skillsDir = join(target, 'skills')
const expected = new Set(entries.map(e => e.path))
const stale = existsSync(skillsDir)
  ? collect(skillsDir, '')
      .map(e => `skills/${e.path}`)
      .filter(p => !expected.has(p))
  : []

if (check) {
  const problems = [
    ...drift.map(e => `  out of date: ${e.path}`),
    ...stale.map(p => `  no longer in jbrowse-components: ${p}`),
  ]
  if (problems.length) {
    console.error(`${problems.length} file(s) differ from the source:`)
    console.error(problems.join('\n'))
    console.error('\nRun sync-skills-repo.ts without --check to update.')
    process.exit(1)
  }
  console.log(`skills mirror up to date (${entries.length} files)`)
} else {
  for (const path of stale) {
    rmSync(join(target, path))
  }
  for (const entry of drift) {
    const dest = join(target, entry.path)
    mkdirSync(join(dest, '..'), { recursive: true })
    writeFileSync(dest, entry.body)
  }
  const changed = drift.length ? `${drift.length} changed` : 'nothing changed'
  const removed = stale.length ? `, ${stale.length} removed` : ''
  console.log(
    `synced ${entries.length} file(s) to ${target}, ${changed}${removed}`,
  )
}
