// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from ldGenomic.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './ldGenomic.iface.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./ldGenomic.wgsl.generated.ts'),
  glsl: () => import('./ldGenomic.glsl.generated.ts'),
}
