// AUTO-GENERATED by packages/shader-tools/src/shader-codegen from score.slang.
// Do not edit. Run `pnpm gen:shaders` to regenerate.

import type { ShaderSource } from '@jbrowse/render-core/hal'

export * from './score.iface.generated.ts'
export * from './score.consts.generated.ts'

export const SOURCE: ShaderSource = {
  wgsl: () => import('./score.wgsl.generated.ts'),
  glsl: () => import('./score.glsl.generated.ts'),
}
