import { readConfObject } from '../configuration/index.ts'
import { isElectron } from '../util/index.ts'

import type { AnyConfigurationModel } from '../configuration/index.ts'

type StatValue = string | number | boolean | undefined
type AnalyticsObj = Record<string, StatValue>

// MST config models expose slot getters; tracks have a 'type' slot
type TrackConfig = AnyConfigurationModel & { type: string }

interface AnalyticsRootModel {
  jbrowse: {
    tracks: TrackConfig[]
    assemblies: unknown[]
    plugins?: { name?: string }[]
    configuration: AnyConfigurationModel
  }
  session?: {
    sessionTracks: TrackConfig[]
    views: unknown[]
  }
  version: string
}

export async function writeAWSAnalytics(
  rootModel: AnalyticsRootModel,
  initialTimestamp: number,
  sessionQuery?: string | null,
) {
  try {
    const url = 'https://analytics.jbrowse.org/api/v1'

    const multiAssemblyTracks = rootModel.jbrowse.tracks.filter(
      track => (readConfObject(track, 'assemblyNames') || []).length > 1,
    ).length

    const savedSessionCount = Object.keys(localStorage).filter(name =>
      name.includes('localSaved-'),
    ).length

    const { jbrowse: config, session, version: ver } = rootModel
    const { tracks, assemblies, plugins } = config

    // stats to be recorded in db
    const stats: AnalyticsObj = {
      ver,
      'plugins-count': plugins?.length ?? 0,
      'plugin-names': plugins?.map(p => p.name).join(','),
      'assemblies-count': assemblies.length,
      'tracks-count': tracks.length,
      'session-tracks-count': session?.sessionTracks.length ?? 0,
      'open-views': session?.views.length ?? 0,
      'synteny-tracks-count': multiAssemblyTracks,
      'saved-sessions-count': savedSessionCount,

      // field if existing session param in query before autogenerated param
      'existing-session-param-type': sessionQuery?.split('-', 1)[0] || 'none',

      // screen geometry
      'scn-h': window.screen.height,
      'scn-w': window.screen.width,

      // window geometry
      'win-h': window.innerHeight,
      'win-w': window.innerWidth,

      electron: isElectron,
      loadTime: (Date.now() - initialTimestamp) / 1000,
      jb2: true,
    }

    // stringifies the track type counts, gets processed in lambda
    for (const track of tracks) {
      const key = `track-types-${track.type}`
      stats[key] = ((stats[key] as number | undefined) ?? 0) + 1
    }

    // stringifies the session track type counts, gets processed in lambda
    for (const track of session?.sessionTracks ?? []) {
      const key = `sessionTrack-types-${track.type}`
      stats[key] = ((stats[key] as number | undefined) ?? 0) + 1
    }

    // put stats into a query string for get request
    const qs = Object.keys(stats)
      .map(key => `${key}=${stats[key]}`)
      .join('&')

    await fetch(`${url}?${qs}`)
  } catch (e) {
    console.error('Failed to write analytics to AWS.', e)
  }
}

export async function writeGAAnalytics(
  rootModel: AnalyticsRootModel,
  initialTimestamp: number,
) {
  const jbrowseUser = 'UA-7115575-5'
  const stats: AnalyticsObj = {
    'tracks-count': rootModel.jbrowse.tracks.length, // this is all possible tracks
    ver: rootModel.version,
    electron: isElectron,
    loadTime: Date.now() - initialTimestamp,
    pluginNames: rootModel.jbrowse.plugins?.map(p => p.name).join(',') || '',
  }

  const gaData: AnalyticsObj = {}
  const googleDimensions = 'tracks-count ver electron loadTime pluginNames'

  for (const [index, key] of googleDimensions.split(/\s+/).entries()) {
    gaData[`dimension${index + 1}`] = stats[key]
  }

  gaData.metric1 = Math.round(stats.loadTime as number)

  const analyticsScript =
    "(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){" +
    '(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),' +
    'm=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)' +
    "})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');" +
    `ga('create', '${jbrowseUser}', 'auto', 'jbrowseTracker');` +
    `ga('jbrowseTracker.send', 'pageview',${JSON.stringify(gaData)});`

  const analyticsScriptNode = document.createElement('script')
  analyticsScriptNode.innerHTML = analyticsScript

  document.getElementsByTagName('head')[0]!.append(analyticsScriptNode)
}

export function doAnalytics(
  rootModel: AnalyticsRootModel | undefined,
  initialTimestamp: number,
  initialSessionQuery: string | null | undefined,
) {
  if (
    rootModel &&
    !readConfObject(rootModel.jbrowse.configuration, 'disableAnalytics')
  ) {
    // ok if these are unhandled
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    writeAWSAnalytics(rootModel, initialTimestamp, initialSessionQuery)
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    writeGAAnalytics(rootModel, initialTimestamp)
  }
}
