yalc publish alignments --private
yalc publish bed --private
yalc publish circular-view --private
yalc publish config --private
yalc publish core --private
yalc publish data-management --private
yalc publish filtering --private
yalc publish generator-jbrowse --private
yalc publish integration-tests --private
yalc publish jbrowse-web --private
yalc publish jbrowse1 --private
yalc publish linear-genome-view --private
yalc publish lollipop --private
yalc publish menus --private
yalc publish protein --private
yalc publish protein-widget --private
yalc publish rdf --private
yalc publish sequence --private
yalc publish svg --private
yalc publish trackhub-registry --private
yalc publish variants --private
yalc publish wiggle --private
