name: Draft desktop beta release
on: push

jobs:
  build:
    name: Create draft release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'desktop beta')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Set release version
        run: echo "RELEASE_VERSION=$(node -p "require('./package.json').desktopBeta")" >> $GITHUB_ENV
        working-directory: products/jbrowse-desktop
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release desktop ${{ env.RELEASE_VERSION }}
          draft: true
          prerelease: true
