name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.pull_request.labels.*.name, 'breaking') &&
      !contains(github.event.pull_request.labels.*.name, 'enhancement') &&
      !contains(github.event.pull_request.labels.*.name, 'bug') &&
      !contains(github.event.pull_request.labels.*.name, 'documentation') &&
      !contains(github.event.pull_request.labels.*.name, 'internal') &&
      !contains(github.event.pull_request.labels.*.name, 'performance')
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
